extern void v1 (unsigned char, signed short, unsigned int);
extern void (*v2) (unsigned char, signed short, unsigned int);
extern signed char v3 (void);
extern signed char (*v4) (void);
extern void v5 (unsigned int, unsigned char, unsigned int);
extern void (*v6) (unsigned int, unsigned char, unsigned int);
extern signed short v7 (signed short, unsigned char, signed int, signed short);
extern signed short (*v8) (signed short, unsigned char, signed int, signed short);
extern signed char v9 (signed short, signed int, unsigned short);
extern signed char (*v10) (signed short, signed int, unsigned short);
extern signed int v11 (signed int, signed char, signed int);
extern signed int (*v12) (signed int, signed char, signed int);
extern unsigned short v13 (signed short, unsigned int);
extern unsigned short (*v14) (signed short, unsigned int);
extern unsigned int v15 (signed char, signed char);
extern unsigned int (*v16) (signed char, signed char);
extern unsigned char v17 (void);
extern unsigned char (*v18) (void);
extern void v19 (signed int, signed short);
extern void (*v20) (signed int, signed short);
extern unsigned int v21 (signed short, signed char, signed int, unsigned int);
extern unsigned int (*v22) (signed short, signed char, signed int, unsigned int);
extern void v23 (unsigned int, signed int, unsigned char, signed int);
extern void (*v24) (unsigned int, signed int, unsigned char, signed int);
extern signed short v25 (signed int);
extern signed short (*v26) (signed int);
extern signed short v29 (unsigned int);
extern signed short (*v30) (unsigned int);
extern int history[];
extern int history_index;
extern int trace;
signed int v74 = 2;
signed char v73 = -4;
signed int v72 = -2;
