extern signed short v1 (signed short, signed short, unsigned char);
extern signed short (*v2) (signed short, signed short, unsigned char);
extern unsigned short v3 (signed int, signed int);
extern unsigned short (*v4) (signed int, signed int);
extern unsigned short v5 (unsigned int, signed int, unsigned char);
extern unsigned short (*v6) (unsigned int, signed int, unsigned char);
extern unsigned char v7 (void);
extern unsigned char (*v8) (void);
extern signed short v9 (unsigned int);
extern signed short (*v10) (unsigned int);
extern signed short v11 (void);
extern signed short (*v12) (void);
extern unsigned short v13 (unsigned int);
extern unsigned short (*v14) (unsigned int);
extern void v15 (void);
extern void (*v16) (void);
extern signed int v17 (unsigned int, unsigned short, unsigned int);
extern signed int (*v18) (unsigned int, unsigned short, unsigned int);
extern signed int v19 (void);
extern signed int (*v20) (void);
extern unsigned short v21 (signed int, signed char, signed int);
extern unsigned short (*v22) (signed int, signed char, signed int);
extern signed int v23 (unsigned int);
extern signed int (*v24) (unsigned int);
extern signed short v25 (signed char, unsigned short, unsigned char);
extern signed short (*v26) (signed char, unsigned short, unsigned char);
extern void v27 (signed int, signed short, signed short);
extern void (*v28) (signed int, signed short, signed short);
extern signed short v29 (void);
extern signed short (*v30) (void);
extern int history[];
extern int history_index;
extern int trace;
unsigned short v132 = 4;
signed char v131 = 0;
unsigned char v130 = 0;
