DIMENSION IDATA(5), NDATA(5)
WRITE(15) (I,I=1,5)
WRITE(15) (J,J=6,10)
BACKSPACE 15
READ(15)IDATA
BACKSPACE 15
READ(15)NDATA
DO I=1,5
  IF (IDATA(i) .NE. NDATA(i)) THEN
    CONTINUE
  ENDIF
  IF (I .EQ. 5) PRINT *,'*** ok ***'
END DO
CLOSE(15,STATUS='DELETE')
END
