DIMENSION IDATA(5), NDATA(5)
WRITE(1) (I,I=1,5)
WRITE(1) (J,J=6,10)
BACKSPACE 1
READ(1)IDATA
BACKSPACE 1
READ(1)NDATA
DO I=1,5
  IF (IDATA(i) .NE. NDATA(i)) THEN
    CONTINUE
  ENDIF
  IF (I .EQ. 5) PRINT *,'*** ok ***'
END DO
CLOSE(1,STATUS='DELETE')
END
