DIMENSION IDATA(5), NDATA(5)
DATA IDATA/1,2,3,4,5/
WRITE(1) (I,I=6,10)
WRITE(1) IDATA
BACKSPACE 1
READ(1)NDATA
DO I=1,5
  IF (IDATA(I) .NE. NDATA(I)) CONTINUE
  IF (I .EQ. 5) PRINT *,'*** ok ***'
ENDDO
CLOSE(1,STATUS='DELETE')
END
