DIMENSION IDATA(5), NDATA(5)
DATA IDATA/1,2,3,4,5/
WRITE(16) (I,I=6,10)
WRITE(16) IDATA
BACKSPACE 16
READ(16)NDATA
DO I=1,5
  IF (IDATA(I) .NE. NDATA(I)) CONTINUE
  IF (I .EQ. 5) PRINT *,'*** ok ***'
ENDDO
CLOSE(16,STATUS='DELETE')
END
