MODULE MOD1
  TYPE TY(k1,k2)
     INTEGER,KIND::k1,k2
     INTEGER::arr(k1+k2)=3
     INTEGER::arr1(k1+2)=8
     INTEGER::arr2(k1+2,k1+k2)= 5
   END TYPE
END MODULE 
PROGRAM MAIN
USE MOD1
IMPLICIT NONE
TYPE(TY(2,4))::obj
IF(SIZE(obj%arr) .eq. 6)THEN
 PRINT*,"PASS"
ELSE
 PRINT*,"ERROR"
ENDIF
END PROGRAM
