extern unsigned short v1 (unsigned short, unsigned short, unsigned int);
extern unsigned short (*v2) (unsigned short, unsigned short, unsigned int);
extern signed int v3 (signed int);
extern signed int (*v4) (signed int);
extern unsigned char v5 (unsigned int);
extern unsigned char (*v6) (unsigned int);
extern signed short v7 (signed int);
extern signed short (*v8) (signed int);
extern void v9 (void);
extern void (*v10) (void);
extern void v11 (unsigned int, signed char);
extern void (*v12) (unsigned int, signed char);
extern signed char v13 (signed short, unsigned short, signed int);
extern signed char (*v14) (signed short, unsigned short, signed int);
extern unsigned char v15 (void);
extern unsigned char (*v16) (void);
extern signed short v17 (signed char);
extern signed short (*v18) (signed char);
extern signed int v19 (signed int, signed int, signed int, signed int);
extern signed int (*v20) (signed int, signed int, signed int, signed int);
extern signed char v21 (unsigned short, unsigned char, unsigned char);
extern signed char (*v22) (unsigned short, unsigned char, unsigned char);
extern void v23 (signed short, unsigned char);
extern void (*v24) (signed short, unsigned char);
extern unsigned short v25 (signed char);
extern unsigned short (*v26) (signed char);
extern signed short v29 (signed int);
extern signed short (*v30) (signed int);
extern int history[];
extern int history_index;
extern int trace;
signed short v78 = -1;
signed char v77 = -4;
unsigned int v76 = 1U;
