PURE FUNCTION F() RESULT(RES)
 INTEGER, POINTER :: RES
 ALLOCATE(RES)
 RES=2
END FUNCTION F

PURE SUBROUTINE S1(F,*,*)
 INTERFACE
  PURE FUNCTION F() RESULT(RES)
   INTEGER, POINTER :: RES
  END FUNCTION F
 END INTERFACE
 RETURN F()
END SUBROUTINE

PROGRAM TEST
   INTERFACE
    PURE FUNCTION F() RESULT(RES)
     INTEGER, POINTER :: RES
    END FUNCTION F
   END INTERFACE


   INTERFACE
    PURE SUBROUTINE S1(F,*,*)
      INTERFACE
       PURE FUNCTION F() RESULT(RES)
        INTEGER, POINTER :: RES
       END FUNCTION F
      END INTERFACE
     END SUBROUTINE
   END INTERFACE


   do 3, concurrent (i=1:3, i ==2)
   CALL S1(F,*1,*2)

   1 CONTINUE

   print *,'fail'
   GOTO 3
   2 CONTINUE
   print *,'PASS'
   3 CONTINUE
END

