extern signed int v3 (unsigned int, unsigned int, signed int);
extern signed int (*v4) (unsigned int, unsigned int, signed int);
extern unsigned int v5 (unsigned int);
extern unsigned int (*v6) (unsigned int);
extern signed char v7 (signed char, unsigned short);
extern signed char (*v8) (signed char, unsigned short);
extern void v9 (signed short);
extern void (*v10) (signed short);
extern unsigned char v11 (signed int, unsigned int);
extern unsigned char (*v12) (signed int, unsigned int);
extern signed char v13 (unsigned char);
extern signed char (*v14) (unsigned char);
extern void v15 (unsigned short, signed short, signed int);
extern void (*v16) (unsigned short, signed short, signed int);
extern unsigned int v17 (signed char);
extern unsigned int (*v18) (signed char);
extern unsigned int v19 (void);
extern unsigned int (*v20) (void);
extern unsigned int v21 (signed short, signed char, signed char);
extern unsigned int (*v22) (signed short, signed char, signed char);
extern unsigned short v23 (unsigned char);
extern unsigned short (*v24) (unsigned char);
extern signed short v25 (unsigned short, unsigned char, signed int, signed int);
extern signed short (*v26) (unsigned short, unsigned char, signed int, signed int);
extern unsigned short v29 (unsigned char, signed short, signed int, signed short);
extern unsigned short (*v30) (unsigned char, signed short, signed int, signed short);
extern int history[];
extern int history_index;
extern int trace;
signed int v146 = 0;
unsigned int v145 = 4U;
signed short v144 = -4;
