extern unsigned short v3 (unsigned char, signed char, unsigned int);
extern unsigned short (*v4) (unsigned char, signed char, unsigned int);
extern unsigned short v5 (void);
extern unsigned short (*v6) (void);
extern void v7 (signed int, signed int);
extern void (*v8) (signed int, signed int);
extern unsigned char v9 (signed short);
extern unsigned char (*v10) (signed short);
extern unsigned short v11 (signed short, signed int);
extern unsigned short (*v12) (signed short, signed int);
extern signed char v13 (unsigned char, signed int, signed short);
extern signed char (*v14) (unsigned char, signed int, signed short);
extern signed int v15 (unsigned int, unsigned int, signed int, signed int);
extern signed int (*v16) (unsigned int, unsigned int, signed int, signed int);
extern unsigned char v17 (signed char);
extern unsigned char (*v18) (signed char);
extern signed short v19 (unsigned int, unsigned int, unsigned short);
extern signed short (*v20) (unsigned int, unsigned int, unsigned short);
extern unsigned short v23 (signed int, unsigned char, unsigned int, signed int);
extern unsigned short (*v24) (signed int, unsigned char, unsigned int, signed int);
extern unsigned short v27 (unsigned int, signed short, signed int);
extern unsigned short (*v28) (unsigned int, signed short, signed int);
extern unsigned int v29 (signed char, signed short);
extern unsigned int (*v30) (signed char, signed short);
extern int history[];
extern int history_index;
extern int trace;
unsigned int v71 = 4U;
signed int v70 = -4;
unsigned char v69 = 0;
