extern unsigned short v1 (unsigned int, unsigned short, unsigned int, signed char);
extern unsigned short (*v2) (unsigned int, unsigned short, unsigned int, signed char);
extern void v3 (unsigned short, signed short, signed int, unsigned char);
extern void (*v4) (unsigned short, signed short, signed int, unsigned char);
extern unsigned short v5 (void);
extern unsigned short (*v6) (void);
extern void v7 (unsigned char, signed int);
extern void (*v8) (unsigned char, signed int);
extern void v11 (signed int);
extern void (*v12) (signed int);
extern signed short v13 (void);
extern signed short (*v14) (void);
extern signed char v15 (unsigned short);
extern signed char (*v16) (unsigned short);
extern signed int v17 (unsigned int, signed short, signed int, unsigned char);
extern signed int (*v18) (unsigned int, signed short, signed int, unsigned char);
extern unsigned short v19 (unsigned int);
extern unsigned short (*v20) (unsigned int);
extern unsigned short v21 (signed short, signed short);
extern unsigned short (*v22) (signed short, signed short);
extern signed short v23 (void);
extern signed short (*v24) (void);
extern unsigned int v25 (void);
extern unsigned int (*v26) (void);
extern unsigned int v27 (unsigned char, unsigned char);
extern unsigned int (*v28) (unsigned char, unsigned char);
extern signed char v29 (unsigned short);
extern signed char (*v30) (unsigned short);
extern int history[];
extern int history_index;
extern int trace;
signed short v49 = -1;
signed short v48 = 3;
unsigned char v47 = 0;
