write(8,'("&
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx&
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx&
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx&
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx&
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx&
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx&
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx&
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx&
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx&
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx&
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx&
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx&
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx&
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx&
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx&
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx&
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx&
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx&
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx&
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx&
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx&
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx&
" )') 
print  *,'pass'
end 
