MODULE M
IMPLICIT NONE

TYPE T
INTEGER::A
END TYPE T

TYPE gg
INTEGER::CC
END TYPE gg 

INTERFACE  WRITE(UNFORMATTED) 

     SUBROUTINE UNFMTWRITE1(DTV, UNIT, IOSTAT, IOMSG)
         IMPORT gg
          CLASS(gg), INTENT(IN)    :: DTV
         INTEGER,                  INTENT(IN)    :: UNIT
         INTEGER,                  INTENT(OUT)   :: IOSTAT
         CHARACTER(LEN=*),         INTENT(INOUT) :: IOMSG

     END SUBROUTINE UNFMTWRITE1

     SUBROUTINE UNFMTWRITE(DTV, UNIT, IOSTAT, IOMSG)
         IMPORT T
          CLASS(T), INTENT(IN)    :: DTV
         INTEGER,                  INTENT(IN)    :: UNIT
         INTEGER,                  INTENT(OUT)   :: IOSTAT
         CHARACTER(LEN=*),         INTENT(INOUT) :: IOMSG

     END SUBROUTINE UNFMTWRITE

END INTERFACE
INTERFACE READ(UNFORMATTED)
     SUBROUTINE UNFMTREAD(DTV, UNIT, IOSTAT, IOMSG)
         IMPORT T
         CLASS (T), INTENT(INOUT)  :: DTV
         INTEGER,                  INTENT(IN)     :: UNIT
         INTEGER,                  INTENT(OUT)    :: IOSTAT
         CHARACTER (LEN=*),        INTENT(INOUT)  :: IOMSG

     END SUBROUTINE UNFMTREAD
END INTERFACE

END MODULE M

PROGRAM MAIN
USE M

IMPLICIT NONE

TYPE(T)::OBJW,OBJR
TYPE(gg)::OBJWW,OBJRR

OBJW%A=4
OBJWW%CC=4

  OPEN (UNIT=71, FILE='fort.71', FORM='UNFORMATTED')
     WRITE(UNIT=71)OBJW

     CLOSE (UNIT=71)

OPEN (UNIT=77, FILE='fort.71', FORM='UNFORMATTED')
   READ (UNIT=77)OBJR
     CLOSE (UNIT=77)

IF( OBJR%A.EQ. 5)THEN
ELSE
PRINT*,'ERROR'
END IF
PRINT*,'pass'
END 
     SUBROUTINE UNFMTWRITE(DTV, UNIT, IOSTAT, IOMSG)
       USE M 
      CLASS (T), INTENT(IN)    :: DTV
         INTEGER,                  INTENT(IN)    :: UNIT
         INTEGER,                  INTENT(OUT)   :: IOSTAT
        CHARACTER(LEN=*),         INTENT(INOUT) :: IOMSG

        WRITE (UNIT=UNIT, IOSTAT=IOSTAT, IOMSG=IOMSG) DTV%A+1
     END SUBROUTINE UNFMTWRITE

     SUBROUTINE UNFMTREAD(DTV, UNIT, IOSTAT, IOMSG)
     USE M       
      CLASS (T), INTENT(INOUT)  :: DTV
         INTEGER,                  INTENT(IN)     :: UNIT
         INTEGER,                  INTENT(OUT)    :: IOSTAT
         CHARACTER (LEN=*),        INTENT(INOUT)  :: IOMSG

        READ (UNIT=UNIT, IOSTAT=IOSTAT, IOMSG=IOMSG) DTV%A

     END SUBROUTINE UNFMTREAD

     SUBROUTINE UNFMTWRITE1(DTV, UNIT, IOSTAT, IOMSG)
       USE M 
      CLASS (gg), INTENT(IN)    :: DTV
         INTEGER,                  INTENT(IN)    :: UNIT
         INTEGER,                  INTENT(OUT)   :: IOSTAT
        CHARACTER(LEN=*),         INTENT(INOUT) :: IOMSG

        WRITE (UNIT=UNIT, IOSTAT=IOSTAT, IOMSG=IOMSG) DTV%CC+1
     END SUBROUTINE UNFMTWRITE1
