extern void v3 (unsigned int, unsigned int, unsigned int);
extern void (*v4) (unsigned int, unsigned int, unsigned int);
extern signed short v5 (void);
extern signed short (*v6) (void);
extern signed char v7 (unsigned char, signed char, unsigned short, unsigned int);
extern signed char (*v8) (unsigned char, signed char, unsigned short, unsigned int);
extern unsigned int v9 (signed int, signed short, unsigned short);
extern unsigned int (*v10) (signed int, signed short, unsigned short);
extern signed char v13 (unsigned short, signed char);
extern signed char (*v14) (unsigned short, signed char);
extern signed int v15 (unsigned char, unsigned short, unsigned int);
extern signed int (*v16) (unsigned char, unsigned short, unsigned int);
extern signed int v19 (signed int, signed short, unsigned char, unsigned int);
extern signed int (*v20) (signed int, signed short, unsigned char, unsigned int);
extern signed short v23 (signed short, unsigned int);
extern signed short (*v24) (signed short, unsigned int);
extern signed char v25 (unsigned short, signed char, unsigned int);
extern signed char (*v26) (unsigned short, signed char, unsigned int);
extern unsigned char v27 (signed int, unsigned short, signed int, unsigned short);
extern unsigned char (*v28) (signed int, unsigned short, signed int, unsigned short);
extern signed short v29 (signed int);
extern signed short (*v30) (signed int);
extern int history[];
extern int history_index;
extern int trace;
signed char v105 = 0;
signed short v104 = -1;
unsigned short v103 = 6;
