      call test01()
      call test02()
      print *,'pass'
      end 
#define DDDAAA XXXX
#define AAA MMMMMMMMMM
#define VVVCCC YY
      subroutine test01()
      integer :: DDDAAA,VVVCCC
      parameter   
     1(DDD
     1A
     1A
     1A=1)
      data VVVCCC  /DDDAAA*DDDAAA/
      if (VVVCCC.ne.1) print *,'fail'
      end

      subroutine test02()
      integer :: DDDAAA,VVVCCC,AAA
      parameter (AAA=1)
      parameter (DDDAAA=1) 
C23456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345
C       10        20        30        40        50        60        70        80        90       100       110       120       130       140       150       160       170       180       190       200       210       220       230       240       250  255
      parameter   
     1(                                                                                                                                                                                                                                                    DDD 
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1A
     1A
     1A=1                                                          ,y=1)
      data VVVCCC  /XXXX*MMMMMMMMMM/
      if (VVVCCC.ne.y) print *,'fail'
      end
      subroutine test03()
      integer :: DDDAAA,VVVCCC,AAA
      parameter (AAA=1)
      parameter (DDDAAA=1)
C23456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345
C       10        20        30        40        50        60        70        80        90       100       110       120       130       140       150       160       170       180       190       200       210       220       230       240       250  255
      parameter   
     1(                                                                                                                                                                                                                                                      DDD
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1!sssss DDDAAA
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1
     1A
     1A
     1A=1                                                          ,y=1)
      data VVVCCC  /XXXX*MMMMMMMMMM/
      if (VVVCCC.ne.y) print *,'fail'
      end
