extern void v1 (signed short, signed char);
extern void (*v2) (signed short, signed char);
extern unsigned short v3 (unsigned short);
extern unsigned short (*v4) (unsigned short);
extern void v5 (signed int);
extern void (*v6) (signed int);
extern void v7 (void);
extern void (*v8) (void);
extern unsigned int v9 (signed char, unsigned short, unsigned char, signed char);
extern unsigned int (*v10) (signed char, unsigned short, unsigned char, signed char);
extern unsigned int v11 (void);
extern unsigned int (*v12) (void);
extern void v13 (unsigned char, signed short);
extern void (*v14) (unsigned char, signed short);
extern signed short v15 (signed int, signed short, unsigned short);
extern signed short (*v16) (signed int, signed short, unsigned short);
extern unsigned char v17 (signed char, signed int);
extern unsigned char (*v18) (signed char, signed int);
extern unsigned char v19 (signed char, signed char, signed int);
extern unsigned char (*v20) (signed char, signed char, signed int);
extern unsigned short v21 (unsigned short, signed int);
extern unsigned short (*v22) (unsigned short, signed int);
extern unsigned char v23 (void);
extern unsigned char (*v24) (void);
extern void v25 (signed char, unsigned short);
extern void (*v26) (signed char, unsigned short);
extern signed short v27 (signed int);
extern signed short (*v28) (signed int);
extern signed int v29 (signed char, signed char, unsigned int);
extern signed int (*v30) (signed char, signed char, unsigned int);
extern int history[];
extern int history_index;
extern int trace;
unsigned int v136 = 0U;
unsigned short v135 = 0;
unsigned char v134 = 5;
