set(openmp_tests
  0044_0078
  0044_0079
  0044_0080
  0044_0081
  0044_0082
  0044_0083
  0044_0084
  0044_0085
  0044_0086
  0044_0087
  0044_0099
  0044_0131
  0044_0132
  0044_0133
  0044_0134
  0044_0135
  0044_0136
)
add_subdirectory(0044_0072)
llvm_singlesource_fujitsu(PREFIX "Fujitsu-C++-")
if(TEST_SUITE_FUJITSU_ENABLE_${llvm_test_lang}_NON_OPENMP)
  set_property(SOURCE 0044_0007.cc APPEND PROPERTY COMPILE_OPTIONS "-std=c++11")
  set_property(SOURCE 0044_0015.cc APPEND PROPERTY COMPILE_OPTIONS "-std=c++03")
  set_property(SOURCE 0044_0017.cc APPEND PROPERTY COMPILE_OPTIONS "-std=c++03")
  set_property(SOURCE 0044_0028.cc APPEND PROPERTY COMPILE_OPTIONS "-std=c++11")
  set_property(SOURCE 0044_0029.cc APPEND PROPERTY COMPILE_OPTIONS "-std=c++11")
  set_property(SOURCE 0044_0106.cc APPEND PROPERTY COMPILE_OPTIONS "-std=c++03")
  set_property(SOURCE 0044_0113.cc APPEND PROPERTY COMPILE_OPTIONS "-std=c++03")
  set_property(SOURCE 0044_0114.cc APPEND PROPERTY COMPILE_OPTIONS "-std=c++03")
  set_property(SOURCE 0044_0115.cc APPEND PROPERTY COMPILE_OPTIONS "-std=c++03")
  set_property(SOURCE 0044_0116.cc APPEND PROPERTY COMPILE_OPTIONS "-std=c++03")
  set_property(SOURCE 0044_0117.cc APPEND PROPERTY COMPILE_OPTIONS "-std=c++03")
  set_property(SOURCE 0044_0118.cc APPEND PROPERTY COMPILE_OPTIONS "-std=c++03")
  set_property(SOURCE 0044_0119.cc APPEND PROPERTY COMPILE_OPTIONS "-std=c++03")
  set_property(SOURCE 0044_0120.cc APPEND PROPERTY COMPILE_OPTIONS "-std=c++03")
  set_property(SOURCE 0044_0121.cc APPEND PROPERTY COMPILE_OPTIONS "-std=c++03")
  set_property(SOURCE 0044_0126.cc APPEND PROPERTY COMPILE_OPTIONS "-std=c++03")
endif()
