extern unsigned char v1 (unsigned char, signed int, unsigned char, unsigned short);
extern unsigned char (*v2) (unsigned char, signed int, unsigned char, unsigned short);
extern signed char v3 (unsigned int, signed int);
extern signed char (*v4) (unsigned int, signed int);
extern unsigned char v5 (void);
extern unsigned char (*v6) (void);
extern void v7 (void);
extern void (*v8) (void);
extern unsigned int v9 (void);
extern unsigned int (*v10) (void);
extern signed char v11 (void);
extern signed char (*v12) (void);
extern signed char v13 (signed int, signed char, unsigned int, unsigned char);
extern signed char (*v14) (signed int, signed char, unsigned int, unsigned char);
extern unsigned int v17 (unsigned char, signed short, signed char);
extern unsigned int (*v18) (unsigned char, signed short, signed char);
extern signed int v19 (signed short, signed short, unsigned short);
extern signed int (*v20) (signed short, signed short, unsigned short);
extern unsigned int v21 (signed short, unsigned short, unsigned char, unsigned short);
extern unsigned int (*v22) (signed short, unsigned short, unsigned char, unsigned short);
extern signed char v23 (void);
extern signed char (*v24) (void);
extern signed int v25 (signed int, signed char, unsigned int);
extern signed int (*v26) (signed int, signed char, unsigned int);
extern signed short v27 (signed char);
extern signed short (*v28) (signed char);
extern void v29 (unsigned int);
extern void (*v30) (unsigned int);
extern int history[];
extern int history_index;
extern int trace;
unsigned char v92 = 7;
unsigned short v91 = 6;
signed char v90 = 2;
