extern unsigned int v1 (unsigned char, signed char, unsigned int);
extern unsigned int (*v2) (unsigned char, signed char, unsigned int);
extern unsigned int v3 (void);
extern unsigned int (*v4) (void);
extern signed char v5 (void);
extern signed char (*v6) (void);
extern signed short v7 (void);
extern signed short (*v8) (void);
extern unsigned int v9 (unsigned char, signed short, unsigned char);
extern unsigned int (*v10) (unsigned char, signed short, unsigned char);
extern signed short v11 (signed int, signed int, unsigned int, signed char);
extern signed short (*v12) (signed int, signed int, unsigned int, signed char);
extern unsigned short v13 (void);
extern unsigned short (*v14) (void);
extern unsigned short v15 (unsigned short, unsigned short);
extern unsigned short (*v16) (unsigned short, unsigned short);
extern unsigned int v17 (signed char, unsigned char);
extern unsigned int (*v18) (signed char, unsigned char);
extern unsigned char v19 (signed char);
extern unsigned char (*v20) (signed char);
extern signed int v21 (signed char, signed char, unsigned short, unsigned short);
extern signed int (*v22) (signed char, signed char, unsigned short, unsigned short);
extern unsigned int v23 (void);
extern unsigned int (*v24) (void);
extern signed int v25 (unsigned char, signed short);
extern signed int (*v26) (unsigned char, signed short);
extern signed int v27 (unsigned short, signed char, signed int, signed int);
extern signed int (*v28) (unsigned short, signed char, signed int, signed int);
extern signed short v29 (unsigned char, signed char, unsigned short, signed int);
extern signed short (*v30) (unsigned char, signed char, unsigned short, signed int);
extern int history[];
extern int history_index;
extern int trace;
unsigned int v66 = 6U;
signed char v65 = -3;
signed int v64 = -3;
