extern void v1 (signed char, signed int, signed int);
extern void (*v2) (signed char, signed int, signed int);
extern unsigned int v3 (unsigned short);
extern unsigned int (*v4) (unsigned short);
extern void v5 (signed char, signed char, unsigned int, unsigned int);
extern void (*v6) (signed char, signed char, unsigned int, unsigned int);
extern unsigned int v7 (unsigned int, unsigned int, signed int, unsigned short);
extern unsigned int (*v8) (unsigned int, unsigned int, signed int, unsigned short);
extern unsigned char v9 (signed int, signed short);
extern unsigned char (*v10) (signed int, signed short);
extern signed short v13 (unsigned short, unsigned char, signed char);
extern signed short (*v14) (unsigned short, unsigned char, signed char);
extern signed int v15 (unsigned char, signed short, unsigned char, unsigned char);
extern signed int (*v16) (unsigned char, signed short, unsigned char, unsigned char);
extern void v17 (void);
extern void (*v18) (void);
extern unsigned int v19 (signed int, signed short, unsigned int, signed short);
extern unsigned int (*v20) (signed int, signed short, unsigned int, signed short);
extern void v21 (void);
extern void (*v22) (void);
extern void v23 (void);
extern void (*v24) (void);
extern signed short v27 (void);
extern signed short (*v28) (void);
extern signed char v29 (signed int, unsigned int);
extern signed char (*v30) (signed int, unsigned int);
extern int history[];
extern int history_index;
extern int trace;
signed short v79 = -4;
signed int v78 = 1;
signed short v77 = -4;
