call internal_sub01(3,2)

contains

 subroutine internal_sub01(dmy_i4_01,dmy_i4_02)

  integer (kind = 4)           :: dmy_i4_01
  integer (kind = 4),target    :: dmy_i4_02
  integer (kind = 4),parameter :: prm_i4_01 = 5

  integer (kind = 4),pointer   :: pnt_i4_01

  character                    :: cha_01
  character(len = 7)           :: cha_02
  character(len = prm_i4_01)   :: cha_03
  character(len = dmy_i4_01)   :: cha_04

  pnt_i4_01 => dmy_i4_02

  print *,[[cha_01], [cha_01]]
  print *,[[cha_01], [cha_02]]
  print *,[[cha_01], [cha_03]]
  print *,[[cha_01], [cha_04]]

  print *,[[character (len(cha_01)) :: 'abcdefg'], [cha_01]]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [cha_02]]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [cha_03]]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [cha_04]]

  print *,[[cha_01], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_01], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_01], [character (pnt_i4_01)   :: 'abcdefg']]

  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]

  print *,[[cha_02], [cha_01]]
  print *,[[cha_02], [cha_02]]
  print *,[[cha_02], [cha_03]]
  print *,[[cha_02], [cha_04]]

  print *,[[character (len(cha_02)) :: 'abcdefg'], [cha_01]]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [cha_02]]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [cha_03]]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [cha_04]]

  print *,[[cha_02], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_02], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_02], [character (pnt_i4_01)   :: 'abcdefg']]

  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]

  print *,[[cha_03], [cha_01]]
  print *,[[cha_03], [cha_02]]
  print *,[[cha_03], [cha_03]]
  print *,[[cha_03], [cha_04]]

  print *,[[character (len(cha_03)) :: 'abcdefg'], [cha_01]]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [cha_02]]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [cha_03]]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [cha_04]]

  print *,[[cha_03], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_03], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_03], [character (pnt_i4_01)   :: 'abcdefg']]

  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]

  print *,[[cha_04], [cha_01]]
  print *,[[cha_04], [cha_02]]
  print *,[[cha_04], [cha_03]]
  print *,[[cha_04], [cha_04]]

  print *,[[character (len(cha_04)) :: 'abcdefg'], [cha_01]]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [cha_02]]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [cha_03]]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [cha_04]]

  print *,[[cha_04], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_04], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_04], [character (pnt_i4_01)   :: 'abcdefg']]

  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]

  print *,[[cha_01], [cha_01], [cha_01]]
  print *,[[cha_01], [cha_01], [cha_02]]
  print *,[[cha_01], [cha_01], [cha_03]]
  print *,[[cha_01], [cha_01], [cha_04]]
  print *,[[cha_01], [cha_02], [cha_01]]
  print *,[[cha_01], [cha_02], [cha_02]]
  print *,[[cha_01], [cha_02], [cha_03]]
  print *,[[cha_01], [cha_02], [cha_04]]
  print *,[[cha_01], [cha_03], [cha_01]]
  print *,[[cha_01], [cha_03], [cha_02]]
  print *,[[cha_01], [cha_03], [cha_03]]
  print *,[[cha_01], [cha_03], [cha_04]]
  print *,[[cha_01], [cha_04], [cha_01]]
  print *,[[cha_01], [cha_04], [cha_02]]
  print *,[[cha_01], [cha_04], [cha_03]]
  print *,[[cha_01], [cha_04], [cha_04]]

  print *,[[character (len(cha_01)) :: 'abcdefg'], [cha_01], [cha_01]]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [cha_01], [cha_02]]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [cha_01], [cha_03]]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [cha_01], [cha_04]]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [cha_02], [cha_01]]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [cha_02], [cha_02]]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [cha_02], [cha_03]]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [cha_02], [cha_04]]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [cha_03], [cha_01]]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [cha_03], [cha_02]]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [cha_03], [cha_03]]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [cha_03], [cha_04]]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [cha_04], [cha_01]]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [cha_04], [cha_02]]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [cha_04], [cha_03]]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [cha_04], [cha_04]]

  print *,[[cha_01], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_01)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_01)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_02)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_02)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_03)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_03)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_04)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_01], [character (len(cha_04)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[cha_01], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_01], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_01], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_01], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_01], [character (dmy_i4_01)   :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_01], [character (dmy_i4_01)   :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[cha_01], [character (pnt_i4_01)   :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_01], [character (pnt_i4_01)   :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_01], [character (pnt_i4_01)   :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_01], [character (pnt_i4_01)   :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_01], [character (pnt_i4_01)   :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_01], [character (pnt_i4_01)   :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]

  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_01)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]

  print *,[[cha_02], [cha_01], [cha_01]]
  print *,[[cha_02], [cha_01], [cha_02]]
  print *,[[cha_02], [cha_01], [cha_03]]
  print *,[[cha_02], [cha_01], [cha_04]]
  print *,[[cha_02], [cha_02], [cha_01]]
  print *,[[cha_02], [cha_02], [cha_02]]
  print *,[[cha_02], [cha_02], [cha_03]]
  print *,[[cha_02], [cha_02], [cha_04]]
  print *,[[cha_02], [cha_03], [cha_01]]
  print *,[[cha_02], [cha_03], [cha_02]]
  print *,[[cha_02], [cha_03], [cha_03]]
  print *,[[cha_02], [cha_03], [cha_04]]
  print *,[[cha_02], [cha_04], [cha_01]]
  print *,[[cha_02], [cha_04], [cha_02]]
  print *,[[cha_02], [cha_04], [cha_03]]
  print *,[[cha_02], [cha_04], [cha_04]]

  print *,[[character (len(cha_02)) :: 'abcdefg'], [cha_01], [cha_01]]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [cha_01], [cha_02]]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [cha_01], [cha_03]]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [cha_01], [cha_04]]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [cha_02], [cha_01]]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [cha_02], [cha_02]]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [cha_02], [cha_03]]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [cha_02], [cha_04]]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [cha_03], [cha_01]]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [cha_03], [cha_02]]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [cha_03], [cha_03]]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [cha_03], [cha_04]]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [cha_04], [cha_01]]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [cha_04], [cha_02]]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [cha_04], [cha_03]]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [cha_04], [cha_04]]

  print *,[[cha_02], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_01)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_01)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_02)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_02)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_03)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_03)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_04)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_02], [character (len(cha_04)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[cha_02], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_02], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_02], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_02], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_02], [character (dmy_i4_01)   :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_02], [character (dmy_i4_01)   :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[cha_02], [character (pnt_i4_01)   :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_02], [character (pnt_i4_01)   :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_02], [character (pnt_i4_01)   :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_02], [character (pnt_i4_01)   :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_02], [character (pnt_i4_01)   :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_02], [character (pnt_i4_01)   :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]

  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_02)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]

  print *,[[cha_03], [cha_01], [cha_01]]
  print *,[[cha_03], [cha_01], [cha_02]]
  print *,[[cha_03], [cha_01], [cha_03]]
  print *,[[cha_03], [cha_01], [cha_04]]
  print *,[[cha_03], [cha_02], [cha_01]]
  print *,[[cha_03], [cha_02], [cha_02]]
  print *,[[cha_03], [cha_02], [cha_03]]
  print *,[[cha_03], [cha_02], [cha_04]]
  print *,[[cha_03], [cha_03], [cha_01]]
  print *,[[cha_03], [cha_03], [cha_02]]
  print *,[[cha_03], [cha_03], [cha_03]]
  print *,[[cha_03], [cha_03], [cha_04]]
  print *,[[cha_03], [cha_04], [cha_01]]
  print *,[[cha_03], [cha_04], [cha_02]]
  print *,[[cha_03], [cha_04], [cha_03]]
  print *,[[cha_03], [cha_04], [cha_04]]

  print *,[[character (len(cha_03)) :: 'abcdefg'], [cha_01], [cha_01]]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [cha_01], [cha_02]]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [cha_01], [cha_03]]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [cha_01], [cha_04]]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [cha_02], [cha_01]]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [cha_02], [cha_02]]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [cha_02], [cha_03]]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [cha_02], [cha_04]]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [cha_03], [cha_01]]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [cha_03], [cha_02]]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [cha_03], [cha_03]]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [cha_03], [cha_04]]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [cha_04], [cha_01]]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [cha_04], [cha_02]]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [cha_04], [cha_03]]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [cha_04], [cha_04]]

  print *,[[cha_03], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_01)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_01)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_02)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_02)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_03)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_03)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_04)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_03], [character (len(cha_04)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[cha_03], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_03], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_03], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_03], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_03], [character (dmy_i4_01)   :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_03], [character (dmy_i4_01)   :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[cha_03], [character (pnt_i4_01)   :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_03], [character (pnt_i4_01)   :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_03], [character (pnt_i4_01)   :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_03], [character (pnt_i4_01)   :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_03], [character (pnt_i4_01)   :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_03], [character (pnt_i4_01)   :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]

  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_03)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]

  print *,[[cha_04], [cha_01], [cha_01]]
  print *,[[cha_04], [cha_01], [cha_02]]
  print *,[[cha_04], [cha_01], [cha_03]]
  print *,[[cha_04], [cha_01], [cha_04]]
  print *,[[cha_04], [cha_02], [cha_01]]
  print *,[[cha_04], [cha_02], [cha_02]]
  print *,[[cha_04], [cha_02], [cha_03]]
  print *,[[cha_04], [cha_02], [cha_04]]
  print *,[[cha_04], [cha_03], [cha_01]]
  print *,[[cha_04], [cha_03], [cha_02]]
  print *,[[cha_04], [cha_03], [cha_03]]
  print *,[[cha_04], [cha_03], [cha_04]]
  print *,[[cha_04], [cha_04], [cha_01]]
  print *,[[cha_04], [cha_04], [cha_02]]
  print *,[[cha_04], [cha_04], [cha_03]]
  print *,[[cha_04], [cha_04], [cha_04]]

  print *,[[character (len(cha_04)) :: 'abcdefg'], [cha_01], [cha_01]]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [cha_01], [cha_02]]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [cha_01], [cha_03]]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [cha_01], [cha_04]]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [cha_02], [cha_01]]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [cha_02], [cha_02]]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [cha_02], [cha_03]]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [cha_02], [cha_04]]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [cha_03], [cha_01]]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [cha_03], [cha_02]]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [cha_03], [cha_03]]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [cha_03], [cha_04]]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [cha_04], [cha_01]]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [cha_04], [cha_02]]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [cha_04], [cha_03]]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [cha_04], [cha_04]]

  print *,[[cha_04], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_01)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_01)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_02)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_02)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_03)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_03)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_04)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_04], [character (len(cha_04)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[cha_04], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_04], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_04], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_04], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_04], [character (dmy_i4_01)   :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_04], [character (dmy_i4_01)   :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[cha_04], [character (pnt_i4_01)   :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[cha_04], [character (pnt_i4_01)   :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[cha_04], [character (pnt_i4_01)   :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[cha_04], [character (pnt_i4_01)   :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[cha_04], [character (pnt_i4_01)   :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[cha_04], [character (pnt_i4_01)   :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]

  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_01)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_02)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_03)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (len(cha_04)) :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg']]
  print *,[[character (len(cha_04)) :: 'abcdefg'], [character (dmy_i4_01)   :: 'abcdefg'], [character (pnt_i4_01)   :: 'abcdefg']]

 end subroutine

end
