	SUBROUTINE SUB1()
	INTEGER,PARAMETER::type=8
	INTEGER,PARAMETER::ltype=1
	INTEGER(KIND=type),PARAMETER::INDATA=9223372036854775807
	INTEGER(KIND=type)::I
	INTEGER(KIND=type),PARAMETER::ANS0=9223372036854775807
	INTEGER(KIND=type),PARAMETER::CALC0=ABS(INDATA)
	LOGICAL(KIND=ltype),PARAMETER::RES0=ANS0==CALC0
	INTEGER(KIND=type)::ANS
	I=INDATA
	ANS=ABS(I)
	if( .not.RES0 .or. ANS /= ANS0 ) print *,' NG 2'
	END
	SUBROUTINE SUB2()
	INTEGER,PARAMETER::type=8
	INTEGER,PARAMETER::ltype=1
	INTEGER(KIND=type),PARAMETER::INDATA=-9223372036854775807
	INTEGER(KIND=type)::I
	INTEGER(KIND=type),PARAMETER::ANS0=9223372036854775807
	INTEGER(KIND=type),PARAMETER::CALC0=ABS(INDATA)
	LOGICAL(KIND=ltype),PARAMETER::RES0=ANS0==CALC0
	INTEGER(KIND=type)::ANS
	I=INDATA
	ANS=ABS(I)
	if( .not.RES0 .or. ANS /= ANS0 ) print *,' NG 3'
	END
	SUBROUTINE SUB3()
	INTEGER,PARAMETER::type=8
	INTEGER,PARAMETER::ltype=4
	INTEGER(KIND=type),PARAMETER::INDATA=-9223372036854775806
	INTEGER(KIND=type)::I
	INTEGER(KIND=type),PARAMETER::ANS0=9223372036854775806
	INTEGER(KIND=type),PARAMETER::CALC0=ABS(INDATA)
	LOGICAL(KIND=ltype),PARAMETER::RES0=ANS0==CALC0
	INTEGER(KIND=type)::ANS
	I=INDATA
	ANS=ABS(I)
	if( .not.RES0 .or. ANS /= ANS0 ) print *,' NG 4'
	END
	SUBROUTINE SUB4()
	INTEGER,PARAMETER::type=8
	INTEGER,PARAMETER::ltype=4
	INTEGER(KIND=type),PARAMETER::INDATA=9223372036854775806
	INTEGER(KIND=type)::I
	INTEGER(KIND=type),PARAMETER::ANS0=9223372036854775806
	INTEGER(KIND=type),PARAMETER::CALC0=ABS(INDATA)
	LOGICAL(KIND=ltype),PARAMETER::RES0=ANS0==CALC0
	INTEGER(KIND=type)::ANS
	I=INDATA
	ANS=ABS(I)
	if( .not.RES0 .or. ANS /= ANS0 ) print *,' NG 5'
	END
	SUBROUTINE SUB5()
	INTEGER,PARAMETER::type=8
	INTEGER,PARAMETER::ltype=1
	INTEGER(KIND=type),PARAMETER::INDATA=9223372036854775805
	INTEGER(KIND=type)::I
	INTEGER(KIND=type),PARAMETER::ANS0=9223372036854775805
	INTEGER(KIND=type),PARAMETER::CALC0=ABS(INDATA)
	LOGICAL(KIND=ltype),PARAMETER::RES0=ANS0==CALC0
	INTEGER(KIND=type)::ANS
	I=INDATA
	ANS=ABS(I)
	if( .not.RES0 .or. ANS /= ANS0 ) print *,' NG 6'
	END
	SUBROUTINE SUB6()
	INTEGER,PARAMETER::type=8
	INTEGER,PARAMETER::ltype=4
	INTEGER(KIND=type),PARAMETER::INDATA=0
	INTEGER(KIND=type)::I
	INTEGER(KIND=type),PARAMETER::ANS0=0
	INTEGER(KIND=type),PARAMETER::CALC0=ABS(INDATA)
	LOGICAL(KIND=ltype),PARAMETER::RES0=ANS0==CALC0
	INTEGER(KIND=type)::ANS
	I=INDATA
	ANS=ABS(I)
	if( .not.RES0 .or. ANS /= ANS0 ) print *,' NG 7'
	END
	SUBROUTINE SUB7()
	INTEGER,PARAMETER::type=8
	INTEGER,PARAMETER::ltype=1
	INTEGER(KIND=type),PARAMETER::INDATA=1
	INTEGER(KIND=type)::I
	INTEGER(KIND=type),PARAMETER::ANS0=1
	INTEGER(KIND=type),PARAMETER::CALC0=ABS(INDATA)
	LOGICAL(KIND=ltype),PARAMETER::RES0=ANS0==CALC0
	INTEGER(KIND=type)::ANS
	I=INDATA
	ANS=ABS(I)
	if( .not.RES0 .or. ANS /= ANS0 ) print *,' NG 8'
	END
	SUBROUTINE SUB8()
	INTEGER,PARAMETER::type=8
	INTEGER,PARAMETER::ltype=4
	INTEGER(KIND=type),PARAMETER::INDATA=2
	INTEGER(KIND=type)::I
	INTEGER(KIND=type),PARAMETER::ANS0=2
	INTEGER(KIND=type),PARAMETER::CALC0=ABS(INDATA)
	LOGICAL(KIND=ltype),PARAMETER::RES0=ANS0==CALC0
	INTEGER(KIND=type)::ANS
	I=INDATA
	ANS=ABS(I)
	if( .not.RES0 .or. ANS /= ANS0 ) print *,' NG 9'
	END
	SUBROUTINE SUB9()
	INTEGER,PARAMETER::type=8
	INTEGER,PARAMETER::ltype=4
	INTEGER(KIND=type),PARAMETER::INDATA=0
	INTEGER(KIND=type)::I
	INTEGER(KIND=type),PARAMETER::ANS0=0
	INTEGER(KIND=type),PARAMETER::CALC0=ABS(INDATA)
	LOGICAL(KIND=ltype),PARAMETER::RES0=ANS0==CALC0
	INTEGER(KIND=type)::ANS
	I=INDATA
	ANS=ABS(I)
	if( .not.RES0 .or. ANS /= ANS0 ) print *,' NG 10'
	END
	SUBROUTINE SUB10()
	INTEGER,PARAMETER::type=8
	INTEGER,PARAMETER::ltype=1
	INTEGER(KIND=type),PARAMETER::INDATA=-1
	INTEGER(KIND=type)::I
	INTEGER(KIND=type),PARAMETER::ANS0=1
	INTEGER(KIND=type),PARAMETER::CALC0=ABS(INDATA)
	LOGICAL(KIND=ltype),PARAMETER::RES0=ANS0==CALC0
	INTEGER(KIND=type)::ANS
	I=INDATA
	ANS=ABS(I)
	if( .not.RES0 .or. ANS /= ANS0 ) print *,' NG 11'
	END
	SUBROUTINE SUB11()
	INTEGER,PARAMETER::type=8
	INTEGER,PARAMETER::ltype=4
	INTEGER(KIND=type),PARAMETER::INDATA=-2
	INTEGER(KIND=type)::I
	INTEGER(KIND=type),PARAMETER::ANS0=2
	INTEGER(KIND=type),PARAMETER::CALC0=ABS(INDATA)
	LOGICAL(KIND=ltype),PARAMETER::RES0=ANS0==CALC0
	INTEGER(KIND=type)::ANS
	I=INDATA
	ANS=ABS(I)
	if( .not.RES0 .or. ANS /= ANS0 ) print *,' NG 12'
	END
	SUBROUTINE SUB12()
	INTEGER,PARAMETER::type=8
	INTEGER,PARAMETER::ltype=1
	INTEGER(KIND=type),PARAMETER::INDATA=2147483647
	INTEGER(KIND=type)::I
	INTEGER(KIND=type),PARAMETER::ANS0=2147483647
	INTEGER(KIND=type),PARAMETER::CALC0=ABS(INDATA)
	LOGICAL(KIND=ltype),PARAMETER::RES0=ANS0==CALC0
	INTEGER(KIND=type)::ANS
	I=INDATA
	ANS=ABS(I)
	if( .not.RES0 .or. ANS /= ANS0 ) print *,' NG 13'
	END
	SUBROUTINE SUB13()
	INTEGER,PARAMETER::type=8
	INTEGER,PARAMETER::ltype=4
	INTEGER(KIND=type),PARAMETER::INDATA=-2147483648
	INTEGER(KIND=type)::I
	INTEGER(KIND=type),PARAMETER::ANS0=2147483648
	INTEGER(KIND=type),PARAMETER::CALC0=ABS(INDATA)
	LOGICAL(KIND=ltype),PARAMETER::RES0=ANS0==CALC0
	INTEGER(KIND=type)::ANS
	I=INDATA
	ANS=ABS(I)
	if( .not.RES0 .or. ANS /= ANS0 ) print *,' NG 14'
	END
	SUBROUTINE SUB14()
	INTEGER,PARAMETER::type=8
	INTEGER,PARAMETER::ltype=4
	INTEGER(KIND=type),PARAMETER::INDATA=2147483648
	INTEGER(KIND=type)::I
	INTEGER(KIND=type),PARAMETER::ANS0=2147483648
	INTEGER(KIND=type),PARAMETER::CALC0=ABS(INDATA)
	LOGICAL(KIND=ltype),PARAMETER::RES0=ANS0==CALC0
	INTEGER(KIND=type)::ANS
	I=INDATA
	ANS=ABS(I)
	if( .not.RES0 .or. ANS /= ANS0 ) print *,' NG 15'
	END
	SUBROUTINE SUB15()
	INTEGER,PARAMETER::type=8
	INTEGER,PARAMETER::ltype=1
	INTEGER(KIND=type),PARAMETER::INDATA=-2147483647
	INTEGER(KIND=type)::I
	INTEGER(KIND=type),PARAMETER::ANS0=2147483647
	INTEGER(KIND=type),PARAMETER::CALC0=ABS(INDATA)
	LOGICAL(KIND=ltype),PARAMETER::RES0=ANS0==CALC0
	INTEGER(KIND=type)::ANS
	I=INDATA
	ANS=ABS(I)
	if( .not.RES0 .or. ANS /= ANS0 ) print *,' NG 16'
	END
	SUBROUTINE SUB16()
	INTEGER,PARAMETER::type=8
	INTEGER,PARAMETER::ltype=4
	INTEGER(KIND=type),PARAMETER::INDATA=2147483646
	INTEGER(KIND=type)::I
	INTEGER(KIND=type),PARAMETER::ANS0=2147483646
	INTEGER(KIND=type),PARAMETER::CALC0=ABS(INDATA)
	LOGICAL(KIND=ltype),PARAMETER::RES0=ANS0==CALC0
	INTEGER(KIND=type)::ANS
	I=INDATA
	ANS=ABS(I)
	if( .not.RES0 .or. ANS /= ANS0 ) print *,' NG 17'
	END
	SUBROUTINE SUB17()
	INTEGER,PARAMETER::type=8
	INTEGER,PARAMETER::ltype=1
	INTEGER(KIND=type),PARAMETER::INDATA=-2147483649
	INTEGER(KIND=type)::I
	INTEGER(KIND=type),PARAMETER::ANS0=2147483649
	INTEGER(KIND=type),PARAMETER::CALC0=ABS(INDATA)
	LOGICAL(KIND=ltype),PARAMETER::RES0=ANS0==CALC0
	INTEGER(KIND=type)::ANS
	I=INDATA
	ANS=ABS(I)
	if( .not.RES0 .or. ANS /= ANS0 ) print *,' NG 18'
	END
	PROGRAM MAIN
	CALL SUB1()
	CALL SUB2()
	CALL SUB3()
	CALL SUB4()
	CALL SUB5()
	CALL SUB6()
	CALL SUB7()
	CALL SUB8()
	CALL SUB9()
	CALL SUB10()
	CALL SUB11()
	CALL SUB12()
	CALL SUB13()
	CALL SUB14()
	CALL SUB15()
	CALL SUB16()
	CALL SUB17()
	PRINT *,'  PASS  '
	END
