SUBROUTINE SUB16()
  IMPLICIT NONE
END SUBROUTINE SUB16

MODULE MOD16
  IMPLICIT NONE
interface
SUBROUTINE SUB16()
  IMPLICIT NONE
END SUBROUTINE SUB16
end interface
  TYPE :: A16
     PROCEDURE(), POINTER, NOPASS :: PROC16 => SUB16
  END TYPE A16
END MODULE MOD16

PROGRAM MAIN
  USE MOD16
  IMPLICIT NONE
  TYPE(A16) :: var_a16
  CALL var_a16%PROC16()
  print *, "pass"
END PROGRAM MAIN
