extern void v1 (void);
extern void (*v2) (void);
extern unsigned char v5 (void);
extern unsigned char (*v6) (void);
extern void v7 (unsigned char, unsigned int, unsigned short);
extern void (*v8) (unsigned char, unsigned int, unsigned short);
extern signed short v9 (signed int);
extern signed short (*v10) (signed int);
extern void v11 (void);
extern void (*v12) (void);
extern signed short v13 (signed int, signed int, unsigned char);
extern signed short (*v14) (signed int, signed int, unsigned char);
extern signed char v15 (signed char, unsigned char);
extern signed char (*v16) (signed char, unsigned char);
extern signed short v19 (void);
extern signed short (*v20) (void);
extern unsigned short v23 (unsigned char, unsigned char, unsigned int);
extern unsigned short (*v24) (unsigned char, unsigned char, unsigned int);
extern unsigned short v25 (unsigned int, unsigned short);
extern unsigned short (*v26) (unsigned int, unsigned short);
extern unsigned int v27 (signed char);
extern unsigned int (*v28) (signed char);
extern void v29 (unsigned int, signed short, signed short, signed short);
extern void (*v30) (unsigned int, signed short, signed short, signed short);
extern int history[];
extern int history_index;
extern int trace;
unsigned char v75 = 5;
unsigned int v74 = 0U;
signed int v73 = 3;
