#include <stdio.h>
#include <stdlib.h>


int suba (i) int i; {
                     return i*i;
} 
int sube (i) int i; {
                     return i+i;
} 
int subc () {
                     return 1;
} 
long long int subla (i) long long int i; {
                     return i*i;
} 
long long int suble (i) long long int i; {
                     return i+i;
} 
long long int sublc () {
                     return 1ll;
} 
int main( ) {
  long long int              aaa,bbb,ccc,ddd,eee,fff,subla( ),sublc( ),suble( );
  int              a,b,c,d,e,f,suba( ),subc( ),sube( );
  c = 0    ; 
                        a=suba(2);e=sube(2);c=subc(); 
  b = a    ;
  a = b + c + e;        
                        if(a==9) printf("**(01)** OK\n");
                        else     printf("**(01)** NG a=%d\n",a);
  a = b - c - e; 
                        if(a==-1) printf("**(02)** OK\n");
                        else     printf("**(02)** NG a=%d\n",a);
  a = b * c * e;
                        if(a==16) printf("**(03)** OK\n");
                        else     printf("**(03)** NG a=%d\n",a);
  a = b / c / e; 
                        if(a==1) printf("**(04)** OK\n");
                        else     printf("**(04)** NG a=%d\n",a);
  a = b % c % e; 
                        if(a==0) printf("**(05)** OK\n");
                        else     printf("**(05)** NG a=%d\n",a);
                        f=subc()+9;
                        b = 10 ; 
  a = 10 + f; 
                        if(a==20) printf("**(06)** OK\n");
                        else     printf("**(06)** NG a=%d\n",a);
  a = 10 - f; 
                        if(a==0) printf("**(07)** OK\n");
                        else     printf("**(07)** NG a=%d\n",a);
  a = 10 * f;
                        if(a==100) printf("**(08)** OK\n");
                        else     printf("**(08)** NG a=%d\n",a);
  a = 10 / f;
                        if(a== 1) printf("**(09)** OK\n");
                        else     printf("**(09)** NG a=%d\n",a);
  a = 10 % f; 
                        if(a== 0) printf("**(10)** OK\n");
                        else     printf("**(10)** NG a=%d\n",a);
                        e=sube(50);
  a = e + 100; 
                        if(a==200) printf("**(11)** OK\n");
                        else     printf("**(11)** NG a=%d\n",a);
  a = e - 100;
                        if(a==0) printf("**(12)** OK\n");
                        else     printf("**(12)** NG a=%d\n",a);
  a = e * 100; 
                        if(a==10000) printf("**(13)** OK\n");
                        else     printf("**(13)** NG a=%d\n",a);
  a = e / 100; 
                        if(a==1) printf("**(14)** OK\n");
                        else     printf("**(14)** NG a=%d\n",a);
  b = e % 100;
                        if(b==0) printf("**(15)** OK\n");
                        else     printf("**(15)** NG b=%d\n",b);
                        b=subc();
  a = b * 1;            
                        if(a==1) printf("**(16)** OK\n");
                        else     printf("**(16)** NG a=%d\n",a);
  a = b * 2;            
                        if(a==2) printf("**(17)** OK\n");
                        else     printf("**(17)** NG a=%d\n",a);
  a = b * 4;            
                        if(a==4) printf("**(18)** OK\n");
                        else     printf("**(18)** NG a=%d\n",a);
  a = b * 8;           
                        if(a==8) printf("**(19)** OK\n");
                        else     printf("**(19)** NG a=%d\n",a);
  a = b * 16;         
                        if(a==16) printf("**(20)** OK\n");
                        else      printf("**(20)** NG a=%d\n",a);
  a = b * 32;           
                        if(a==32) printf("**(21)** OK\n");
                        else      printf("**(21)** NG a=%d\n",a);
  a = b * 64;          
                        if(a==64) printf("**(22)** OK\n");
                        else      printf("**(22)** NG a=%d\n",a);
  a = b * 128;          
                        if(a==128) printf("**(23)** OK\n");
                        else       printf("**(23)** NG a=%d\n",a);
  a = b * 256;          
                        if(a==256) printf("**(24)** OK\n");
                        else       printf("**(24)** NG a=%d\n",a);
  a = b * 512;          
                        if(a==512) printf("**(25)** OK\n");
                        else       printf("**(25)** NG a=%d\n",a);
  a = b * 1024;         
                        if(a==1024) printf("**(26)** OK\n");
                        else        printf("**(26)** NG a=%d\n",a);
  a = b * 2048;         
                        if(a==2048) printf("**(27)** OK\n");
                        else        printf("**(27)** NG a=%d\n",a);
  a = b * 4096;         
                        if(a==4096) printf("**(28)** OK\n");
                        else        printf("**(28)** NG a=%d\n",a);
  a = b * 8192;         
                        if(a==8192) printf("**(29)** OK\n");
                        else        printf("**(29)** NG a=%d\n",a);
  a = b * 16384;        
                        if(a==16384) printf("**(30)** OK\n");
                        else         printf("**(30)** NG a=%d\n",a);
  a = b * 32768;        
                        if(a==32768) printf("**(31)** OK\n");
                        else         printf("**(31)** NG a=%d\n",a);
  a = b * 65536;        
                        if(a==65536) printf("**(32)** OK\n");
                        else         printf("**(32)** NG a=%d\n",a);
  a = b * 131072;       
                        if(a==131072) printf("**(33)** OK\n");
                        else          printf("**(33)** NG a=%d\n",a);
  a = b * 262144;       
                        if(a==262144) printf("**(34)** OK\n");
                        else          printf("**(34)** NG a=%d\n",a);
  a = b * 524288;       
                        if(a==524288) printf("**(35)** OK\n");
                        else          printf("**(35)** NG a=%d\n",a);
  a = b * 1048576;      
                        if(a==1048576) printf("**(36)** OK\n");
                        else           printf("**(36)** NG a=%d\n",a);
  a = b * 2097152;      
                        if(a==2097152) printf("**(37)** OK\n");
                        else           printf("**(37)** NG a=%d\n",a);
  a = b * 4194304;      
                        if(a==4194304) printf("**(38)** OK\n");
                        else           printf("**(38)** NG a=%d\n",a);
  a = b * 8388608;      
                        if(a==8388608) printf("**(39)** OK\n");
                        else           printf("**(39)** NG a=%d\n",a);
  a = b * 16777216;     
                        if(a==16777216) printf("**(40)** OK\n");
                        else            printf("**(40)** NG a=%d\n",a);
  a = b * 33554432;     
                        if(a==33554432) printf("**(41)** OK\n");
                        else            printf("**(41)** NG a=%d\n",a);
  a = b * 67108864;     
                        if(a==67108864) printf("**(42)** OK\n");
                        else            printf("**(42)** NG a=%d\n",a);
  a = b * 134217728;    
                        if(a==134217728) printf("**(43)** OK\n");
                        else             printf("**(43)** NG a=%d\n",a);
  a = b * 268435456;    
                        if(a==268435456) printf("**(44)** OK\n");
                        else             printf("**(44)** NG a=%d\n",a);
  a = b * 536870912;    
                        if(a==536870912) printf("**(45)** OK\n"); 
                        else             printf("**(45)** NG a=%d\n",a);
  a = b * 1073741824;   
                        if(a==1073741824) printf("**(46)** OK\n");
                        else              printf("**(46)** NG a=%d\n",a);
  a = b * 2147483648;   
#if LONG64 ||__x86_64__ || __aarch64__ || defined(_LP64)
                        if(a==-2147483648) printf("**(47)** OK\n");
                        else              printf("**(47)** NG a=%d\n",a);
#else
                        if(a==2147483648) printf("**(47)** OK\n");
                        else              printf("**(47)** NG a=%d\n",a);
#endif
                        a=subc();
  c = 1 * a;            
                        if(c==1)    printf("**(48)** OK\n");
                        else        printf("**(48)** NG a=%d\n",c);
  c = 2 * a;           
                        if(c==2)    printf("**(49)** OK\n");
                        else        printf("**(49)** NG a=%d\n",c);
  c = 4 * a;          
                        if(c==4)    printf("**(50)** OK\n");
                        else        printf("**(50)** NG a=%d\n",c);
  c = 8 * a;            
                        if(c==8   ) printf("**(51)** OK\n");
                        else        printf("**(51)** NG a=%d\n",c);
  c = 16 * a;           
                        if(c==16)   printf("**(52)** OK\n");
                        else        printf("**(52)** NG a=%d\n",c);
  c = 32 * a;           
                        if(c==32)   printf("**(53)** OK\n");
                        else        printf("**(53)** NG a=%d\n",c);
  c = 64 * a;           
                        if(c==64)   printf("**(54)** OK\n");
                        else        printf("**(54)** NG a=%d\n",c);
  c = 128 * a;          
                        if(c==128)  printf("**(55)** OK\n");
                        else        printf("**(55)** NG a=%d\n",c);
  c = 256 * a;         
                        if(c==256)  printf("**(56)** OK\n");
                        else        printf("**(56)** NG a=%d\n",c);
  c = 512 * a;          
                        if(c==512)  printf("**(57)** OK\n");
                        else        printf("**(57)** NG a=%d\n",c);
  c = 1024 * a;        
                        if(c==1024) printf("**(58)** OK\n");
                        else        printf("**(58)** NG a=%d\n",c);
  c = 2048 * a;         
                        if(c==2048) printf("**(59)** OK\n");
                        else        printf("**(59)** NG a=%d\n",c);
  c = 4096 * a;         
                        if(c==4096) printf("**(60)** OK\n");
                        else        printf("**(60)** NG a=%d\n",c);
  c = 8192 * a;         
                        if(c==8192) printf("**(61)** OK\n");
                        else        printf("**(61)** NG a=%d\n",c);
  c = 16384 * a;        
                        if(c==16384) printf("**(62)** OK\n");
                        else         printf("**(62)** NG a=%d\n",c);
  c = 32768 * a;        
                        if(c==32768) printf("**(63)** OK\n");
                        else         printf("**(63)** NG a=%d\n",c);
  c = 65536 * a;        
                        if(c==65536) printf("**(64)** OK\n");
                        else         printf("**(64)** NG a=%d\n",c);
  c = 131072 * a;       
                        if(c==131072) printf("**(65)** OK\n");
                        else          printf("**(65)** NG a=%d\n",c);
  c = 262144 * a;       
                        if(c==262144) printf("**(66)** OK\n");
                        else          printf("**(66)** NG a=%d\n",c);
  c = 524288 * a;       
                        if(c==524288) printf("**(67)** OK\n");
                        else          printf("**(67)** NG a=%d\n",c);
  c = 1048576 * a;      
                        if(c==1048576) printf("**(68)** OK\n");
                        else           printf("**(68)** NG a=%d\n",c);
  c = 2097152 * a;      
                        if(c==2097152) printf("**(69)** OK\n");
                        else           printf("**(69)** NG a=%d\n",c);
  c = 4194304 * a;      
                        if(c==4194304) printf("**(70)** OK\n");
                        else           printf("**(70)** NG a=%d\n",c);
  c = 8388608 * a;      
                        if(c==8388608) printf("**(71)** OK\n");
                        else           printf("**(71)** NG a=%d\n",c);
  c = 16777216 * a;     
                        if(c==16777216) printf("**(72)** OK\n");
                        else            printf("**(72)** NG a=%d\n",c);
  c = 33554432 * a;     
                        if(c==33554432) printf("**(73)** OK\n");
                        else            printf("**(73)** NG a=%d\n",c);
  c = 67108864 * a;     
                        if(c==67108864) printf("**(74)** OK\n");
                        else            printf("**(74)** NG a=%d\n",c);
  c = 134217728 * a;    
                        if(c==134217728) printf("**(75)** OK\n");
                        else             printf("**(75)** NG a=%d\n",c);
  c = 268435456 * a;    
                        if(c==268435456) printf("**(76)** OK\n");
                        else             printf("**(76)** NG a=%d\n",c);
  c = 536870912 * a;    
                        if(c==536870912) printf("**(77)** OK\n"); 
                        else             printf("**(77)** NG a=%d\n",c);
  c = 1073741824 * a;   
                        if(c==1073741824) printf("**(78)** OK\n");
                        else              printf("**(78)** NG a=%d\n",c);
  c = 2147483648 * a;   
#if LONG64||__x86_64__ || __aarch64__ || defined(_LP64)
                        if(c==-2147483648) printf("**(79)** OK\n");
                        else              printf("**(79)** NG a=%d\n",c);
#else
                        if(c==2147483648) printf("**(79)** OK\n");
                        else              printf("**(79)** NG a=%d\n",c);
#endif

  ccc = 0    ; 
                        aaa=subla(3ll);eee=suble(2ll);ccc=sublc(); 
  bbb = aaa    ;
  aaa = bbb + ccc + eee;        
                        if(aaa==14ll) printf("**(01)** OK\n");
                        else     printf("**(01)** NG aaa=%d\n",aaa);
  aaa = bbb - ccc - eee; 
                        if(aaa==4ll) printf("**(02)** OK\n");
                        else     printf("**(02)** NG aaa=%d\n",aaa);
  aaa = bbb * ccc * eee;
                        if(aaa==36ll) printf("**(03)** OK\n");
                        else     printf("**(03)** NG aaa=%d\n",aaa);
                        aaa=subla(10ll);eee=suble(2ll); 
  bbb = aaa    ;
  aaa = bbb / eee / eee; 
                        if(aaa==6ll) printf("**(04)** OK\n");
                        else     printf("**(04)** NG aaa=%d\n",aaa);
                        aaa=subla(10ll);eee=suble(3ll); 
  bbb = aaa    ;
  ccc = 60ll;
  aaa = bbb % ccc % eee; 
                        if(aaa==4ll) printf("**(05)** OK\n");
                        else     printf("**(05)** NG aaa=%d\n",aaa);
                        fff=sublc()+9ll;
  aaa = 10ll + fff; 
                        if(aaa==20ll) printf("**(06)** OK\n");
                        else     printf("**(06)** NG aaa=%d\n",aaa);
  aaa = 10ll - fff; 
                        if(aaa==0) printf("**(07)** OK\n");
                        else     printf("**(07)** NG aaa=%d\n",aaa);
  aaa = 10ll * fff;
                        if(aaa==100ll) printf("**(08)** OK\n");
                        else     printf("**(08)** NG aaa=%d\n",aaa);
  aaa = 10ll / fff;
                        if(aaa== 1ll) printf("**(09)** OK\n");
                        else     printf("**(09)** NG aaa=%d\n",aaa);
  aaa = 10ll % fff; 
                        if(aaa== 0) printf("**(10)** OK\n");
                        else     printf("**(10)** NG aaa=%d\n",aaa);
                        eee=suble(50ll);
  aaa = eee + 100ll; 
                        if(aaa==200ll) printf("**(11)** OK\n");
                        else     printf("**(11)** NG aaa=%d\n",aaa);
  aaa = eee - 100ll;
                        if(aaa==0) printf("**(12)** OK\n");
                        else     printf("**(12)** NG aaa=%d\n",aaa);
  aaa = eee * 100ll; 
                        if(aaa==10000ll) printf("**(13)** OK\n");
                        else     printf("**(13)** NG aaa=%d\n",aaa);
  aaa = eee / 100ll; 
                        if(aaa==1ll) printf("**(14)** OK\n");
                        else     printf("**(14)** NG aaa=%d\n",aaa);
  bbb = eee % 100ll;
                        if(bbb==0) printf("**(15)** OK\n");
                        else     printf("**(15)** NG bbb=%d\n",bbb);
                        bbb=sublc();
  aaa = bbb * 1;            
                        if(aaa==1) printf("**(16)** OK\n");
                        else     printf("**(16)** NG aaa=%d\n",aaa);
  aaa = bbb * 2;            
                        if(aaa==2) printf("**(17)** OK\n");
                        else     printf("**(17)** NG aaa=%d\n",aaa);
  aaa = bbb * 4;            
                        if(aaa==4) printf("**(18)** OK\n");
                        else     printf("**(18)** NG aaa=%d\n",aaa);
  aaa = bbb * 8;           
                        if(aaa==8) printf("**(19)** OK\n");
                        else     printf("**(19)** NG aaa=%d\n",aaa);
  aaa = bbb * 16;         
                        if(aaa==16) printf("**(20)** OK\n");
                        else printf("**(20)** NG aaa=%d\n",aaa);
  aaa = bbb * 32;           
                        if(aaa==32) printf("**(21)** OK\n");
                        else printf("**(21)** NG aaa=%d\n",aaa);
  aaa = bbb * 64;          
                        if(aaa==64) printf("**(22)** OK\n");
                        else printf("**(22)** NG aaa=%d\n",aaa);
  aaa = bbb * 128;          
                        if(aaa==128) printf("**(23)** OK\n");
                        else printf("**(23)** NG aaa=%d\n",aaa);
  aaa = bbb * 256;          
                        if(aaa==256) printf("**(24)** OK\n");
                        else printf("**(24)** NG aaa=%d\n",aaa);
  aaa = bbb * 512;          
                        if(aaa==512) printf("**(25)** OK\n");
                        else printf("**(25)** NG aaa=%d\n",aaa);
  aaa = bbb * 1024;         
                        if(aaa==1024) printf("**(26)** OK\n");
                        else  printf("**(26)** NG aaa=%d\n",aaa);
  aaa = bbb * 2048;         
                        if(aaa==2048) printf("**(27)** OK\n");
                        else  printf("**(27)** NG aaa=%d\n",aaa);
  aaa = bbb * 4096;         
                        if(aaa==4096) printf("**(28)** OK\n");
                        else  printf("**(28)** NG aaa=%d\n",aaa);
  aaa = bbb * 8192;         
                        if(aaa==8192) printf("**(29)** OK\n");
                        else  printf("**(29)** NG aaa=%d\n",aaa);
  aaa = bbb * 16384;        
                        if(aaa==16384) printf("**(30)** OK\n");
                        else   printf("**(30)** NG aaa=%d\n",aaa);
  aaa = bbb * 32768;        
                        if(aaa==32768) printf("**(31)** OK\n");
                        else   printf("**(31)** NG aaa=%d\n",aaa);
  aaa = bbb * 65536;        
                        if(aaa==65536) printf("**(32)** OK\n");
                        else   printf("**(32)** NG aaa=%d\n",aaa);
  aaa = bbb * 131072;       
                        if(aaa==131072) printf("**(33)** OK\n");
                        else    printf("**(33)** NG aaa=%d\n",aaa);
  aaa = bbb * 262144;       
                        if(aaa==262144) printf("**(34)** OK\n");
                        else    printf("**(34)** NG aaa=%d\n",aaa);
  aaa = bbb * 524288;       
                        if(aaa==524288) printf("**(35)** OK\n");
                        else    printf("**(35)** NG aaa=%d\n",aaa);
  aaa = bbb * 1048576;      
                        if(aaa==1048576) printf("**(36)** OK\n");
                        else     printf("**(36)** NG aaa=%d\n",aaa);
  aaa = bbb * 2097152;      
                        if(aaa==2097152) printf("**(37)** OK\n");
                        else     printf("**(37)** NG aaa=%d\n",aaa);
  aaa = bbb * 4194304;      
                        if(aaa==4194304) printf("**(38)** OK\n");
                        else     printf("**(38)** NG aaa=%d\n",aaa);
  aaa = bbb * 8388608;      
                        if(aaa==8388608) printf("**(39)** OK\n");
                        else     printf("**(39)** NG aaa=%d\n",aaa);
  aaa = bbb * 16777216;     
                        if(aaa==16777216) printf("**(40)** OK\n");
                        else      printf("**(40)** NG aaa=%d\n",aaa);
  aaa = bbb * 33554432;     
                        if(aaa==33554432) printf("**(41)** OK\n");
                        else      printf("**(41)** NG aaa=%d\n",aaa);
  aaa = bbb * 67108864;     
                        if(aaa==67108864) printf("**(42)** OK\n");
                        else      printf("**(42)** NG aaa=%d\n",aaa);
  aaa = bbb * 134217728;    
                        if(aaa==134217728) printf("**(43)** OK\n");
                        else       printf("**(43)** NG aaa=%d\n",aaa);
  aaa = bbb * 268435456;    
                        if(aaa==268435456) printf("**(44)** OK\n");
                        else       printf("**(44)** NG aaa=%d\n",aaa);
  aaa = bbb * 536870912;    
                        if(aaa==536870912) printf("**(45)** OK\n"); 
                        else       printf("**(45)** NG aaa=%d\n",aaa);
  aaa = bbb * 1073741824;   
                        if(aaa==1073741824) printf("**(46)** OK\n");
                        else        printf("**(46)** NG aaa=%d\n",aaa);
  aaa = bbb * 2147483648LL;   
                        if(aaa==2147483648LL) printf("**(47)** OK\n");
                        else        printf("**(47)** NG aaa=%d\n",aaa);
                        aaa=sublc();
  ccc = 1 * aaa;            
                        if(ccc==1)    printf("**(48)** OK\n");
                        else  printf("**(48)** NG aaa=%d\n",ccc);
  ccc = 2 * aaa;           
                        if(ccc==2)    printf("**(49)** OK\n");
                        else  printf("**(49)** NG aaa=%d\n",ccc);
  ccc = 4 * aaa;          
                        if(ccc==4)    printf("**(50)** OK\n");
                        else  printf("**(50)** NG aaa=%d\n",ccc);
  ccc = 8 * aaa;            
                        if(ccc==8   ) printf("**(51)** OK\n");
                        else  printf("**(51)** NG aaa=%d\n",ccc);
  ccc = 16 * aaa;           
                        if(ccc==16)   printf("**(52)** OK\n");
                        else  printf("**(52)** NG aaa=%d\n",ccc);
  ccc = 32 * aaa;           
                        if(ccc==32)   printf("**(53)** OK\n");
                        else  printf("**(53)** NG aaa=%d\n",ccc);
  ccc = 64 * aaa;           
                        if(ccc==64)   printf("**(54)** OK\n");
                        else  printf("**(54)** NG aaa=%d\n",ccc);
  ccc = 128 * aaa;          
                        if(ccc==128)  printf("**(55)** OK\n");
                        else  printf("**(55)** NG aaa=%d\n",ccc);
  ccc = 256 * aaa;         
                        if(ccc==256)  printf("**(56)** OK\n");
                        else  printf("**(56)** NG aaa=%d\n",ccc);
  ccc = 512 * aaa;          
                        if(ccc==512)  printf("**(57)** OK\n");
                        else  printf("**(57)** NG aaa=%d\n",ccc);
  ccc = 1024 * aaa;        
                        if(ccc==1024) printf("**(58)** OK\n");
                        else  printf("**(58)** NG aaa=%d\n",ccc);
  ccc = 2048 * aaa;         
                        if(ccc==2048) printf("**(59)** OK\n");
                        else  printf("**(59)** NG aaa=%d\n",ccc);
  ccc = 4096 * aaa;         
                        if(ccc==4096) printf("**(60)** OK\n");
                        else  printf("**(60)** NG aaa=%d\n",ccc);
  ccc = 8192 * aaa;         
                        if(ccc==8192) printf("**(61)** OK\n");
                        else  printf("**(61)** NG aaa=%d\n",ccc);
  ccc = 16384 * aaa;        
                        if(ccc==16384) printf("**(62)** OK\n");
                        else   printf("**(62)** NG aaa=%d\n",ccc);
  ccc = 32768 * aaa;        
                        if(ccc==32768) printf("**(63)** OK\n");
                        else   printf("**(63)** NG aaa=%d\n",ccc);
  ccc = 65536 * aaa;        
                        if(ccc==65536) printf("**(64)** OK\n");
                        else   printf("**(64)** NG aaa=%d\n",ccc);
  ccc = 131072 * aaa;       
                        if(ccc==131072) printf("**(65)** OK\n");
                        else    printf("**(65)** NG aaa=%d\n",ccc);
  ccc = 262144 * aaa;       
                        if(ccc==262144) printf("**(66)** OK\n");
                        else    printf("**(66)** NG aaa=%d\n",ccc);
  ccc = 524288 * aaa;       
                        if(ccc==524288) printf("**(67)** OK\n");
                        else    printf("**(67)** NG aaa=%d\n",ccc);
  ccc = 1048576 * aaa;      
                        if(ccc==1048576) printf("**(68)** OK\n");
                        else     printf("**(68)** NG aaa=%d\n",ccc);
  ccc = 2097152 * aaa;      
                        if(ccc==2097152) printf("**(69)** OK\n");
                        else     printf("**(69)** NG aaa=%d\n",ccc);
  ccc = 4194304 * aaa;      
                        if(ccc==4194304) printf("**(70)** OK\n");
                        else     printf("**(70)** NG aaa=%d\n",ccc);
  ccc = 8388608 * aaa;      
                        if(ccc==8388608) printf("**(71)** OK\n");
                        else     printf("**(71)** NG aaa=%d\n",ccc);
  ccc = 16777216 * aaa;     
                        if(ccc==16777216) printf("**(72)** OK\n");
                        else      printf("**(72)** NG aaa=%d\n",ccc);
  ccc = 33554432 * aaa;     
                        if(ccc==33554432) printf("**(73)** OK\n");
                        else      printf("**(73)** NG aaa=%d\n",ccc);
  ccc = 67108864 * aaa;     
                        if(ccc==67108864) printf("**(74)** OK\n");
                        else      printf("**(74)** NG aaa=%d\n",ccc);
  ccc = 134217728 * aaa;    
                        if(ccc==134217728) printf("**(75)** OK\n");
                        else       printf("**(75)** NG aaa=%d\n",ccc);
  ccc = 268435456 * aaa;    
                        if(ccc==268435456) printf("**(76)** OK\n");
                        else       printf("**(76)** NG aaa=%d\n",ccc);
  ccc = 536870912 * aaa;    
                        if(ccc==536870912) printf("**(77)** OK\n"); 
                        else       printf("**(77)** NG aaa=%d\n",ccc);
  ccc = 1073741824 * aaa;   
                        if(ccc==1073741824) printf("**(78)** OK\n");
                        else        printf("**(78)** NG aaa=%d\n",ccc);
  ccc = 2147483648LL * aaa;
                        if(ccc==2147483648LL) printf("**(79)** OK\n");
                        else        printf("**(79)** NG aaa=%d\n",ccc);
}  

