MODULE mod1
IMPLICIT NONE

TYPE t1
  REAL :: r1 =0.0
END TYPE

TYPE,EXTENDS(t1) :: t2
  REAL :: r2 = 0.0
END TYPE

INTERFACE OPERATOR(.plus.)
  MODULE PROCEDURE addit
END INTERFACE

CONTAINS

FUNCTION addit(dy1,dy2)
IMPLICIT NONE
CLASS(t1),DIMENSION(:),INTENT(IN) :: dy1
CLASS(t2),DIMENSION(:),INTENT(IN) :: dy2
CLASS(t2),DIMENSION(:),ALLOCATABLE :: addit
ALLOCATE(addit(5))
addit%r2 = dy1%r1 + dy2%r2
END FUNCTION

END MODULE


PROGRAM main
USE mod1
IMPLICIT NONE

CLASS(t1),DIMENSION(:),POINTER :: ptr
CLASS(t2),DIMENSION(:),ALLOCATABLE :: acc,acc2
ALLOCATE(ptr(10),acc(10))
acc%r2 = 10.0
ptr%r1 = 12.0

SELECT TYPE(aa => ptr([2,5,3,8,6]) .plus. acc( : :2))
  TYPE  IS(t2)
    ALLOCATE(acc2(5),SOURCE = aa) 
 CLASS DEFAULT
    PRINT*,103
END SELECT

IF(acc2(1)%r2 .EQ. 22.0) THEN
  PRINT*,'pass'
ELSE
  PRINT*,101
END IF

END PROGRAM  


