MODULE TYPES

  TYPE :: T1
    INTEGER :: X1=10
  CONTAINS
    PROCEDURE :: RFORM,WFORM
    GENERIC :: READ(FORMATTED) => RFORM
    GENERIC :: WRITE(FORMATTED) => WFORM

  END TYPE 

     CHARACTER(LEN=15)::CH

  CONTAINS

  SUBROUTINE WFORM(DTV, UNIT, IOTYPE, VLIST, STAT, MSG)
    CLASS(T1), INTENT(IN)    :: DTV
    INTEGER, INTENT(IN)         :: UNIT
    CHARACTER(*), INTENT(IN)    :: IOTYPE
    INTEGER, INTENT(IN)         :: VLIST(:)
    INTEGER, INTENT(OUT)        :: STAT
    CHARACTER(*), INTENT(INOUT) :: MSG
    IF(SIZE(VLIST)/=0) THEN
        WRITE(UNIT,*,IOSTAT=STAT,IOMSG=MSG)VLIST(1),DTV%X1,IOTYPE
      ELSE
        WRITE(UNIT,*,IOSTAT=STAT,IOMSG=MSG) DTV%X1
      END IF
  END SUBROUTINE WFORM
  SUBROUTINE RFORM(DTV, UNIT, IOTYPE, VLIST, STAT, MSG)
    CLASS(T1), INTENT(INOUT)    :: DTV
    INTEGER, INTENT(IN)         :: UNIT
    CHARACTER(*), INTENT(IN)    :: IOTYPE
    INTEGER, INTENT(IN)         :: VLIST(:)
    INTEGER, INTENT(OUT)        :: STAT
    CHARACTER(*), INTENT(INOUT) :: MSG
     CH=IOTYPE
      IF(SIZE(VLIST)/=0) THEN
       READ(UNIT,*,IOSTAT=STAT,IOMSG=MSG) DTV%X1
      ELSE
        READ(UNIT,*,IOSTAT=STAT,IOMSG=MSG) DTV%X1
      END IF
  END SUBROUTINE RFORM

END MODULE TYPES

  USE TYPES
  TYPE(T1) :: VAR1,VAR2
  VAR1%X1=50
  OPEN(10,FILE="fort.10",FORM="FORMATTED")
 WRITE(10,*)VAR1
    CLOSE(10)

  OPEN(15,FILE="fort.10",FORM="FORMATTED")
  READ(15,*)VAR2
  backspace(15)
  READ(15,*)FUN()
  VAR2=FUN()
  if(VAR2%X1 .ne. 50)print*,"101",VAR2%X1
  print*,"Pass"
  CLOSE(15,STATUS="DELETE")
CONTAINS
FUNCTION FUN()
CLASS(T1),POINTER :: FUN
TYPE(T1),TARGET  :: TAR=T1(70)
FUN=>TAR
END FUNCTION
END PROGRAM
