interface
subroutine suba(a,b,i)
integer :: a(i)
integer :: b(:)
end subroutine
subroutine subb(a,b,i)
integer :: a(i)
integer :: b(:)
end subroutine
subroutine subc(a,b,i)
integer :: a(i)
integer :: b(:)
end subroutine
subroutine subd(b,a,i)
integer :: a(i)
integer :: b(:)
end subroutine
subroutine sub2(a,b,i)
integer :: a(i,i)
integer :: b(:,:)
end subroutine
end interface
integer a(10),b(10)
integer a2(10,10),b2(10,10)
call suba(a,b,10)
call subb(a,b,10)
call subc(a,b,10)
call subd(a,b,10)
call sub2(a2,b2,10)
print *,'pass'
end 

subroutine sub2(a,b,i)
integer,pointer :: p(:,:)
integer,allocatable:: z(:,:)
integer :: a(i,i)
integer :: b(:,:)
integer :: x(10,10)
allocate(p(10,10),z(10,10))
x=1;p=1;z=1;a=1;b=1
x=max(x,p+p)
end

subroutine suba(a,b,ii)
integer,pointer :: p(:) 
integer,allocatable:: z(:)
integer :: a(ii)
integer :: b(:)
integer :: x(10)
allocate(p(10),z(10))
x=1;p=1;z=1;a=1;b=1
x=max(x,p+p)
x=max(x,1+p+p)
x=max(x,p+1+p)
x=max(x,1*p+p)
x=max(x,1*p+p*1)
x=max(x,1*p+p*1)
x=max(x,p)
x=max(x,p(:)+p)
x=max(x,1+p(:)+p(:))
x=max(x,p(:)+1+p(:))
x=max(x,1*p(:)+p(:))
x=max(x,1*p(:)+p(:)*1)
x=max(x,1*p(:)+p(:)*1)
x=max(x,p(:))
x=max(x,p(x)+p)
x=max(x,1+p(x)+p(x))
x=max(x,p(x)+1+p(x))
x=max(x,1*p(x)+p(x))
x=max(x,1*p(x)+p(x)*1)
x=max(x,1*p(x)+p(x)*1)
x=max(x,p(x))
x=max(x,p(1:)+p)
x=max(x,1+p(1:)+p(1:))
x=max(x,p(1:)+1+p(1:))
x=max(x,1*p(1:)+p(1:))
x=max(x,1*p(1:)+p(1:)*1)
x=max(x,1*p(1:)+p(1:)*1)
x=max(x,p(1:))
i=1
x=max(x,p(i:)+p)
x=max(x,1+p(i:)+p(i:))
x=max(x,p(i:)+1+p(i:))
x=max(x,1*p(i:)+p(i:))
x=max(x,1*p(i:)+p(i:)*1)
x=max(x,1*p(i:)+p(i:)*1)
x=max(x,p(i:))
j=10
x=max(x,p(1:j)+p)
x=max(x,1+p(1:j)+p(1:j))
x=max(x,p(1:j)+1+p(1:j))
x=max(x,1*p(1:j)+p(1:j))
x=max(x,1*p(1:j)+p(1:j)*1)
x=max(x,1*p(1:j)+p(1:j)*1)
x=max(x,p(1:j))
x=max(x,p(i:j)+p)
x=max(x,1+p(i:j)+p(i:j))
x=max(x,p(i:j)+1+p(i:j))
x=max(x,1*p(i:j)+p(i:j))
x=max(x,1*p(i:j)+p(i:j)*1)
x=max(x,1*p(i:j)+p(i:j)*1)
x=max(x,p(i:j))
x=max(x,p(:j)+p)
x=max(x,1+p(:j)+p(:j))
x=max(x,p(:j)+1+p(:j))
x=max(x,1*p(:j)+p(:j))
x=max(x,1*p(:j)+p(:j)*1)
x=max(x,1*p(:j)+p(:j)*1)
x=max(x,p(:j))
x=max(x,p(:)+p)
x=max(x,1+p+p(:))
x=max(x,p+1+p(:))
x=max(x,1*p+p(:))
x=max(x,1*p+p(:)*1)
x=max(x,1*p+p(:)*1)
x=max(x,p(:))
x=max(x,p(x)+p)
x=max(x,1+p(x)+p)
x=max(x,p(x)+1+p)
x=max(x,1*p(x)+p)
x=max(x,1*p(x)+p*1)
x=max(x,1*p(x)+p*1)
x=max(x,p(x))
x=max(x,p(1:)+p)
x=max(x,1+p(1:)+p(1:))
x=max(x,p(1:)+1+p(1:))
x=max(x,1*p(1:)+p(1:))
x=max(x,1*p(1:)+p(1:)*1)
x=max(x,1*p(1:)+p(1:)*1)
x=max(x,p(1:))
i=1
x=max(x,p(i:)+p)
x=max(x,1+p(i:)+p(i:))
x=max(x,p(i:)+1+p(i:))
x=max(x,1*p(i:)+p(i:))
x=max(x,1*p(i:)+p(i:)*1)
x=max(x,1*p(i:)+p(i:)*1)
x=max(x,p(i:))
j=10
x=max(x,p(1:j)+p)
x=max(x,1+p(1:j)+p)
x=max(x,p(1:j)+1+p)
x=max(x,1*p(1:j)+p)
x=max(x,1*p(1:j)+p*1)
x=max(x,1*p(1:j)+p*1)
x=max(x,p(1:j))
x=max(x,p(i:j)+p)
x=max(x,1+p(i:j)+p)
x=max(x,p(i:j)+1+p)
x=max(x,1*p(i:j)+p)
x=max(x,1*p(i:j)+p*1)
x=max(x,1*p(i:j)+p*1)
x=max(x,p(i:j))
x=max(x,p+p)
x=max(x,1+p+p(:j))
x=max(x,p+1+p(:j))
x=max(x,1*p+p(:j))
x=max(x,1*p+p(:j)*1)
x=max(x,1*p+p(:j)*1)
x=max(x,p(:j))
deallocate(p,z)

end
subroutine subb(a,b,ii)
integer,pointer :: z(:) 
integer,allocatable:: p(:)
integer :: a(ii)
integer :: b(:)
integer :: x(10)
allocate(p(10),z(10))
x=1;p=1;z=1;a=1;b=1
x=max(x,p+p)
x=max(x,1+p+p)
x=max(x,p+1+p)
x=max(x,1*p+p)
x=max(x,1*p+p*1)
x=max(x,1*p+p*1)
x=max(x,p)
x=max(x,p(:)+p)
x=max(x,1+p(:)+p(:))
x=max(x,p(:)+1+p(:))
x=max(x,1*p(:)+p(:))
x=max(x,1*p(:)+p(:)*1)
x=max(x,1*p(:)+p(:)*1)
x=max(x,p(:))
x=max(x,p(x)+p)
x=max(x,1+p(x)+p(x))
x=max(x,p(x)+1+p(x))
x=max(x,1*p(x)+p(x))
x=max(x,1*p(x)+p(x)*1)
x=max(x,1*p(x)+p(x)*1)
x=max(x,p(x))
x=max(x,p(1:)+p)
x=max(x,1+p(1:)+p(1:))
x=max(x,p(1:)+1+p(1:))
x=max(x,1*p(1:)+p(1:))
x=max(x,1*p(1:)+p(1:)*1)
x=max(x,1*p(1:)+p(1:)*1)
x=max(x,p(1:))
i=1
x=max(x,p(i:)+p)
x=max(x,1+p(i:)+p(i:))
x=max(x,p(i:)+1+p(i:))
x=max(x,1*p(i:)+p(i:))
x=max(x,1*p(i:)+p(i:)*1)
x=max(x,1*p(i:)+p(i:)*1)
x=max(x,p(i:))
j=10
x=max(x,p(1:j)+p)
x=max(x,1+p(1:j)+p(1:j))
x=max(x,p(1:j)+1+p(1:j))
x=max(x,1*p(1:j)+p(1:j))
x=max(x,1*p(1:j)+p(1:j)*1)
x=max(x,1*p(1:j)+p(1:j)*1)
x=max(x,p(1:j))
x=max(x,p(i:j)+p)
x=max(x,1+p(i:j)+p(i:j))
x=max(x,p(i:j)+1+p(i:j))
x=max(x,1*p(i:j)+p(i:j))
x=max(x,1*p(i:j)+p(i:j)*1)
x=max(x,1*p(i:j)+p(i:j)*1)
x=max(x,p(i:j))
x=max(x,p(:j)+p)
x=max(x,1+p(:j)+p(:j))
x=max(x,p(:j)+1+p(:j))
x=max(x,1*p(:j)+p(:j))
x=max(x,1*p(:j)+p(:j)*1)
x=max(x,1*p(:j)+p(:j)*1)
x=max(x,p(:j))
x=max(x,p(:)+p)
x=max(x,1+p+p(:))
x=max(x,p+1+p(:))
x=max(x,1*p+p(:))
x=max(x,1*p+p(:)*1)
x=max(x,1*p+p(:)*1)
x=max(x,p(:))
x=max(x,p(x)+p)
x=max(x,1+p(x)+p)
x=max(x,p(x)+1+p)
x=max(x,1*p(x)+p)
x=max(x,1*p(x)+p*1)
x=max(x,1*p(x)+p*1)
x=max(x,p(x))
x=max(x,p(1:)+p)
x=max(x,1+p(1:)+p(1:))
x=max(x,p(1:)+1+p(1:))
x=max(x,1*p(1:)+p(1:))
x=max(x,1*p(1:)+p(1:)*1)
x=max(x,1*p(1:)+p(1:)*1)
x=max(x,p(1:))
i=1
x=max(x,p(i:)+p)
x=max(x,1+p(i:)+p(i:))
x=max(x,p(i:)+1+p(i:))
x=max(x,1*p(i:)+p(i:))
x=max(x,1*p(i:)+p(i:)*1)
x=max(x,1*p(i:)+p(i:)*1)
x=max(x,p(i:))
j=10
x=max(x,p(1:j)+p)
x=max(x,1+p(1:j)+p)
x=max(x,p(1:j)+1+p)
x=max(x,1*p(1:j)+p)
x=max(x,1*p(1:j)+p*1)
x=max(x,1*p(1:j)+p*1)
x=max(x,p(1:j))
x=max(x,p(i:j)+p)
x=max(x,1+p(i:j)+p)
x=max(x,p(i:j)+1+p)
x=max(x,1*p(i:j)+p)
x=max(x,1*p(i:j)+p*1)
x=max(x,1*p(i:j)+p*1)
x=max(x,p(i:j))
x=max(x,p+p)
x=max(x,1+p+p(:j))
x=max(x,p+1+p(:j))
x=max(x,1*p+p(:j))
x=max(x,1*p+p(:j)*1)
x=max(x,1*p+p(:j)*1)
x=max(x,p(:j))
deallocate(p,z)

end
subroutine subc(p,b,ii)
integer,pointer :: a(:) 
integer,allocatable:: z(:)
integer :: p(ii)
integer :: b(:)
integer :: x(10)
allocate(a(10),z(10))
x=1;p=1;z=1;a=1;b=1
x=max(x,p+p)
x=max(x,1+p+p)
x=max(x,p+1+p)
x=max(x,1*p+p)
x=max(x,1*p+p*1)
x=max(x,1*p+p*1)
x=max(x,p)
x=max(x,p(:)+p)
x=max(x,1+p(:)+p(:))
x=max(x,p(:)+1+p(:))
x=max(x,1*p(:)+p(:))
x=max(x,1*p(:)+p(:)*1)
x=max(x,1*p(:)+p(:)*1)
x=max(x,p(:))
x=max(x,p(x)+p)
x=max(x,1+p(x)+p(x))
x=max(x,p(x)+1+p(x))
x=max(x,1*p(x)+p(x))
x=max(x,1*p(x)+p(x)*1)
x=max(x,1*p(x)+p(x)*1)
x=max(x,p(x))
x=max(x,p(1:)+p)
x=max(x,1+p(1:)+p(1:))
x=max(x,p(1:)+1+p(1:))
x=max(x,1*p(1:)+p(1:))
x=max(x,1*p(1:)+p(1:)*1)
x=max(x,1*p(1:)+p(1:)*1)
x=max(x,p(1:))
i=1
x=max(x,p(i:)+p)
x=max(x,1+p(i:)+p(i:))
x=max(x,p(i:)+1+p(i:))
x=max(x,1*p(i:)+p(i:))
x=max(x,1*p(i:)+p(i:)*1)
x=max(x,1*p(i:)+p(i:)*1)
x=max(x,p(i:))
j=10
x=max(x,p(1:j)+p)
x=max(x,1+p(1:j)+p(1:j))
x=max(x,p(1:j)+1+p(1:j))
x=max(x,1*p(1:j)+p(1:j))
x=max(x,1*p(1:j)+p(1:j)*1)
x=max(x,1*p(1:j)+p(1:j)*1)
x=max(x,p(1:j))
x=max(x,p(i:j)+p)
x=max(x,1+p(i:j)+p(i:j))
x=max(x,p(i:j)+1+p(i:j))
x=max(x,1*p(i:j)+p(i:j))
x=max(x,1*p(i:j)+p(i:j)*1)
x=max(x,1*p(i:j)+p(i:j)*1)
x=max(x,p(i:j))
x=max(x,p(:j)+p)
x=max(x,1+p(:j)+p(:j))
x=max(x,p(:j)+1+p(:j))
x=max(x,1*p(:j)+p(:j))
x=max(x,1*p(:j)+p(:j)*1)
x=max(x,1*p(:j)+p(:j)*1)
x=max(x,p(:j))
x=max(x,p(:)+p)
x=max(x,1+p+p(:))
x=max(x,p+1+p(:))
x=max(x,1*p+p(:))
x=max(x,1*p+p(:)*1)
x=max(x,1*p+p(:)*1)
x=max(x,p(:))
x=max(x,p(x)+p)
x=max(x,1+p(x)+p)
x=max(x,p(x)+1+p)
x=max(x,1*p(x)+p)
x=max(x,1*p(x)+p*1)
x=max(x,1*p(x)+p*1)
x=max(x,p(x))
x=max(x,p(1:)+p)
x=max(x,1+p(1:)+p(1:))
x=max(x,p(1:)+1+p(1:))
x=max(x,1*p(1:)+p(1:))
x=max(x,1*p(1:)+p(1:)*1)
x=max(x,1*p(1:)+p(1:)*1)
x=max(x,p(1:))
i=1
x=max(x,p(i:)+p)
x=max(x,1+p(i:)+p(i:))
x=max(x,p(i:)+1+p(i:))
x=max(x,1*p(i:)+p(i:))
x=max(x,1*p(i:)+p(i:)*1)
x=max(x,1*p(i:)+p(i:)*1)
x=max(x,p(i:))
j=10
x=max(x,p(1:j)+p)
x=max(x,1+p(1:j)+p)
x=max(x,p(1:j)+1+p)
x=max(x,1*p(1:j)+p)
x=max(x,1*p(1:j)+p*1)
x=max(x,1*p(1:j)+p*1)
x=max(x,p(1:j))
x=max(x,p(i:j)+p)
x=max(x,1+p(i:j)+p)
x=max(x,p(i:j)+1+p)
x=max(x,1*p(i:j)+p)
x=max(x,1*p(i:j)+p*1)
x=max(x,1*p(i:j)+p*1)
x=max(x,p(i:j))
x=max(x,p+p)
x=max(x,1+p+p(:j))
x=max(x,p+1+p(:j))
x=max(x,1*p+p(:j))
x=max(x,1*p+p(:j)*1)
x=max(x,1*p+p(:j)*1)
x=max(x,p(:j))
deallocate(a,z)
end
subroutine subd(p,b,ii)
integer,pointer :: a(:) 
integer,allocatable:: z(:)
integer :: b(ii)
integer :: p(:)
integer :: x(10)
x=1
allocate(a(10),z(10))
x=1;p=1;z=1;a=1;b=1
x=max(x,p+p)
x=max(x,1+p+p)
x=max(x,p+1+p)
x=max(x,1*p+p)
x=max(x,1*p+p*1)
x=max(x,1*p+p*1)
x=max(x,p)
x=max(x,p(:)+p)
x=max(x,1+p(:)+p(:))
x=max(x,p(:)+1+p(:))
x=max(x,1*p(:)+p(:))
x=max(x,1*p(:)+p(:)*1)
x=max(x,1*p(:)+p(:)*1)
x=max(x,p(:))
x=max(x,p(x)+p)
x=max(x,1+p(x)+p(x))
x=max(x,p(x)+1+p(x))
x=max(x,1*p(x)+p(x))
x=max(x,1*p(x)+p(x)*1)
x=max(x,1*p(x)+p(x)*1)
x=max(x,p(x))
x=max(x,p(1:)+p)
x=max(x,1+p(1:)+p(1:))
x=max(x,p(1:)+1+p(1:))
x=max(x,1*p(1:)+p(1:))
x=max(x,1*p(1:)+p(1:)*1)
x=max(x,1*p(1:)+p(1:)*1)
x=max(x,p(1:))
i=1
x=max(x,p(i:)+p)
x=max(x,1+p(i:)+p(i:))
x=max(x,p(i:)+1+p(i:))
x=max(x,1*p(i:)+p(i:))
x=max(x,1*p(i:)+p(i:)*1)
x=max(x,1*p(i:)+p(i:)*1)
x=max(x,p(i:))
j=10
x=max(x,p(1:j)+p)
x=max(x,1+p(1:j)+p(1:j))
x=max(x,p(1:j)+1+p(1:j))
x=max(x,1*p(1:j)+p(1:j))
x=max(x,1*p(1:j)+p(1:j)*1)
x=max(x,1*p(1:j)+p(1:j)*1)
x=max(x,p(1:j))
x=max(x,p(i:j)+p)
x=max(x,1+p(i:j)+p(i:j))
x=max(x,p(i:j)+1+p(i:j))
x=max(x,1*p(i:j)+p(i:j))
x=max(x,1*p(i:j)+p(i:j)*1)
x=max(x,1*p(i:j)+p(i:j)*1)
x=max(x,p(i:j))
x=max(x,p(:j)+p)
x=max(x,1+p(:j)+p(:j))
x=max(x,p(:j)+1+p(:j))
x=max(x,1*p(:j)+p(:j))
x=max(x,1*p(:j)+p(:j)*1)
x=max(x,1*p(:j)+p(:j)*1)
x=max(x,p(:j))
x=max(x,p(:)+p)
x=max(x,1+p+p(:))
x=max(x,p+1+p(:))
x=max(x,1*p+p(:))
x=max(x,1*p+p(:)*1)
x=max(x,1*p+p(:)*1)
x=max(x,p(:))
x=max(x,p(x)+p)
x=max(x,1+p(x)+p)
x=max(x,p(x)+1+p)
x=max(x,1*p(x)+p)
x=max(x,1*p(x)+p*1)
x=max(x,1*p(x)+p*1)
x=max(x,p(x))
x=max(x,p(1:)+p)
x=max(x,1+p(1:)+p(1:))
x=max(x,p(1:)+1+p(1:))
x=max(x,1*p(1:)+p(1:))
x=max(x,1*p(1:)+p(1:)*1)
x=max(x,1*p(1:)+p(1:)*1)
x=max(x,p(1:))
i=1
x=max(x,p(i:)+p)
x=max(x,1+p(i:)+p(i:))
x=max(x,p(i:)+1+p(i:))
x=max(x,1*p(i:)+p(i:))
x=max(x,1*p(i:)+p(i:)*1)
x=max(x,1*p(i:)+p(i:)*1)
x=max(x,p(i:))
j=10
x=max(x,p(1:j)+p)
x=max(x,1+p(1:j)+p)
x=max(x,p(1:j)+1+p)
x=max(x,1*p(1:j)+p)
x=max(x,1*p(1:j)+p*1)
x=max(x,1*p(1:j)+p*1)
x=max(x,p(1:j))
x=max(x,p(i:j)+p)
x=max(x,1+p(i:j)+p)
x=max(x,p(i:j)+1+p)
x=max(x,1*p(i:j)+p)
x=max(x,1*p(i:j)+p*1)
x=max(x,1*p(i:j)+p*1)
x=max(x,p(i:j))
x=max(x,p+p)
x=max(x,1+p+p(:j))
x=max(x,p+1+p(:j))
x=max(x,1*p+p(:j))
x=max(x,1*p+p(:j)*1)
x=max(x,1*p+p(:j)*1)
x=max(x,p(:j))

deallocate(a,z)
end
