extern signed int v1 (signed short, unsigned char, unsigned short, unsigned int);
extern signed int (*v2) (signed short, unsigned char, unsigned short, unsigned int);
extern unsigned char v5 (unsigned short, unsigned int, unsigned char, unsigned char);
extern unsigned char (*v6) (unsigned short, unsigned int, unsigned char, unsigned char);
extern unsigned short v7 (signed char, unsigned short);
extern unsigned short (*v8) (signed char, unsigned short);
extern signed short v9 (void);
extern signed short (*v10) (void);
extern void v11 (unsigned int, signed int, signed short);
extern void (*v12) (unsigned int, signed int, signed short);
extern signed short v15 (unsigned int, unsigned char, unsigned char);
extern signed short (*v16) (unsigned int, unsigned char, unsigned char);
extern unsigned int v17 (signed short, signed char, signed short, signed short);
extern unsigned int (*v18) (signed short, signed char, signed short, signed short);
extern unsigned char v19 (unsigned char, unsigned int, signed int, unsigned short);
extern unsigned char (*v20) (unsigned char, unsigned int, signed int, unsigned short);
extern void v21 (signed char, signed int, signed int);
extern void (*v22) (signed char, signed int, signed int);
extern signed int v23 (signed short, unsigned short);
extern signed int (*v24) (signed short, unsigned short);
extern signed char v25 (unsigned int, unsigned char);
extern signed char (*v26) (unsigned int, unsigned char);
extern signed char v27 (signed int);
extern signed char (*v28) (signed int);
extern unsigned short v29 (void);
extern unsigned short (*v30) (void);
extern int history[];
extern int history_index;
extern int trace;
signed short v106 = 0;
signed int v105 = 3;
signed short v104 = 2;
