extern unsigned char v1 (signed int, unsigned short, signed char);
extern unsigned char (*v2) (signed int, unsigned short, signed char);
extern unsigned int v3 (signed char, signed char, signed short, signed int);
extern unsigned int (*v4) (signed char, signed char, signed short, signed int);
extern signed char v5 (signed int, unsigned int, unsigned char);
extern signed char (*v6) (signed int, unsigned int, unsigned char);
extern unsigned char v7 (void);
extern unsigned char (*v8) (void);
extern signed short v9 (unsigned short);
extern signed short (*v10) (unsigned short);
extern void v11 (signed short, unsigned int);
extern void (*v12) (signed short, unsigned int);
extern void v13 (unsigned int);
extern void (*v14) (unsigned int);
extern unsigned char v15 (signed int, unsigned int);
extern unsigned char (*v16) (signed int, unsigned int);
extern unsigned short v17 (unsigned char);
extern unsigned short (*v18) (unsigned char);
extern void v19 (unsigned char, signed short, unsigned int);
extern void (*v20) (unsigned char, signed short, unsigned int);
extern unsigned int v21 (signed short, unsigned short);
extern unsigned int (*v22) (signed short, unsigned short);
extern unsigned int v23 (void);
extern unsigned int (*v24) (void);
extern unsigned int v25 (signed int);
extern unsigned int (*v26) (signed int);
extern unsigned char v27 (unsigned short, unsigned char, signed short);
extern unsigned char (*v28) (unsigned short, unsigned char, signed short);
extern unsigned char v29 (unsigned int, unsigned char, signed int);
extern unsigned char (*v30) (unsigned int, unsigned char, signed int);
extern int history[];
extern int history_index;
extern int trace;
unsigned int v59 = 4U;
signed char v58 = -3;
signed short v57 = -2;
