extern void v1 (unsigned int);
extern void (*v2) (unsigned int);
extern signed short v3 (unsigned char, unsigned int, unsigned short, signed char);
extern signed short (*v4) (unsigned char, unsigned int, unsigned short, signed char);
extern unsigned short v5 (signed char);
extern unsigned short (*v6) (signed char);
extern unsigned int v7 (signed short, unsigned int, signed char);
extern unsigned int (*v8) (signed short, unsigned int, signed char);
extern void v9 (unsigned short, signed int, unsigned short);
extern void (*v10) (unsigned short, signed int, unsigned short);
extern unsigned int v11 (unsigned short, unsigned int, signed char);
extern unsigned int (*v12) (unsigned short, unsigned int, signed char);
extern signed char v13 (signed char, signed char, signed int);
extern signed char (*v14) (signed char, signed char, signed int);
extern unsigned short v15 (signed char, signed char, unsigned char);
extern unsigned short (*v16) (signed char, signed char, unsigned char);
extern void v17 (unsigned int, unsigned short);
extern void (*v18) (unsigned int, unsigned short);
extern unsigned int v19 (unsigned int, unsigned char, signed short);
extern unsigned int (*v20) (unsigned int, unsigned char, signed short);
extern unsigned short v21 (unsigned char, unsigned int, unsigned int);
extern unsigned short (*v22) (unsigned char, unsigned int, unsigned int);
extern unsigned int v23 (unsigned char, unsigned short);
extern unsigned int (*v24) (unsigned char, unsigned short);
extern unsigned short v27 (signed char, unsigned short);
extern unsigned short (*v28) (signed char, unsigned short);
extern unsigned short v29 (signed int);
extern unsigned short (*v30) (signed int);
extern int history[];
extern int history_index;
extern int trace;
unsigned short v136 = 0;
unsigned char v135 = 3;
signed char v134 = 3;
