MODULE mod1
IMPLICIT NONE

INTEGER,DIMENSION(5) :: arr1 = (/1,2,3,4,5/) , arr2 = (/12,13,14,15,16/)

INTERFACE
FUNCTION fun_1(dd)
IMPLICIT NONE
INTEGER,DIMENSION(5) :: fun_1,dd
END FUNCTION
FUNCTION fun_2(dd2)
IMPLICIT NONE
INTEGER,DIMENSION(5) :: fun_2,dd2
END FUNCTION
END INTERFACE

END MODULE

PROGRAM main
USE mod1
IMPLICIT NONE

ASSOCIATE(aa => fun_1(arr1) + fun_2(arr2))   
  IF(aa(3) .EQ. 17) PRINT*,'pass'
END ASSOCIATE

END PROGRAM

FUNCTION fun_1(dd)
IMPLICIT NONE
INTEGER,DIMENSION(5) :: fun_1,dd
fun_1 = dd
END FUNCTION

FUNCTION fun_2(dd2)
IMPLICIT NONE
INTEGER,DIMENSION(5) :: fun_2,dd2
fun_2 = dd2
END FUNCTION
