MODULE mod1
IMPLICIT NONE

TYPE t1
  INTEGER(KIND = 4) :: r1
END TYPE

TYPE,EXTENDS(t1) :: t2
  INTEGER(KIND = 4) :: r2
END TYPE

INTERFACE OPERATOR( * )
  MODULE PROCEDURE multip1
END INTERFACE

INTERFACE OPERATOR( + )
  MODULE PROCEDURE addit
END INTERFACE

CONTAINS

FUNCTION multip1(d1,d2)
IMPLICIT NONE
CLASS(t2),DIMENSION(:),INTENT(IN) :: d1
CLASS(t1),DIMENSION(:),INTENT(IN) :: d2
CLASS(t2),DIMENSION(:),ALLOCATABLE :: multip1
ALLOCATE(multip1(5))
multip1%r2 = d1%r2 * d2%r1
END FUNCTION

FUNCTION addit(d1,d2)
IMPLICIT NONE
CLASS(t2),DIMENSION(:),INTENT(IN) :: d1
TYPE(t1),DIMENSION(5),INTENT(IN) :: d2
CLASS(t2),DIMENSION(:),ALLOCATABLE :: addit
ALLOCATE(addit(5))
addit%r2 = d1%r2 + d2%r1
END FUNCTION

END MODULE

PROGRAM main
USE mod1
IMPLICIT NONE

INTEGER(KIND = 4) :: res
TYPE(t1),DIMENSION(1:5) :: obj1
CLASS(*),DIMENSION(:),POINTER :: ptr
CLASS(t1),DIMENSION(:),POINTER :: ptr2
CLASS(t2),DIMENSION(:),ALLOCATABLE :: allc
ALLOCATE(allc(5),ptr2(5))
allc%r2 = 3
obj1%r1 = 2
ptr2%r1 = 4

ALLOCATE(ptr(5),SOURCE = ptr2)

res = fun(allc,ptr,obj1)

IF(res .EQ. 1) THEN
  PRINT*,'pass'
ELSE
  PRINT*,101
END IF 

CONTAINS

FUNCTION fun(dd1,dd2,dd3)
INTEGER(KIND = 4) :: fun
CLASS(t2),DIMENSION(:),ALLOCATABLE :: dd1
CLASS(*),DIMENSION(:),POINTER :: dd2
TYPE(t1),DIMENSION(1:5) :: dd3
SELECT TYPE(dd2)
TYPE IS(t1)
  ASSOCIATE(aa => (dd1 * dd2) + dd3)
    IF(ALL(aa(2:4)%r2 .EQ. 14)) THEN
      fun = 1
    ELSE
      fun = 0
    END IF
  END ASSOCIATE
END SELECT
END FUNCTION

END PROGRAM
