MODULE mod1
IMPLICIT NONE

INTERFACE
SUBROUTINE sub(dy1,dy2,*,*)
REAL,DIMENSION(2:6) :: dy1
REAL,DIMENSION(:),POINTER :: dy2
END SUBROUTINE
END INTERFACE

END MODULE

PROGRAM main
USE mod1
IMPLICIT NONE

REAL,DIMENSION(2:6) :: arr = [2.2,1.0,3.0,6.0,2.1]
REAL,DIMENSION(:),POINTER :: ptr 
ALLOCATE(ptr(3:7))
ptr = [2.1,0.0,1.1,5.4,3.2]

CALL sub(arr,ptr,*10,*20)
10 PRINT*,101
20 PRINT*,'pass'

END PROGRAM

SUBROUTINE sub(dy1,dy2,*,*)
IMPLICIT NONE
REAL,DIMENSION(2:6) :: dy1
REAL,DIMENSION(:),POINTER :: dy2
ASSOCIATE(aa => dy1(2:6:2)+dy2(3:7:2))
  IF(ALL(aa(1:3) .GT. 6.0)) THEN
    RETURN 1
  ELSE
    RETURN 2
  END IF
END ASSOCIATE
END SUBROUTINE
