MODULE mod1
IMPLICIT NONE

TYPE t1
  INTEGER(KIND = 2) :: r1
END TYPE

TYPE,EXTENDS(t1) :: t2
  INTEGER(KIND = 2) :: r2
END TYPE

INTERFACE OPERATOR(.plus.)
  MODULE PROCEDURE addit
END INTERFACE

INTERFACE OPERATOR(.mult.)
  MODULE PROCEDURE multip
END INTERFACE

CONTAINS

FUNCTION addit(d1,d2)
IMPLICIT NONE
CLASS(t2),INTENT(IN) :: d1,d2
CLASS(t2),ALLOCATABLE :: addit
ALLOCATE(addit)
addit%r2 = d1%r2 + d2%r2
END FUNCTION

FUNCTION multip(d1,d2)
IMPLICIT NONE
CLASS(t2),INTENT(IN) :: d1
INTEGER,INTENT(IN) :: d2
CLASS(t2),ALLOCATABLE :: multip
ALLOCATE(multip)
multip%r2 = d1%r2 * d2
END FUNCTION
END MODULE

PROGRAM main
USE mod1
IMPLICIT NONE

INTEGER :: res
CLASS(*),ALLOCATABLE :: aa1
CLASS(t2),ALLOCATABLE :: aa2
ALLOCATE(aa2)

aa2%r2 = 2

ALLOCATE(t2 :: aa1)

res = fun(aa1,aa2)

IF(res .EQ. 1) THEN
  PRINT*,'pass'
ELSE
  PRINT*,101
END IF

CONTAINS

INTEGER FUNCTION fun(d1,d2)
IMPLICIT NONE
CLASS(*),ALLOCATABLE :: d1
CLASS(t2),ALLOCATABLE :: d2
SELECT TYPE(d1)
TYPE IS(t2)
  d1%r2 = 3
  ASSOCIATE(aa => d1 .mult. 5)
    ASSOCIATE(bb => aa .plus. d2)
      SELECT TYPE(bb)
        TYPE IS(t2)
        fun = 1   
      END SELECT
    END ASSOCIATE
  END ASSOCIATE
END SELECT
END FUNCTION

END PROGRAM
