MODULE mod1
IMPLICIT NONE

TYPE t1
  INTEGER(KIND = 1):: r1
END TYPE

TYPE,EXTENDS(t1) :: t2
  INTEGER(KIND = 1) :: r2
END TYPE

INTERFACE OPERATOR ( * )
  MODULE PROCEDURE multip
END INTERFACE

CONTAINS

FUNCTION multip(dd1,dd2)
IMPLICIT NONE
CLASS(t2),DIMENSION(:),INTENT(IN) :: dd1 
CLASS(t1),DIMENSION(:),ALLOCATABLE :: multip 
CLASS(t1),DIMENSION(:),INTENT(IN) :: dd2
ALLOCATE(t2 :: multip(1:10))
SELECT TYPE(multip)
TYPE IS(t2)
  multip%r2 = dd1%r2 * dd2%r1
END SELECT
END FUNCTION

END MODULE 

PROGRAM main
USE mod1
IMPLICIT NONE

INTEGER(KIND = 1) :: num = 20
CLASS(*),DIMENSION(:),ALLOCATABLE :: allc
CLASS(t1),DIMENSION(:),POINTER :: ptr

ALLOCATE(ptr(1:10))
ptr%r1 = 3

ALLOCATE(t2 :: allc(1:10))

SELECT TYPE(allc)
CLASS IS(t2)
  allc%r2 = 2
  ASSOCIATE(aa => fun_1(allc) * fun_2(ptr))
    SELECT TYPE(aa)
    CLASS IS(t2)
    DO WHILE(num .GT. aa(5)%r2)
      num = num - 2
    END DO
    IF(SIZE(aa) .NE. 10) PRINT*,102
    IF(SIZEOF(aa) .NE. 20) PRINT*,103,sizeof(aa(1))
    IF(ALL(SHAPE(aa) .NE. 10)) PRINT*,104
    END SELECT
  END ASSOCIATE
END SELECT

IF(num .eq. 6) THEN
  PRINT*,'pass'
ELSE
  PRINT*,101
END IF

CONTAINS

FUNCTION fun_1(dd1)
IMPLICIT NONE
CLASS(t2),DIMENSION(:),ALLOCATABLE :: fun_1
CLASS(t2),DIMENSION(:) :: dd1
ALLOCATE(fun_1(1:10))
fun_1%r2 = dd1%r2
END FUNCTION

FUNCTION fun_2(dd1)
IMPLICIT NONE
CLASS(t1),DIMENSION(:),POINTER :: dd1,fun_2
ALLOCATE(fun_2(1:10))
fun_2 => dd1(1:10)
END FUNCTION

END PROGRAM
