MODULE mod1
IMPLICIT NONE

TYPE t1
  CHARACTER(LEN = 5) :: ch
END TYPE

TYPE,EXTENDS(t1) :: t2
  CHARACTER(LEN = 6) :: ch2
END TYPE

INTERFACE
FUNCTION fun_2(dd2)
CHARACTER :: fun_2,dd2
END FUNCTION
END INTERFACE

INTERFACE OPERATOR ( + )
  MODULE PROCEDURE addit
END INTERFACE

CONTAINS

FUNCTION addit(d1,d2)
IMPLICIT NONE
CLASS(t2),INTENT(IN) :: d1
CHARACTER,INTENT(IN) :: d2
CLASS(t2),ALLOCATABLE :: addit
ALLOCATE(addit)
addit%ch2 = d1%ch2 // d2
END FUNCTION

END MODULE

PROGRAM main
USE mod1
IMPLICIT NONE

CHARACTER :: ac1 = 'x' 
CLASS(t2),ALLOCATABLE :: allc
ALLOCATE(allc) 
allc%ch2 ='xxax'

ASSOCIATE(aa => fun_1(allc) +  fun_2(ac1))
  IF('xax' .EQ. aa%ch2(2:4)) THEN 
    PRINT*,'pass'
  ELSE
    PRINT*,101
  END IF
END ASSOCIATE

CONTAINS

FUNCTION fun_1(dd1)
IMPLICIT NONE
CLASS(t2),ALLOCATABLE :: dd1,fun_1
ALLOCATE(fun_1)
fun_1%ch2 = TRIM(dd1%ch2)
END FUNCTION

END PROGRAM

FUNCTION fun_2(dd2)
IMPLICIT NONE
CHARACTER :: dd2,fun_2
fun_2 = dd2
END FUNCTION
