MODULE mod1
IMPLICIT NONE

TYPE t1
  REAL :: r1
END TYPE

TYPE,EXTENDS(t1) :: t2
  REAL :: r2
END TYPE

INTERFACE OPERATOR ( * )
  MODULE PROCEDURE multip
END INTERFACE

CONTAINS

FUNCTION multip(dd1,dd2)
IMPLICIT NONE
CLASS(t2),DIMENSION(:),INTENT(IN) :: dd1
CLASS(t2),DIMENSION(:),ALLOCATABLE :: multip 
REAL,INTENT(IN) :: dd2
ALLOCATE(multip(1:10))
multip%r2 = dd1%r2 * dd2
END FUNCTION

END MODULE 

PROGRAM main
USE mod1
IMPLICIT NONE

INTEGER :: i
TYPE(t2),DIMENSION(1:10) :: obj
CLASS(t2),DIMENSION(:),ALLOCATABLE :: allc
ALLOCATE(allc(1:10))
allc%r2 = (/1.0,-1.0,1.0,-1.0,1.0,-1.0,1.0,-1.0,1.0,-1.0/)
obj = fun(allc)

IF(ALL(obj(2:10:2)%r2 .EQ. 0.0)) THEN
  PRINT*,'pass'
ELSE
  PRINT*,101
END IF

CONTAINS

FUNCTION fun(dd1)
IMPLICIT NONE
CLASS(t2),DIMENSION(:),ALLOCATABLE :: dd1,fun
ALLOCATE(fun(1:10))
ASSOCIATE(aa => dd1 * 3.0)
  FORALL(i = 1:10,aa(i)%r2 .EQ. -3.0)
    fun(i)%r2 = 0.0
  END FORALL
END ASSOCIATE
END FUNCTION

END PROGRAM
