MODULE mod1
IMPLICIT NONE

INTEGER,DIMENSION(:),ALLOCATABLE :: arr1

INTERFACE
FUNCTION fun_1(dd)
IMPLICIT NONE
INTEGER,DIMENSION(:),POINTER :: fun_1
INTEGER,DIMENSION(:),ALLOCATABLE,TARGET :: dd
END FUNCTION
END INTERFACE

END MODULE

PROGRAM main
USE mod1
IMPLICIT NONE

ALLOCATE(arr1(5))
arr1 = (/1,2,3,4,5/)

ASSOCIATE(aa => fun_1(arr1) + (/1,-2,3,-4,5/))   
  IF(aa(3) .EQ. 6) PRINT*,'pass'
END ASSOCIATE

END PROGRAM

FUNCTION fun_1(dd)
IMPLICIT NONE
INTEGER,DIMENSION(:),POINTER :: fun_1
INTEGER,DIMENSION(:),ALLOCATABLE,TARGET :: dd
fun_1 => dd
END FUNCTION
