MODULE mod1
IMPLICIT NONE

INTEGER,DIMENSION(:,:,:),ALLOCATABLE :: arr1

INTERFACE
FUNCTION fun_1(dd)
IMPLICIT NONE
INTEGER,DIMENSION(:,:,:),POINTER :: fun_1
INTEGER,DIMENSION(:,:,:),ALLOCATABLE,TARGET :: dd
END FUNCTION
END INTERFACE

END MODULE

PROGRAM main
USE mod1
IMPLICIT NONE

INTEGER,DIMENSION(:,:,:),ALLOCATABLE :: arr2 

ALLOCATE(arr1(-3:-2,1:3,10:13),arr2(-2:1,1:5,9:14))
arr2(:,:,:) = 3

ASSOCIATE(aa => fun_1(arr1) + arr2(-1:0,2:4,10:13))   
  IF(ALL(aa(1:2,1:3,1:4) .EQ. 6)) PRINT*,'pass'
END ASSOCIATE

END PROGRAM

FUNCTION fun_1(dd)
IMPLICIT NONE
INTEGER,DIMENSION(:,:,:),POINTER :: fun_1
INTEGER,DIMENSION(:,:,:),ALLOCATABLE,TARGET :: dd
dd = 3
fun_1 => dd
END FUNCTION
