extern void v1 (unsigned short);
extern void (*v2) (unsigned short);
extern signed int v3 (unsigned int, unsigned char, unsigned char, unsigned short);
extern signed int (*v4) (unsigned int, unsigned char, unsigned char, unsigned short);
extern void v5 (unsigned int, signed char);
extern void (*v6) (unsigned int, signed char);
extern unsigned int v7 (unsigned char, signed short, unsigned short);
extern unsigned int (*v8) (unsigned char, signed short, unsigned short);
extern signed short v9 (signed short);
extern signed short (*v10) (signed short);
extern unsigned short v11 (unsigned char, signed char, unsigned char, signed short);
extern unsigned short (*v12) (unsigned char, signed char, unsigned char, signed short);
extern void v13 (signed short);
extern void (*v14) (signed short);
extern signed int v15 (signed int, signed int, signed char);
extern signed int (*v16) (signed int, signed int, signed char);
extern unsigned short v17 (signed char);
extern unsigned short (*v18) (signed char);
extern unsigned char v19 (unsigned short, unsigned int);
extern unsigned char (*v20) (unsigned short, unsigned int);
extern signed char v21 (unsigned char, signed int, signed int);
extern signed char (*v22) (unsigned char, signed int, signed int);
extern void v23 (signed int, unsigned int, signed char);
extern void (*v24) (signed int, unsigned int, signed char);
extern unsigned int v25 (signed short);
extern unsigned int (*v26) (signed short);
extern unsigned char v27 (unsigned short, unsigned int, signed char);
extern unsigned char (*v28) (unsigned short, unsigned int, signed char);
extern unsigned short v29 (unsigned short, signed char, unsigned short, signed char);
extern unsigned short (*v30) (unsigned short, signed char, unsigned short, signed char);
extern int history[];
extern int history_index;
extern int trace;
unsigned short v159 = 3;
signed int v158 = -4;
signed char v157 = 3;
