extern signed short v3 (signed int, signed char);
extern signed short (*v4) (signed int, signed char);
extern unsigned short v5 (unsigned char, signed short, unsigned int, unsigned int);
extern unsigned short (*v6) (unsigned char, signed short, unsigned int, unsigned int);
extern unsigned short v7 (void);
extern unsigned short (*v8) (void);
extern signed short v9 (signed short, unsigned char);
extern signed short (*v10) (signed short, unsigned char);
extern unsigned short v11 (unsigned short);
extern unsigned short (*v12) (unsigned short);
extern signed int v13 (unsigned char);
extern signed int (*v14) (unsigned char);
extern unsigned short v15 (signed short, signed char, signed int, signed char);
extern unsigned short (*v16) (signed short, signed char, signed int, signed char);
extern unsigned short v17 (void);
extern unsigned short (*v18) (void);
extern void v19 (unsigned char, signed int);
extern void (*v20) (unsigned char, signed int);
extern unsigned int v21 (signed char);
extern unsigned int (*v22) (signed char);
extern void v23 (signed int, signed int);
extern void (*v24) (signed int, signed int);
extern unsigned int v25 (unsigned int, signed short, unsigned char);
extern unsigned int (*v26) (unsigned int, signed short, unsigned char);
extern void v27 (unsigned int);
extern void (*v28) (unsigned int);
extern unsigned char v29 (unsigned char, signed short);
extern unsigned char (*v30) (unsigned char, signed short);
extern int history[];
extern int history_index;
extern int trace;
signed char v67 = -2;
unsigned short v66 = 7;
unsigned short v65 = 0;
