MODULE MOD1
TYPE NODE
INTEGER,ALLOCATABLE :: VALUE(:)
TYPE (NODE), ALLOCATABLE :: NEXT_NODE(:)
TYPE (NODE), ALLOCATABLE :: PREV_NODE(:)
  
CONTAINS
PROCEDURE :: WFORM
PROCEDURE :: RFORM
GENERIC :: WRITE(UNFORMATTED) => WFORM
GENERIC :: READ(UNFORMATTED)  => RFORM
END TYPE

TYPE TY
TYPE(NODE),ALLOCATABLE :: OBJ(:)
TYPE(NODE),ALLOCATABLE :: OBJ2(:)
END TYPE

TYPE(TY)::BASE

CONTAINS
SUBROUTINE WFORM (DTV, UNIT, IOSTAT, IOMSG)
CLASS(NODE), INTENT(IN)     :: DTV
INTEGER, INTENT(IN) :: UNIT
INTEGER, INTENT(OUT)        :: IOSTAT
CHARACTER(*), INTENT(INOUT) :: IOMSG

IF (ALLOCATED(DTV%VALUE))THEN
WRITE(UNIT, IOSTAT = IOSTAT, IOMSG = IOMSG) DTV%VALUE
ENDIF

IF(ALLOCATED(DTV%NEXT_NODE))THEN
 WRITE(UNIT,IOSTAT=IOSTAT,IOMSG=IOMSG) DTV%NEXT_NODE
ENDIF

IF(ALLOCATED(DTV%PREV_NODE))THEN
 WRITE(UNIT,IOSTAT=IOSTAT,IOMSG=IOMSG) DTV%PREV_NODE
ENDIF
END SUBROUTINE

SUBROUTINE RFORM (DTV, UNIT, IOSTAT, IOMSG)
CLASS(NODE), INTENT(INOUT)  :: DTV
INTEGER, INTENT(IN) :: UNIT
INTEGER, INTENT(OUT)        :: IOSTAT
CHARACTER(*), INTENT(INOUT) :: IOMSG

IF (ALLOCATED(DTV%VALUE))THEN
READ(UNIT,IOSTAT=IOSTAT,IOMSG=IOMSG) DTV%VALUE
ENDIF

IF(ALLOCATED(DTV%NEXT_NODE))THEN
 READ(UNIT,IOSTAT=IOSTAT,IOMSG=IOMSG) DTV%NEXT_NODE
ENDIF

IF(ALLOCATED(DTV%PREV_NODE))THEN
 READ(UNIT,IOSTAT=IOSTAT,IOMSG=IOMSG) DTV%PREV_NODE
ENDIF
END SUBROUTINE
END MODULE

PROGRAM MAIN
USE MOD1
ALLOCATE(BASE%OBJ(2))
ALLOCATE(BASE%OBJ(2)%NEXT_NODE(3))
ALLOCATE(BASE%OBJ(2)%NEXT_NODE(3)%VALUE(3))
ALLOCATE(BASE%OBJ(2)%NEXT_NODE(3)%PREV_NODE(4))
ALLOCATE(BASE%OBJ(2)%NEXT_NODE(3)%PREV_NODE(3)%VALUE(4))
ALLOCATE(BASE%OBJ(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(5))
ALLOCATE(BASE%OBJ(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(3)%VALUE(5))

BASE%OBJ(2)%NEXT_NODE(3)%VALUE = 11
BASE%OBJ(2)%NEXT_NODE(3)%PREV_NODE(3)%VALUE = 12
BASE%OBJ(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(3)%VALUE = 13

ALLOCATE(BASE%OBJ(1)%PREV_NODE(2))
ALLOCATE(BASE%OBJ(1)%PREV_NODE(2)%VALUE(2))
ALLOCATE(BASE%OBJ(1)%PREV_NODE(2)%NEXT_NODE(3))
ALLOCATE(BASE%OBJ(1)%PREV_NODE(2)%NEXT_NODE(2)%VALUE(3))
ALLOCATE(BASE%OBJ(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(4))
ALLOCATE(BASE%OBJ(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(2)%VALUE(4))

BASE%OBJ(1)%PREV_NODE(2)%VALUE = 14
BASE%OBJ(1)%PREV_NODE(2)%NEXT_NODE(2)%VALUE = 15
BASE%OBJ(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(2)%VALUE = 16

ALLOCATE(BASE%OBJ2(2))
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE(3))
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE(3)%VALUE(3))
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(4))
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%VALUE(4))
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(5))
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(3)%VALUE(5))

BASE%OBJ2(2)%NEXT_NODE(3)%VALUE = 21
BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%VALUE = 22
BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(3)%VALUE = 23

ALLOCATE(BASE%OBJ2(1)%PREV_NODE(2))
ALLOCATE(BASE%OBJ2(1)%PREV_NODE(2)%VALUE(2))
ALLOCATE(BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(3))
ALLOCATE(BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%VALUE(3))
ALLOCATE(BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(4))
ALLOCATE(BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(2)%VALUE(4))

BASE%OBJ2(1)%PREV_NODE(2)%VALUE = 24
BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%VALUE = 25
BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(2)%VALUE = 26

OPEN(71, FILE='fort.90', FORM='UNFORMATTED')
WRITE(71) BASE%OBJ2
CLOSE(71)

OPEN(77, FILE='fort.90', FORM='UNFORMATTED')
READ(77) BASE%OBJ
CLOSE(77, STATUS='DELETE')

BASE%OBJ2(2)%NEXT_NODE(3)%VALUE = 31
BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%VALUE = 32
BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(3)%VALUE = 33

BASE%OBJ2(1)%PREV_NODE(2)%VALUE = 34
BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%VALUE = 35
BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(2)%VALUE = 36

if (BASE%OBJ(2)%NEXT_NODE(3)%VALUE(2) /= 21) print*, 101
if (BASE%OBJ(2)%NEXT_NODE(3)%PREV_NODE(3)%VALUE(2) /= 22) print*, 102
if (BASE%OBJ(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(3)%VALUE(2) /= 23) print*, 103

if (BASE%OBJ(1)%PREV_NODE(2)%VALUE(2) /= 24) print*, 104
if (BASE%OBJ(1)%PREV_NODE(2)%NEXT_NODE(2)%VALUE(2) /= 25) print*, 105
if (BASE%OBJ(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(2)%VALUE(2) /= 26) print*, 106

print*,"PASS"
END
