TYPE NODE
INTEGER :: VALUE(3) = 20
CHARACTER(LEN=5) :: MSG = "WORLD"
TYPE (NODE), ALLOCATABLE :: NEXT_NODE(:)
END TYPE

TYPE TY
TYPE(NODE),ALLOCATABLE :: OBJ1
TYPE(NODE),ALLOCATABLE :: OBJ2
END TYPE

TYPE(TY)::BASE

ALLOCATE(BASE%OBJ1)

ALLOCATE(BASE%OBJ2)
ALLOCATE(BASE%OBJ2%NEXT_NODE(2))
ALLOCATE(BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(3))
ALLOCATE(BASE%OBJ2%NEXT_NODE(2)%NEXT_NODE(5))

BASE%OBJ1 = BASE%OBJ2

BASE%OBJ2%MSG = "OLLEH"
BASE%OBJ2%NEXT_NODE(1)%MSG = "DLROW"
BASE%OBJ2%NEXT_NODE(2)%MSG = "THGIN"
BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(1)%MSG = "NAPAJ"
BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(2)%MSG = "AIDNI"
BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(3)%MSG = "ANIHC"

BASE%OBJ2%VALUE = 30
BASE%OBJ2%NEXT_NODE(1)%VALUE = 31
BASE%OBJ2%NEXT_NODE(1)%VALUE(2) = 32
BASE%OBJ2%NEXT_NODE(2)%VALUE = 33
BASE%OBJ2%NEXT_NODE(2)%VALUE(2) = 34
BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(1)%VALUE = 35
BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(2)%VALUE = 36
BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(3)%VALUE = 37

if (BASE%OBJ1%VALUE(2) /= 20) print*, 101
if (BASE%OBJ1%NEXT_NODE(1)%VALUE(1) /= 20) print*, 102
if (BASE%OBJ1%NEXT_NODE(1)%VALUE(2) /= 20) print*, 103
if (BASE%OBJ1%NEXT_NODE(2)%VALUE(1) /= 20) print*, 104
if (BASE%OBJ1%NEXT_NODE(2)%VALUE(2) /= 20) print*, 105
if (BASE%OBJ1%NEXT_NODE(1)%NEXT_NODE(1)%VALUE(2) /= 20) print*, 106
if (BASE%OBJ1%NEXT_NODE(1)%NEXT_NODE(2)%VALUE(2) /= 20) print*, 107
if (BASE%OBJ1%NEXT_NODE(1)%NEXT_NODE(3)%VALUE(2) /= 20) print*, 108

if (BASE%OBJ1%MSG /= "WORLD") print*, 201
if (BASE%OBJ1%NEXT_NODE(1)%MSG /= "WORLD") print*, 202
if (BASE%OBJ1%NEXT_NODE(2)%MSG /= "WORLD") print*, 203
if (BASE%OBJ1%NEXT_NODE(1)%NEXT_NODE(1)%MSG /= "WORLD") print*, 204
if (BASE%OBJ1%NEXT_NODE(1)%NEXT_NODE(2)%MSG /= "WORLD") print*, 205
if (BASE%OBJ1%NEXT_NODE(1)%NEXT_NODE(3)%MSG /= "WORLD") print*, 206

if (SIZE(BASE%OBJ1%NEXT_NODE) /= 2) print*, 301
if (SIZE(BASE%OBJ1%NEXT_NODE(1)%NEXT_NODE) /= 3) print*, 301
if (SIZE(BASE%OBJ1%NEXT_NODE(2)%NEXT_NODE) /= 5) print*, 301
print*,"PASS"
END
