MODULE MOD1
TYPE NODE
INTEGER,ALLOCATABLE :: VALUE(:)
CHARACTER(LEN=:),ALLOCATABLE :: MSG
TYPE (NODE), ALLOCATABLE :: NEXT_NODE(:)
END TYPE

TYPE TY
TYPE(NODE),ALLOCATABLE :: OBJ1
TYPE(NODE),ALLOCATABLE :: OBJ2
END TYPE

TYPE(TY)::BASE

CONTAINS 
SUBROUTINE SUB()
ALLOCATE(BASE%OBJ1)

ALLOCATE(BASE%OBJ2)
ALLOCATE(BASE%OBJ2%VALUE(2))
ALLOCATE(CHARACTER(LEN=5)::BASE%OBJ2%MSG)
ALLOCATE(BASE%OBJ2%NEXT_NODE(2))
ALLOCATE(BASE%OBJ2%NEXT_NODE(1)%VALUE(3))
ALLOCATE(BASE%OBJ2%NEXT_NODE(2)%VALUE(4))
ALLOCATE(CHARACTER(LEN=6)::BASE%OBJ2%NEXT_NODE(1)%MSG)
ALLOCATE(CHARACTER(LEN=6)::BASE%OBJ2%NEXT_NODE(2)%MSG)
ALLOCATE(BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(3))
ALLOCATE(BASE%OBJ2%NEXT_NODE(2)%NEXT_NODE(5))
ALLOCATE(BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(1)%VALUE(5))
ALLOCATE(BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(2)%VALUE(4))
ALLOCATE(BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(3)%VALUE(3))
ALLOCATE(CHARACTER(LEN=4)::BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(1)%MSG)
ALLOCATE(CHARACTER(LEN=4)::BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(2)%MSG)
ALLOCATE(CHARACTER(LEN=4)::BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(3)%MSG)

BASE%OBJ2%VALUE = 20
BASE%OBJ2%NEXT_NODE(1)%VALUE = 21
BASE%OBJ2%NEXT_NODE(1)%VALUE(2) = 22
BASE%OBJ2%NEXT_NODE(2)%VALUE = 23
BASE%OBJ2%NEXT_NODE(2)%VALUE(2) = 24
BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(1)%VALUE = 25
BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(2)%VALUE = 26
BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(3)%VALUE = 27

BASE%OBJ2%MSG = "HELLO"
BASE%OBJ2%NEXT_NODE(1)%MSG = "WORLD"
BASE%OBJ2%NEXT_NODE(2)%MSG = "NIGHT"
BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(1)%MSG = "JAPA"
BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(2)%MSG = "INDI"
BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(3)%MSG = "AERO"

BASE%OBJ1 = BASE%OBJ2

BASE%OBJ2%MSG = "OLLEH"
BASE%OBJ2%NEXT_NODE(1)%MSG = "DLROW"
BASE%OBJ2%NEXT_NODE(2)%MSG = "THGIN"
BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(1)%MSG = "NAPAJ"
BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(2)%MSG = "AIDNI"
BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(3)%MSG = "AEROK"

BASE%OBJ2%VALUE = 30
BASE%OBJ2%NEXT_NODE(1)%VALUE = 31
BASE%OBJ2%NEXT_NODE(1)%VALUE(2) = 32
BASE%OBJ2%NEXT_NODE(2)%VALUE = 33
BASE%OBJ2%NEXT_NODE(2)%VALUE(2) = 34
BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(1)%VALUE = 35
BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(2)%VALUE = 36
BASE%OBJ2%NEXT_NODE(1)%NEXT_NODE(3)%VALUE = 37

if (BASE%OBJ1%VALUE(2) /= 20) print*, 101
if (BASE%OBJ1%NEXT_NODE(1)%VALUE(1) /= 21) print*, 102
if (BASE%OBJ1%NEXT_NODE(1)%VALUE(2) /= 22) print*, 103
if (BASE%OBJ1%NEXT_NODE(2)%VALUE(1) /= 23) print*, 104
if (BASE%OBJ1%NEXT_NODE(2)%VALUE(2) /= 24) print*, 105
if (BASE%OBJ1%NEXT_NODE(1)%NEXT_NODE(1)%VALUE(2) /= 25) print*, 106
if (BASE%OBJ1%NEXT_NODE(1)%NEXT_NODE(2)%VALUE(2) /= 26) print*, 107
if (BASE%OBJ1%NEXT_NODE(1)%NEXT_NODE(3)%VALUE(2) /= 27) print*, 108

if (BASE%OBJ1%MSG /= "HELLO") print*, 201
if (BASE%OBJ1%NEXT_NODE(1)%MSG /= "WORLD") print*, 202
if (BASE%OBJ1%NEXT_NODE(2)%MSG /= "NIGHT") print*, 203
if (BASE%OBJ1%NEXT_NODE(1)%NEXT_NODE(1)%MSG /= "JAPA") print*, 204
if (BASE%OBJ1%NEXT_NODE(1)%NEXT_NODE(2)%MSG /= "INDI") print*, 205
if (BASE%OBJ1%NEXT_NODE(1)%NEXT_NODE(3)%MSG /= "AERO") print*, 206

if (SIZE(BASE%OBJ1%NEXT_NODE) /= 2) print*, 301
if (SIZE(BASE%OBJ1%NEXT_NODE(1)%NEXT_NODE) /= 3) print*, 301
if (SIZE(BASE%OBJ1%NEXT_NODE(2)%NEXT_NODE) /= 5) print*, 301
print*,"PASS"
END SUBROUTINE
END MODULE

USE MOD1

CALL SUB()
END
