TYPE NODE
INTEGER,ALLOCATABLE :: VALUE
TYPE (NODE), ALLOCATABLE :: NEXT_NODE
TYPE (NODE), ALLOCATABLE :: PREV_NODE
END TYPE

TYPE(NODE) :: OBJ
TYPE(NODE) :: OBJ2

ALLOCATE(OBJ%NEXT_NODE)
ALLOCATE(OBJ%NEXT_NODE%VALUE)
ALLOCATE(OBJ%NEXT_NODE%PREV_NODE)
ALLOCATE(OBJ%NEXT_NODE%PREV_NODE%VALUE)
ALLOCATE(OBJ%NEXT_NODE%PREV_NODE%NEXT_NODE)
ALLOCATE(OBJ%NEXT_NODE%PREV_NODE%NEXT_NODE%VALUE)

ALLOCATE(OBJ%PREV_NODE)
ALLOCATE(OBJ%PREV_NODE%NEXT_NODE)
ALLOCATE(OBJ%PREV_NODE%NEXT_NODE%PREV_NODE)

OBJ%NEXT_NODE%VALUE = 10
OBJ%NEXT_NODE%PREV_NODE%VALUE = 11
OBJ%NEXT_NODE%PREV_NODE%NEXT_NODE%VALUE = 12

ALLOCATE(OBJ2%NEXT_NODE)
ALLOCATE(OBJ2%NEXT_NODE%VALUE)
ALLOCATE(OBJ2%NEXT_NODE%PREV_NODE)
ALLOCATE(OBJ2%NEXT_NODE%PREV_NODE%VALUE)
ALLOCATE(OBJ2%NEXT_NODE%PREV_NODE%NEXT_NODE)
ALLOCATE(OBJ2%NEXT_NODE%PREV_NODE%NEXT_NODE%VALUE)

ALLOCATE(OBJ2%PREV_NODE)
ALLOCATE(OBJ2%PREV_NODE%VALUE)
ALLOCATE(OBJ2%PREV_NODE%NEXT_NODE)
ALLOCATE(OBJ2%PREV_NODE%NEXT_NODE%VALUE)
ALLOCATE(OBJ2%PREV_NODE%NEXT_NODE%PREV_NODE)

OBJ2%NEXT_NODE%VALUE = 21
OBJ2%NEXT_NODE%PREV_NODE%VALUE = 22
OBJ2%NEXT_NODE%PREV_NODE%NEXT_NODE%VALUE = 23

OBJ2%PREV_NODE%VALUE = 24
OBJ2%PREV_NODE%NEXT_NODE%VALUE = 25

OBJ=OBJ2

OBJ2%NEXT_NODE%VALUE = 31
OBJ2%NEXT_NODE%PREV_NODE%VALUE = 32
OBJ2%NEXT_NODE%PREV_NODE%NEXT_NODE%VALUE = 33

OBJ2%PREV_NODE%VALUE = 34
OBJ2%PREV_NODE%NEXT_NODE%VALUE = 35

if (OBJ%NEXT_NODE%VALUE /= 21) print*, 101
if (OBJ%NEXT_NODE%PREV_NODE%VALUE /= 22) print*, 102
if (OBJ%NEXT_NODE%PREV_NODE%NEXT_NODE%VALUE /= 23) print*, 103
if (OBJ%PREV_NODE%VALUE /= 24) print*, 104
if (OBJ%PREV_NODE%NEXT_NODE%VALUE /= 25) print*, 105
print*,"PASS"
END
