TYPE NODE
INTEGER,ALLOCATABLE :: VALUE(:)
CLASS (NODE), ALLOCATABLE :: NEXT_NODE(:)
CLASS (NODE), ALLOCATABLE :: PREV_NODE(:)
END TYPE

TYPE, EXTENDS(NODE)::EXT
INTEGER,ALLOCATABLE :: II(:)
END TYPE

TYPE TY
TYPE(NODE),ALLOCATABLE :: OBJ2(:)
END TYPE

TYPE(TY)::BASE

ALLOCATE(BASE%OBJ2(2))
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE(3))
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE(3)%VALUE(3))
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(4))
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%VALUE(4))
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(5))
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(3)%VALUE(5))

BASE%OBJ2(2)%NEXT_NODE(3)%VALUE = 21
BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%VALUE = 22
BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(3)%VALUE = 23

ALLOCATE(BASE%OBJ2(1)%PREV_NODE(2))
ALLOCATE(BASE%OBJ2(1)%PREV_NODE(2)%VALUE(2))
ALLOCATE(EXT::BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(3))
ALLOCATE(BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%VALUE(3))
ALLOCATE(EXT::BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(4))
ALLOCATE(BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(2)%VALUE(4))

BASE%OBJ2(1)%PREV_NODE(2)%VALUE = 24
BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%VALUE = 25
BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(2)%VALUE = 26

CALL SUB((BASE%OBJ2))

CONTAINS
SUBROUTINE SUB(DMY)
TYPE(NODE)::DMY(:)

if (DMY(2)%NEXT_NODE(3)%VALUE(2) /= 21) print*, 101
if (DMY(2)%NEXT_NODE(3)%PREV_NODE(3)%VALUE(2) /= 22) print*, 102
if (DMY(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(3)%VALUE(2) /= 23) print*, 103

if (DMY(1)%PREV_NODE(2)%VALUE(2) /= 24) print*, 104
if (DMY(1)%PREV_NODE(2)%NEXT_NODE(2)%VALUE(2) /= 25) print*, 105
if (DMY(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(2)%VALUE(2) /= 26) print*, 106

if (SIZE(DMY) /= 2) print*, 201
if (SIZE(DMY(2)%NEXT_NODE) /= 3) print*, 202
if (SIZE(DMY(2)%NEXT_NODE(3)%PREV_NODE) /= 4) print*, 203
if (SIZE(DMY(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE) /= 5) print*, 204

if (SIZE(DMY(1)%PREV_NODE) /= 2) print*, 205
if (SIZE(DMY(1)%PREV_NODE(2)%NEXT_NODE) /= 3) print*, 206
if (SIZE(DMY(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE) /= 4) print*, 207

SELECT TYPE(X=>DMY(1)%PREV_NODE(2)%NEXT_NODE)
 TYPE IS(EXT)
 CLASS DEFAULT
  PRINT*,911
END SELECT

SELECT TYPE(X=>DMY(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE)
 TYPE IS(EXT)
 CLASS DEFAULT
  PRINT*,922
END SELECT

SELECT TYPE(X=>DMY(2)%NEXT_NODE(3)%PREV_NODE)
 TYPE IS(NODE)
 CLASS DEFAULT
  PRINT*,922
END SELECT

print*,"PASS"
END SUBROUTINE
END
