TYPE NODE
INTEGER,ALLOCATABLE :: VALUE
TYPE (NODE), ALLOCATABLE :: NEXT_NODE(:)
END TYPE

TYPE TY
TYPE(NODE),ALLOCATABLE::OBJ(:)
END TYPE

TYPE(TY) :: OBJ2

ALLOCATE(OBJ2%OBJ(3))
ALLOCATE(OBJ2%OBJ(1)%VALUE)
ALLOCATE(OBJ2%OBJ(3)%VALUE)

ALLOCATE(OBJ2%OBJ(3)%NEXT_NODE(2))
ALLOCATE(OBJ2%OBJ(3)%NEXT_NODE(1)%NEXT_NODE(3))
ALLOCATE(OBJ2%OBJ(3)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE(2))
ALLOCATE(OBJ2%OBJ(3)%NEXT_NODE(1)%NEXT_NODE(2)%NEXT_NODE(3))
ALLOCATE(OBJ2%OBJ(3)%NEXT_NODE(1)%NEXT_NODE(3)%NEXT_NODE(4))
ALLOCATE(OBJ2%OBJ(3)%NEXT_NODE(2)%NEXT_NODE(5))
ALLOCATE(OBJ2%OBJ(3)%NEXT_NODE(2)%NEXT_NODE(2)%NEXT_NODE(5))

ALLOCATE(OBJ2%OBJ(3)%NEXT_NODE(2)%VALUE)
ALLOCATE(OBJ2%OBJ(3)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE)
ALLOCATE(OBJ2%OBJ(3)%NEXT_NODE(2)%NEXT_NODE(3)%VALUE)
ALLOCATE(OBJ2%OBJ(3)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE)

OBJ2%OBJ(1)%VALUE = 21
OBJ2%OBJ(3)%VALUE = 22
OBJ2%OBJ(3)%NEXT_NODE(2)%VALUE = 23
OBJ2%OBJ(3)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE = 24
OBJ2%OBJ(3)%NEXT_NODE(2)%NEXT_NODE(3)%VALUE = 25
OBJ2%OBJ(3)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE = 26

CALL SUB ((OBJ2%OBJ))

CONTAINS
SUBROUTINE SUB(DMY)
TYPE(NODE)::DMY(:)

if (DMY(1)%VALUE /= 21) print*, 101
if (DMY(3)%VALUE /= 22) print*, 102
if (DMY(3)%NEXT_NODE(2)%VALUE /= 23) print*, 103
if (DMY(3)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE /= 24) print*, 104
if (DMY(3)%NEXT_NODE(2)%NEXT_NODE(3)%VALUE /= 25) print*, 105
if (DMY(3)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE /= 26) print*, 106

if (SIZE(DMY(3)%NEXT_NODE) /= 2) print*, 201
if (SIZE(DMY(3)%NEXT_NODE(1)%NEXT_NODE) /= 3) print*, 202
if (SIZE(DMY(3)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE) /= 2) print*, 203
if (SIZE(DMY(3)%NEXT_NODE(1)%NEXT_NODE(2)%NEXT_NODE) /= 3) print*, 204
if (SIZE(DMY(3)%NEXT_NODE(1)%NEXT_NODE(3)%NEXT_NODE) /= 4) print*, 205
if (SIZE(DMY(3)%NEXT_NODE(2)%NEXT_NODE) /= 5) print*, 206
if (SIZE(DMY(3)%NEXT_NODE(2)%NEXT_NODE(2)%NEXT_NODE) /= 5) print*, 207

print*,"PASS"
END SUBROUTINE
END
