TYPE TY
INTEGER,ALLOCATABLE :: VALUE
CLASS (TT), ALLOCATABLE :: OBJTT(:)
END TYPE

TYPE TT
INTEGER,ALLOCATABLE :: ALC
CHARACTER(LEN=:),ALLOCATABLE :: MSG(:)
END TYPE

TYPE, EXTENDS(TT)::EXT
INTEGER,ALLOCATABLE :: CMP
END TYPE

TYPE(TY),ALLOCATABLE :: OBJ1
TYPE(TY),ALLOCATABLE :: OBJ2

ALLOCATE(OBJ1)
ALLOCATE(OBJ1%VALUE)
ALLOCATE(OBJ1%OBJTT(2))
ALLOCATE(OBJ1%OBJTT(1)%ALC)
ALLOCATE(CHARACTER(LEN=5)::OBJ1%OBJTT(1)%MSG(2))
ALLOCATE(OBJ1%OBJTT(2)%ALC)
ALLOCATE(CHARACTER(LEN=5)::OBJ1%OBJTT(2)%MSG(3))

ALLOCATE(OBJ2)
ALLOCATE(OBJ2%VALUE)
ALLOCATE(EXT::OBJ2%OBJTT(3))
ALLOCATE(OBJ2%OBJTT(1)%ALC)
ALLOCATE(CHARACTER(LEN=6)::OBJ2%OBJTT(1)%MSG(3))
ALLOCATE(OBJ2%OBJTT(2)%ALC)
ALLOCATE(CHARACTER(LEN=7)::OBJ2%OBJTT(2)%MSG(4))
ALLOCATE(OBJ2%OBJTT(3)%ALC)
ALLOCATE(CHARACTER(LEN=8)::OBJ2%OBJTT(3)%MSG(5))

SELECT TYPE(X => OBJ2%OBJTT)
 TYPE IS (EXT)
  ALLOCATE(X(1)%CMP) 
  ALLOCATE(X(2)%CMP) 
  ALLOCATE(X(3)%CMP)

  X(1)%CMP = 44 
  X(2)%CMP = 55 
  X(3)%CMP = 66 
 CLASS DEFAULT
  print*, "200"
END SELECT

OBJ1%VALUE = 10
OBJ1%OBJTT(1)%ALC = 11
OBJ1%OBJTT(2)%ALC = 12
OBJ1%OBJTT(1)%MSG = "AAAAA"
OBJ1%OBJTT(2)%MSG = "BBBBB"

OBJ2%VALUE = 20
OBJ2%OBJTT(1)%ALC = 21
OBJ2%OBJTT(2)%ALC = 22
OBJ2%OBJTT(3)%ALC = 23
OBJ2%OBJTT(1)%MSG = "DDDDDD"
OBJ2%OBJTT(2)%MSG = "EEEEEEE"
OBJ2%OBJTT(3)%MSG = "FFFFFFFF"

CALL MOVE_ALLOC(OBJ2, OBJ1)

if (OBJ1%VALUE /= 20) print*, 101
if (OBJ1%OBJTT(1)%ALC /= 21) print*, 102
if (OBJ1%OBJTT(2)%ALC /= 22) print*, 103
if (OBJ1%OBJTT(3)%ALC /= 23) print*, 104
if (OBJ1%OBJTT(1)%MSG(2) /= "DDDDDD") print*, 105
if (OBJ1%OBJTT(2)%MSG(3) /= "EEEEEEE") print*, 106
if (OBJ1%OBJTT(3)%MSG(4) /= "FFFFFFFF") print*, 107
if (SIZE(OBJ1%OBJTT(1)%MSG) /= 3) print*, 108
if (SIZE(OBJ1%OBJTT(2)%MSG) /= 4) print*, 109
if (SIZE(OBJ1%OBJTT(3)%MSG) /= 5) print*, 110
if (LEN(OBJ1%OBJTT(1)%MSG(2)) /= 6) print*, 111
if (LEN(OBJ1%OBJTT(2)%MSG(2)) /= 7) print*, 112
if (LEN(OBJ1%OBJTT(3)%MSG(4)) /= 8) print*, 113

SELECT TYPE(X => OBJ1%OBJTT)
 TYPE IS (EXT)
  IF(X(1)%CMP /= 44) print*, 201
  IF(X(2)%CMP /= 55) print*, 202
  IF(X(3)%CMP /= 66) print*, 203
 CLASS DEFAULT
  print*, "204"
END SELECT

print*,"PASS"
END
