TYPE NODE
INTEGER,ALLOCATABLE :: VALUE
TYPE (NODE), ALLOCATABLE :: NEXT_NODE
TYPE (NODE), ALLOCATABLE :: PREV_NODE
END TYPE

TYPE(NODE),ALLOCATABLE :: OBJ(:)
TYPE(NODE),ALLOCATABLE :: OBJ2(:)

ALLOCATE(OBJ2(2))
ALLOCATE(OBJ2(2)%NEXT_NODE)
ALLOCATE(OBJ2(2)%NEXT_NODE%VALUE)
ALLOCATE(OBJ2(2)%NEXT_NODE%PREV_NODE)
ALLOCATE(OBJ2(2)%NEXT_NODE%PREV_NODE%VALUE)
ALLOCATE(OBJ2(2)%NEXT_NODE%PREV_NODE%NEXT_NODE)
ALLOCATE(OBJ2(2)%NEXT_NODE%PREV_NODE%NEXT_NODE%VALUE)

OBJ2(2)%NEXT_NODE%VALUE = 21
OBJ2(2)%NEXT_NODE%PREV_NODE%VALUE = 22
OBJ2(2)%NEXT_NODE%PREV_NODE%NEXT_NODE%VALUE = 23

ALLOCATE(OBJ2(1)%PREV_NODE)
ALLOCATE(OBJ2(1)%PREV_NODE%VALUE)
ALLOCATE(OBJ2(1)%PREV_NODE%NEXT_NODE)
ALLOCATE(OBJ2(1)%PREV_NODE%NEXT_NODE%VALUE)
ALLOCATE(OBJ2(1)%PREV_NODE%NEXT_NODE%PREV_NODE)
ALLOCATE(OBJ2(1)%PREV_NODE%NEXT_NODE%PREV_NODE%VALUE)

OBJ2(1)%PREV_NODE%VALUE = 24
OBJ2(1)%PREV_NODE%NEXT_NODE%VALUE = 25
OBJ2(1)%PREV_NODE%NEXT_NODE%PREV_NODE%VALUE = 26

ALLOCATE(OBJ, SOURCE = OBJ2)

OBJ2(2)%NEXT_NODE%VALUE = 31
OBJ2(2)%NEXT_NODE%PREV_NODE%VALUE = 32
OBJ2(2)%NEXT_NODE%PREV_NODE%NEXT_NODE%VALUE = 33

OBJ2(1)%PREV_NODE%VALUE = 34
OBJ2(1)%PREV_NODE%NEXT_NODE%VALUE = 35
OBJ2(1)%PREV_NODE%NEXT_NODE%PREV_NODE%VALUE = 36

if (OBJ(2)%NEXT_NODE%VALUE /= 21) print*, 101
if (OBJ(2)%NEXT_NODE%PREV_NODE%VALUE /= 22) print*, 102
if (OBJ(2)%NEXT_NODE%PREV_NODE%NEXT_NODE%VALUE /= 23) print*, 103
if (OBJ(1)%PREV_NODE%VALUE /= 24) print*, 104
if (OBJ(1)%PREV_NODE%NEXT_NODE%VALUE /= 25) print*, 105
if (OBJ(1)%PREV_NODE%NEXT_NODE%PREV_NODE%VALUE /= 26) print*, 106
print*,"PASS"
END
