TYPE NODE
INTEGER,ALLOCATABLE :: VALUE
TYPE (NODE), ALLOCATABLE :: ALC_NODE
TYPE (NODE), POINTER     :: PTR_NODE
END TYPE

TYPE(NODE) :: OBJ
TYPE(NODE) :: OBJ2

ALLOCATE(OBJ%ALC_NODE)
ALLOCATE(OBJ%PTR_NODE)
ALLOCATE(OBJ%ALC_NODE%VALUE)
ALLOCATE(OBJ%PTR_NODE%VALUE)
ALLOCATE(OBJ%ALC_NODE%ALC_NODE)
ALLOCATE(OBJ%ALC_NODE%PTR_NODE)
ALLOCATE(OBJ%ALC_NODE%ALC_NODE%VALUE)
ALLOCATE(OBJ%ALC_NODE%PTR_NODE%VALUE)
ALLOCATE(OBJ%ALC_NODE%ALC_NODE%ALC_NODE)
ALLOCATE(OBJ%ALC_NODE%PTR_NODE%ALC_NODE)
ALLOCATE(OBJ%ALC_NODE%ALC_NODE%ALC_NODE%VALUE)
ALLOCATE(OBJ%ALC_NODE%PTR_NODE%ALC_NODE%VALUE)

ALLOCATE(OBJ%PTR_NODE%PTR_NODE)
ALLOCATE(OBJ%PTR_NODE%ALC_NODE)
ALLOCATE(OBJ%PTR_NODE%PTR_NODE%VALUE)
ALLOCATE(OBJ%PTR_NODE%ALC_NODE%VALUE)
ALLOCATE(OBJ%PTR_NODE%PTR_NODE%PTR_NODE)
ALLOCATE(OBJ%PTR_NODE%ALC_NODE%PTR_NODE)
ALLOCATE(OBJ%PTR_NODE%PTR_NODE%PTR_NODE%VALUE)
ALLOCATE(OBJ%PTR_NODE%ALC_NODE%PTR_NODE%VALUE)
ALLOCATE(OBJ%PTR_NODE%PTR_NODE%PTR_NODE%PTR_NODE)
ALLOCATE(OBJ%PTR_NODE%ALC_NODE%PTR_NODE%ALC_NODE)
ALLOCATE(OBJ%PTR_NODE%PTR_NODE%PTR_NODE%PTR_NODE%VALUE)
ALLOCATE(OBJ%PTR_NODE%ALC_NODE%PTR_NODE%ALC_NODE%VALUE)

OBJ%ALC_NODE%VALUE = 110
OBJ%PTR_NODE%VALUE = 111
OBJ%ALC_NODE%ALC_NODE%VALUE = 112
OBJ%ALC_NODE%PTR_NODE%VALUE = 113
OBJ%ALC_NODE%ALC_NODE%ALC_NODE%VALUE = 114
OBJ%ALC_NODE%PTR_NODE%ALC_NODE%VALUE = 115

OBJ%PTR_NODE%PTR_NODE%VALUE = 116
OBJ%PTR_NODE%ALC_NODE%VALUE = 117
OBJ%PTR_NODE%PTR_NODE%PTR_NODE%VALUE = 118
OBJ%PTR_NODE%ALC_NODE%PTR_NODE%VALUE = 119
OBJ%PTR_NODE%PTR_NODE%PTR_NODE%PTR_NODE%VALUE = 120
OBJ%PTR_NODE%ALC_NODE%PTR_NODE%ALC_NODE%VALUE = 121

ALLOCATE(OBJ2%ALC_NODE)
ALLOCATE(OBJ2%PTR_NODE)
ALLOCATE(OBJ2%ALC_NODE%VALUE)
ALLOCATE(OBJ2%PTR_NODE%VALUE)
ALLOCATE(OBJ2%ALC_NODE%ALC_NODE)
ALLOCATE(OBJ2%ALC_NODE%PTR_NODE)
ALLOCATE(OBJ2%ALC_NODE%ALC_NODE%VALUE)
ALLOCATE(OBJ2%ALC_NODE%PTR_NODE%VALUE)
ALLOCATE(OBJ2%ALC_NODE%ALC_NODE%ALC_NODE)
ALLOCATE(OBJ2%ALC_NODE%PTR_NODE%ALC_NODE)
ALLOCATE(OBJ2%ALC_NODE%ALC_NODE%ALC_NODE%VALUE)
ALLOCATE(OBJ2%ALC_NODE%PTR_NODE%ALC_NODE%VALUE)

ALLOCATE(OBJ2%PTR_NODE%PTR_NODE)
ALLOCATE(OBJ2%PTR_NODE%ALC_NODE)
ALLOCATE(OBJ2%PTR_NODE%PTR_NODE%VALUE)
ALLOCATE(OBJ2%PTR_NODE%ALC_NODE%VALUE)
ALLOCATE(OBJ2%PTR_NODE%PTR_NODE%PTR_NODE)
ALLOCATE(OBJ2%PTR_NODE%ALC_NODE%PTR_NODE)
ALLOCATE(OBJ2%PTR_NODE%PTR_NODE%PTR_NODE%VALUE)
ALLOCATE(OBJ2%PTR_NODE%ALC_NODE%PTR_NODE%VALUE)
ALLOCATE(OBJ2%PTR_NODE%PTR_NODE%PTR_NODE%PTR_NODE)
ALLOCATE(OBJ2%PTR_NODE%ALC_NODE%PTR_NODE%ALC_NODE)
ALLOCATE(OBJ2%PTR_NODE%PTR_NODE%PTR_NODE%PTR_NODE%VALUE)
ALLOCATE(OBJ2%PTR_NODE%ALC_NODE%PTR_NODE%ALC_NODE%VALUE)

OBJ2%ALC_NODE%VALUE = 210
OBJ2%PTR_NODE%VALUE = 211
OBJ2%ALC_NODE%ALC_NODE%VALUE = 212
OBJ2%ALC_NODE%PTR_NODE%VALUE = 213
OBJ2%ALC_NODE%ALC_NODE%ALC_NODE%VALUE = 214
OBJ2%ALC_NODE%PTR_NODE%ALC_NODE%VALUE = 215

OBJ2%PTR_NODE%PTR_NODE%VALUE = 216
OBJ2%PTR_NODE%ALC_NODE%VALUE = 217
OBJ2%PTR_NODE%PTR_NODE%PTR_NODE%VALUE = 218
OBJ2%PTR_NODE%ALC_NODE%PTR_NODE%VALUE = 219
OBJ2%PTR_NODE%PTR_NODE%PTR_NODE%PTR_NODE%VALUE = 220
OBJ2%PTR_NODE%ALC_NODE%PTR_NODE%ALC_NODE%VALUE = 221

OBJ = OBJ2

OBJ2%ALC_NODE%VALUE = 310
OBJ2%PTR_NODE%VALUE = 311
OBJ2%ALC_NODE%ALC_NODE%VALUE = 312
OBJ2%ALC_NODE%PTR_NODE%VALUE = 313
OBJ2%ALC_NODE%ALC_NODE%ALC_NODE%VALUE = 314
OBJ2%ALC_NODE%PTR_NODE%ALC_NODE%VALUE = 315

OBJ2%PTR_NODE%PTR_NODE%VALUE = 316
OBJ2%PTR_NODE%ALC_NODE%VALUE = 317
OBJ2%PTR_NODE%PTR_NODE%PTR_NODE%VALUE = 318
OBJ2%PTR_NODE%ALC_NODE%PTR_NODE%VALUE = 319
OBJ2%PTR_NODE%PTR_NODE%PTR_NODE%PTR_NODE%VALUE = 320
OBJ2%PTR_NODE%ALC_NODE%PTR_NODE%ALC_NODE%VALUE = 321

if (OBJ%ALC_NODE%VALUE /= 210) print*, 101
if (OBJ%ALC_NODE%ALC_NODE%VALUE /= 212) print*, 102
if (OBJ%ALC_NODE%ALC_NODE%ALC_NODE%VALUE /= 214) print*, 103

if (OBJ%PTR_NODE%VALUE /= 311) print*, 104
if (OBJ%ALC_NODE%PTR_NODE%VALUE /= 313) print*, 105
if (OBJ%ALC_NODE%PTR_NODE%ALC_NODE%VALUE /= 315) print*, 106
if (OBJ%PTR_NODE%PTR_NODE%VALUE /= 316) print*, 107
if (OBJ%PTR_NODE%ALC_NODE%VALUE /= 317) print*, 108
if (OBJ%PTR_NODE%PTR_NODE%PTR_NODE%VALUE /= 318) print*, 109
if (OBJ%PTR_NODE%ALC_NODE%PTR_NODE%VALUE /= 319) print*, 110
if (OBJ%PTR_NODE%PTR_NODE%PTR_NODE%PTR_NODE%VALUE /= 320) print*, 111
if (OBJ%PTR_NODE%ALC_NODE%PTR_NODE%ALC_NODE%VALUE /= 321) print*, 112

print*,"PASS"
END
