TYPE TY0
INTEGER,ALLOCATABLE :: II
TYPE(TY0),ALLOCATABLE :: NODE0
END TYPE

TYPE TY1
INTEGER,ALLOCATABLE :: II
TYPE(TY1), ALLOCATABLE :: NODE1
TYPE(TY0),ALLOCATABLE :: NODE2
END TYPE

TYPE TY
INTEGER,ALLOCATABLE :: II
TYPE(TY1), ALLOCATABLE :: NODE3
END TYPE

TYPE BASE
TYPE(TY),ALLOCATABLE :: OBJ2
END TYPE

TYPE(BASE):: OBJ_BASE

ALLOCATE(OBJ_BASE%OBJ2)
ALLOCATE(OBJ_BASE%OBJ2%II)
ALLOCATE(OBJ_BASE%OBJ2%NODE3)
ALLOCATE(OBJ_BASE%OBJ2%NODE3%II)
ALLOCATE(OBJ_BASE%OBJ2%NODE3%NODE1)
ALLOCATE(OBJ_BASE%OBJ2%NODE3%NODE1%II)
ALLOCATE(OBJ_BASE%OBJ2%NODE3%NODE1%NODE1)
ALLOCATE(OBJ_BASE%OBJ2%NODE3%NODE1%NODE1%II)
ALLOCATE(OBJ_BASE%OBJ2%NODE3%NODE1%NODE2)
ALLOCATE(OBJ_BASE%OBJ2%NODE3%NODE1%NODE2%II)
ALLOCATE(OBJ_BASE%OBJ2%NODE3%NODE1%NODE2%NODE0)
ALLOCATE(OBJ_BASE%OBJ2%NODE3%NODE1%NODE2%NODE0%II)
ALLOCATE(OBJ_BASE%OBJ2%NODE3%NODE1%NODE2%NODE0%NODE0)
ALLOCATE(OBJ_BASE%OBJ2%NODE3%NODE1%NODE2%NODE0%NODE0%II)

ALLOCATE(OBJ_BASE%OBJ2%NODE3%NODE2)
ALLOCATE(OBJ_BASE%OBJ2%NODE3%NODE2%II)
ALLOCATE(OBJ_BASE%OBJ2%NODE3%NODE2%NODE0)
ALLOCATE(OBJ_BASE%OBJ2%NODE3%NODE2%NODE0%II)
ALLOCATE(OBJ_BASE%OBJ2%NODE3%NODE2%NODE0%NODE0)
ALLOCATE(OBJ_BASE%OBJ2%NODE3%NODE2%NODE0%NODE0%II)
ALLOCATE(OBJ_BASE%OBJ2%NODE3%NODE2%NODE0%NODE0%NODE0)
ALLOCATE(OBJ_BASE%OBJ2%NODE3%NODE2%NODE0%NODE0%NODE0%II)

OBJ_BASE%OBJ2%II = 20
OBJ_BASE%OBJ2%NODE3%II = 21
OBJ_BASE%OBJ2%NODE3%NODE1%II = 22
OBJ_BASE%OBJ2%NODE3%NODE1%NODE1%II = 23
OBJ_BASE%OBJ2%NODE3%NODE1%NODE2%II = 24
OBJ_BASE%OBJ2%NODE3%NODE1%NODE2%NODE0%II = 25
OBJ_BASE%OBJ2%NODE3%NODE1%NODE2%NODE0%NODE0%II = 26
OBJ_BASE%OBJ2%NODE3%NODE2%II = 27
OBJ_BASE%OBJ2%NODE3%NODE2%NODE0%II = 28
OBJ_BASE%OBJ2%NODE3%NODE2%NODE0%NODE0%II = 29
OBJ_BASE%OBJ2%NODE3%NODE2%NODE0%NODE0%NODE0%II = 299

DEALLOCATE(OBJ_BASE%OBJ2)

if (ALLOCATED(OBJ_BASE%OBJ2)) print*, 101
print*,"PASS"
END
