TYPE TY
INTEGER :: VALUE = 20
END TYPE

TYPE NODE
TYPE (TY),ALLOCATABLE :: OBJTY
TYPE (NODE), ALLOCATABLE :: NEXT_NODE
END TYPE

TYPE(NODE),ALLOCATABLE :: OBJ
TYPE(NODE),ALLOCATABLE :: OBJ2

ALLOCATE(OBJ)
ALLOCATE(OBJ%OBJTY)
ALLOCATE(OBJ%NEXT_NODE)
ALLOCATE(OBJ%NEXT_NODE%OBJTY)
ALLOCATE(OBJ%NEXT_NODE%NEXT_NODE)
ALLOCATE(OBJ%NEXT_NODE%NEXT_NODE%OBJTY)

OBJ%OBJTY%VALUE = 10
OBJ%NEXT_NODE%OBJTY%VALUE = 11
OBJ%NEXT_NODE%NEXT_NODE%OBJTY%VALUE = 12

ALLOCATE(OBJ2)
ALLOCATE(OBJ2%OBJTY)
ALLOCATE(OBJ2%NEXT_NODE)
ALLOCATE(OBJ2%NEXT_NODE%OBJTY)
ALLOCATE(OBJ2%NEXT_NODE%NEXT_NODE)
ALLOCATE(OBJ2%NEXT_NODE%NEXT_NODE%OBJTY)
ALLOCATE(OBJ2%NEXT_NODE%NEXT_NODE%NEXT_NODE)
ALLOCATE(OBJ2%NEXT_NODE%NEXT_NODE%NEXT_NODE%OBJTY)

OBJ=OBJ2

OBJ2%OBJTY%VALUE = 30
OBJ2%NEXT_NODE%OBJTY%VALUE = 31
OBJ2%NEXT_NODE%NEXT_NODE%OBJTY%VALUE = 32
OBJ2%NEXT_NODE%NEXT_NODE%NEXT_NODE%OBJTY%VALUE = 33

if (OBJ%OBJTY%VALUE /= 20) print*, 101
if (OBJ%NEXT_NODE%OBJTY%VALUE /= 20) print*, 103
if (OBJ%NEXT_NODE%NEXT_NODE%OBJTY%VALUE /= 20) print*, 105
if (OBJ%NEXT_NODE%NEXT_NODE%NEXT_NODE%OBJTY%VALUE /= 20) print*, 107

print*,"PASS"
END
