TYPE NODE
INTEGER,ALLOCATABLE :: VALUE
TYPE (NODE), ALLOCATABLE :: NEXT_NODE
TYPE (NODE), ALLOCATABLE :: PREV_NODE
END TYPE

TYPE TY
TYPE(NODE),ALLOCATABLE :: OBJ(:)
TYPE(NODE),ALLOCATABLE :: OBJ2(:)
END TYPE

TYPE(TY)::BASE

ALLOCATE(BASE%OBJ(2))
ALLOCATE(BASE%OBJ(1)%NEXT_NODE)
ALLOCATE(BASE%OBJ(1)%NEXT_NODE%VALUE)
ALLOCATE(BASE%OBJ(1)%NEXT_NODE%PREV_NODE)
ALLOCATE(BASE%OBJ(1)%NEXT_NODE%PREV_NODE%VALUE)
ALLOCATE(BASE%OBJ(1)%NEXT_NODE%PREV_NODE%NEXT_NODE)
ALLOCATE(BASE%OBJ(1)%NEXT_NODE%PREV_NODE%NEXT_NODE%VALUE)

BASE%OBJ(1)%NEXT_NODE%VALUE = 10
BASE%OBJ(1)%NEXT_NODE%PREV_NODE%VALUE = 11
BASE%OBJ(1)%NEXT_NODE%PREV_NODE%NEXT_NODE%VALUE = 12

ALLOCATE(BASE%OBJ(2)%PREV_NODE)
ALLOCATE(BASE%OBJ(2)%PREV_NODE%NEXT_NODE)
ALLOCATE(BASE%OBJ(2)%PREV_NODE%NEXT_NODE%PREV_NODE)

ALLOCATE(BASE%OBJ2(2))
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE)
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE%VALUE)
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE%PREV_NODE)
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE%PREV_NODE%VALUE)
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE%PREV_NODE%NEXT_NODE)
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE%PREV_NODE%NEXT_NODE%VALUE)

BASE%OBJ2(2)%NEXT_NODE%VALUE = 21
BASE%OBJ2(2)%NEXT_NODE%PREV_NODE%VALUE = 22
BASE%OBJ2(2)%NEXT_NODE%PREV_NODE%NEXT_NODE%VALUE = 23

ALLOCATE(BASE%OBJ2(1)%PREV_NODE)
ALLOCATE(BASE%OBJ2(1)%PREV_NODE%VALUE)
ALLOCATE(BASE%OBJ2(1)%PREV_NODE%NEXT_NODE)
ALLOCATE(BASE%OBJ2(1)%PREV_NODE%NEXT_NODE%VALUE)
ALLOCATE(BASE%OBJ2(1)%PREV_NODE%NEXT_NODE%PREV_NODE)

BASE%OBJ2(1)%PREV_NODE%VALUE = 24
BASE%OBJ2(1)%PREV_NODE%NEXT_NODE%VALUE = 25

BASE%OBJ = BASE%OBJ2

BASE%OBJ2(2)%NEXT_NODE%VALUE = 31
BASE%OBJ2(2)%NEXT_NODE%PREV_NODE%VALUE = 32
BASE%OBJ2(2)%NEXT_NODE%PREV_NODE%NEXT_NODE%VALUE = 33

BASE%OBJ2(1)%PREV_NODE%VALUE = 34
BASE%OBJ2(1)%PREV_NODE%NEXT_NODE%VALUE = 35

if (SIZE(BASE%OBJ) /= 2) print*, 901

if (BASE%OBJ(2)%NEXT_NODE%VALUE /= 21) print*, 101
if (BASE%OBJ(2)%NEXT_NODE%PREV_NODE%VALUE /= 22) print*, 102
if (BASE%OBJ(2)%NEXT_NODE%PREV_NODE%NEXT_NODE%VALUE /= 23) print*, 103
if (BASE%OBJ(1)%PREV_NODE%VALUE /= 24) print*, 104
if (BASE%OBJ(1)%PREV_NODE%NEXT_NODE%VALUE /= 25) print*, 105
print*,"PASS"
END
