MODULE MOD
TYPE NODE
INTEGER,ALLOCATABLE :: VALUE
TYPE (NODE), ALLOCATABLE :: NEXT_NODE(:)
END TYPE

TYPE TY
TYPE(NODE),ALLOCATABLE :: OBJ2(:)
END TYPE

TYPE(TY)::BASE

INTERFACE
SUBROUTINE SUB(DMY)
IMPORT NODE
TYPE(NODE)::DMY(:)
END SUBROUTINE
END INTERFACE
END MODULE

USE MOD
ALLOCATE(BASE%OBJ2(6))
ALLOCATE(BASE%OBJ2(3)%VALUE)
ALLOCATE(BASE%OBJ2(5)%VALUE)

ALLOCATE(BASE%OBJ2(5)%NEXT_NODE(2))
ALLOCATE(BASE%OBJ2(5)%NEXT_NODE(1)%NEXT_NODE(3))
ALLOCATE(BASE%OBJ2(5)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE(2))
ALLOCATE(BASE%OBJ2(5)%NEXT_NODE(1)%NEXT_NODE(2)%NEXT_NODE(3))
ALLOCATE(BASE%OBJ2(5)%NEXT_NODE(1)%NEXT_NODE(3)%NEXT_NODE(4))
ALLOCATE(BASE%OBJ2(5)%NEXT_NODE(2)%NEXT_NODE(5))
ALLOCATE(BASE%OBJ2(5)%NEXT_NODE(2)%NEXT_NODE(2)%NEXT_NODE(5))

ALLOCATE(BASE%OBJ2(5)%NEXT_NODE(2)%VALUE)
ALLOCATE(BASE%OBJ2(5)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE)
ALLOCATE(BASE%OBJ2(5)%NEXT_NODE(2)%NEXT_NODE(3)%VALUE)
ALLOCATE(BASE%OBJ2(5)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE)

BASE%OBJ2(3)%VALUE = 21
BASE%OBJ2(5)%VALUE = 22
BASE%OBJ2(5)%NEXT_NODE(2)%VALUE = 23
BASE%OBJ2(5)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE = 24
BASE%OBJ2(5)%NEXT_NODE(2)%NEXT_NODE(3)%VALUE = 25
BASE%OBJ2(5)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE = 26

CALL SUB((BASE%OBJ2(3:5)))
END

SUBROUTINE SUB(DMY)
USE MOD
TYPE(NODE)::DMY(:)

if (DMY(1)%VALUE /= 21) print*, 101
if (DMY(3)%VALUE /= 22) print*, 102
if (DMY(3)%NEXT_NODE(2)%VALUE /= 23) print*, 103
if (DMY(3)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE /= 24) print*, 104
if (DMY(3)%NEXT_NODE(2)%NEXT_NODE(3)%VALUE /= 25) print*, 105
if (DMY(3)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE /= 26) print*, 106

if (SIZE(DMY(3)%NEXT_NODE) /= 2) print*, 201
if (SIZE(DMY(3)%NEXT_NODE(1)%NEXT_NODE) /= 3) print*, 202
if (SIZE(DMY(3)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE) /= 2) print*, 203
if (SIZE(DMY(3)%NEXT_NODE(1)%NEXT_NODE(2)%NEXT_NODE) /= 3) print*, 204
if (SIZE(DMY(3)%NEXT_NODE(1)%NEXT_NODE(3)%NEXT_NODE) /= 4) print*, 205
if (SIZE(DMY(3)%NEXT_NODE(2)%NEXT_NODE) /= 5) print*, 206
if (SIZE(DMY(3)%NEXT_NODE(2)%NEXT_NODE(2)%NEXT_NODE) /= 5) print*, 207

print*,"PASS"
END SUBROUTINE
