TYPE NODE
INTEGER,ALLOCATABLE :: VALUE
CLASS (NODE), ALLOCATABLE :: NEXT_NODE(:)
END TYPE

TYPE, EXTENDS(NODE)::EXT
INTEGER,ALLOCATABLE :: II
END TYPE

TYPE TT
CLASS(NODE),ALLOCATABLE :: OBJ1(:)
END TYPE

TYPE,EXTENDS(TT)::TY
CLASS(NODE),ALLOCATABLE :: OBJ2(:)
END TYPE

TYPE(TY)::BASE

ALLOCATE(BASE%OBJ1(4))

ALLOCATE(BASE%OBJ2(3))
ALLOCATE(BASE%OBJ2(1)%VALUE)
ALLOCATE(BASE%OBJ2(3)%VALUE)

ALLOCATE(EXT::BASE%OBJ2(3)%NEXT_NODE(2))
ALLOCATE(BASE%OBJ2(3)%NEXT_NODE(1)%NEXT_NODE(3))
ALLOCATE(EXT::BASE%OBJ2(3)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE(2))
ALLOCATE(BASE%OBJ2(3)%NEXT_NODE(1)%NEXT_NODE(2)%NEXT_NODE(3))
ALLOCATE(BASE%OBJ2(3)%NEXT_NODE(1)%NEXT_NODE(3)%NEXT_NODE(4))
ALLOCATE(BASE%OBJ2(3)%NEXT_NODE(2)%NEXT_NODE(5))
ALLOCATE(BASE%OBJ2(3)%NEXT_NODE(2)%NEXT_NODE(2)%NEXT_NODE(5))

ALLOCATE(BASE%OBJ2(3)%NEXT_NODE(2)%VALUE)
ALLOCATE(BASE%OBJ2(3)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE)
ALLOCATE(BASE%OBJ2(3)%NEXT_NODE(2)%NEXT_NODE(3)%VALUE)
ALLOCATE(BASE%OBJ2(3)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE)

BASE%OBJ2(1)%VALUE = 21
BASE%OBJ2(3)%VALUE = 22
BASE%OBJ2(3)%NEXT_NODE(2)%VALUE = 23
BASE%OBJ2(3)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE = 24
BASE%OBJ2(3)%NEXT_NODE(2)%NEXT_NODE(3)%VALUE = 25
BASE%OBJ2(3)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE = 26

BASE%OBJ1 = BASE%OBJ2

BASE%OBJ2(1)%VALUE = 31
BASE%OBJ2(3)%VALUE = 32
BASE%OBJ2(3)%NEXT_NODE(2)%VALUE = 33
BASE%OBJ2(3)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE = 34
BASE%OBJ2(3)%NEXT_NODE(2)%NEXT_NODE(3)%VALUE = 35
BASE%OBJ2(3)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE = 36

if (BASE%OBJ1(1)%VALUE /= 21) print*, 101
if (BASE%OBJ1(3)%VALUE /= 22) print*, 102
if (BASE%OBJ1(3)%NEXT_NODE(2)%VALUE /= 23) print*, 103
if (BASE%OBJ1(3)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE /= 24) print*, 104
if (BASE%OBJ1(3)%NEXT_NODE(2)%NEXT_NODE(3)%VALUE /= 25) print*, 105
if (BASE%OBJ1(3)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE /= 26) print*, 106

if (SIZE(BASE%OBJ1) /= 3) print*, 301
if (SIZE(BASE%OBJ1(3)%NEXT_NODE) /= 2) print*, 201
if (SIZE(BASE%OBJ1(3)%NEXT_NODE(1)%NEXT_NODE) /= 3) print*, 202
if (SIZE(BASE%OBJ1(3)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE) /= 2) print*, 203
if (SIZE(BASE%OBJ1(3)%NEXT_NODE(1)%NEXT_NODE(2)%NEXT_NODE) /= 3) print*, 204
if (SIZE(BASE%OBJ1(3)%NEXT_NODE(1)%NEXT_NODE(3)%NEXT_NODE) /= 4) print*, 205
if (SIZE(BASE%OBJ1(3)%NEXT_NODE(2)%NEXT_NODE) /= 5) print*, 206
if (SIZE(BASE%OBJ1(3)%NEXT_NODE(2)%NEXT_NODE(2)%NEXT_NODE) /= 5) print*, 207

SELECT TYPE(X=>BASE%OBJ1(3)%NEXT_NODE)
 TYPE IS(EXT)
 CLASS DEFAULT
  PRINT*, 911
END SELECT

SELECT TYPE(X=>BASE%OBJ1(3)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE)
 TYPE IS(EXT)
 CLASS DEFAULT
  PRINT*, 912
END SELECT

SELECT TYPE(X=>BASE%OBJ1(3)%NEXT_NODE(1)%NEXT_NODE)
 TYPE IS(NODE)
  print*,"PASS"
 CLASS DEFAULT
  PRINT*, 913
END SELECT
END
