TYPE NODE
INTEGER :: VALUE(3) = 20
TYPE (NODE), ALLOCATABLE :: NEXT_NODE(:)
TYPE (NODE), ALLOCATABLE :: PREV_NODE(:)
END TYPE

TYPE TY
TYPE(NODE),ALLOCATABLE :: OBJ(:)
TYPE(NODE),ALLOCATABLE :: OBJ2(:)
END TYPE

TYPE(TY)::BASE

ALLOCATE(BASE%OBJ(2))
ALLOCATE(BASE%OBJ(1)%NEXT_NODE(2))
ALLOCATE(BASE%OBJ(1)%NEXT_NODE(2)%PREV_NODE(3))
ALLOCATE(BASE%OBJ(1)%NEXT_NODE(2)%PREV_NODE(2)%NEXT_NODE(4))

BASE%OBJ(1)%NEXT_NODE(2)%VALUE = 10
BASE%OBJ(1)%NEXT_NODE(2)%PREV_NODE(2)%VALUE = 11
BASE%OBJ(1)%NEXT_NODE(2)%PREV_NODE(2)%NEXT_NODE(2)%VALUE = 12

ALLOCATE(BASE%OBJ(2)%PREV_NODE(3))
ALLOCATE(BASE%OBJ(2)%PREV_NODE(3)%NEXT_NODE(4))
ALLOCATE(BASE%OBJ(2)%PREV_NODE(3)%NEXT_NODE(3)%PREV_NODE(5))

ALLOCATE(BASE%OBJ2(2))
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE(3))
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(4))
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(5))

ALLOCATE(BASE%OBJ2(1)%PREV_NODE(2))
ALLOCATE(BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(3))
ALLOCATE(BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(4))

BASE%OBJ = BASE%OBJ2

BASE%OBJ2(2)%NEXT_NODE(3)%VALUE = 31
BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%VALUE = 32
BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(3)%VALUE = 33

BASE%OBJ2(1)%PREV_NODE(2)%VALUE = 34
BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%VALUE = 35
BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(2)%VALUE = 36

if (BASE%OBJ(2)%NEXT_NODE(3)%VALUE(2) /= 20) print*, 101
if (BASE%OBJ(2)%NEXT_NODE(3)%PREV_NODE(3)%VALUE(2) /= 20) print*, 102
if (BASE%OBJ(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(3)%VALUE(2) /= 20) print*, 103

if (BASE%OBJ(1)%PREV_NODE(2)%VALUE(2) /= 20) print*, 104
if (BASE%OBJ(1)%PREV_NODE(2)%NEXT_NODE(2)%VALUE(2) /= 20) print*, 105
if (BASE%OBJ(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(2)%VALUE(2) /= 20) print*, 106

if (SIZE(BASE%OBJ) /= 2) print*, 201
if (SIZE(BASE%OBJ(2)%NEXT_NODE) /= 3) print*, 202
if (SIZE(BASE%OBJ(2)%NEXT_NODE(3)%PREV_NODE) /= 4) print*, 203
if (SIZE(BASE%OBJ(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE) /= 5) print*, 204

if (SIZE(BASE%OBJ(1)%PREV_NODE) /= 2) print*, 205
if (SIZE(BASE%OBJ(1)%PREV_NODE(2)%NEXT_NODE) /= 3) print*, 206
if (SIZE(BASE%OBJ(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE) /= 4) print*, 207

print*,"PASS"
END
