TYPE NODE
INTEGER :: VALUE = 20
TYPE (NODE), ALLOCATABLE :: NEXT_NODE
TYPE (NODE), ALLOCATABLE :: PREV_NODE
END TYPE

TYPE(NODE),ALLOCATABLE :: OBJ(:)
TYPE(NODE),ALLOCATABLE :: OBJ2(:)

ALLOCATE(OBJ(2))
ALLOCATE(OBJ(1)%NEXT_NODE)
ALLOCATE(OBJ(1)%NEXT_NODE%PREV_NODE)
ALLOCATE(OBJ(1)%NEXT_NODE%PREV_NODE%NEXT_NODE)

OBJ(1)%NEXT_NODE%VALUE = 10
OBJ(1)%NEXT_NODE%PREV_NODE%VALUE = 11
OBJ(1)%NEXT_NODE%PREV_NODE%NEXT_NODE%VALUE = 12

ALLOCATE(OBJ(2)%PREV_NODE)
ALLOCATE(OBJ(2)%PREV_NODE%NEXT_NODE)
ALLOCATE(OBJ(2)%PREV_NODE%NEXT_NODE%PREV_NODE)

ALLOCATE(OBJ2(2))
ALLOCATE(OBJ2(2)%NEXT_NODE)
ALLOCATE(OBJ2(2)%NEXT_NODE%PREV_NODE)
ALLOCATE(OBJ2(2)%NEXT_NODE%PREV_NODE%NEXT_NODE)

ALLOCATE(OBJ2(1)%PREV_NODE)
ALLOCATE(OBJ2(1)%PREV_NODE%NEXT_NODE)
ALLOCATE(OBJ2(1)%PREV_NODE%NEXT_NODE%PREV_NODE)

OBJ = OBJ2

OBJ2(2)%NEXT_NODE%VALUE = 31
OBJ2(2)%NEXT_NODE%PREV_NODE%VALUE = 32
OBJ2(2)%NEXT_NODE%PREV_NODE%NEXT_NODE%VALUE = 33

OBJ2(1)%PREV_NODE%VALUE = 34
OBJ2(1)%PREV_NODE%NEXT_NODE%VALUE = 35
OBJ2(1)%PREV_NODE%NEXT_NODE%PREV_NODE%VALUE = 36

if (OBJ(2)%NEXT_NODE%VALUE /= 20) print*, 101
if (OBJ(2)%NEXT_NODE%PREV_NODE%VALUE /= 20) print*, 102
if (OBJ(2)%NEXT_NODE%PREV_NODE%NEXT_NODE%VALUE /= 20) print*, 103
if (OBJ(1)%PREV_NODE%VALUE /= 20) print*, 104
if (OBJ(1)%PREV_NODE%NEXT_NODE%VALUE /= 20) print*, 105
if (OBJ(1)%PREV_NODE%NEXT_NODE%PREV_NODE%VALUE /= 20) print*, 106
print*,"PASS"
END
