MODULE MOD1
TYPE NODE
INTEGER,ALLOCATABLE :: VALUE
TYPE (NODE), ALLOCATABLE :: NEXT_NODE(:)
END TYPE

TYPE(NODE),ALLOCATABLE :: OBJ2(:)

CONTAINS 
SUBROUTINE SUB(DMY)
TYPE(NODE), ALLOCATABLE::DMY(:)
TYPE(NODE), ALLOCATABLE::RES(:)

ALLOCATE(RES(3))

RES = DMY

if (RES(1)%VALUE /= 21) print*, 101
if (RES(3)%VALUE /= 22) print*, 102
if (RES(3)%NEXT_NODE(2)%VALUE /= 23) print*, 103, RES(3)%NEXT_NODE(2)%VALUE
if (RES(3)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE /= 24) print*, 104, RES(3)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE
if (RES(3)%NEXT_NODE(2)%NEXT_NODE(3)%VALUE /= 25) print*, 105, RES(3)%NEXT_NODE(2)%NEXT_NODE(3)%VALUE
if (RES(3)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE /= 26) print*, 106, RES(3)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE

if (SIZE(RES(3)%NEXT_NODE) /= 2) print*, 201
if (SIZE(RES(3)%NEXT_NODE(1)%NEXT_NODE) /= 3) print*, 202
if (SIZE(RES(3)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE) /= 2) print*, 203
if (SIZE(RES(3)%NEXT_NODE(1)%NEXT_NODE(2)%NEXT_NODE) /= 3) print*, 204
if (SIZE(RES(3)%NEXT_NODE(1)%NEXT_NODE(3)%NEXT_NODE) /= 4) print*, 205
if (SIZE(RES(3)%NEXT_NODE(2)%NEXT_NODE) /= 5) print*, 206
if (SIZE(RES(3)%NEXT_NODE(2)%NEXT_NODE(2)%NEXT_NODE) /= 5) print*, 207
END SUBROUTINE
END MODULE

USE MOD1
ALLOCATE(OBJ2(3))
ALLOCATE(OBJ2(1)%VALUE)
ALLOCATE(OBJ2(3)%VALUE)

ALLOCATE(OBJ2(3)%NEXT_NODE(2))
ALLOCATE(OBJ2(3)%NEXT_NODE(1)%NEXT_NODE(3))
ALLOCATE(OBJ2(3)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE(2))
ALLOCATE(OBJ2(3)%NEXT_NODE(1)%NEXT_NODE(2)%NEXT_NODE(3))
ALLOCATE(OBJ2(3)%NEXT_NODE(1)%NEXT_NODE(3)%NEXT_NODE(4))
ALLOCATE(OBJ2(3)%NEXT_NODE(2)%NEXT_NODE(5))
ALLOCATE(OBJ2(3)%NEXT_NODE(2)%NEXT_NODE(2)%NEXT_NODE(5))

ALLOCATE(OBJ2(3)%NEXT_NODE(2)%VALUE)
ALLOCATE(OBJ2(3)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE)
ALLOCATE(OBJ2(3)%NEXT_NODE(2)%NEXT_NODE(3)%VALUE)
ALLOCATE(OBJ2(3)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE)

OBJ2(1)%VALUE = 21
OBJ2(3)%VALUE = 22
OBJ2(3)%NEXT_NODE(2)%VALUE = 23
OBJ2(3)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE = 24
OBJ2(3)%NEXT_NODE(2)%NEXT_NODE(3)%VALUE = 25
OBJ2(3)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE = 26

CALL SUB(OBJ2)

OBJ2(1)%VALUE = 31
OBJ2(3)%VALUE = 32
OBJ2(3)%NEXT_NODE(2)%VALUE = 33
OBJ2(3)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE = 34
OBJ2(3)%NEXT_NODE(2)%NEXT_NODE(3)%VALUE = 35
OBJ2(3)%NEXT_NODE(1)%NEXT_NODE(1)%NEXT_NODE(2)%VALUE = 36

print*,"PASS"
END
