CALL EX_SUB()
CONTAINS
SUBROUTINE EX_SUB()
         TYPE TY
         INTEGER :: JJ
         INTEGER,ALLOCATABLE :: ALC
         END TYPE

        TYPE TY1
         INTEGER :: II
        TYPE(TY), ALLOCATABLE :: NODE2
        END TYPE

        TYPE(TY),ALLOCATABLE :: OBJ2
        TYPE(TY1),ALLOCATABLE::LHS
        ALLOCATE(OBJ2)
        ALLOCATE(OBJ2%ALC)
        OBJ2%JJ = 4
        OBJ2%ALC = 5
        ALLOCATE(LHS, SOURCE =TY1(6,OBJ2))
        IF(OBJ2%ALC.NE.5)PRINT*,"101", OBJ2%ALC
        IF(LHS%NODE2%ALC.NE.5)PRINT*,"101", OBJ2%ALC
        LHS%NODE2%ALC = 66
        IF(LHS%NODE2%ALC.NE.66)PRINT*,"101", OBJ2%ALC
        PRINT*,"PASS"
        END SUBROUTINE
END
