TYPE NODE
INTEGER,ALLOCATABLE :: VALUE(:)
TYPE (NODE), ALLOCATABLE :: NEXT_NODE(:)
TYPE (NODE), ALLOCATABLE :: PREV_NODE(:)
END TYPE

TYPE(NODE),ALLOCATABLE :: OBJ2(:)

ALLOCATE(OBJ2(2))
ALLOCATE(OBJ2(2)%NEXT_NODE(3))
ALLOCATE(OBJ2(2)%NEXT_NODE(3)%VALUE(3))
ALLOCATE(OBJ2(2)%NEXT_NODE(3)%PREV_NODE(4))
ALLOCATE(OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%VALUE(4))
ALLOCATE(OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(5))
ALLOCATE(OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(3)%VALUE(5))

OBJ2(2)%NEXT_NODE(3)%VALUE = 21
OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%VALUE = 22
OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(3)%VALUE = 23

ALLOCATE(OBJ2(1)%PREV_NODE(2))
ALLOCATE(OBJ2(1)%PREV_NODE(2)%VALUE(2))
ALLOCATE(OBJ2(1)%PREV_NODE(2)%NEXT_NODE(3))
ALLOCATE(OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%VALUE(3))
ALLOCATE(OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(4))
ALLOCATE(OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(2)%VALUE(4))

OBJ2(1)%PREV_NODE(2)%VALUE = 24
OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%VALUE = 25
OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(2)%VALUE = 26

CALL SUB((OBJ2))

CONTAINS
SUBROUTINE SUB(DMY)
TYPE(NODE)::DMY(:)

if (DMY(2)%NEXT_NODE(3)%VALUE(2) /= 21) print*, 101
if (DMY(2)%NEXT_NODE(3)%PREV_NODE(3)%VALUE(2) /= 22) print*, 102
if (DMY(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(3)%VALUE(2) /= 23) print*, 103

if (DMY(1)%PREV_NODE(2)%VALUE(2) /= 24) print*, 104
if (DMY(1)%PREV_NODE(2)%NEXT_NODE(2)%VALUE(2) /= 25) print*, 105
if (DMY(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(2)%VALUE(2) /= 26) print*, 106

if (SIZE(DMY) /= 2) print*, 201
if (SIZE(DMY(2)%NEXT_NODE) /= 3) print*, 202
if (SIZE(DMY(2)%NEXT_NODE(3)%PREV_NODE) /= 4) print*, 203
if (SIZE(DMY(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE) /= 5) print*, 204

if (SIZE(DMY(1)%PREV_NODE) /= 2) print*, 205
if (SIZE(DMY(1)%PREV_NODE(2)%NEXT_NODE) /= 3) print*, 206
if (SIZE(DMY(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE) /= 4) print*, 207

print*,"PASS"
END SUBROUTINE
END
