MODULE MOD1
TYPE NODE
INTEGER,ALLOCATABLE :: VALUE(:)
CLASS (NODE), ALLOCATABLE :: NEXT_NODE(:)
CLASS (NODE), ALLOCATABLE :: PREV_NODE(:)
END TYPE

TYPE, EXTENDS(NODE)::EXT
INTEGER,ALLOCATABLE :: II(:)
END TYPE

TYPE TY
TYPE(NODE),ALLOCATABLE :: OBJ(:)
TYPE(NODE),ALLOCATABLE :: OBJ2(:)
END TYPE

TYPE(TY)::BASE

CONTAINS
SUBROUTINE SUB (DMY, RES)
TYPE(NODE),ALLOCATABLE, INTENT(OUT) :: DMY(:)
TYPE(NODE),ALLOCATABLE :: RES(:)

ALLOCATE(DMY(2))

DMY = RES
END SUBROUTINE
END MODULE

USE MOD1
ALLOCATE(BASE%OBJ(2))
ALLOCATE(BASE%OBJ(1)%NEXT_NODE(2))
ALLOCATE(BASE%OBJ(1)%NEXT_NODE(2)%VALUE(2))
ALLOCATE(BASE%OBJ(1)%NEXT_NODE(2)%PREV_NODE(3))
ALLOCATE(BASE%OBJ(1)%NEXT_NODE(2)%PREV_NODE(2)%VALUE(3))
ALLOCATE(BASE%OBJ(1)%NEXT_NODE(2)%PREV_NODE(2)%NEXT_NODE(4))
ALLOCATE(BASE%OBJ(1)%NEXT_NODE(2)%PREV_NODE(2)%NEXT_NODE(2)%VALUE(4))

BASE%OBJ(1)%NEXT_NODE(2)%VALUE = 10
BASE%OBJ(1)%NEXT_NODE(2)%PREV_NODE(2)%VALUE = 11
BASE%OBJ(1)%NEXT_NODE(2)%PREV_NODE(2)%NEXT_NODE(2)%VALUE = 12

ALLOCATE(BASE%OBJ(2)%PREV_NODE(3))
ALLOCATE(BASE%OBJ(2)%PREV_NODE(3)%NEXT_NODE(4))
ALLOCATE(BASE%OBJ(2)%PREV_NODE(3)%NEXT_NODE(3)%PREV_NODE(5))

ALLOCATE(BASE%OBJ2(2))
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE(3))
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE(3)%VALUE(3))
ALLOCATE(EXT::BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(4))
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%VALUE(4))
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(5))
ALLOCATE(BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(3)%VALUE(5))

BASE%OBJ2(2)%NEXT_NODE(3)%VALUE = 21
BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%VALUE = 22
BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(3)%VALUE = 23

ALLOCATE(BASE%OBJ2(1)%PREV_NODE(2))
ALLOCATE(BASE%OBJ2(1)%PREV_NODE(2)%VALUE(2))
ALLOCATE(BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(3))
ALLOCATE(BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%VALUE(3))
ALLOCATE(EXT::BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(4))
ALLOCATE(BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(2)%VALUE(4))

BASE%OBJ2(1)%PREV_NODE(2)%VALUE = 24
BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%VALUE = 25
BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(2)%VALUE = 26

CALL SUB(BASE%OBJ, BASE%OBJ2)

BASE%OBJ2(2)%NEXT_NODE(3)%VALUE = 31
BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%VALUE = 32
BASE%OBJ2(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(3)%VALUE = 33

BASE%OBJ2(1)%PREV_NODE(2)%VALUE = 34
BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%VALUE = 35
BASE%OBJ2(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(2)%VALUE = 36

if (BASE%OBJ(2)%NEXT_NODE(3)%VALUE(2) /= 21) print*, 101
if (BASE%OBJ(2)%NEXT_NODE(3)%PREV_NODE(3)%VALUE(2) /= 22) print*, 102
if (BASE%OBJ(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE(3)%VALUE(2) /= 23) print*, 103

if (BASE%OBJ(1)%PREV_NODE(2)%VALUE(2) /= 24) print*, 104
if (BASE%OBJ(1)%PREV_NODE(2)%NEXT_NODE(2)%VALUE(2) /= 25) print*, 105
if (BASE%OBJ(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE(2)%VALUE(2) /= 26) print*, 106

if (SIZE(BASE%OBJ) /= 2) print*, 201
if (SIZE(BASE%OBJ(2)%NEXT_NODE) /= 3) print*, 202
if (SIZE(BASE%OBJ(2)%NEXT_NODE(3)%PREV_NODE) /= 4) print*, 203
if (SIZE(BASE%OBJ(2)%NEXT_NODE(3)%PREV_NODE(3)%NEXT_NODE) /= 5) print*, 204

if (SIZE(BASE%OBJ(1)%PREV_NODE) /= 2) print*, 205
if (SIZE(BASE%OBJ(1)%PREV_NODE(2)%NEXT_NODE) /= 3) print*, 206
if (SIZE(BASE%OBJ(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE) /= 4) print*, 207

SELECT TYPE(X=>BASE%OBJ(2)%NEXT_NODE(3)%PREV_NODE)
 TYPE IS(EXT)
 CLASS DEFAULT
  PRINT*,911
END SELECT

SELECT TYPE(X=>BASE%OBJ(1)%PREV_NODE(2)%NEXT_NODE(2)%PREV_NODE)
 TYPE IS(EXT)
 CLASS DEFAULT
  PRINT*,912
END SELECT

SELECT TYPE(X=>BASE%OBJ(1)%PREV_NODE(2)%NEXT_NODE)
 TYPE IS(NODE)
 CLASS DEFAULT
  PRINT*,913
END SELECT

PRINT*,"PASS"
END
