TYPE NODE
INTEGER,ALLOCATABLE :: VALUE(:)
TYPE (NODE), ALLOCATABLE :: NEXT_NODE
END TYPE

TYPE(NODE),ALLOCATABLE :: OBJ
TYPE(NODE),ALLOCATABLE :: OBJ2

ALLOCATE(OBJ)
ALLOCATE(OBJ%NEXT_NODE)
ALLOCATE(OBJ%NEXT_NODE%NEXT_NODE)

ALLOCATE(OBJ%VALUE(2))
ALLOCATE(OBJ%NEXT_NODE%VALUE(3))
ALLOCATE(OBJ%NEXT_NODE%NEXT_NODE%VALUE(4))

OBJ%VALUE = 10
OBJ%NEXT_NODE%VALUE = 11
OBJ%NEXT_NODE%NEXT_NODE%VALUE = 12

ALLOCATE(OBJ2)
ALLOCATE(OBJ2%NEXT_NODE)
ALLOCATE(OBJ2%NEXT_NODE%NEXT_NODE)
ALLOCATE(OBJ2%NEXT_NODE%NEXT_NODE%NEXT_NODE)

ALLOCATE(OBJ2%VALUE(3))
ALLOCATE(OBJ2%NEXT_NODE%VALUE(4))
ALLOCATE(OBJ2%NEXT_NODE%NEXT_NODE%VALUE(5))
ALLOCATE(OBJ2%NEXT_NODE%NEXT_NODE%NEXT_NODE%VALUE(6))

OBJ2%VALUE = 20
OBJ2%NEXT_NODE%VALUE = 21
OBJ2%NEXT_NODE%NEXT_NODE%VALUE = 22
OBJ2%NEXT_NODE%NEXT_NODE%NEXT_NODE%VALUE = 23

OBJ=OBJ2

OBJ2%VALUE = 30
OBJ2%NEXT_NODE%VALUE = 31
OBJ2%NEXT_NODE%NEXT_NODE%VALUE = 32
OBJ2%NEXT_NODE%NEXT_NODE%NEXT_NODE%VALUE = 33

if (OBJ%VALUE(2) /= 20) print*, 101
if (SIZE(OBJ%VALUE) /= 3) print*, 102
if (OBJ%NEXT_NODE%VALUE(2) /= 21) print*, 103
if (SIZE(OBJ%NEXT_NODE%VALUE) /= 4) print*, 104
if (OBJ%NEXT_NODE%NEXT_NODE%VALUE(2) /= 22) print*, 105
if (SIZE(OBJ%NEXT_NODE%NEXT_NODE%VALUE) /= 5) print*, 106
if (OBJ%NEXT_NODE%NEXT_NODE%NEXT_NODE%VALUE(2) /= 23) print*, 107
if (SIZE(OBJ%NEXT_NODE%NEXT_NODE%NEXT_NODE%VALUE) /= 6) print*, 108

print*,"PASS"
END
