TYPE NODE
INTEGER :: VALUE(3) = 20
TYPE (NODE), ALLOCATABLE :: NEXT_NODE
END TYPE

TYPE(NODE),ALLOCATABLE :: OBJ
TYPE(NODE),ALLOCATABLE :: OBJ2

ALLOCATE(OBJ)
ALLOCATE(OBJ%NEXT_NODE)
ALLOCATE(OBJ%NEXT_NODE%NEXT_NODE)

OBJ%VALUE = 10
OBJ%NEXT_NODE%VALUE = 11
OBJ%NEXT_NODE%NEXT_NODE%VALUE = 12

ALLOCATE(OBJ2)
ALLOCATE(OBJ2%NEXT_NODE)
ALLOCATE(OBJ2%NEXT_NODE%NEXT_NODE)
ALLOCATE(OBJ2%NEXT_NODE%NEXT_NODE%NEXT_NODE)

OBJ=OBJ2

OBJ2%VALUE = 30
OBJ2%NEXT_NODE%VALUE = 31
OBJ2%NEXT_NODE%NEXT_NODE%VALUE = 32
OBJ2%NEXT_NODE%NEXT_NODE%NEXT_NODE%VALUE = 33

if (OBJ%VALUE(2) /= 20) print*, 101
if (SIZE(OBJ%VALUE) /= 3) print*, 102
if (OBJ%NEXT_NODE%VALUE(2) /= 20) print*, 103
if (SIZE(OBJ%NEXT_NODE%VALUE) /= 3) print*, 104
if (OBJ%NEXT_NODE%NEXT_NODE%VALUE(2) /= 20) print*, 105
if (SIZE(OBJ%NEXT_NODE%NEXT_NODE%VALUE) /= 3) print*, 106
if (OBJ%NEXT_NODE%NEXT_NODE%NEXT_NODE%VALUE(2) /= 20) print*, 107
if (SIZE(OBJ%NEXT_NODE%NEXT_NODE%NEXT_NODE%VALUE) /= 3) print*, 108

print*,"PASS"
END
