TYPE NODE
INTEGER,ALLOCATABLE :: VALUE(:)
TYPE (NODE), ALLOCATABLE :: NEXT_NODE(:)
TYPE (NODE), ALLOCATABLE :: PREV_NODE(:)
END TYPE

TYPE(NODE),ALLOCATABLE :: OBJ(:)

ALLOCATE(OBJ(2))

ALLOCATE(OBJ(1)%NEXT_NODE(2))
ALLOCATE(OBJ(1)%NEXT_NODE(2)%VALUE(2))
ALLOCATE(OBJ(1)%NEXT_NODE(2)%PREV_NODE(3))
ALLOCATE(OBJ(1)%NEXT_NODE(2)%PREV_NODE(2)%VALUE(3))
ALLOCATE(OBJ(1)%NEXT_NODE(2)%PREV_NODE(2)%NEXT_NODE(4))
ALLOCATE(OBJ(1)%NEXT_NODE(2)%PREV_NODE(2)%NEXT_NODE(2)%VALUE(4))

OBJ(1)%NEXT_NODE(2)%VALUE = 10
OBJ(1)%NEXT_NODE(2)%PREV_NODE(2)%VALUE = 11
OBJ(1)%NEXT_NODE(2)%PREV_NODE(2)%NEXT_NODE(2)%VALUE = 12

ALLOCATE(OBJ(2)%PREV_NODE(3))
ALLOCATE(OBJ(2)%PREV_NODE(3)%VALUE(2))
ALLOCATE(OBJ(2)%PREV_NODE(3)%NEXT_NODE(4))
ALLOCATE(OBJ(2)%PREV_NODE(3)%NEXT_NODE(3)%VALUE(3))
ALLOCATE(OBJ(2)%PREV_NODE(3)%NEXT_NODE(3)%PREV_NODE(5))
ALLOCATE(OBJ(2)%PREV_NODE(3)%NEXT_NODE(3)%PREV_NODE(3)%VALUE(4))

DEALLOCATE(OBJ)

if (ALLOCATED(OBJ)) print*, 101
print*,"PASS"
END
