extern unsigned char v3 (unsigned int);
extern unsigned char (*v4) (unsigned int);
extern void v5 (unsigned char, unsigned int);
extern void (*v6) (unsigned char, unsigned int);
extern void v7 (signed short, unsigned char, signed int);
extern void (*v8) (signed short, unsigned char, signed int);
extern unsigned short v9 (signed short);
extern unsigned short (*v10) (signed short);
extern unsigned char v11 (signed short, unsigned int, unsigned char, signed short);
extern unsigned char (*v12) (signed short, unsigned int, unsigned char, signed short);
extern unsigned short v13 (unsigned int);
extern unsigned short (*v14) (unsigned int);
extern unsigned int v15 (void);
extern unsigned int (*v16) (void);
extern unsigned int v17 (void);
extern unsigned int (*v18) (void);
extern signed short v19 (void);
extern signed short (*v20) (void);
extern signed char v21 (signed short, unsigned short);
extern signed char (*v22) (signed short, unsigned short);
extern unsigned int v23 (signed char, signed short);
extern unsigned int (*v24) (signed char, signed short);
extern void v25 (void);
extern void (*v26) (void);
extern unsigned short v27 (signed char, signed short, unsigned short);
extern unsigned short (*v28) (signed char, signed short, unsigned short);
extern signed char v29 (signed char, unsigned char, unsigned int, signed int);
extern signed char (*v30) (signed char, unsigned char, unsigned int, signed int);
extern int history[];
extern int history_index;
extern int trace;
signed int v100 = 0;
signed int v99 = 2;
unsigned int v98 = 3U;
