extern unsigned short v1 (unsigned short, signed short, unsigned int, signed char);
extern unsigned short (*v2) (unsigned short, signed short, unsigned int, signed char);
extern signed int v3 (void);
extern signed int (*v4) (void);
extern signed int v5 (signed short, unsigned int, signed int);
extern signed int (*v6) (signed short, unsigned int, signed int);
extern void v7 (unsigned short);
extern void (*v8) (unsigned short);
extern void v9 (unsigned short, signed int, unsigned int);
extern void (*v10) (unsigned short, signed int, unsigned int);
extern unsigned char v11 (signed int, unsigned int, signed short, signed short);
extern unsigned char (*v12) (signed int, unsigned int, signed short, signed short);
extern unsigned char v13 (void);
extern unsigned char (*v14) (void);
extern signed char v15 (signed int);
extern signed char (*v16) (signed int);
extern signed char v17 (unsigned char, unsigned int, unsigned char, unsigned short);
extern signed char (*v18) (unsigned char, unsigned int, unsigned char, unsigned short);
extern unsigned int v19 (unsigned int, unsigned int, unsigned char);
extern unsigned int (*v20) (unsigned int, unsigned int, unsigned char);
extern signed char v21 (unsigned int);
extern signed char (*v22) (unsigned int);
extern signed char v23 (void);
extern signed char (*v24) (void);
extern unsigned short v25 (void);
extern unsigned short (*v26) (void);
extern unsigned int v27 (void);
extern unsigned int (*v28) (void);
extern unsigned int v29 (unsigned char, signed int, signed short, signed char);
extern unsigned int (*v30) (unsigned char, signed int, signed short, signed char);
extern int history[];
extern int history_index;
extern int trace;
signed int v139 = 3;
signed int v138 = -2;
signed char v137 = 1;
