extern signed char v1 (signed short, unsigned short, unsigned int);
extern signed char (*v2) (signed short, unsigned short, unsigned int);
extern signed char v3 (unsigned char);
extern signed char (*v4) (unsigned char);
extern signed int v5 (unsigned int, unsigned int, unsigned int);
extern signed int (*v6) (unsigned int, unsigned int, unsigned int);
extern unsigned int v7 (unsigned short, signed char);
extern unsigned int (*v8) (unsigned short, signed char);
extern signed char v9 (unsigned char, unsigned int);
extern signed char (*v10) (unsigned char, unsigned int);
extern signed int v11 (signed char, unsigned char, signed short);
extern signed int (*v12) (signed char, unsigned char, signed short);
extern signed short v13 (signed short, signed int, unsigned short, unsigned char);
extern signed short (*v14) (signed short, signed int, unsigned short, unsigned char);
extern unsigned char v15 (void);
extern unsigned char (*v16) (void);
extern signed short v17 (unsigned char);
extern signed short (*v18) (unsigned char);
extern signed char v19 (signed char, unsigned short);
extern signed char (*v20) (signed char, unsigned short);
extern signed short v21 (signed int, unsigned int, signed short);
extern signed short (*v22) (signed int, unsigned int, signed short);
extern void v23 (signed char, signed short);
extern void (*v24) (signed char, signed short);
extern unsigned int v25 (signed short, unsigned int, signed int, signed short);
extern unsigned int (*v26) (signed short, unsigned int, signed int, signed short);
extern signed short v27 (unsigned int, unsigned int, unsigned short);
extern signed short (*v28) (unsigned int, unsigned int, unsigned short);
extern signed int v29 (void);
extern signed int (*v30) (void);
extern int history[];
extern int history_index;
extern int trace;
unsigned int v70 = 7U;
unsigned char v69 = 5;
signed int v68 = -2;
