extern signed char v1 (signed int, signed short);
extern signed char (*v2) (signed int, signed short);
extern unsigned int v3 (unsigned char, signed short);
extern unsigned int (*v4) (unsigned char, signed short);
extern signed short v5 (unsigned char, unsigned short);
extern signed short (*v6) (unsigned char, unsigned short);
extern signed short v7 (unsigned int, signed char, unsigned char);
extern signed short (*v8) (unsigned int, signed char, unsigned char);
extern unsigned char v9 (unsigned short, unsigned short);
extern unsigned char (*v10) (unsigned short, unsigned short);
extern signed short v11 (signed int, signed int, unsigned char);
extern signed short (*v12) (signed int, signed int, unsigned char);
extern signed char v13 (signed short);
extern signed char (*v14) (signed short);
extern unsigned short v15 (unsigned int, unsigned short);
extern unsigned short (*v16) (unsigned int, unsigned short);
extern signed char v17 (signed int);
extern signed char (*v18) (signed int);
extern signed short v19 (signed short, signed char);
extern signed short (*v20) (signed short, signed char);
extern void v21 (unsigned int, signed short, unsigned int);
extern void (*v22) (unsigned int, signed short, unsigned int);
extern signed char v23 (unsigned char, signed short, signed char, signed short);
extern signed char (*v24) (unsigned char, signed short, signed char, signed short);
extern unsigned int v25 (unsigned int);
extern unsigned int (*v26) (unsigned int);
extern unsigned char v29 (signed short, unsigned char, signed int);
extern unsigned char (*v30) (signed short, unsigned char, signed int);
extern int history[];
extern int history_index;
extern int trace;
unsigned int v131 = 6U;
unsigned char v130 = 3;
unsigned char v129 = 0;
