USE, INTRINSIC:: IEEE_ARITHMETIC
REAL*2::R2
LOGICAL::L1=IEEE_SUPPORT_SQRT(1.5_2)
PRINT*,IEEE_SUPPORT_FLAG(IEEE_INEXACT,R2)
PRINT*,IEEE_SUPPORT_ROUNDING(IEEE_TO_ZERO,R2)
PRINT*,IEEE_SUPPORT_SQRT(R2)

END

