MODULE MOD
  REAL(8),DIMENSION(3) :: A,B
END MODULE MOD

SUBROUTINE SUB0()
  USE MOD
  DO I=1,48 
     A(I) = SQRT(SQRT(SQRT(SQRT(SQRT(SQRT(SQRT(SQRT(B(I)))))))))
  ENDDO
END SUBROUTINE SUB0

PROGRAM MAIN
  print *,"OK"
END PROGRAM MAIN
