extern unsigned char v1 (unsigned short);
extern unsigned char (*v2) (unsigned short);
extern unsigned char v3 (signed short, unsigned int);
extern unsigned char (*v4) (signed short, unsigned int);
extern unsigned short v5 (unsigned char, signed int);
extern unsigned short (*v6) (unsigned char, signed int);
extern unsigned short v7 (signed int, signed int, signed char, signed char);
extern unsigned short (*v8) (signed int, signed int, signed char, signed char);
extern signed short v11 (void);
extern signed short (*v12) (void);
extern unsigned short v13 (signed char, unsigned short, signed short);
extern unsigned short (*v14) (signed char, unsigned short, signed short);
extern signed short v15 (unsigned short);
extern signed short (*v16) (unsigned short);
extern unsigned short v17 (signed short);
extern unsigned short (*v18) (signed short);
extern signed int v19 (signed char, unsigned int, unsigned short);
extern signed int (*v20) (signed char, unsigned int, unsigned short);
extern signed char v21 (unsigned short, unsigned char);
extern signed char (*v22) (unsigned short, unsigned char);
extern signed short v23 (unsigned short, unsigned short, signed int);
extern signed short (*v24) (unsigned short, unsigned short, signed int);
extern void v25 (void);
extern void (*v26) (void);
extern unsigned int v27 (signed int, unsigned int, unsigned char, unsigned short);
extern unsigned int (*v28) (signed int, unsigned int, unsigned char, unsigned short);
extern unsigned char v29 (unsigned char, unsigned char);
extern unsigned char (*v30) (unsigned char, unsigned char);
extern int history[];
extern int history_index;
extern int trace;
unsigned char v143 = 3;
signed char v142 = -2;
signed int v141 = -1;
