extern void v1 (unsigned short, signed char);
extern void (*v2) (unsigned short, signed char);
extern unsigned char v3 (unsigned int, signed char, unsigned int);
extern unsigned char (*v4) (unsigned int, signed char, unsigned int);
extern signed int v5 (signed char, signed int);
extern signed int (*v6) (signed char, signed int);
extern signed short v7 (signed int, unsigned char, signed short, signed char);
extern signed short (*v8) (signed int, unsigned char, signed short, signed char);
extern unsigned char v9 (unsigned short, unsigned int);
extern unsigned char (*v10) (unsigned short, unsigned int);
extern signed int v11 (signed int);
extern signed int (*v12) (signed int);
extern unsigned int v13 (unsigned char, signed short);
extern unsigned int (*v14) (unsigned char, signed short);
extern unsigned char v15 (unsigned int, signed short, unsigned int);
extern unsigned char (*v16) (unsigned int, signed short, unsigned int);
extern signed int v17 (unsigned int, unsigned char, signed short);
extern signed int (*v18) (unsigned int, unsigned char, signed short);
extern signed char v21 (unsigned short, unsigned char, unsigned char, unsigned char);
extern signed char (*v22) (unsigned short, unsigned char, unsigned char, unsigned char);
extern signed short v23 (void);
extern signed short (*v24) (void);
extern void v29 (signed char, signed int, signed int, unsigned int);
extern void (*v30) (signed char, signed int, signed int, unsigned int);
extern int history[];
extern int history_index;
extern int trace;
unsigned short v68 = 7;
signed int v67 = 0;
signed short v66 = -3;
