extern signed short v1 (unsigned int, signed int, unsigned short);
extern signed short (*v2) (unsigned int, signed int, unsigned short);
extern void v5 (signed char, signed int, unsigned short, unsigned short);
extern void (*v6) (signed char, signed int, unsigned short, unsigned short);
extern signed char v7 (signed int, unsigned char, unsigned short);
extern signed char (*v8) (signed int, unsigned char, unsigned short);
extern signed int v9 (signed char, signed char);
extern signed int (*v10) (signed char, signed char);
extern signed int v11 (unsigned int, signed int, unsigned short, signed int);
extern signed int (*v12) (unsigned int, signed int, unsigned short, signed int);
extern unsigned short v13 (signed char);
extern unsigned short (*v14) (signed char);
extern unsigned char v15 (signed short);
extern unsigned char (*v16) (signed short);
extern unsigned char v17 (signed int, signed char);
extern unsigned char (*v18) (signed int, signed char);
extern signed int v21 (signed int);
extern signed int (*v22) (signed int);
extern unsigned char v23 (signed short, signed int, signed int, signed int);
extern unsigned char (*v24) (signed short, signed int, signed int, signed int);
extern unsigned short v25 (signed char, unsigned short, unsigned int);
extern unsigned short (*v26) (signed char, unsigned short, unsigned int);
extern signed short v27 (signed int, unsigned short);
extern signed short (*v28) (signed int, unsigned short);
extern unsigned int v29 (unsigned short, signed short, signed short);
extern unsigned int (*v30) (unsigned short, signed short, signed short);
extern int history[];
extern int history_index;
extern int trace;
signed int v121 = 3;
signed short v120 = 1;
signed short v119 = 1;
