REAL::B=5
if(F(B)/=8) print*,101,F(B)
print*,"PASS"
contains
ELEMENTAL INTEGER FUNCTION F (A)
REAL, INTENT (IN) :: A
REAL (SELECTED_REAL_KIND (PRECISION (A)*2)) :: WORK
F=SELECTED_REAL_KIND(PRECISION(WORK))
END FUNCTION F

END
