extern void v1 (unsigned short, unsigned char, unsigned int, signed int);
extern void (*v2) (unsigned short, unsigned char, unsigned int, signed int);
extern unsigned int v3 (unsigned int, signed int, signed int, unsigned char);
extern unsigned int (*v4) (unsigned int, signed int, signed int, unsigned char);
extern signed int v5 (signed short, signed char, signed int, unsigned int);
extern signed int (*v6) (signed short, signed char, signed int, unsigned int);
extern unsigned char v7 (unsigned char, signed short, signed short);
extern unsigned char (*v8) (unsigned char, signed short, signed short);
extern unsigned char v9 (unsigned int, unsigned short, unsigned int, unsigned char);
extern unsigned char (*v10) (unsigned int, unsigned short, unsigned int, unsigned char);
extern signed short v11 (signed char, signed short, signed char);
extern signed short (*v12) (signed char, signed short, signed char);
extern unsigned short v13 (unsigned char);
extern unsigned short (*v14) (unsigned char);
extern signed int v15 (signed int, unsigned short, signed int, signed short);
extern signed int (*v16) (signed int, unsigned short, signed int, signed short);
extern unsigned int v17 (unsigned char, unsigned int, signed short, signed int);
extern unsigned int (*v18) (unsigned char, unsigned int, signed short, signed int);
extern signed short v19 (void);
extern signed short (*v20) (void);
extern unsigned short v23 (signed int, signed short, unsigned short, signed short);
extern unsigned short (*v24) (signed int, signed short, unsigned short, signed short);
extern void v25 (signed int, unsigned int);
extern void (*v26) (signed int, unsigned int);
extern unsigned int v29 (signed int);
extern unsigned int (*v30) (signed int);
extern int history[];
extern int history_index;
extern int trace;
signed short v162 = 0;
unsigned short v161 = 4;
signed short v160 = -4;
