      implicit integer (a-h,o-z)
      dimension q(200)
      dimension nt(8),x(3)
      data nt /7, 3, 3, 1, 7, 3, 3, 1/

      do i = 1,200
        q(i) = i
      end do

      is=2
      jnt=nt(is)
      write(3,*) (q(  j*3),j=1,3) 
      write(3,*) (q(  3*j),j=1,3) 
      write(3,*) (q(  j*jnt),j=1,3) 
      write(3,*) (q(  jnt*j),j=1,3) 
      write(3,*) (q(  j*nt(is)),j=1,3) 
      write(3,*) (q(  nt(is)*j),j=1,3) 
      write(3,*) (q(  j*nt(2)),j=1,3)
      write(3,*) (q(  j*in(3)),j=1,3) 
      write(3,*) (q(  3*in(j)),j=1,3) 
      write(3,*) (q(  j*in(jnt)),j=1,3) 
      write(3,*) (q(  jnt*in(j)),j=1,3) 
      write(3,*) (q(  j*in(nt(is))),j=1,3) 
      write(3,*) (q(  nt(is)*in(j)),j=1,3) 
      write(3,*) (q(  j*in(nt(2))),j=1,3)  
      write(3,*) (q(  in(j)*3),j=1,3) 
      write(3,*) (q(  in(3)*j),j=1,3) 
      write(3,*) (q(  in(j)*jnt),j=1,3) 
      write(3,*) (q(  in(jnt)*j),j=1,3) 
      write(3,*) (q(  in(j)*nt(is)),j=1,3) 
      write(3,*) (q(  in(nt(is))*j),j=1,3) 
      write(3,*) (q(  in(j)*nt(2)),j=1,3)
      write(3,*) (q(  j*(3)),j=1,3) 
      write(3,*) (q(  3*(j)),j=1,3) 
      write(3,*) (q(  j*(jnt)),j=1,3) 
      write(3,*) (q(  jnt*(j)),j=1,3) 
      write(3,*) (q(  j*(nt(is))),j=1,3) 
      write(3,*) (q(  nt(is)*(j)),j=1,3) 
      write(3,*) (q(  j*(nt(2))),j=1,3)
      write(3,*) (q(  j*(in(3))),j=1,3) 
      write(3,*) (q(  3*(in(j))),j=1,3) 
      write(3,*) (q(  j*(in(jnt))),j=1,3) 
      write(3,*) (q(  jnt*(in(j))),j=1,3) 
      write(3,*) (q(  j*(in(nt(is)))),j=1,3) 
      write(3,*) (q(  nt(is)*(in(j))),j=1,3) 
      write(3,*) (q(  j*(in(nt(2)))),j=1,3)  
      write(3,*) (q(  in(j)*(3)),j=1,3) 
      write(3,*) (q(  in(3)*(j)),j=1,3) 
      write(3,*) (q(  in(j)*(jnt)),j=1,3) 
      write(3,*) (q(  in(jnt)*(j)),j=1,3) 
      write(3,*) (q(  in(j)*(nt(is))),j=1,3) 
      write(3,*) (q(  in(nt(is))*(j)),j=1,3) 
      write(3,*) (q(  in(j)*(nt(2))),j=1,3)
      write(3,*) (q(  (j)*3),j=1,3) 
      write(3,*) (q(  (3)*j),j=1,3) 
      write(3,*) (q(  (j)*jnt),j=1,3) 
      write(3,*) (q(  (jnt)*j),j=1,3) 
      write(3,*) (q(  (j)*nt(is)),j=1,3) 
      write(3,*) (q(  (nt(is))*j),j=1,3) 
      write(3,*) (q(  (j)*nt(2)),j=1,3)
      write(3,*) (q(  (j)*in(3)),j=1,3) 
      write(3,*) (q(  (3)*in(j)),j=1,3) 
      write(3,*) (q(  (j)*in(jnt)),j=1,3) 
      write(3,*) (q(  (jnt)*in(j)),j=1,3) 
      write(3,*) (q(  (j)*in(nt(is))),j=1,3) 
      write(3,*) (q(  (nt(is))*in(j)),j=1,3) 
      write(3,*) (q(  (j)*in(nt(2))),j=1,3)  
      write(3,*) (q(  (in(j))*3),j=1,3) 
      write(3,*) (q(  (in(3))*j),j=1,3) 
      write(3,*) (q(  (in(j))*jnt),j=1,3) 
      write(3,*) (q(  (in(jnt))*j),j=1,3) 
      write(3,*) (q(  (in(j))*nt(is)),j=1,3) 
      write(3,*) (q(  (in(nt(is)))*j),j=1,3) 
      write(3,*) (q(  (in(j))*nt(2)),j=1,3)
      write(3,*) (q(  (j)*(3)),j=1,3) 
      write(3,*) (q(  (3)*(j)),j=1,3) 
      write(3,*) (q(  (j)*(jnt)),j=1,3) 
      write(3,*) (q(  (jnt)*(j)),j=1,3) 
      write(3,*) (q(  (j)*(nt(is))),j=1,3) 
      write(3,*) (q(  (nt(is))*(j)),j=1,3) 
      write(3,*) (q(  (j)*(nt(2))),j=1,3)
      write(3,*) (q(  (j)*(in(3))),j=1,3) 
      write(3,*) (q(  (3)*(in(j))),j=1,3) 
      write(3,*) (q(  (j)*(in(jnt))),j=1,3) 
      write(3,*) (q(  (jnt)*(in(j))),j=1,3) 
      write(3,*) (q(  (j)*(in(nt(is)))),j=1,3) 
      write(3,*) (q(  (nt(is))*(in(j))),j=1,3) 
      write(3,*) (q(  (j)*(in(nt(2)))),j=1,3)  
      write(3,*) (q(  (in(j))*(3)),j=1,3) 
      write(3,*) (q(  (in(3))*(j)),j=1,3) 
      write(3,*) (q(  (in(j))*(jnt)),j=1,3) 
      write(3,*) (q(  (in(jnt))*(j)),j=1,3) 
      write(3,*) (q(  (in(j))*(nt(is))),j=1,3) 
      write(3,*) (q(  (in(nt(is)))*(j)),j=1,3) 
      write(3,*) (q(  (in(j))*(nt(2))),j=1,3)

      rewind 3
      do k=1,84
      read(3,*) x;if (any(x/=(/3,6,9/)))then
             write(6,*) "NG";print *,'code=',k
        end if
      end do
      print *,'pass'
      end
      function in(j) result(k)
       k=j
      end
