      implicit integer (a-h,o-z)
      dimension q(200)
      dimension nt(8),x(3)
      data nt /7, 3, 3, 1, 7, 3, 3, 1/

      do i = 1,200
        q(i) = i
      end do

      is=2
      n=1
      jnt=nt(is)
      write(9,*) (q(  j*3*n),j=1,3) 
      write(9,*) (q(  3*j*n),j=1,3) 
      write(9,*) (q(  j*jnt*n),j=1,3) 
      write(9,*) (q(  jnt*j*n),j=1,3) 
      write(9,*) (q(  j*nt(is)*n),j=1,3) 
      write(9,*) (q(  nt(is)*j*n),j=1,3) 
      write(9,*) (q(  j*nt(2)*n),j=1,3)
      write(9,*) (q(  j*in(3)*n),j=1,3) 
      write(9,*) (q(  3*in(j)*n),j=1,3) 
      write(9,*) (q(  j*in(jnt)*n),j=1,3) 
      write(9,*) (q(  jnt*in(j)*n),j=1,3) 
      write(9,*) (q(  j*in(nt(is))*n),j=1,3) 
      write(9,*) (q(  nt(is)*in(j)*n),j=1,3) 
      write(9,*) (q(  j*in(nt(2))*n),j=1,3)  
      write(9,*) (q(  in(j)*3*n),j=1,3) 
      write(9,*) (q(  in(3)*j*n),j=1,3) 
      write(9,*) (q(  in(j)*jnt*n),j=1,3) 
      write(9,*) (q(  in(jnt)*j*n),j=1,3) 
      write(9,*) (q(  in(j)*nt(is)*n),j=1,3) 
      write(9,*) (q(  in(nt(is))*j*n),j=1,3) 
      write(9,*) (q(  in(j)*nt(2)*n),j=1,3)
      write(9,*) (q(  j*(3)*n),j=1,3) 
      write(9,*) (q(  3*(j)*n),j=1,3) 
      write(9,*) (q(  j*(jnt)*n),j=1,3) 
      write(9,*) (q(  jnt*(j)*n),j=1,3) 
      write(9,*) (q(  j*(nt(is))*n),j=1,3) 
      write(9,*) (q(  nt(is)*(j)*n),j=1,3) 
      write(9,*) (q(  j*(nt(2))*n),j=1,3)
      write(9,*) (q(  j*(in(3))*n),j=1,3) 
      write(9,*) (q(  3*(in(j))*n),j=1,3) 
      write(9,*) (q(  j*(in(jnt))*n),j=1,3) 
      write(9,*) (q(  jnt*(in(j))*n),j=1,3) 
      write(9,*) (q(  j*(in(nt(is)))*n),j=1,3) 
      write(9,*) (q(  nt(is)*(in(j))*n),j=1,3) 
      write(9,*) (q(  j*(in(nt(2)))*n),j=1,3)  
      write(9,*) (q(  in(j)*(3)*n),j=1,3) 
      write(9,*) (q(  in(3)*(j)*n),j=1,3) 
      write(9,*) (q(  in(j)*(jnt)*n),j=1,3) 
      write(9,*) (q(  in(jnt)*(j)*n),j=1,3) 
      write(9,*) (q(  in(j)*(nt(is))*n),j=1,3) 
      write(9,*) (q(  in(nt(is))*(j)*n),j=1,3) 
      write(9,*) (q(  in(j)*(nt(2))*n),j=1,3)
      write(9,*) (q(  (j)*3*n),j=1,3) 
      write(9,*) (q(  (3)*j*n),j=1,3) 
      write(9,*) (q(  (j)*jnt*n),j=1,3) 
      write(9,*) (q(  (jnt)*j*n),j=1,3) 
      write(9,*) (q(  (j)*nt(is)*n),j=1,3) 
      write(9,*) (q(  (nt(is))*j*n),j=1,3) 
      write(9,*) (q(  (j)*nt(2)*n),j=1,3)
      write(9,*) (q(  (j)*in(3)*n),j=1,3) 
      write(9,*) (q(  (3)*in(j)*n),j=1,3) 
      write(9,*) (q(  (j)*in(jnt)*n),j=1,3) 
      write(9,*) (q(  (jnt)*in(j)*n),j=1,3) 
      write(9,*) (q(  (j)*in(nt(is))*n),j=1,3) 
      write(9,*) (q(  (nt(is))*in(j)*n),j=1,3) 
      write(9,*) (q(  (j)*in(nt(2))*n),j=1,3)  
      write(9,*) (q(  (in(j))*3*n),j=1,3) 
      write(9,*) (q(  (in(3))*j*n),j=1,3) 
      write(9,*) (q(  (in(j))*jnt*n),j=1,3) 
      write(9,*) (q(  (in(jnt))*j*n),j=1,3) 
      write(9,*) (q(  (in(j))*nt(is)*n),j=1,3) 
      write(9,*) (q(  (in(nt(is)))*j*n),j=1,3) 
      write(9,*) (q(  (in(j))*nt(2)*n),j=1,3)
      write(9,*) (q(  (j)*(3)*n),j=1,3) 
      write(9,*) (q(  (3)*(j)*n),j=1,3) 
      write(9,*) (q(  (j)*(jnt)*n),j=1,3) 
      write(9,*) (q(  (jnt)*(j)*n),j=1,3) 
      write(9,*) (q(  (j)*(nt(is))*n),j=1,3) 
      write(9,*) (q(  (nt(is))*(j)*n),j=1,3) 
      write(9,*) (q(  (j)*(nt(2))*n),j=1,3)
      write(9,*) (q(  (j)*(in(3))*n),j=1,3) 
      write(9,*) (q(  (3)*(in(j))*n),j=1,3) 
      write(9,*) (q(  (j)*(in(jnt))*n),j=1,3) 
      write(9,*) (q(  (jnt)*(in(j))*n),j=1,3) 
      write(9,*) (q(  (j)*(in(nt(is)))*n),j=1,3) 
      write(9,*) (q(  (nt(is))*(in(j))*n),j=1,3) 
      write(9,*) (q(  (j)*(in(nt(2)))*n),j=1,3)  
      write(9,*) (q(  (in(j))*(3)*n),j=1,3) 
      write(9,*) (q(  (in(3))*(j)*n),j=1,3) 
      write(9,*) (q(  (in(j))*(jnt)*n),j=1,3) 
      write(9,*) (q(  (in(jnt))*(j)*n),j=1,3) 
      write(9,*) (q(  (in(j))*(nt(is))*n),j=1,3) 
      write(9,*) (q(  (in(nt(is)))*(j)*n),j=1,3) 
      write(9,*) (q(  (in(j))*(nt(2))*n),j=1,3)

      rewind 9
      do k=1,84
      read(9,*) x;if (any(x/=(/3,6,9/)))then
             write(6,*) "NG";print *,'code=',k
        end if
      end do
      print *,'pass'
      end
      function in(j) result(k)
       k=j
      end
