extern unsigned int v1 (unsigned short, signed int, unsigned char);
extern unsigned int (*v2) (unsigned short, signed int, unsigned char);
extern void v3 (unsigned short);
extern void (*v4) (unsigned short);
extern signed char v5 (unsigned int, signed short);
extern signed char (*v6) (unsigned int, signed short);
extern unsigned short v7 (signed short, signed int);
extern unsigned short (*v8) (signed short, signed int);
extern signed char v9 (unsigned int, signed char, signed short, unsigned int);
extern signed char (*v10) (unsigned int, signed char, signed short, unsigned int);
extern signed int v11 (unsigned char, signed int, unsigned short, signed char);
extern signed int (*v12) (unsigned char, signed int, unsigned short, signed char);
extern signed int v13 (unsigned int, unsigned short, unsigned int);
extern signed int (*v14) (unsigned int, unsigned short, unsigned int);
extern void v15 (void);
extern void (*v16) (void);
extern signed char v17 (unsigned char, signed char);
extern signed char (*v18) (unsigned char, signed char);
extern signed int v19 (void);
extern signed int (*v20) (void);
extern signed int v21 (signed short, unsigned char);
extern signed int (*v22) (signed short, unsigned char);
extern signed int v23 (signed char);
extern signed int (*v24) (signed char);
extern signed short v25 (signed short, unsigned int, unsigned char, unsigned char);
extern signed short (*v26) (signed short, unsigned int, unsigned char, unsigned char);
extern unsigned short v27 (void);
extern unsigned short (*v28) (void);
extern signed int v29 (unsigned short, signed short, signed short, unsigned char);
extern signed int (*v30) (unsigned short, signed short, signed short, unsigned char);
extern int history[];
extern int history_index;
extern int trace;
unsigned short v120 = 4;
unsigned char v119 = 5;
signed char v118 = 3;
