extern unsigned char v1 (unsigned int, signed char, signed int, signed int);
extern unsigned char (*v2) (unsigned int, signed char, signed int, signed int);
extern signed short v3 (signed char);
extern signed short (*v4) (signed char);
extern void v5 (unsigned int, unsigned char, unsigned int);
extern void (*v6) (unsigned int, unsigned char, unsigned int);
extern unsigned short v7 (signed short, signed short, unsigned char);
extern unsigned short (*v8) (signed short, signed short, unsigned char);
extern void v9 (signed short, unsigned int, signed char, unsigned char);
extern void (*v10) (signed short, unsigned int, signed char, unsigned char);
extern signed short v11 (void);
extern signed short (*v12) (void);
extern signed short v13 (signed char);
extern signed short (*v14) (signed char);
extern void v15 (unsigned short, unsigned char, signed char, unsigned char);
extern void (*v16) (unsigned short, unsigned char, signed char, unsigned char);
extern unsigned int v17 (unsigned short, unsigned int);
extern unsigned int (*v18) (unsigned short, unsigned int);
extern unsigned short v19 (unsigned int);
extern unsigned short (*v20) (unsigned int);
extern signed int v21 (signed int, unsigned int);
extern signed int (*v22) (signed int, unsigned int);
extern signed char v23 (unsigned char, unsigned int, unsigned int, unsigned int);
extern signed char (*v24) (unsigned char, unsigned int, unsigned int, unsigned int);
extern void v27 (unsigned int, signed char, unsigned int);
extern void (*v28) (unsigned int, signed char, unsigned int);
extern unsigned short v29 (unsigned char, unsigned short, unsigned short, signed char);
extern unsigned short (*v30) (unsigned char, unsigned short, unsigned short, signed char);
extern int history[];
extern int history_index;
extern int trace;
signed char v66 = -2;
signed short v65 = -3;
signed int v64 = -2;
