MODULE CPU_TIME_MODULE
      IMPLICIT NONE
CONTAINS
      SUBROUTINE CPU_TIME(TIME)
      REAL, INTENT(OUT) :: TIME
      INTEGER :: COUNT, COUNT_RATE
      CALL SYSTEM_CLOCK(COUNT,COUNT_RATE)
      IF (COUNT_RATE /= 0) THEN
        TIME = REAL(COUNT)/COUNT_RATE
      ELSE
        TIME = -1
      END IF
      END SUBROUTINE CPU_TIME
END MODULE CPU_TIME_MODULE

      PROGRAM MAIN
      USE CPU_TIME_MODULE, ONLY: CPU_TIME
      IMPLICIT NONE
      REAL :: TIME
      CALL CPU_TIME(TIME)
      WRITE(21,*) TIME
      print *,'pass'
      END PROGRAM MAIN
