MODULE M
  TYPE T
      INTEGER::A
     CONTAINS 
        PROCEDURE::SUB
        GENERIC::WRITE(FORMATTED)=>SUB
END TYPE T
TYPE T2
    INTEGER::A1
    TYPE(T),ALLOCATABLE::OBJ1
  END TYPE T2
    INTEGER::C=1,B=1
   INTEGER,SAVE::AA=1
   CHARACTER(LEN=15)::CH,CH2='A'
CONTAINS
SUBROUTINE SUB (DTV, UNIT, IOTYPE, V_LIST, IOSTAT,IOMSG)
    CLASS(T), INTENT(IN)            :: DTV
    INTEGER, INTENT(IN)            :: UNIT
    CHARACTER(LEN=*), INTENT(IN)    :: IOTYPE
    INTEGER, INTENT(IN)             :: V_LIST (:)
    INTEGER, INTENT(OUT)            :: IOSTAT
    CHARACTER(LEN=*), INTENT(INOUT) :: IOMSG
     CH=IOTYPE
    IF(SIZE(V_LIST)/=0) THEN
        CH2='VLIST'
        C=V_LIST(1)
        B=V_LIST(2)
        AA=AA+DTV%A

      ELSE
         AA=AA+DTV%A
      END IF
      IF(AA .EQ. 5)WRITE(UNIT,*,IOSTAT=IOSTAT,IOMSG=IOMSG)'PASS'

END SUBROUTINE SUB

END MODULE M

PROGRAM MAIN

USE M
TYPE(T)::OBJW
OBJW%A=4

 PRINT *,OBJW
           IF(AA .NE. 5)PRINT*,101
  IF(CH .NE. 'LISTDIRECTED')PRINT*,102
  IF(CH2 .EQ. 'VLIST' .AND. (C .NE.2 .AND. B .NE.3))PRINT*,103
END PROGRAM
