MODULE M
IMPLICIT NONE

TYPE TY
    INTEGER :: X=9
     REAL :: Y=8
END TYPE TY
INTERFACE  WRITE(UNFORMATTED) 

     SUBROUTINE UNFMTWRITE(DTV, UNIT, IOSTAT, IOMSG)
         IMPORT TY
          CLASS(TY), INTENT(IN)    :: DTV
         INTEGER,                  INTENT(IN)    :: UNIT
         INTEGER,                  INTENT(OUT)   :: IOSTAT
         CHARACTER(LEN=*),         INTENT(INOUT) :: IOMSG

     END SUBROUTINE UNFMTWRITE

END INTERFACE
INTERFACE READ(UNFORMATTED)
     SUBROUTINE UNFMTREAD(DTV, UNIT, IOSTAT, IOMSG)
        IMPORT TY
        CLASS (TY), INTENT(INOUT)  :: DTV
         INTEGER,                  INTENT(IN)     :: UNIT
         INTEGER,                  INTENT(OUT)    :: IOSTAT
         CHARACTER (LEN=*),        INTENT(INOUT)  :: IOMSG

     END SUBROUTINE UNFMTREAD

END INTERFACE
END MODULE M



PROGRAM MAIN
USE M

IMPLICIT NONE

 INTERFACE
  FUNCTION FUN(D)
  IMPORT TY
  TYPE (TY) :: D,FUN
  END FUNCTION
  END INTERFACE

  TYPE (TY) :: T1,T2
  CALL SS(FUN)

  CONTAINS

  SUBROUTINE SS(DFUN)
 INTEGER::A,B
  INTERFACE
  FUNCTION DFUN(DD)
  IMPORT TY
  TYPE (TY) :: DD,DFUN
  END FUNCTION
 END INTERFACE
 A=8
 B=9
  OPEN(UNIT =70,FILE='fort.19',FORM='UNFORMATTED')


  WRITE(UNIT=70)A,DFUN(T1),B
  
CLOSE(UNIT=70)
  OPEN(UNIT =77,FILE='fort.19',FORM='UNFORMATTED')
   READ(UNIT=77)A,T2,B
CLOSE(UNIT=77,status='delete')
IF( T2%X.EQ. 21 )THEN
 PRINT*,'PASS'
ELSE
 PRINT*,'ERROR'
END IF
  END SUBROUTINE
END PROGRAM

       FUNCTION FUN(D)
        USE M
        TYPE (TY) :: D,FUN
        FUN=D
        FUN%X = FUN%X+10
        FUN%Y = FUN%Y+10
      END FUNCTION

     SUBROUTINE UNFMTWRITE(DTV, UNIT, IOSTAT, IOMSG)
       USE M 
      CLASS (TY), INTENT(IN)    :: DTV
         INTEGER,                  INTENT(IN)    :: UNIT
         INTEGER,                  INTENT(OUT)   :: IOSTAT
        CHARACTER(LEN=*),         INTENT(INOUT) :: IOMSG

      WRITE(UNIT,IOSTAT=IOSTAT,IOMSG=IOMSG)DTV%X+1
     END SUBROUTINE UNFMTWRITE

     SUBROUTINE UNFMTREAD(DTV, UNIT, IOSTAT, IOMSG)
        USE M 
        CLASS (TY), INTENT(INOUT)  :: DTV
         INTEGER,                  INTENT(IN)     :: UNIT
         INTEGER,                  INTENT(OUT)    :: IOSTAT
         CHARACTER (LEN=*),        INTENT(INOUT)  :: IOMSG

        READ (UNIT=UNIT, IOSTAT=IOSTAT, IOMSG=IOMSG) DTV%X
     DTV%X=DTV%X+1   
     END SUBROUTINE UNFMTREAD
