MODULE M
IMPLICIT NONE

TYPE T
INTEGER::A=666
CONTAINS
  PROCEDURE::FMTWRITE
GENERIC::write(formatted)=>FMTWRITE
  END TYPE T
private FMTWRITE
INTEGER::AA=1
CONTAINS
SUBROUTINE FMTWRITE (DTV, UNIT, IOTYPE, V_LIST, IOSTAT,IOMSG)
    CLASS(T), INTENT(IN)            :: DTV
    INTEGER, INTENT(IN)            :: UNIT
    CHARACTER(LEN=*), INTENT(IN)    :: IOTYPE
    INTEGER, INTENT(IN)             :: V_LIST (:)
    INTEGER, INTENT(OUT)            :: IOSTAT
    CHARACTER(LEN=*), INTENT(INOUT) :: IOMSG
AA=DTV%A+5
    IF(SIZE(V_LIST)/=0) THEN
        WRITE(UNIT,*,IOSTAT=IOSTAT,IOMSG=IOMSG) V_LIST(1),V_LIST(2),DTV%A+1,IOTYPE
      ELSE
        WRITE (UNIT=UNIT,*, IOSTAT=IOSTAT, IOMSG=IOMSG) DTV%A+1
      END IF  
  END SUBROUTINE FMTWRITE


END MODULE M
MODULE M2
USE M
type,extends(T)::tty
integer::aa
CONTAINS
  PROCEDURE::FMTWRITE
end type 
CONTAINS
SUBROUTINE FMTWRITE (DTV, UNIT, IOTYPE, V_LIST, IOSTAT,IOMSG)
    CLASS(tty), INTENT(IN)            :: DTV
    INTEGER, INTENT(IN)            :: UNIT
    CHARACTER(LEN=*), INTENT(IN)    :: IOTYPE
    INTEGER, INTENT(IN)             :: V_LIST (:)
    INTEGER, INTENT(OUT)            :: IOSTAT
    CHARACTER(LEN=*), INTENT(INOUT) :: IOMSG
AA=DTV%aa+5
    IF(SIZE(V_LIST)/=0) THEN
        WRITE(UNIT,*,IOSTAT=IOSTAT,IOMSG=IOMSG) V_LIST(1),V_LIST(2),DTV%A+1,IOTYPE
      ELSE
        WRITE (UNIT=UNIT,*, IOSTAT=IOSTAT, IOMSG=IOMSG) DTV%A+1
      END IF  
  END SUBROUTINE FMTWRITE

end module M2
PROGRAM MAIN
USE M2

IMPLICIT NONE
type(tty)::obj
obj%aa=55        
open(44,file='fort.45',form='formatted')
write(44,*)obj
close(44,status='delete')
if(AA/=60)print*,'101',AA
print*,'pass'
END

