MODULE M
  TYPE T
      INTEGER::A
     CONTAINS 
        PROCEDURE::SUB
        GENERIC::WRITE(FORMATTED)=>SUB
END TYPE T
   INTEGER::C=1,B=1
   INTEGER,SAVE::AA=1
   CHARACTER(LEN=15)::CH,CH2='A'

CONTAINS
SUBROUTINE SUB (DTV, UNIT, IOTYPE, V_LIST, IOSTAT,IOMSG)
    CLASS(T), INTENT(IN)            :: DTV
    INTEGER, INTENT(IN)            :: UNIT
    CHARACTER(LEN=*), INTENT(IN)    :: IOTYPE
    INTEGER, INTENT(IN)             :: V_LIST (:)
    INTEGER, INTENT(OUT)            :: IOSTAT
    CHARACTER(LEN=*), INTENT(INOUT) :: IOMSG
     CH=IOTYPE
    IF(SIZE(V_LIST)/=0) THEN
        CH2='VLIST'
        C=V_LIST(1)
        B=V_LIST(2)
        AA=AA+DTV%A
    
      ELSE
         AA=AA+DTV%A
      END IF
      IF(AA .EQ. 10)WRITE(UNIT,*,IOSTAT=IOSTAT,IOMSG=IOMSG)'PASS'
          
END SUBROUTINE SUB


END MODULE M

PROGRAM MAIN

USE M
TYPE(T)::OBJW
NAMELIST /LIST1/ OBJW
OBJW%A=9

     PRINT LIST1
           IF(AA .NE. 10)PRINT*,101
  IF(CH .NE. 'NAMELIST')PRINT*,102
  IF(CH2 .EQ. 'VLIST' .AND. (C .NE.2 .AND. B .NE.3))PRINT*,103

END PROGRAM

