MODULE M
IMPLICIT NONE

TYPE T
 INTEGER::A
END TYPE T
TYPE T2
    INTEGER::A1
    TYPE(T)::OBJ1,OBJ11
  END TYPE T2
TYPE gg
 INTEGER::CC
END TYPE gg
INTERFACE  WRITE(UNFORMATTED) 

     SUBROUTINE UNFMTWRITE1(DTV, UNIT, IOSTAT, IOMSG)
         IMPORT gg
          CLASS(gg), INTENT(IN)    :: DTV
         INTEGER,                  INTENT(IN)    :: UNIT
         INTEGER,                  INTENT(OUT)   :: IOSTAT
         CHARACTER(LEN=*),         INTENT(INOUT) :: IOMSG

     END SUBROUTINE UNFMTWRITE1
     SUBROUTINE UNFMTWRITE(DTV, UNIT, IOSTAT, IOMSG)
         IMPORT T
          CLASS(T), INTENT(IN)    :: DTV
         INTEGER,                  INTENT(IN)    :: UNIT
         INTEGER,                  INTENT(OUT)   :: IOSTAT
         CHARACTER(LEN=*),         INTENT(INOUT) :: IOMSG

     END SUBROUTINE UNFMTWRITE

END INTERFACE
INTERFACE READ(UNFORMATTED)
     SUBROUTINE UNFMTREAD(DTV, UNIT, IOSTAT, IOMSG)
         IMPORT T
         CLASS (T), INTENT(INOUT)  :: DTV
         INTEGER,                  INTENT(IN)     :: UNIT
         INTEGER,                  INTENT(OUT)    :: IOSTAT
         CHARACTER (LEN=*),        INTENT(INOUT)  :: IOMSG

     END SUBROUTINE UNFMTREAD
END INTERFACE

END MODULE M

PROGRAM MAIN
USE M

IMPLICIT NONE

INTEGER::C=7,D=9
TYPE(T2)::OBJW1,OBJW2,OBJR1,OBJR2
OBJW1%OBJ1%A=6
OBJW2%OBJ1%A=7
  OPEN (UNIT=71, FILE='fort.4', FORM='UNFORMATTED')
     WRITE(UNIT=71)C,OBJW1%OBJ1,OBJW2%OBJ1,D

     CLOSE (UNIT=71)

 OPEN (UNIT=77, FILE='fort.4', FORM='UNFORMATTED')
   READ (UNIT=77)C,OBJR1%OBJ1,OBJR2%OBJ1,D
     CLOSE (UNIT=77,status='delete')

IF(( OBJR1%OBJ1%A.EQ. 8).AND. (OBJR2%OBJ1%A .EQ. 9) )THEN
 PRINT*,'PASS'
ELSE
 PRINT*,'ERROR'
END IF
END 
     SUBROUTINE UNFMTWRITE1(DTV, UNIT, IOSTAT, IOMSG)
       USE M 
      CLASS (gg), INTENT(IN)    :: DTV
         INTEGER,                  INTENT(IN)    :: UNIT
         INTEGER,                  INTENT(OUT)   :: IOSTAT
        CHARACTER(LEN=*),         INTENT(INOUT) :: IOMSG

        WRITE (UNIT=UNIT, IOSTAT=IOSTAT, IOMSG=IOMSG) DTV%CC+3
     END SUBROUTINE UNFMTWRITE1

     SUBROUTINE UNFMTWRITE(DTV, UNIT, IOSTAT, IOMSG)
       USE M 
      CLASS (T), INTENT(IN)    :: DTV
         INTEGER,                  INTENT(IN)    :: UNIT
         INTEGER,                  INTENT(OUT)   :: IOSTAT
        CHARACTER(LEN=*),         INTENT(INOUT) :: IOMSG

        WRITE (UNIT=UNIT, IOSTAT=IOSTAT, IOMSG=IOMSG) DTV%A+1
     END SUBROUTINE UNFMTWRITE

     SUBROUTINE UNFMTREAD(DTV, UNIT, IOSTAT, IOMSG)
     USE M       
      CLASS (T), INTENT(INOUT)  :: DTV
         INTEGER,                  INTENT(IN)     :: UNIT
         INTEGER,                  INTENT(OUT)    :: IOSTAT
         CHARACTER (LEN=*),        INTENT(INOUT)  :: IOMSG

        READ (UNIT=UNIT, IOSTAT=IOSTAT, IOMSG=IOMSG) DTV%A
        DTV%A=DTV%A+1
     END SUBROUTINE UNFMTREAD
