MODULE M
  TYPE T
      INTEGER::A
     CONTAINS 
        PROCEDURE::SUB
        PROCEDURE::SUB1
        GENERIC::WRITE(FORMATTED)=>SUB
        GENERIC::READ(FORMATTED)=>SUB1
END TYPE T
TYPE T2
    INTEGER::A1=7
    TYPE(T)::OBJ1,OBJ11
  END TYPE T2
    CHARACTER(9) :: CH
    INTEGER :: VV

CONTAINS
SUBROUTINE SUB (DTV, UNIT, IOTYPE, V_LIST, IOSTAT,IOMSG)
    CLASS(T), INTENT(IN)            :: DTV
    INTEGER, INTENT(IN)            :: UNIT
    CHARACTER(LEN=*), INTENT(IN)    :: IOTYPE
    INTEGER, INTENT(IN)             :: V_LIST (:)
    INTEGER, INTENT(OUT)            :: IOSTAT
    CHARACTER(LEN=*), INTENT(INOUT) :: IOMSG
    IF(SIZE(V_LIST)/=0)  VV=V_LIST(1)
    CH=IOTYPE
    WRITE(UNIT,*,IOSTAT=IOSTAT,IOMSG=IOMSG) DTV%A+1
END SUBROUTINE SUB

SUBROUTINE SUB1 (DTV, UNIT, IOTYPE, V_LIST, IOSTAT, IOMSG)
    CLASS(T), INTENT(INOUT)            :: DTV
    INTEGER, INTENT(IN)             :: UNIT
    CHARACTER(LEN=*), INTENT(IN)    :: IOTYPE
    INTEGER, INTENT(IN)             :: V_LIST (:)
    INTEGER, INTENT(OUT)            :: IOSTAT
    CHARACTER(LEN=*), INTENT(INOUT) :: IOMSG
CH=IOTYPE
          IF(SIZE(V_LIST)/=0) THEN
         VV=V_LIST(1)
        READ(UNIT,*,IOSTAT=IOSTAT,IOMSG=IOMSG) DTV%A,CH
      ELSE
        READ(UNIT,*,IOSTAT=IOSTAT,IOMSG=IOMSG) DTV%A
     END IF
     DTV%A=DTV%A+1
END SUBROUTINE SUB1

END MODULE M

PROGRAM MAIN

USE M
TYPE(T2)::OBJW1,OBJW2,OBJR1,OBJR2

OBJW1%OBJ1%A=8
OBJW2%OBJ1%A=8

 OPEN (UNIT=71, FILE='fort.49', FORM='FORMATTED')
     WRITE(UNIT=71,FMT="(2(DT'LINKLIST'))")OBJW1%OBJ1,OBJW2%OBJ1

     CLOSE (UNIT=71)

 OPEN (UNIT=77, FILE='fort.49', FORM='FORMATTED')
   READ (UNIT=77,FMT="(2DT)")OBJR1%OBJ1,OBJR2%OBJ1
     CLOSE (UNIT=77,status='delete')
IF(( OBJR1%OBJ1%A.EQ. 10).AND. (OBJR2%OBJ1%A .EQ. 10))THEN
 PRINT*,'PASS'
ELSE
 PRINT*,'ERROR'
END IF

END PROGRAM
