extern signed int v1 (signed short, unsigned int, signed int);
extern signed int (*v2) (signed short, unsigned int, signed int);
extern signed short v3 (signed short);
extern signed short (*v4) (signed short);
extern unsigned int v5 (void);
extern unsigned int (*v6) (void);
extern unsigned short v7 (signed char, unsigned short, signed int, unsigned int);
extern unsigned short (*v8) (signed char, unsigned short, signed int, unsigned int);
extern signed int v9 (unsigned char, unsigned int);
extern signed int (*v10) (unsigned char, unsigned int);
extern signed char v11 (unsigned short, unsigned char, unsigned char, unsigned int);
extern signed char (*v12) (unsigned short, unsigned char, unsigned char, unsigned int);
extern unsigned char v13 (signed char, unsigned int, unsigned char);
extern unsigned char (*v14) (signed char, unsigned int, unsigned char);
extern signed int v15 (signed char, signed short, signed short);
extern signed int (*v16) (signed char, signed short, signed short);
extern signed short v17 (unsigned int, signed int, signed int);
extern signed short (*v18) (unsigned int, signed int, signed int);
extern void v19 (signed int, signed char, signed short);
extern void (*v20) (signed int, signed char, signed short);
extern signed char v21 (void);
extern signed char (*v22) (void);
extern signed short v23 (unsigned char, signed char);
extern signed short (*v24) (unsigned char, signed char);
extern unsigned char v25 (unsigned char, unsigned char, signed short);
extern unsigned char (*v26) (unsigned char, unsigned char, signed short);
extern unsigned char v27 (unsigned int, signed short);
extern unsigned char (*v28) (unsigned int, signed short);
extern signed short v29 (signed short, unsigned char);
extern signed short (*v30) (signed short, unsigned char);
extern int history[];
extern int history_index;
extern int trace;
unsigned int v57 = 7U;
signed short v56 = 3;
unsigned int v55 = 4U;
