int main()
{
extern int lto_sub_1();
  lto_sub_1();
extern int lto_sub_2();
  lto_sub_2();
extern int lto_sub_3();
  lto_sub_3();
extern int lto_sub_4();
  lto_sub_4();
extern int lto_sub_5();
  lto_sub_5();
extern int lto_sub_6();
  lto_sub_6();
extern int lto_sub_7();
  lto_sub_7();
extern int lto_sub_8();
  lto_sub_8();
extern int lto_sub_9();
  lto_sub_9();
extern int lto_sub_10();
  lto_sub_10();
extern int lto_sub_11();
  lto_sub_11();
extern int lto_sub_12();
  lto_sub_12();
extern int lto_sub_13();
  lto_sub_13();
extern int lto_sub_14();
  lto_sub_14();
extern int lto_sub_15();
  lto_sub_15();
extern void lto_sub_16();
  lto_sub_16();
extern void lto_sub_17();
  lto_sub_17();
extern void lto_sub_18();
  lto_sub_18();
extern void lto_sub_19();
  lto_sub_19();
extern void lto_sub_20();
  lto_sub_20();
extern void lto_sub_21();
  lto_sub_21();
extern void lto_sub_22();
  lto_sub_22();
extern void lto_sub_23();
  lto_sub_23();
extern void lto_sub_24();
  lto_sub_24();
extern void lto_sub_25();
  lto_sub_25();
extern void lto_sub_26();
  lto_sub_26();
extern void lto_sub_27();
  lto_sub_27();
extern int lto_sub_28();
  lto_sub_28();
extern void lto_sub_29();
  lto_sub_29();
extern void lto_sub_30();
  lto_sub_30();
extern void lto_sub_31();
  lto_sub_31();
extern void lto_sub_32();
  lto_sub_32();
extern void lto_sub_33();
  lto_sub_33();
extern int lto_sub_34();
  lto_sub_34();
extern int lto_sub_35();
  lto_sub_35();
extern int lto_sub_36();
  lto_sub_36();
extern void lto_sub_37();
  lto_sub_37();
extern int lto_sub_38();
  lto_sub_38();
extern int lto_sub_39();
  lto_sub_39();
extern int lto_sub_40();
  lto_sub_40();
extern int lto_sub_41();
  lto_sub_41();
extern int lto_sub_42();
  lto_sub_42();
extern int lto_sub_43();
  lto_sub_43();
extern int lto_sub_44();
  lto_sub_44();
extern int lto_sub_45();
  lto_sub_45();
  return 0;
}
