 module solvers
 contains
 subroutine pcg()
     !$OMP PARALLEL
     !$OMP PARALLEL
     !$OMP PARALLEL
     !$OMP PARALLEL
     !$OMP PARALLEL
     !$OMP PARALLEL
     !$OMP PARALLEL
     !$OMP END PARALLEL
     !$OMP END PARALLEL
     !$OMP END PARALLEL
     !$OMP PARALLEL
     !$OMP PARALLEL
     !$OMP PARALLEL
     !$OMP END PARALLEL
     !$OMP END PARALLEL
     !$OMP END PARALLEL
     !$OMP END PARALLEL
     !$OMP END PARALLEL
     !$OMP PARALLEL
     !$OMP PARALLEL
     !$OMP PARALLEL
     !$OMP END PARALLEL
     !$OMP END PARALLEL
     !$OMP PARALLEL
     !$OMP PARALLEL
     !$OMP PARALLEL
     !$OMP END PARALLEL
     !$OMP END PARALLEL
     !$OMP END PARALLEL
     !$OMP PARALLEL
     !$OMP PARALLEL
     !$OMP PARALLEL
     !$OMP PARALLEL
     !$OMP END PARALLEL
     !$OMP END PARALLEL
     !$OMP PARALLEL
     !$OMP PARALLEL
     !$OMP PARALLEL
     !$OMP PARALLEL
     !$OMP PARALLEL
     !$OMP PARALLEL
     !$OMP END PARALLEL
     !$OMP END PARALLEL
     !$OMP PARALLEL
     !$OMP END PARALLEL
     !$OMP PARALLEL
     !$OMP END PARALLEL
     !$OMP PARALLEL
     !$OMP END PARALLEL
     !$OMP PARALLEL
     !$OMP END PARALLEL
     !$OMP PARALLEL
     !$OMP END PARALLEL
     !$OMP END PARALLEL
     !$OMP END PARALLEL
     !$OMP END PARALLEL
     !$OMP END PARALLEL
     !$OMP END PARALLEL
     !$OMP END PARALLEL
     !$OMP END PARALLEL
     !$OMP END PARALLEL
     !$OMP END PARALLEL
 end subroutine
end

print *,"pass"
end
