MODULE M
IMPLICIT NONE
INTERFACE TESTIF
  MODULE PROCEDURE TEST1
  MODULE PROCEDURE TEST2
END INTERFACE
CONTAINS
SUBROUTINE TEST1 (OBJ)
 COMPLEX*4 :: OBJ
 OBJ=OBJ+1
END SUBROUTINE
SUBROUTINE TEST2 (OBJ2)
  COMPLEX*8 :: OBJ2
  OBJ2=OBJ2+2
END SUBROUTINE
END MODULE

PROGRAM TEST
USE M
IMPLICIT NONE
COMPLEX(KIND=2):: CMP1
COMPLEX(KIND=4):: CMP2
CMP1=(4,5)
CMP2=(6,7)
CALL TESTIF(CMP1)
CALL TESTIF(CMP2) 
IF(CMP1/= (5,5)) PRINT *,101
IF(CMP2/= (8,7)) PRINT *,102
PRINT *,"PASS"
END PROGRAM

