INTEGER::I_RECLENGTH
INTEGER,PARAMETER::K=2
COMPLEX(KIND=K)::C2=(10.4_K,45.6_K)
REAL(KIND=K)::R2=10.4_K

INQUIRE (IOLENGTH=I_RECLENGTH) C2
IF(I_RECLENGTH /= 4)PRINT*,"101"
INQUIRE (IOLENGTH=I_RECLENGTH) R2
IF(I_RECLENGTH /= 2)PRINT*,"102"


PRINT*,"PASS"



END
