MODULE M
TYPE TY
COMPLEX (KIND=2),POINTER :: C(:)
COMPLEX (KIND=2) :: C1
END TYPE
END MODULE

USE M
CALL S()
CONTAINS
SUBROUTINE S()
TYPE(TY) :: OBJ1
INTEGER :: I
ALLOCATE(OBJ1%C(3))
FORALL (I=1:5)
OBJ1%C1=(5,6)
OBJ1%C(I:2)=OBJ1%C1
END FORALL
IF(OBJ1%C(1) .NE. (5,6))PRINT*,"101"
IF(OBJ1%C(2) .NE. (5,6))PRINT*,"102"
PRINT*,"PASS"
END SUBROUTINE
END

