MODULE MOD1
TYPE TY
   REAL(KIND =2):: R2(3)
   COMPLEX(KIND =2):: C2(3)
END TYPE
TYPE TY2
  TYPE(TY) :: CMP
END TYPE

CONTAINS
SUBROUTINE SUB(DMY)
TYPE(TY2),POINTER,INTENT(IN) :: DMY
IF(ANY(DMY%CMP%R2 .NE. 3.0))PRINT*,"101"
IF(ANY(DMY%CMP%C2 .NE.(4.0,5.0)))PRINT*,"102"
END SUBROUTINE
END MODULE

PROGRAM MAIN
USE MOD1
IMPLICIT NONE
TYPE(TY2),TARGET :: OBJ
OBJ%CMP%R2 = 3.0
OBJ%CMP%C2 = (4.0,5.0)
CALL SUB(OBJ)
PRINT*,"PASS"
END PROGRAM
