REAL*2, ALLOCATABLE :: A(:), B(:)
TYPE TY
 REAL*2, ALLOCATABLE :: A(:), B(:)
END TYPE
TYPE(TY)::OBJ
ALLOCATE(OBJ%A(3))
    ALLOCATE(A(3))
    A = [ 1.5, 2.5, 3.5 ]
    OBJ%A = [ 1.5, 2.5, 3.5 ]
    CALL MOVE_ALLOC(A, B)
    CALL MOVE_ALLOC(OBJ%A, OBJ%B)
    IF(ALLOCATED(A) .NEQV. .FALSE.) PRINT*,"101"
    IF(ALLOCATED(B) .NEQV. .TRUE.) PRINT*,"102"
    IF(ANY (B /= [ 1.5, 2.5, 3.5 ]))PRINT*,"103"
    IF(ALLOCATED(OBJ%A) .NEQV. .FALSE.) PRINT*,"104"
    IF(ALLOCATED(OBJ%B) .NEQV. .TRUE.) PRINT*,"105"
    IF(ANY (OBJ%B /= [ 1.5, 2.5, 3.5 ]))PRINT*,"106"
 PRINT*,"PASS"
END PROGRAM 
