REAL*2,ALLOCATABLE::R2
REAL*2,ALLOCATABLE::RR2(:)
COMPLEX(KIND=2),ALLOCATABLE::C2
COMPLEX(KIND=2),ALLOCATABLE::CC2(:)
ALLOCATE(R2,RR2(4),C2,CC2(5))
IF(ALLOCATED(R2) .NEQV. .TRUE.)PRINT*,"101"
IF(ALLOCATED(RR2) .NEQV. .TRUE.)PRINT*,"102"
IF(ALLOCATED(C2) .NEQV. .TRUE.)PRINT*,"103"
IF(ALLOCATED(CC2) .NEQV. .TRUE.)PRINT*,"104"

PRINT*,"PASS"

END




