REAL (KIND=2) ,ALLOCATABLE  :: R(:)
COMPLEX (KIND=2),ALLOCATABLE  :: C(:)
REAL (KIND=2) ,POINTER :: R1
COMPLEX (KIND=2),POINTER :: C1
INTEGER ::  N=1,CHECKSTAT,POINT
ALLOCATE(R(N),C(N),STAT=CHECKSTAT)
ALLOCATE(R1,C1,STAT=POINT)
IF (ALLOCATED(R)) R(1)=1.0_2
IF (ALLOCATED(C))C(1)=(1.0_2,1.0_2)     
IF (R(1) /= 1.0_2) PRINT*,'101'
IF (C(1) /= (1.0_2,1.0_2)) PRINT*,'102'   
IF (POINT /= 0) PRINT*,'103'
IF (CHECKSTAT /= 0)PRINT*,"104"
PRINT*,'PASS'
END
