MODULE M1
 INTEGER,PARAMETER::K=2
CONTAINS
   SUBROUTINE FOO(A,M)
    COMPLEX(KIND=K),CONTIGUOUS::A(:)
    COMPLEX(KIND=K),CONTIGUOUS::M(:)
    IF (ANY(A/=[1,3])) PRINT *,105
    IF (ANY(M/=[1,2,3,4,5])) PRINT *,109
    A=[11,12]
    M=[11,12,13,14,15]
   END SUBROUTINE
SUBROUTINE SS2(B,F)
COMPLEX(KIND=K),POINTER:: B(:)
COMPLEX(KIND=K),POINTER:: F(:)
CALL FOO(B(:),F(:))
END SUBROUTINE
END
SUBROUTINE S1
USE M1
COMPLEX(KIND=K),TARGET:: C(3)=[1,2,3]
COMPLEX(KIND=K),TARGET:: D(5)=[1,2,3,4,5]
COMPLEX(KIND=K),POINTER:: P(:)
COMPLEX(KIND=K),POINTER:: Q(:)
INTEGER::NUMBER =1
P=> C(::2)
Q=> D(::NUMBER)
CALL SS2(P,Q)
IF (ANY(C/=[11,2,12])) PRINT *,102
IF (ANY(D/=[11,12,13,14,15])) PRINT *,104
END
CALL S1
PRINT *,'PASS'
END

