 MODULE M_IMPORT
 TYPE TY
 REAL (KIND=2) :: R
 COMPLEX (KIND=2) :: C
 END TYPE TY
 REAL (KIND=2) :: RR
 COMPLEX (KIND=2) :: CC
 END MODULE

 USE M_IMPORT
 INTERFACE
 FUNCTION SUB()
 IMPORT TY
 CLASS (TY),POINTER :: SUB
 TYPE (TY),TARGET :: TY1
 END FUNCTION SUB
 END INTERFACE
 CLASS (TY),ALLOCATABLE :: PFUN
 PFUN=SUB()
 PFUN%R=1.0_2
 PFUN%C=(1.0_2,1.0_2)
 IF (PFUN%R/=1.0_2) PRINT*,'103'
 IF (PFUN%C/=(1.0_2,1.0_2)) PRINT*,'104'
 PRINT *,'PASS'
 END

 FUNCTION SUB()
 USE M_IMPORT
 CLASS (TY),POINTER :: SUB
 TYPE (TY),TARGET :: TY1
 SUB=>TY1
 END FUNCTION SUB

