REAL*2,POINTER::R2
REAL*2,POINTER::RR2(:)
COMPLEX(KIND=2),POINTER::C2
COMPLEX(KIND=2),POINTER::CC2(:)
REAL*2,TARGET::TR2
REAL*2,TARGET::TRR2(4)
COMPLEX(KIND=2),TARGET::TC2
COMPLEX(KIND=2),TARGET::TCC2(4)
TR2=5.5_2
TRR2=TR2
TC2=(4.5_2,3.5_2)
TCC2=TC2

R2=>TR2
RR2=>TRR2
C2=>TC2
CC2=>TCC2
CALL SUB(R2,RR2,C2,CC2)
IF(ASSOCIATED(R2) .NEQV. .TRUE.)PRINT*,"101"
IF(ASSOCIATED(RR2) .NEQV. .TRUE.)PRINT*,"102"
IF(ASSOCIATED(C2) .NEQV. .TRUE.)PRINT*,"103"
IF(ASSOCIATED(CC2) .NEQV. .TRUE.)PRINT*,"104"

PRINT*,"PASS"
CONTAINS
SUBROUTINE SUB(D1,D2,D3,D4)
REAL*2,POINTER,INTENT(INOUT)::D1
REAL*2,POINTER,INTENT(INOUT)::D2(:)
COMPLEX(KIND=2),POINTER,INTENT(INOUT)::D3
COMPLEX(KIND=2),POINTER,INTENT(INOUT)::D4(:)
IF(ASSOCIATED(D1) .NEQV. .TRUE.)PRINT*,"201"
IF(ASSOCIATED(D2) .NEQV. .TRUE.)PRINT*,"202"
IF(ASSOCIATED(D3) .NEQV. .TRUE.)PRINT*,"203"
IF(ASSOCIATED(D4) .NEQV. .TRUE.)PRINT*,"204"
END SUBROUTINE

END




