MODULE MOD
TYPE TY
  COMPLEX*4:: X
END TYPE TY

INTERFACE OPERATOR(+)
 FUNCTION FUN (PX,AX) RESULT (C)
  IMPORT TY
  TYPE(TY), INTENT(IN) :: PX 
  COMPLEX*4,INTENT(IN)::AX
  TYPE(TY) :: C
  END FUNCTION 
END INTERFACE
END MODULE 

PROGRAM MAIN
USE MOD
 TYPE(TY) ::OBJ1,OBJ2
 COMPLEX*4::C2
 OBJ2=TY((5.0,6.0))
 C2=(7.0,8.0)
 OBJ1=OBJ2+C2
 IF(OBJ1%X .NE. (12,14))PRINT*,"101"
 PRINT*,"PASS"
END
  
 FUNCTION FUN (PX,AX) RESULT (C)
  USE MOD
  TYPE(TY), INTENT(IN) :: PX 
  COMPLEX*4,INTENT(IN)::AX
  TYPE(TY) :: C
  C%X=PX%X + AX
  END FUNCTION 
