REAL*2,POINTER :: CC(:,:)
REAL*2,TARGET :: CC2(3,3)
CC=>CC2
CALL SUB(CC(1:3:2,:),CC)
CONTAINS
SUBROUTINE SUB(DMY1,DMY2)
REAL*2 :: DMY1(2,3)
REAL*2,POINTER :: DMY2(:,:)
IF(IS_CONTIGUOUS(DMY1) .NEQV. .TRUE.)PRINT*,"101"
IF(IS_CONTIGUOUS(DMY2) .NEQV. .TRUE.)PRINT*,"102"
PRINT*,"PASS"
END SUBROUTINE SUB
END
