REAL(KIND=2):: R1(:)
ALLOCATABLE :: R1
REAL(KIND=2) :: R2(:)
ALLOCATABLE :: R2
REAL(KIND=2) :: SRC(2)
SRC=4
ALLOCATE(R1,R2,SOURCE=SRC)
IF(ANY(R1 .NE. 4))PRINT*,"101"
IF(ALLOCATED(R1) .EQV. .FALSE.)PRINT*,"102"
IF(ANY(R2 .NE. 4))PRINT*,"101"
IF(ALLOCATED(R2) .EQV. .FALSE.)PRINT*,"102"
PRINT*,"PASS"
END
