COMPLEX(KIND=2) :: C1(:)
ALLOCATABLE :: C1
COMPLEX(KIND=2) :: C2(:)
ALLOCATABLE :: C2
COMPLEX(KIND=2) :: SRC(2)
SRC=4
ALLOCATE(C1,C2,MOLD=SRC)
C1=SRC
C2=SRC
IF(ANY(C1 .NE. 4))PRINT*,"101"
IF(ANY(C2 .NE. 4))PRINT*,"102"
IF(ALLOCATED(C1) .EQV. .FALSE.)PRINT*,"103"
IF(ALLOCATED(C2) .EQV. .FALSE.)PRINT*,"104"
PRINT*,"PASS"
END
