REAL(KIND=2),ALLOCATABLE :: R1
REAL(KIND=2),ALLOCATABLE :: R2(:)
REAL(KIND=2),ALLOCATABLE :: R3(:,:)
REAL(KIND=2),ALLOCATABLE :: R4(:,:,:)
ALLOCATE(REAL(2) :: R1)
ALLOCATE(REAL(2) :: R2(4))
ALLOCATE(REAL(2) :: R3(5,6),R4(1,2,3))
IF(ALLOCATED(R1) .EQV. .FALSE.)PRINT*,"101"
IF(ALLOCATED(R2) .EQV. .FALSE.)PRINT*,"102"
IF(ALLOCATED(R3) .EQV. .FALSE.)PRINT*,"103"
IF(ALLOCATED(R4) .EQV. .FALSE.)PRINT*,"104"
DEALLOCATE(R1,R2,R3,R4)
IF(ALLOCATED(R1) .EQV. .TRUE.)PRINT*,"105"
IF(ALLOCATED(R2) .EQV. .TRUE.)PRINT*,"106"
IF(ALLOCATED(R3) .EQV. .TRUE.)PRINT*,"107"
IF(ALLOCATED(R4) .EQV. .TRUE.)PRINT*,"108"
PRINT*,"PASS"
END
