TYPE TY
REAL*2,ALLOCATABLE :: CC(:,:)
COMPLEX(2),ALLOCATABLE :: DD(:,:)
END TYPE TY
TYPE(TY)::OBJ
ALLOCATE(OBJ%CC(3,3),OBJ%DD(3,3))
CALL SUB(OBJ,OBJ%CC(1:3:2,:),OBJ%DD(:,1:3:2))
CONTAINS
SUBROUTINE SUB(DMY1,DMY2,DMY3)
TYPE(TY) :: DMY1(..)
REAL*2 :: DMY2(..)
COMPLEX(2) :: DMY3(..)
IF(IS_CONTIGUOUS(DMY1) .NEQV. .TRUE.)PRINT*,"101"
IF(IS_CONTIGUOUS(DMY2) .NEQV. .FALSE.)PRINT*,"102"
IF(IS_CONTIGUOUS(DMY3) .NEQV. .FALSE.)PRINT*,"103"
PRINT*,"PASS"
END SUBROUTINE SUB
END
