extern unsigned int v1 (signed char);
extern unsigned int (*v2) (signed char);
extern signed char v3 (unsigned int, signed int, signed int);
extern signed char (*v4) (unsigned int, signed int, signed int);
extern signed short v5 (signed int);
extern signed short (*v6) (signed int);
extern unsigned short v7 (void);
extern unsigned short (*v8) (void);
extern unsigned int v9 (void);
extern unsigned int (*v10) (void);
extern unsigned short v11 (unsigned char);
extern unsigned short (*v12) (unsigned char);
extern unsigned short v13 (signed short, signed char, signed short, signed char);
extern unsigned short (*v14) (signed short, signed char, signed short, signed char);
extern unsigned char v17 (signed short);
extern unsigned char (*v18) (signed short);
extern unsigned short v21 (void);
extern unsigned short (*v22) (void);
extern unsigned int v23 (unsigned int);
extern unsigned int (*v24) (unsigned int);
extern signed short v25 (unsigned short, signed int, signed short);
extern signed short (*v26) (unsigned short, signed int, signed short);
extern signed int v27 (signed int, signed char, unsigned short, signed char);
extern signed int (*v28) (signed int, signed char, unsigned short, signed char);
extern unsigned int v29 (signed int, signed char);
extern unsigned int (*v30) (signed int, signed char);
extern int history[];
extern int history_index;
extern int trace;
signed short v107 = -1;
signed char v106 = 3;
signed int v105 = 2;
