extern unsigned char v3 (signed int, signed char, signed char);
extern unsigned char (*v4) (signed int, signed char, signed char);
extern signed char v7 (unsigned char, signed short, signed char, signed char);
extern signed char (*v8) (unsigned char, signed short, signed char, signed char);
extern signed int v9 (signed short, signed int, signed short, signed int);
extern signed int (*v10) (signed short, signed int, signed short, signed int);
extern unsigned int v11 (signed char);
extern unsigned int (*v12) (signed char);
extern signed short v13 (signed short, signed short);
extern signed short (*v14) (signed short, signed short);
extern signed char v15 (void);
extern signed char (*v16) (void);
extern signed int v17 (void);
extern signed int (*v18) (void);
extern signed int v19 (void);
extern signed int (*v20) (void);
extern unsigned short v21 (signed char);
extern unsigned short (*v22) (signed char);
extern signed char v23 (unsigned char, signed char);
extern signed char (*v24) (unsigned char, signed char);
extern signed short v25 (unsigned char);
extern signed short (*v26) (unsigned char);
extern unsigned short v27 (signed int, signed short, signed short, unsigned int);
extern unsigned short (*v28) (signed int, signed short, signed short, unsigned int);
extern int history[];
extern int history_index;
extern int trace;
signed int v129 = 1;
signed char v128 = 1;
unsigned char v127 = 5;
