integer*1,parameter::a=8
integer*2,parameter::b=8
integer*4,parameter::c=8
integer*8,parameter::d=8
integer*1,parameter::e=1
integer*2,parameter::j=1
integer*4,parameter::k=1
integer*8,parameter::l=1
integer,parameter::f=maskl(a,e)
integer,parameter::g=maskl(b,j)
integer,parameter::h=maskl(c,k)
integer,parameter::i=maskl(d,l)
if(f.ne.-1)print*,"100"
if(g.ne.-1)print*,"101"
if(h.ne.-1)print*,"101"
if(i.ne.-1)print*,"101"
print*,"PASS"
end

