	integer*1,parameter::i1=70
	integer*2,parameter::i2=70
	integer*2,parameter::it=z'ff00'
	print *,btest(i1,0)
	print *,btest(i1,1)
	print *,btest(i1,2)
	print *,btest(i1,3)
	print *,btest(i1,4)
	print *,btest(i1,5)
	print *,btest(i1,6)
	print *,btest(i1,7)
	print *,btest(i2,0)
	print *,btest(i2,1)
	print *,btest(i2,2)
	print *,btest(i2,3)
	print *,btest(i2,4)
	print *,btest(i2,5)
	print *,btest(i2,6)
	print *,btest(i2,7)
	print *,btest(it,8)
	print *,btest(it,9)
	print *,btest(it,10)
	print *,btest(it,11)
	print *,btest(it,12)
	print *,btest(it,13)
	print *,btest(it,14)
	print *,btest(it,15)
	print *,btest(it,0)
	print *,btest(it,15)
	end
