SUBROUTINE TEST(DATA1,DATA2,DATA3,B,N,FLAG)
  REAL(KIND=8),DIMENSION(1:N) :: DATA1,DATA2,DATA3,B,C,D
  INTEGER(KIND=4) :: I,N
  LOGICAL(KIND=1) :: FLAG
  C=0.0_8; D=0.0_8
  DO I=1,N
    DATA1(I)=DATA1(I)+B(I)
  END DO
  IF (FLAG.EQV..TRUE.) THEN
     C=DATA1
  END IF
  DO I=1,N
    DATA2(I)=DATA2(I)+C(I)
  END DO
  IF (FLAG.EQV..TRUE.) THEN
     D=DATA2
  END IF
  DO I=1,N
    DATA3(I)=DATA3(I)+D(I)
  END DO
END SUBROUTINE TEST

PROGRAM MAIN
  REAL(KIND=8),DIMENSION(64) :: DATA1,DATA2,DATA3,TEMP1,TEMP2,TEMP3,B
  B=1.0_8
  DATA1=RESHAPE((/(I,I=1,64)/),(/64/))
  DATA2=DATA1+1.0_8
  DATA3=DATA2+1.0_8
  TEMP1=DATA2
  TEMP2=DATA2
  TEMP3=DATA3
  CALL TEST(DATA1,DATA2,DATA3,B,64_4,.FALSE._1)
  IF (ANSWER_CHECK(DATA1,TEMP1).NE.0 .OR. &
      ANSWER_CHECK(DATA2,TEMP2).NE.0 .OR. &
      ANSWER_CHECK(DATA3,TEMP3).NE.0) THEN
     PRINT *, "NG"
  ELSE
     PRINT *, "OK"
  END IF  
END PROGRAM MAIN

FUNCTION ANSWER_CHECK(RES,MASTER)
  REAL(KIND=8),DIMENSION(64) :: RES,MASTER
  ANSWER_CHECK = 0
  DO I=1,64
     IF (RES(I).NE.MASTER(I)) THEN
        ANSWER_CHECK = 1
        PRINT *, RES(I),MASTER(I)
        RETURN
     END IF
  END DO
END FUNCTION ANSWER_CHECK
