SUBROUTINE TEST(D1,D2,D3,B,N)
  REAL(KIND=8),DIMENSION(1:N) :: D1,D2,D3,B
  INTEGER(KIND=4) :: I
  INTEGER(KIND=4),INTENT(IN) :: N
  DO I=1,N,2
    D1(I)=D1(I)+B(I)
  END DO
  DO I=1,N,3
    D2(I)=D2(I)+B(I)
  END DO
  DO I=1,N,4
    D3(I)=D3(I)+B(I)
  END DO
END SUBROUTINE TEST

PROGRAM MAIN
  REAL(KIND=8),DIMENSION(64) :: D1/64*1.0_8/,D2/64*1.0_8/,D3/64*1.0_8/,B/64*1.0_8/
  CALL TEST(D1,D2,D3,B,64_4)
  IF (ANSWER_CHECK(D1,2_4).NE.0 .OR. &
      ANSWER_CHECK(D2,3_4).NE.0 .OR. &
      ANSWER_CHECK(D3,4_4).NE.0) THEN
     PRINT *, "NG"
  ELSE
     PRINT *, "OK"
  END IF  
END PROGRAM MAIN

FUNCTION ANSWER_CHECK(RES,VAL)
  REAL(KIND=8),DIMENSION(64) :: RES
  REAL(KIND=8) :: MASTER
  INTEGER(KIND=4) :: VAL
  ANSWER_CHECK = 0
  DO I=1,64
     IF(MOD(I-1,VAL).EQ.0) THEN
        MASTER=2.0_4
     ELSE
        MASTER=1.0_4
     END IF
     IF (RES(I).NE.MASTER) THEN
        ANSWER_CHECK = 1
        PRINT *, RES(I),MASTER,I
        RETURN
     END IF
  END DO
END FUNCTION ANSWER_CHECK
