SUBROUTINE TEST_1(DATA1,DATA2,DATA3,B,N)
  REAL(KIND=8),DIMENSION(1:N) :: DATA1,DATA2,DATA3
  REAL(KIND=8),DIMENSION(1:N,1:N) :: B
  INTEGER(KIND=4) :: I,N,M
  M=1
  DO I=1,N
    DATA1(I)=DATA1(I)+B(I,M)
    M=MOD(M+I,N)+1
  END DO
  DO I=1,N
    DATA2(I)=DATA2(I)+B(I,M)
    M=MOD(M+I,N)+1
  END DO
  DO I=1,N
    DATA3(I)=DATA3(I)+B(I,M)
    M=MOD(M+I,N)+1
  END DO
END SUBROUTINE TEST_1

SUBROUTINE TEST_2(DATA1,DATA2,DATA3,B,N,M)
  REAL(KIND=8),DIMENSION(1:N) :: DATA1,DATA2,DATA3
  REAL(KIND=8),DIMENSION(1:N,1:N) :: B
  INTEGER(KIND=4) :: I,N,M
  DO I=1,N
    DATA1(I)=DATA1(I)+B(I,M)
    M=MOD(M+I,N)+1
  END DO
  DO I=1,N
    DATA2(I)=DATA2(I)+B(I,M)
    M=MOD(M+I,N)+1
  END DO
  DO I=1,N
    DATA3(I)=DATA3(I)+B(I,M)
    M=MOD(M+I,N)+1
  END DO
END SUBROUTINE TEST_2

PROGRAM MAIN
  REAL(KIND=8),DIMENSION(64) :: DATA1/64*1.0_8/,DATA2/64*1.0_8/,DATA3/64*1.0_8/
  REAL(KIND=8),DIMENSION(64) :: TEMP1,TEMP2,TEMP3
  REAL(KIND=8),DIMENSION(64,64) :: B/4096*1.0_8/
  INTEGER(KIND=4) :: M/1_4/
  TEMP1=DATA1+1.0_8
  TEMP2=DATA2+1.0_8
  TEMP3=DATA3+1.0_8
  CALL TEST_1(DATA1,DATA2,DATA3,B,64_4)
  IF (ANSWER_CHECK(DATA1,TEMP1).NE.0 .OR. &
      ANSWER_CHECK(DATA2,TEMP2).NE.0 .OR. &
      ANSWER_CHECK(DATA3,TEMP3).NE.0) THEN
     PRINT *, "NG"
  ELSE
     PRINT *, "OK"
  END IF  
  TEMP1=DATA1+1.0_8
  TEMP2=DATA2+1.0_8
  TEMP3=DATA3+1.0_8
  CALL TEST_2(DATA1,DATA2,DATA3,B,64_4,M)
  IF (ANSWER_CHECK(DATA1,TEMP1).NE.0 .OR. &
      ANSWER_CHECK(DATA2,TEMP2).NE.0 .OR. &
      ANSWER_CHECK(DATA3,TEMP3).NE.0) THEN
     PRINT *, "NG"
  ELSE
     PRINT *, "OK"
  END IF  
END PROGRAM MAIN

FUNCTION ANSWER_CHECK(RES,MASTER)
  REAL(KIND=8),DIMENSION(64) :: RES,MASTER
  ANSWER_CHECK = 0
  DO I=1,64
     IF (RES(I).NE.MASTER(I)) THEN
        ANSWER_CHECK = 1
        PRINT *, RES(I),MASTER(I),I
        RETURN
     END IF
  END DO
END FUNCTION ANSWER_CHECK
