MODULE FT
  TYPE FTYPE
     REAL(KIND=8) :: F,G
  END TYPE FTYPE
END MODULE FT

SUBROUTINE TEST_1(D1,D2)
  USE FT
  TYPE(FTYPE),DIMENSION(1:65) :: D1,D2
  INTEGER(KIND=4) :: I
  DO I=1,64
    D1(I)%F=D1(I)%F+D1(1)%F
  END DO
  DO I=1,64
    D2(I)%F=D2(I)%F+D2(1)%F
  END DO
END SUBROUTINE TEST_1

SUBROUTINE TEST_2(D1,D2)
  USE FT
  TYPE(FTYPE),DIMENSION(1:65) :: D1,D2
  INTEGER(KIND=4) :: I
  DO I=1,64
    D1(I)%F=D1(I)%F+D1(65)%F
  END DO
  DO I=1,64
    D2(I)%F=D2(I)%F+D2(65)%F
  END DO
END SUBROUTINE TEST_2

PROGRAM MAIN
  USE FT
  TYPE(FTYPE),DIMENSION(65) :: D1=FTYPE(1.0_8,1.0_8),D2
  D2=FTYPE(1.0_8,1.0_8)
  CALL TEST_1(D1,D2)
  IF (ANSWER_CHECK(D1,3.0_8).NE.0 .OR. &
      ANSWER_CHECK(D2,3.0_8).NE.0) THEN
     PRINT *, "NG"
  ELSE
     PRINT *, "OK"
  END IF  
  CALL TEST_2(D1,D2)
  IF (ANSWER_CHECK(D1,4.0_8).NE.0 .OR. &
      ANSWER_CHECK(D2,4.0_8).NE.0) THEN
     PRINT *, "NG"
  ELSE
     PRINT *, "OK"
  END IF  
END PROGRAM MAIN

FUNCTION ANSWER_CHECK(RES,MASTER)
  USE FT
  TYPE(FTYPE),DIMENSION(65) :: RES
  REAL(KIND=8) :: MASTER
  ANSWER_CHECK = 0
  DO I=2,64
     IF (RES(I)%F.NE.MASTER) THEN
        ANSWER_CHECK = 1
        PRINT *, RES(I)%F,MASTER,I
        RETURN
     END IF
  END DO
END FUNCTION ANSWER_CHECK
