MODULE FT
  TYPE FTYPE
     REAL(KIND=8) :: F
  END TYPE FTYPE
END MODULE FT

SUBROUTINE TEST_1(P1,P2,N,M)
  USE FT
  TYPE(FTYPE),POINTER,DIMENSION(:) :: P1,P2
  INTEGER(KIND=4) :: I
  INTEGER(KIND=4),INTENT(IN) :: N,M
  DO I=1,N
    P1(I)%F=P1(I)%F+P1(M)%F
  END DO
  DO I=1,N-1
    P2(I)%F=P2(I)%F+P2(M)%F
  END DO
END SUBROUTINE TEST_1

SUBROUTINE TEST_2(P1,P2,N)
  USE FT
  TYPE(FTYPE),POINTER,DIMENSION(:) :: P1,P2
  INTEGER(KIND=4) :: I
  INTEGER(KIND=4),INTENT(IN) :: N
  DO I=1,N
    P1(I)%F=P1(I)%F+P1(N+1)%F
  END DO
  DO I=1,N-1
    P2(I)%F=P2(I)%F+P2(N+1)%F
  END DO
END SUBROUTINE TEST_2

PROGRAM MAIN
  USE FT
  TYPE(FTYPE),DIMENSION(65),TARGET :: D1=FTYPE(1.0_8)
  TYPE(FTYPE),POINTER,DIMENSION(:) :: P1,P2
  INTERFACE 
     SUBROUTINE TEST_1(P1,P2,N,M)
       USE FT
       TYPE(FTYPE),POINTER,DIMENSION(:) :: P1,P2
       INTEGER(KIND=4),INTENT(IN) :: N,M
     END SUBROUTINE TEST_1
     SUBROUTINE TEST_2(P1,P2,N)
       USE FT
       TYPE(FTYPE),POINTER,DIMENSION(:) :: P1,P2
       INTEGER(KIND=4),INTENT(IN) :: N
     END SUBROUTINE TEST_2
  END INTERFACE
  P1=>D1
  P2=>D1
  CALL TEST_1(P1,P2,64_4,65_4)
  IF (ANSWER_CHECK(D1,3.0_8).NE.0) THEN
     PRINT *, "NG"
  ELSE
     PRINT *, "OK"
  END IF  
  CALL TEST_2(P1,P2,64_4)
  IF (ANSWER_CHECK(D1,5.0_8).NE.0) THEN
     PRINT *, "NG"
  ELSE
     PRINT *, "OK"
  END IF  
END PROGRAM MAIN

FUNCTION ANSWER_CHECK(RES,MASTER)
  USE FT
  TYPE(FTYPE),DIMENSION(65) :: RES
  REAL(KIND=8) :: MASTER
  ANSWER_CHECK = 0
  DO I=1,63
     IF (RES(I)%F.NE.MASTER) THEN
        ANSWER_CHECK = 1
        PRINT *, RES(I)%F,MASTER,I
        RETURN
     END IF
  END DO
END FUNCTION ANSWER_CHECK
