MODULE FT
  TYPE FTYPE
     REAL(KIND=8) :: F
  END TYPE FTYPE
END MODULE FT

SUBROUTINE TEST_1(P1,P2,P3,D1,D2,D3,N,M)
  USE FT
  TYPE(FTYPE),POINTER,DIMENSION(:) :: P1,P2,P3
  TYPE(FTYPE),DIMENSION(1:N+3) :: D1,D2,D3
  INTEGER(KIND=4) :: I
  INTEGER(KIND=4),INTENT(IN) :: N,M
  DO I=1,N
    P1(I)%F=P1(I)%F+D1(M)%F
  END DO
  DO I=1,N-1
    P2(I)%F=P2(I)%F+D2(M+1)%F
  END DO
  DO I=1,N
    P3(I)%F=P3(I)%F+D3(M+2)%F
  END DO
END SUBROUTINE TEST_1

SUBROUTINE TEST_2(P1,P2,P3,D1,D2,D3,N)
  USE FT
  TYPE(FTYPE),POINTER,DIMENSION(:) :: P1,P2,P3
  TYPE(FTYPE),DIMENSION(1:N+3) :: D1,D2,D3
  INTEGER(KIND=4) :: I
  INTEGER(KIND=4),INTENT(IN) :: N
  DO I=1,N
    P1(I)%F=P1(I)%F+D1(N+1)%F
  END DO
  DO I=1,N-1
    P2(I)%F=P2(I)%F+D2(N+1)%F
  END DO
  DO I=1,N
    P3(I)%F=P3(I)%F+D3(N+1)%F
  END DO
END SUBROUTINE TEST_2

SUBROUTINE TEST_3(D1,D2,D3,N)
  USE FT
  TYPE(FTYPE),POINTER,DIMENSION(:) :: P1,P2,P3
  TYPE(FTYPE),DIMENSION(1:N+3),TARGET :: D1,D2,D3
  INTEGER(KIND=4) :: I
  INTEGER(KIND=4),INTENT(IN) :: N
  P1=>D1
  P2=>D2
  P3=>D3
  DO I=1,N
    P1(I)%F=P1(I)%F+D1(65)%F
  END DO
  DO I=1,N-1
    P2(I)%F=P2(I)%F+D2(66)%F
  END DO
  DO I=1,N
    P3(I)%F=P3(I)%F+D3(67)%F
  END DO
END SUBROUTINE TEST_3

PROGRAM MAIN
  USE FT
  TYPE(FTYPE),DIMENSION(67),TARGET :: D1=FTYPE(1.0_8),D2,D3
  TYPE(FTYPE),POINTER,DIMENSION(:) :: P1,P2,P3
  INTERFACE 
     SUBROUTINE TEST_1(P1,P2,P3,D1,D2,D3,N,M)
       USE FT
       TYPE(FTYPE),POINTER,DIMENSION(:) :: P1,P2,P3
       TYPE(FTYPE),DIMENSION(1:N+1) :: D1,D2,D3
       INTEGER(KIND=4),INTENT(IN) :: N,M
     END SUBROUTINE TEST_1
     SUBROUTINE TEST_2(P1,P2,P3,D1,D2,D3,N)
       USE FT
       TYPE(FTYPE),POINTER,DIMENSION(:) :: P1,P2,P3
       TYPE(FTYPE),DIMENSION(1:N+1) :: D1,D2,D3
       INTEGER(KIND=4),INTENT(IN) :: N
     END SUBROUTINE TEST_2
     SUBROUTINE TEST_3(D1,D2,D3,N)
       USE FT
       TYPE(FTYPE),POINTER,DIMENSION(:) :: P1,P2,P3
       TYPE(FTYPE),DIMENSION(1:N+1),TARGET :: D1,D2,D3
       INTEGER(KIND=4) :: I
       INTEGER(KIND=4),INTENT(IN) :: N
     END SUBROUTINE TEST_3
  END INTERFACE
  D2=FTYPE(1.0_8)
  D3=FTYPE(1.0_8)
  P1=>D1
  P2=>D2
  P3=>D3
  CALL TEST_1(P1,P2,P3,D1,D2,D3,64_4,65_4)
  IF (ANSWER_CHECK(D1,2.0_8).NE.0 .OR. &
      ANSWER_CHECK(D2,2.0_8).NE.0 .OR. &
      ANSWER_CHECK(D3,2.0_8).NE.0) THEN
     PRINT *, "NG"
  ELSE
     PRINT *, "OK"
  END IF  
  CALL TEST_2(P1,P2,P3,D1,D2,D3,64_4)
  IF (ANSWER_CHECK(D1,3.0_8).NE.0 .OR. &
      ANSWER_CHECK(D2,3.0_8).NE.0 .OR. &
      ANSWER_CHECK(D3,3.0_8).NE.0) THEN
     PRINT *, "NG"
  ELSE
     PRINT *, "OK"
  END IF  
  CALL TEST_3(D1,D2,D3,64_4)
  IF (ANSWER_CHECK(D1,4.0_8).NE.0 .OR. &
      ANSWER_CHECK(D2,4.0_8).NE.0 .OR. &
      ANSWER_CHECK(D3,4.0_8).NE.0) THEN
     PRINT *, "NG"
  ELSE
     PRINT *, "OK"
  END IF  
END PROGRAM MAIN

FUNCTION ANSWER_CHECK(RES,MASTER)
  USE FT
  TYPE(FTYPE),DIMENSION(67) :: RES
  REAL(KIND=8) :: MASTER
  ANSWER_CHECK = 0
  DO I=1,63
     IF (RES(I)%F.NE.MASTER) THEN
        ANSWER_CHECK = 1
        PRINT *, RES(I)%F,MASTER,I
        RETURN
     END IF
  END DO
END FUNCTION ANSWER_CHECK
