SUBROUTINE TEST(D1,B,C,N,M)
  REAL(KIND=8),DIMENSION(1:N) :: D1,B
  INTEGER(KIND=4) :: I
  INTEGER(KIND=4),INTENT(IN) :: N,M
  INTEGER(KIND=4),DIMENSION(4) :: C
  DO I=-10+M+SUM(C),64
    D1(I)=D1(I)+B(I)
  END DO
END SUBROUTINE TEST

PROGRAM MAIN
  INTEGER(KIND=4),DIMENSION(4) :: C/1,2,3,4/
  REAL(KIND=8),DIMENSION(64) :: D1/64*1.0_8/,B/64*1.0_8/
  REAL(KIND=8),DIMENSION(64) :: TEMP1
  TEMP1=D1+1.0_8
  CALL TEST(D1,B,C,64_4,1_4)
  IF (ANSWER_CHECK(D1,TEMP1).NE.0) THEN
     PRINT *, "NG"
  ELSE
     PRINT *, "OK"
  END IF  
END PROGRAM MAIN

FUNCTION ANSWER_CHECK(RES,MASTER)
  REAL(KIND=8),DIMENSION(64) :: RES,MASTER
  ANSWER_CHECK = 0
  DO I=1,64
     IF (RES(I).NE.MASTER(I)) THEN
        ANSWER_CHECK = 1
        PRINT *, RES(I),MASTER(I),I
        RETURN
     END IF
  END DO
END FUNCTION ANSWER_CHECK
