SUBROUTINE TEST(D1,N,M)
  REAL(KIND=8),DIMENSION(1:N) :: D1
  INTEGER(KIND=4) :: I
  INTEGER(KIND=4),INTENT(IN) :: N,M
  DO I=1,N
    D1(I)=D1(I)+D1(M)
  END DO
END SUBROUTINE TEST

PROGRAM MAIN
  REAL(KIND=8),DIMENSION(64) :: D1/64*1.0_8/
  CALL TEST(D1,64_4,1_4)
  IF (ANSWER_CHECK(D1).NE.0) THEN
     PRINT *, "NG"
  ELSE
     PRINT *, "OK"
  END IF  
END PROGRAM MAIN

FUNCTION ANSWER_CHECK(RES)
  REAL(KIND=8),DIMENSION(64) :: RES
  REAL(KIND=8) :: MASTER
  ANSWER_CHECK = 0
  DO I=1,64
     IF(I.EQ.1) THEN
        MASTER=2.0_4
     ELSE
        MASTER=3.0_4
     END IF
     IF (RES(I).NE.MASTER) THEN
        ANSWER_CHECK = 1
        PRINT *, RES(I),MASTER,I
        RETURN
     END IF
  END DO
END FUNCTION ANSWER_CHECK
