SUBROUTINE TEST_1(D1,D2,B,N,X)
  REAL(KIND=8),DIMENSION(1:N) :: D1,D2,B,X
  INTEGER(KIND=4) :: I,N
  DO I=1,N
    B(I)=B(I)+D1(I)
  END DO
  X(1) = 1
  DO I=1,N
    B(I)=B(I)+D2(I)
  END DO
END SUBROUTINE TEST_1

PROGRAM MAIN
  REAL(KIND=8),DIMENSION(64) :: D1/64*1.0_8/,D3/64*1.0_8/,B/64*1.0_8/,X/64*1_8/
  REAL(KIND=8),DIMENSION(64) :: TEMP1
  TEMP1=B+2.0_8
  CALL TEST_1(D1,D3,B,64_4,X)
  IF (ANSWER_CHECK(B,TEMP1).NE.0) THEN
     PRINT *, "NG"
  ELSE
     PRINT *, "OK"
  END IF  
END PROGRAM MAIN

FUNCTION ANSWER_CHECK(RES,MASTER)
  REAL(KIND=8),DIMENSION(64) :: RES,MASTER
  ANSWER_CHECK = 0
  DO I=1,64
     IF (RES(I).NE.MASTER(I)) THEN
        ANSWER_CHECK = 1
        PRINT *, RES(I),MASTER(I),I
        RETURN
     END IF
  END DO
END FUNCTION ANSWER_CHECK
