SUBROUTINE TEST(DATA1,DATA2,B,N)
  INTEGER(KIND=8) :: I,J,N
  REAL(KIND=8),DIMENSION(1:N,1:N) :: DATA1,DATA2,B
  DO I=2,N
     DO J=1,N
       DATA1(J,I)=DATA1(J,I-1)+B(J,I)
     END DO
  END DO
  DO I=2,N
     DO J=1,N
       DATA2(J,I)=DATA2(J,I-1)+B(J,I)
     END DO
  END DO
END SUBROUTINE TEST

PROGRAM MAIN
  REAL(KIND=8),DIMENSION(64,64) :: DATA1,DATA2,B
  REAL(KIND=8),DIMENSION(64) :: TEMP1,TEMP2
  B=1.0_8
  DATA1=RESHAPE((/(I,I=1,4096)/),(/64,64/))
  DATA2=DATA1+1.0_8
  TEMP1=RESHAPE((/(I,I=1,64)/),(/64/))
  TEMP2=TEMP1+1.0_8
  CALL TEST(DATA1,DATA2,B,64_8)
  IF (ANSWER_CHECK(DATA1,TEMP1).NE.0 .OR. &
      ANSWER_CHECK(DATA2,TEMP2).NE.0) THEN
     PRINT *, "NG"
  ELSE
     PRINT *, "OK"
  END IF
END PROGRAM MAIN

FUNCTION ANSWER_CHECK(RES,MASTER)
  REAL(KIND=8),DIMENSION(64,64) :: RES
  REAL(KIND=8),DIMENSION(64) :: MASTER
  REAL(KIND=8) :: TEMP
  ANSWER_CHECK = 0
  DO I=2,64
     TEMP=MASTER(I)
     DO J=1,64
        IF (RES(J,I).NE.TEMP) THEN
           ANSWER_CHECK = 1
           PRINT *, RES(J,I),TEMP,J,I
           RETURN
        END IF
        TEMP=TEMP+1.0_8
     END DO
  END DO
END FUNCTION ANSWER_CHECK
