#ifndef __CPP11_TEST_HEADER_CONFIG_H__
#define __CPP11_TEST_HEADER_CONFIG_H__

#define PASS_CASE_RUN_OK_INFO "ok"
#define FAIL_CASE_RUN_OK_INFO "should not compile success"

#define _HAS_CXX11_RVALUE_REFERENCE
#define _HAS_CXX11_VARIADIC_TEMPLATE
#define _HAS_CXX11_STATIC_ASSERT
#define _HAS_CXX11_AUTO_TYPE
#define _HAS_CXX11_LAMBDAS_EXPRESSION
#define _HAS_CXX11_DECLTYPE
#define _HAS_CXX11_RIGHT_ANGLE_BRACKETS
#define _HAS_CXX11_DEF_TMPL_ARGS_FOR_FUN_TMPL
#define _HAS_CXX11_ADVANCED_SFINAE
#define _HAS_CXX11_TEMPLATE_ALIAS
#define _HAS_CXX11_EXTERN_TEMPLATE
#define _HAS_CXX11_NULLPTR
#define _HAS_CXX11_STRONG_ENUMS
#define _HAS_CXX11_DEFAULTED_FUNCTIONS
#define _HAS_CXX11_DELETED_FUNCTIONS
#define _HAS_CXX11_EXTENDED_FRIEND
#define _HAS_CXX11_LOCAL_UNNAMED_TYPE_AS_ARG
#define _HAS_CXX11_RANGE_BASED_FOR





#define _HAS_CXX11_MOVE_SPECIAL_MEMBER_FUNCTIONS


#endif 
