MODULE M
  TYPE T
      INTEGER::A
     CONTAINS 
        PROCEDURE::SUB
        GENERIC::WRITE(FORMATTED)=>SUB
END TYPE T
CHARACTER(14) :: CH
  INTEGER :: VV
character(500)::C 

CONTAINS
SUBROUTINE SUB (DTV, UNIT, IOTYPE, V_LIST, IOSTAT,IOMSG)
    CLASS(T), INTENT(IN)            :: DTV
    INTEGER, INTENT(IN)            :: UNIT
    CHARACTER(LEN=*), INTENT(IN)    :: IOTYPE
    INTEGER, INTENT(IN)             :: V_LIST (:)
    INTEGER, INTENT(OUT)            :: IOSTAT
    CHARACTER(LEN=*), INTENT(INOUT) :: IOMSG
    integer ::x
    x=unit
    IF(SIZE(V_LIST)/=0) THEN
stop 99
      ELSE
        VV=DTV%A
        WRITE(C,*,IOSTAT=IOSTAT,IOMSG=IOMSG) DTV%A+1,IOTYPE
      END IF
END SUBROUTINE SUB

END MODULE M

PROGRAM MAIN

USE M
TYPE(T)::OBJW
CHARACTER(500)::D
NAMELIST /LIST1/OBJW
OBJW%A=4

     WRITE(D,NML=LIST1)

 PRINT*,'pass'
END PROGRAM

