       SUBROUTINE SUB(CHX,CHZ,CHY)
       CHARACTER   CH3*3,CHA*5,CHX*(*),CHZ*(*),DEF*(*),AD*(*),CHY*(*)
       PARAMETER  (DEF='DEF',AD='')
       PARAMETER  (I1=1,I2=2,I3=3,I4=4,I5=5,I10=10)
       CH3='DEF'
       CHA(2:5)='ABC'
       CALL S1(3, (/ 'ABC' , ((/ DEF//AD  /) ,IJK=1,4) /) )
       CALL S1(3, (/ 'ABC' , ((/ CH3//AD /) ,IJK=1,4) /) )
       CALL S1(3, (/ 'ABC' ,((/  DEF//AD  /) ,IJK=1,I4) /) )
       CALL S1(3, (/ 'ABC' ,((/ CH3//AD /) ,IJK=1,I4) /) )
       CALL S1(3, (/ CHA(I2:I4) , ((/ DEF//AD  /) ,IJK=1,4) /) )
       CALL S1(3, (/ CHA(I2:I4) , ((/ CH3//AD /) ,IJK=1,4) /) )
       CALL S1(3, (/ CHA(I2:I4) ,((/  DEF//AD  /) ,IJK=1,I4) /) )
       CALL S1(3, (/ CHA(I2:I4) ,((/ CH3//AD /) ,IJK=1,I4) /) )
       CALL S1(3, (/ CHX       , ((/ DEF//AD  /) ,IJK=1,4) /) )
       CALL S1(3, (/ CHX       , ((/ CH3//AD /) ,IJK=1,4) /) )
       CALL S1(3, (/ CHX       ,((/  DEF//AD  /) ,IJK=1,I4) /) )
       CALL S1(3, (/ CHX       ,((/ CH3//AD /) ,IJK=1,I4) /) )
       CALL S1(3, (/ 'ABC'     , ((/ CH3(I1:I3)//AD /) ,IJK=1,4) /) )
       CALL S1(3, (/ 'ABC'     ,((/ CH3(I1:I3)//AD /) ,IJK=1,I4) /) )
       CALL S1(3, (/ CHA(I2:I4) , ((/ CH3(I1:I3)//AD /) ,IJK=1,4) /) )
       CALL S1(3, (/ CHA(I2:I4) ,((/ CH3(I1:I3)//AD /) ,IJK=1,I4) /) )
       CALL S1(3, (/ CHX       , ((/ CH3(I1:I3)//AD /) ,IJK=1,4) /) )
       CALL S1(3, (/ CHX       ,((/ CH3(I1:I3)//AD /) ,IJK=1,I4) /) )
       CALL S1(3, (/ 'ABC'     , ((/ CHZ//AD      /) ,IJK=1,4) /) )
       CALL S1(3, (/ 'ABC'     ,((/ CHZ//AD    /) ,IJK=1,I4) /) )
       CALL S1(3, (/ CHA(I2:I4) , ((/ CHZ//AD   /) ,IJK=1,4) /) )
       CALL S1(3, (/ CHA(I2:I4) ,((/ CHZ//AD   /) ,IJK=1,I4) /) )
       CALL S1(3, (/ CHX       , ((/ CHZ//AD    /) ,IJK=1,4) /) )
       CALL S1(3, (/ CHX       ,((/ CHZ//AD    /) ,IJK=1,I4) /) )
       CALL S1(3, (/ 'ABC' , ((/ DEF//CHY(1:0) /) ,IJK=1,4) /) )
       CALL S1(3, (/ 'ABC' , ((/ CH3//CHY(1:0) /) ,IJK=1,4) /) )
       CALL S1(3, (/ 'ABC' ,((/  DEF//CHY(1:0)  /) ,IJK=1,I4) /) )
       CALL S1(3, (/ 'ABC' ,((/ CH3//CHY(1:0) /) ,IJK=1,I4) /) )
       CALL S1(3, (/ CHA(I2:I4) , ((/ DEF//CHY(1:0)  /) ,IJK=1,4) /) )
       CALL S1(3, (/ CHA(I2:I4) , ((/ CH3//CHY(1:0) /) ,IJK=1,4) /) )
       CALL S1(3, (/ CHA(I2:I4) ,((/  DEF//CHY(1:0)  /) ,IJK=1,I4) /) )
       CALL S1(3, (/ CHA(I2:I4) ,((/ CH3//CHY(1:0) /) ,IJK=1,I4) /) )
       CALL S1(3, (/ CHX       , ((/ DEF//CHY(1:0)  /) ,IJK=1,4) /) )
       CALL S1(3, (/ CHX       , ((/ CH3//CHY(1:0) /) ,IJK=1,4) /) )
       CALL S1(3, (/ CHX       ,((/  DEF//CHY(1:0)  /) ,IJK=1,I4) /) )
       CALL S1(3, (/ CHX       ,((/ CH3//CHY(1:0) /) ,IJK=1,I4) /) )
       CALL S1(3, (/ 'ABC' , ((/ CH3(I1:I3)//CHY(1:0) /) ,IJK=1,4) /) )
       CALL S1(3, (/ 'ABC' ,((/ CH3(I1:I3)//CHY(1:0) /) ,IJK=1,I4) /) )
       CALL S1(3, (/ CHA(I2:I4),((/ CH3(I1:I3)//CHY(1:0)/),IJK=1,4) /) )
       CALL S1(3, (/ CHA(I2:I4) ,((/ CH3(I1:I3)//CHY(1:0)/),IJK=1,I4)/))
       CALL S1(3, (/ CHX  , ((/ CH3(I1:I3)//CHY(1:0) /) ,IJK=1,4) /) )
       CALL S1(3, (/ CHX  ,((/ CH3(I1:I3)//CHY(1:0) /) ,IJK=1,I4) /) )
       CALL S1(3, (/ 'ABC'  , ((/ CHZ//CHY(1:0)      /) ,IJK=1,4) /) )
       CALL S1(3, (/ 'ABC'  ,((/ CHZ//CHY(1:0)    /) ,IJK=1,I4) /) )
       CALL S1(3, (/ CHA(I2:I4) , ((/ CHZ//CHY(1:0)   /) ,IJK=1,4) /) )
       CALL S1(3, (/ CHA(I2:I4) ,((/ CHZ//CHY(1:0)   /) ,IJK=1,I4) /) )
       CALL S1(3, (/ CHX       , ((/ CHZ//CHY(1:0)    /) ,IJK=1,4) /) )
       CALL S1(3, (/ CHX       ,((/ CHZ//CHY(1:0)    /) ,IJK=1,I4) /) )
       PRINT *,' PASS'
       END
       SUBROUTINE S1(I,X)
       CHARACTER*(*) X(5)
       IF (LEN(X).NE.I) PRINT *,'FAIL'
       IF (X(1).NE.'ABC') PRINT *,'FAIL'
       DO 1 J=2,5
         IF (X(J).NE.'DEF') PRINT *,'FAIL'
   1   CONTINUE
       END
       CALL SUB('ABC','DEF','??????')
       END
