#include <stdio.h>
#include <math.h>

double		SQR3I;			
double		SQR3I2;			
double*		Zp;			
double*		HP;			
double**	ERP;

int main() {
  printf("ok\n");
}

int ovpDDD(int* this, int np, double* px, double* py, double* pz,	double* pax, double* pay, double* paz,	double* pbx, double* pby, double* pbz, double Gamma,	double cx, double cy, double cz, double cc) {
  long	i;
  double	hc, RZG, Roo, t;
  double	pcx, pcy, pcz;
  double	Gax, Gay, Gaz;
  double	Gbx, Gby, Gbz;
  double	Gcx, Gcy, Gcz;
  double	Gx, Gy, Gz;
  double	ABx, ABy, ABz;
  double	sss;
  double	Rsss;
  double	RZGP5;
  double	xss, yss, zss;
  double	sxs, sys, szs;
  double	ass, bss, css, dss, ess;
  double	xxssww, yyssww;
  double	Rxss, Ryss, Rzss;
  double	xxs, xys, xzs;
  double	yxs, yys, yzs;
  double	zxs, zys, zzs;
  double	Rxxs, Rxys, Rxzs;
  double	Ryxs, Ryys, Ryzs;
  double	Rzxs, Rzys, Rzzs;
  double	x2ss, y2ss, z2ss;
  double	x2xs, y2ys, z2zs;
  double	axs, ays, azs;
  double	bxs, bys, bzs;
  double	cxs, cys, czs;
  double	dxs, dys, dzs;
  double	exs, eys, ezs;
  double	axxsw, ayysw, azzsw;
  double	bxxsw, byysw, bzzsw;
  double	cxxsw, cyysw, czzsw;
  double	dxxsw, dyysw, dzzsw;
  double	exxsw, eyysw, ezzsw;
  double	xas, xbs, xcs, xds, xes;
  double	yas, ybs, ycs, yds, yes;
  double	zas, zbs, zcs, zds, zes;
  double	Rass, Rbss, Rcss, Rdss, Ress;
  double	axx, axy, axz, ayx, ayy, ayz, azx, azy, azz;
  double	bxx, bxy, bxz, byx, byy, byz, bzx, bzy, bzz;
  double	cxx, cxy, cxz, cyx, cyy, cyz, czx, czy, czz;
  double	dxx, dxy, dxz, dyx, dyy, dyz, dzx, dzy, dzz;
  double	exx, exy, exz, eyx, eyy, eyz, ezx, ezy, ezz;
  double	aas, abs, acs, ads, aes;
  double	bas, bbs, bcs, bds, bes;
  double	cas, cbs, ccs, cds, ces;
  double	das, dbs, dcs, dds, des;
  double	eas, ebs, ecs, eds, ees;
  double	Raxs, Rays, Razs;
  double	Rbxs, Rbys, Rbzs;
  double	Rcxs, Rcys, Rczs;
  double	Rdxs, Rdys, Rdzs;
  double	Rexs, Reys, Rezs;
  double	Rxas, Rxbs, Rxcs, Rxds, Rxes;
  double	Ryas, Rybs, Rycs, Ryds, Ryes;
  double	Rzas, Rzbs, Rzcs, Rzds, Rzes;
  double	sas, sbs, scs, sds, ses;
  double	sx2s, sy2s, sz2s;
  double	Rsas, Rsbs, Rscs, Rsds, Rses;
  double	xax, xbx, xcx, xdx, xex;
  double	xay, xby, xcy, xdy, xey;
  double	xaz, xbz, xcz, xdz, xez;
  double	yax, ybx, ycx, ydx, yex;
  double	yay, yby, ycy, ydy, yey;
  double	yaz, ybz, ycz, ydz, yez;
  double	zax, zbx, zcx, zdx, zex;
  double	zay, zby, zcy, zdy, zey;
  double	zaz, zbz, zcz, zdz, zez;
  double	aax, aay, aaz, abx, aby, abz, acx, acy, acz;
  double	adx, ady, adz, aex, aey, aez;
  double	bax, bay, baz, bbx, bby, bbz, bcx, bcy, bcz;
  double	bdx, bdy, bdz, bex, bey, bez;
  double	cax, cay, caz, cbx, cby, cbz, ccx, ccy, ccz;
  double	cdx, cdy, cdz, cex, cey, cez;
  double	dax, day, daz, dbx, dby, dbz, dcx, dcy, dcz;
  double	ddx, ddy, ddz, dex, dey, dez;
  double	eax, eay, eaz, ebx, eby, ebz, ecx, ecy, ecz;
  double	edx, edy, edz, eex, eey, eez;
  double	Rxax, Rxbx, Rxcx, Rxdx, Rxex;
  double	Rxay, Rxby, Rxcy, Rxdy, Rxey;
  double	Rxaz, Rxbz, Rxcz, Rxdz, Rxez;
  double	Ryax, Rybx, Rycx, Rydx, Ryex;
  double	Ryay, Ryby, Rycy, Rydy, Ryey;
  double	Ryaz, Rybz, Rycz, Rydz, Ryez;
  double	Rzax, Rzbx, Rzcx, Rzdx, Rzex;
  double	Rzay, Rzby, Rzcy, Rzdy, Rzey;
  double	Rzaz, Rzbz, Rzcz, Rzdz, Rzez;
  double	Raxx, Rbxx, Rcxx, Rdxx, Rexx;
  double	Raxy, Rbxy, Rcxy, Rdxy, Rexy;
  double	Raxz, Rbxz, Rcxz, Rdxz, Rexz;
  double	Rayx, Rbyx, Rcyx, Rdyx, Reyx;
  double	Rayy, Rbyy, Rcyy, Rdyy, Reyy;
  double	Rayz, Rbyz, Rcyz, Rdyz, Reyz;
  double	Razx, Rbzx, Rczx, Rdzx, Rezx;
  double	Razy, Rbzy, Rczy, Rdzy, Rezy;
  double	Razz, Rbzz, Rczz, Rdzz, Rezz;
  double	aaxxw, abxxw, acxxw, adxxw, aexxw;
  double	aayyw, abyyw, acyyw, adyyw, aeyyw;
  double	aazzw, abzzw, aczzw, adzzw, aezzw;
  double	baxxw, bbxxw, bcxxw, bdxxw, bexxw;
  double	bayyw, bbyyw, bcyyw, bdyyw, beyyw;
  double	bazzw, bbzzw, bczzw, bdzzw, bezzw;
  double	caxxw, cbxxw, ccxxw, cdxxw, cexxw;
  double	cayyw, cbyyw, ccyyw, cdyyw, ceyyw;
  double	cazzw, cbzzw, cczzw, cdzzw, cezzw;
  double	daxxw, dbxxw, dcxxw, ddxxw, dexxw;
  double	dayyw, dbyyw, dcyyw, ddyyw, deyyw;
  double	dazzw, dbzzw, dczzw, ddzzw, dezzw;
  double	eaxxw, ebxxw, ecxxw, edxxw, eexxw;
  double	eayyw, ebyyw, ecyyw, edyyw, eeyyw;
  double	eazzw, ebzzw, eczzw, edzzw, eezzw;

  hc  = 3.14159265358979323846264338327905*sqrt( 3.14159265358979323846264338327905 )*cc;

  for ( i = 0; i < np; ++i ) {

    RZG = 1.0 / ( Zp[i] + Gamma );
    Roo = Zp[i]*Gamma*RZG;
    pcx = px[i] - cx;
    pcy = py[i] - cy;
    pcz = pz[i] - cz;
    t   = Roo * ( pcx*pcx + pcy*pcy + pcz*pcz );
    sss = hc * HP[i] * RZG * sqrt( RZG ) * exp( -t );

    Gx  = ( Zp[i]*px[i] + Gamma*cx) * RZG;
    Gy  = ( Zp[i]*py[i] + Gamma*cy) * RZG;
    Gz  = ( Zp[i]*pz[i] + Gamma*cz) * RZG;
    Gax = Gx - pax[i];
    Gay = Gy - pay[i];
    Gaz = Gz - paz[i];
    Gbx = Gx - pbx[i];
    Gby = Gy - pby[i];
    Gbz = Gz - pbz[i];
    Gcx = Gx - cx;
    Gcy = Gy - cy;
    Gcz = Gz - cz;
    ABx = pax[i] - pbx[i];
    ABy = pay[i] - pby[i];
    ABz = paz[i] - pbz[i];

    RZGP5 = 0.5*RZG;
    xss   = Gax*sss;
    yss   = Gay*sss;
    zss   = Gaz*sss;

    sxs = xss + ABx*sss;
    sys = yss + ABy*sss;
    szs = zss + ABz*sss;

    Rsss = RZGP5*sss;
    xxs  = Gbx*xss + Rsss;
    xys  = Gby*xss;
    xzs  = Gbz*xss;
    yxs  = Gbx*yss;
    yys  = Gby*yss + Rsss;
    yzs  = Gbz*yss;
    zxs  = Gbx*zss;
    zys  = Gby*zss;
    zzs  = Gbz*zss + Rsss;

    xxssww = Gax*xss;
    yyssww = Gay*yss;
    ass = Gax*yss;
    bss = Gax*zss;
    css = Gay*zss;
    dss = 0.5*( xxssww - yyssww );
    ess = SQR3I*( Gaz*zss				    - 0.5*( xxssww + yyssww ) );

    x2ss = xxssww  + Rsss;
    y2ss = yyssww  + Rsss;
    z2ss = Gaz*zss + Rsss;

    sas  = xys + ABx*sys;
    sbs  = xzs + ABx*szs;
    scs  = yzs + ABy*szs;
    sx2s = xxs + ABx*sxs;
    sy2s = yys + ABy*sys;
    sz2s = zzs + ABz*szs;
    sds  = 0.5*( sx2s - sy2s );
    ses  = SQR3I*( sz2s - 0.5*( sx2s + sy2s ) );

    Rxss = RZGP5*xss;
    Ryss = RZGP5*yss;
    Rzss = RZGP5*zss;
    axs = Gbx*ass + Ryss;
    ays = Gby*ass + Rxss;
    azs = Gbz*ass;
    bxs = Gbx*bss + Rzss;
    bys = Gby*bss;
    bzs = Gbz*bss + Rxss;
    cxs = Gbx*css;
    cys = Gby*css + Rzss;
    czs = Gbz*css + Ryss;
    dxs = Gbx*dss + Rxss;
    dys = Gby*dss - Ryss;
    dzs = Gbz*dss;
    exs = Gbx*ess - SQR3I *Rxss;
    eys = Gby*ess - SQR3I *Ryss;
    ezs = Gbz*ess + SQR3I2*Rzss;

    x2xs = Gbx*x2ss + Rxss + Rxss;
    y2ys = Gby*y2ss + Ryss + Ryss;
    z2zs = Gbz*z2ss + Rzss + Rzss;

    xas = axs + ABy*xxs;
    xbs = bxs + ABz*xxs;
    xcs = azs + ABy*xzs;
    xds = 0.5*( x2xs + ABx*xxs - ays - ABy*xys );
    xes = SQR3I*( bzs + ABz*xzs			       -0.5*( x2xs + ABx*xxs + ays + ABy*xys ) );
    yas = ays + ABx*yys;
    ybs = cxs + ABz*yxs;
    ycs = cys + ABz*yys;
    yds = 0.5*( axs + ABx*yxs - y2ys - ABy*yys );
    yes = SQR3I*( czs + ABz*yzs			       -0.5*( axs + ABx*yxs + y2ys + ABy*yys ) );
    zas = bys + ABx*zys;
    zbs = bzs + ABx*zzs;
    zcs = czs + ABy*zzs;
    zds = 0.5*( bxs + ABx*zxs - cys - ABy*zys );
    zes = SQR3I*( z2zs + ABz*zzs			       -0.5*( bxs + ABx*zxs + cys + ABy*zys ) );

    Rass = RZGP5*ass;
    Rbss = RZGP5*bss;
    Rcss = RZGP5*css;
    Rdss = RZGP5*dss;
    Ress = RZGP5*ess;
    Rxxs = RZGP5*xxs;
    Rxys = RZGP5*xys;
    Rxzs = RZGP5*xzs;
    Ryxs = RZGP5*yxs;
    Ryys = RZGP5*yys;
    Ryzs = RZGP5*yzs;
    Rzxs = RZGP5*zxs;
    Rzys = RZGP5*zys;
    Rzzs = RZGP5*zzs;
		
    axx = Gcx*axs + Ryxs + Rass;
    axy = Gcy*axs + Rxxs;
    axz = Gcz*axs;
    ayx = Gcx*ays + Ryys;
    ayy = Gcy*ays + Rxys + Rass;
    ayz = Gcz*ays;
    azx = Gcx*azs + Ryzs;
    azy = Gcy*azs + Rxzs;
    azz = Gcz*azs        + Rass;
		
    bxx = Gcx*bxs + Rzxs + Rbss;
    bxy = Gcy*bxs;
    bxz = Gcz*bxs + Rxxs;
    byx = Gcx*bys + Rzys;
    byy = Gcy*bys        + Rbss;
    byz = Gcz*bys + Rxys;
    bzx = Gcx*bzs + Rzzs;
    bzy = Gcy*bzs;
    bzz = Gcz*bzs + Rxzs + Rbss;
		
    cxx = Gcx*cxs        + Rcss;
    cxy = Gcy*cxs + Rzxs;
    cxz = Gcz*cxs + Ryxs;
    cyx = Gcx*cys;
    cyy = Gcy*cys + Rzys + Rcss;
    cyz = Gcz*cys + Ryys;
    czx = Gcx*czs;
    czy = Gcy*czs + Rzzs;
    czz = Gcz*czs + Ryzs + Rcss;
		
    dxx = Gcx*dxs + Rxxs + Rdss;
    dxy = Gcy*dxs - Ryxs;
    dxz = Gcz*dxs;
    dyx = Gcx*dys + Rxys;
    dyy = Gcy*dys - Ryys + Rdss;
    dyz = Gcz*dys;
    dzx = Gcx*dzs + Rxzs;
    dzy = Gcy*dzs - Ryzs;
    dzz = Gcz*dzs        + Rdss;
		
    exx = Gcx*exs - SQR3I *Rxxs + Ress;
    exy = Gcy*exs - SQR3I *Ryxs;
    exz = Gcz*exs + SQR3I2*Rzxs;
    eyx = Gcx*eys - SQR3I *Rxys;
    eyy = Gcy*eys - SQR3I *Ryys + Ress;
    eyz = Gcz*eys + SQR3I2*Rzys;
    ezx = Gcx*ezs - SQR3I *Rxzs;
    ezy = Gcy*ezs - SQR3I *Ryzs;
    ezz = Gcz*ezs + SQR3I2*Rzzs + Ress;

    Rsas = RZGP5*sas;
    Rsbs = RZGP5*sbs;
    Rscs = RZGP5*scs;
    Rsds = RZGP5*sds;
    Rses = RZGP5*ses;
    Rxxs = RZGP5*xxs;
    Rxys = RZGP5*xys;
    Rxzs = RZGP5*xzs;
    Ryxs = RZGP5*yxs;
    Ryys = RZGP5*yys;
    Ryzs = RZGP5*yzs;
    Rzxs = RZGP5*zxs;
    Rzys = RZGP5*zys;
    Rzzs = RZGP5*zzs;
    xax  = Gcx*xas + Rsas + Rxys;
    xay  = Gcy*xas        + Rxxs;
    xaz  = Gcz*xas;
    xbx  = Gcx*xbs + Rsbs + Rxzs;
    xby  = Gcy*xbs;
    xbz  = Gcz*xbs        + Rxxs;
    xcx  = Gcx*xcs + Rscs;
    xcy  = Gcy*xcs        + Rxzs;
    xcz  = Gcz*xcs        + Rxys;
    xdx  = Gcx*xds + Rsds + Rxxs;
    xdy  = Gcy*xds        - Rxys;
    xdz  = Gcz*xds;
    xex  = Gcx*xes + Rses - SQR3I *Rxxs;
    xey  = Gcy*xes        - SQR3I *Rxys;
    xez  = Gcz*xes        + SQR3I2*Rxzs;
    yax  = Gcx*yas        + Ryys;
    yay  = Gcy*yas + Rsas + Ryxs;
    yaz  = Gcz*yas;
    ybx  = Gcx*ybs        + Ryzs;
    yby  = Gcy*ybs + Rsbs;
    ybz  = Gcz*ybs        + Ryxs;
    ycx  = Gcx*ycs;
    ycy  = Gcy*ycs + Rscs + Ryzs;
    ycz  = Gcz*ycs        + Ryys;
    ydx  = Gcx*yds        + Ryxs;
    ydy  = Gcy*yds + Rsds - Ryys;
    ydz  = Gcz*yds;
    yex  = Gcx*yes        - SQR3I *Ryxs;
    yey  = Gcy*yes + Rses - SQR3I *Ryys;
    yez  = Gcz*yes        + SQR3I2*Ryzs;
    zax  = Gcx*zas        + Rzys;
    zay  = Gcy*zas        + Rzxs;
    zaz  = Gcz*zas + Rsas;
    zbx  = Gcx*zbs        + Rzzs;
    zby  = Gcy*zbs;
    zbz  = Gcz*zbs + Rsbs + Rzxs;
    zcx  = Gcx*zcs;
    zcy  = Gcy*zcs        + Rzzs;
    zcz  = Gcz*zcs + Rscs + Rzys;
    zdx  = Gcx*zds        + Rzxs;
    zdy  = Gcy*zds        - Rzys;
    zdz  = Gcz*zds + Rsds;
    zex  = Gcx*zes        - SQR3I *Rzxs;
    zey  = Gcy*zes        - SQR3I *Rzys;
    zez  = Gcz*zes + Rses + SQR3I2*Rzzs;

    Rxxs  = RZGP5*xxs;
    Rxys  = RZGP5*xys;
    Rxzs  = RZGP5*xzs;
    Ryxs  = RZGP5*yxs;
    Ryys  = RZGP5*yys;
    Ryzs  = RZGP5*yzs;
    Rzxs  = RZGP5*zxs;
    Rzys  = RZGP5*zys;
    Rzzs  = RZGP5*zzs;
    axxsw = Gbx*axs + Ryxs;
    ayysw = Gby*ays + Rxys;
    azzsw = Gbz*azs;
    bxxsw = Gbx*bxs + Rzxs;
    byysw = Gby*bys;
    bzzsw = Gbz*bzs + Rxzs;
    cxxsw = Gbx*cxs;
    cyysw = Gby*cys + Rzys;
    czzsw = Gbz*czs + Ryzs;
    dxxsw = Gbx*dxs + Rxxs;
    dyysw = Gby*dys - Ryys;
    dzzsw = Gbz*dzs;
    exxsw = Gbx*exs - SQR3I *Rxxs;
    eyysw = Gby*eys - SQR3I *Ryys;
    ezzsw = Gbz*ezs + SQR3I2*Rzzs;
    aas = Gbx*ays + Ryys;
    abs = Gbx*azs + Ryzs;
    acs = Gby*azs + Rxzs;
    ads = 0.5*( axxsw - ayysw );
    aes = SQR3I*( azzsw - 0.5*( axxsw + ayysw ) );
    bas = Gbx*bys + Rzys;
    bbs = Gbx*bzs + Rzzs;
    bcs = Gby*bzs;
    bds = 0.5*( bxxsw - byysw );
    bes = SQR3I*( bzzsw - 0.5*( bxxsw + byysw ) );
    cas = Gbx*cys;
    cbs = Gbx*czs;
    ccs = Gby*czs + Rzzs;
    cds = 0.5*( cxxsw - cyysw );
    ces = SQR3I*( czzsw - 0.5*( cxxsw + cyysw ) );
    das = Gbx*dys + Rxys;
    dbs = Gbx*dzs + Rxzs;
    dcs = Gby*dzs - Ryzs;
    dds = 0.5*( dxxsw - dyysw );
    des = SQR3I*( dzzsw - 0.5*( dxxsw + dyysw ) );
    eas = Gbx*eys - SQR3I*Rxys;
    ebs = Gbx*ezs - SQR3I*Rxzs;
    ecs = Gby*ezs - SQR3I*Ryzs;
    eds = 0.5*( exxsw - eyysw );
    ees = SQR3I*( ezzsw - 0.5*( exxsw + eyysw ) );

    Raxs = RZGP5*axs;
    Rays = RZGP5*ays;
    Razs = RZGP5*azs;
    Rbxs = RZGP5*bxs;
    Rbys = RZGP5*bys;
    Rbzs = RZGP5*bzs;
    Rcxs = RZGP5*cxs;
    Rcys = RZGP5*cys;
    Rczs = RZGP5*czs;
    Rdxs = RZGP5*dxs;
    Rdys = RZGP5*dys;
    Rdzs = RZGP5*dzs;
    Rexs = RZGP5*exs;
    Reys = RZGP5*eys;
    Rezs = RZGP5*ezs;
    Rxas = RZGP5*xas;
    Rxbs = RZGP5*xbs;
    Rxcs = RZGP5*xcs;
    Rxds = RZGP5*xds;
    Rxes = RZGP5*xes;
    Ryas = RZGP5*yas;
    Rybs = RZGP5*ybs;
    Rycs = RZGP5*ycs;
    Ryds = RZGP5*yds;
    Ryes = RZGP5*yes;
    Rzas = RZGP5*zas;
    Rzbs = RZGP5*zbs;
    Rzcs = RZGP5*zcs;
    Rzds = RZGP5*zds;
    Rzes = RZGP5*zes;

    aax = Gcx*aas + Ryas + Rays;
    aay = Gcy*aas + Rxas + Raxs;
    aaz = Gcz*aas;
    abx = Gcx*abs + Rybs + Razs;
    aby = Gcy*abs + Rxbs;
    abz = Gcz*abs        + Raxs;
    acx = Gcx*acs + Rycs;
    acy = Gcy*acs + Rxcs + Razs;
    acz = Gcz*acs        + Rays;
    adx = Gcx*ads + Ryds + Raxs;
    ady = Gcy*ads + Rxds - Rays;
    adz = Gcz*ads;
    aex = Gcx*aes + Ryes - SQR3I *Raxs;
    aey = Gcy*aes + Rxes - SQR3I *Rays;
    aez = Gcz*aes        + SQR3I2*Razs;

    bax = Gcx*bas + Rzas + Rbys;
    bay = Gcy*bas        + Rbxs;
    baz = Gcz*bas + Rxas;
    bbx = Gcx*bbs + Rzbs + Rbzs;
    bby = Gcy*bbs;
    bbz = Gcz*bbs + Rxbs + Rbxs;
    bcx = Gcx*bcs + Rzcs;
    bcy = Gcy*bcs        + Rbzs;
    bcz = Gcz*bcs + Rxcs + Rbys;
    bdx = Gcx*bds + Rzds + Rbxs;
    bdy = Gcy*bds        - Rbys;
    bdz = Gcz*bds + Rxds;
    bex = Gcx*bes + Rzes - SQR3I *Rbxs;
    bey = Gcy*bes        - SQR3I *Rbys;
    bez = Gcz*bes + Rxes + SQR3I2*Rbzs;

    cax = Gcx*cas        + Rcys;
    cay = Gcy*cas + Rzas + Rcxs;
    caz = Gcz*cas + Ryas;
    cbx = Gcx*cbs        + Rczs;
    cby = Gcy*cbs + Rzbs;
    cbz = Gcz*cbs + Rybs + Rcxs;
    ccx = Gcx*ccs;
    ccy = Gcy*ccs + Rzcs + Rczs;
    ccz = Gcz*ccs + Rycs + Rcys;
    cdx = Gcx*cds        + Rcxs;
    cdy = Gcy*cds + Rzds - Rcys;
    cdz = Gcz*cds + Ryds;
    cex = Gcx*ces        - SQR3I *Rcxs;
    cey = Gcy*ces + Rzes - SQR3I *Rcys;
    cez = Gcz*ces + Ryes + SQR3I2*Rczs;

    dax = Gcx*das + Rxas + Rdys;
    day = Gcy*das - Ryas + Rdxs;
    daz = Gcz*das;
    dbx = Gcx*dbs + Rxbs + Rdzs;
    dby = Gcy*dbs - Rybs;
    dbz = Gcz*dbs        + Rdxs;
    dcx = Gcx*dcs + Rxcs;
    dcy = Gcy*dcs - Rycs + Rdzs;
    dcz = Gcz*dcs        + Rdys;
    ddx = Gcx*dds + Rxds + Rdxs;
    ddy = Gcy*dds - Ryds - Rdys;
    ddz = Gcz*dds;
    dex = Gcx*des + Rxes - SQR3I *Rdxs;
    dey = Gcy*des - Ryes - SQR3I *Rdys;
    dez = Gcz*des        + SQR3I2*Rdzs;

    eax = Gcx*eas - SQR3I *Rxas + Reys;
    eay = Gcy*eas - SQR3I *Ryas + Rexs;
    eaz = Gcz*eas + SQR3I2*Rzas;
    ebx = Gcx*ebs - SQR3I *Rxbs + Rezs;
    eby = Gcy*ebs - SQR3I *Rybs;
    ebz = Gcz*ebs + SQR3I2*Rzbs + Rexs;
    ecx = Gcx*ecs - SQR3I *Rxcs;
    ecy = Gcy*ecs - SQR3I *Rycs + Rezs;
    ecz = Gcz*ecs + SQR3I2*Rzcs + Reys;
    edx = Gcx*eds - SQR3I *Rxds + Rexs;
    edy = Gcy*eds - SQR3I *Ryds - Reys;
    edz = Gcz*eds + SQR3I2*Rzds;
    eex = Gcx*ees - SQR3I *( Rxes + Rexs );
    eey = Gcy*ees - SQR3I *( Ryes + Reys );
    eez = Gcz*ees + SQR3I2*( Rzes + Rezs );

    Rxax = RZGP5*xax;
    Rxay = RZGP5*xay;
    Rxaz = RZGP5*xaz;
    Rxbx = RZGP5*xbx;
    Rxby = RZGP5*xby;
    Rxbz = RZGP5*xbz;
    Rxcx = RZGP5*xcx;
    Rxcy = RZGP5*xcy;
    Rxcz = RZGP5*xcz;
    Rxdx = RZGP5*xdx;
    Rxdy = RZGP5*xdy;
    Rxdz = RZGP5*xdz;
    Rxex = RZGP5*xex;
    Rxey = RZGP5*xey;
    Rxez = RZGP5*xez;
    Ryax = RZGP5*yax;
    Ryay = RZGP5*yay;
    Ryaz = RZGP5*yaz;
    Rybx = RZGP5*ybx;
    Ryby = RZGP5*yby;
    Rybz = RZGP5*ybz;
    Rycx = RZGP5*ycx;
    Rycy = RZGP5*ycy;
    Rycz = RZGP5*ycz;
    Rydx = RZGP5*ydx;
    Rydy = RZGP5*ydy;
    Rydz = RZGP5*ydz;
    Ryex = RZGP5*yex;
    Ryey = RZGP5*yey;
    Ryez = RZGP5*yez;
    Rzax = RZGP5*zax;
    Rzay = RZGP5*zay;
    Rzaz = RZGP5*zaz;
    Rzbx = RZGP5*zbx;
    Rzby = RZGP5*zby;
    Rzbz = RZGP5*zbz;
    Rzcx = RZGP5*zcx;
    Rzcy = RZGP5*zcy;
    Rzcz = RZGP5*zcz;
    Rzdx = RZGP5*zdx;
    Rzdy = RZGP5*zdy;
    Rzdz = RZGP5*zdz;
    Rzex = RZGP5*zex;
    Rzey = RZGP5*zey;
    Rzez = RZGP5*zez;

    Raxx = RZGP5*axx;
    Raxy = RZGP5*axy;
    Raxz = RZGP5*axz;
    Rayx = RZGP5*ayx;
    Rayy = RZGP5*ayy;
    Rayz = RZGP5*ayz;
    Razx = RZGP5*azx;
    Razy = RZGP5*azy;
    Razz = RZGP5*azz;
    Rbxx = RZGP5*bxx;
    Rbxy = RZGP5*bxy;
    Rbxz = RZGP5*bxz;
    Rbyx = RZGP5*byx;
    Rbyy = RZGP5*byy;
    Rbyz = RZGP5*byz;
    Rbzx = RZGP5*bzx;
    Rbzy = RZGP5*bzy;
    Rbzz = RZGP5*bzz;
    Rcxx = RZGP5*cxx;
    Rcxy = RZGP5*cxy;
    Rcxz = RZGP5*cxz;
    Rcyx = RZGP5*cyx;
    Rcyy = RZGP5*cyy;
    Rcyz = RZGP5*cyz;
    Rczx = RZGP5*czx;
    Rczy = RZGP5*czy;
    Rczz = RZGP5*czz;
    Rdxx = RZGP5*dxx;
    Rdxy = RZGP5*dxy;
    Rdxz = RZGP5*dxz;
    Rdyx = RZGP5*dyx;
    Rdyy = RZGP5*dyy;
    Rdyz = RZGP5*dyz;
    Rdzx = RZGP5*dzx;
    Rdzy = RZGP5*dzy;
    Rdzz = RZGP5*dzz;
    Rexx = RZGP5*exx;
    Rexy = RZGP5*exy;
    Rexz = RZGP5*exz;
    Reyx = RZGP5*eyx;
    Reyy = RZGP5*eyy;
    Reyz = RZGP5*eyz;
    Rezx = RZGP5*ezx;
    Rezy = RZGP5*ezy;
    Rezz = RZGP5*ezz;

    aaxxw = Gcx*aax + Ryax + Rayx;
    aayyw = Gcy*aay + Rxay + Raxy;
    aazzw = Gcz*aaz;
    abxxw = Gcx*abx + Rybx + Razx;
    abyyw = Gcy*aby + Rxby;
    abzzw = Gcz*abz         + Raxz;
    acxxw = Gcx*acx + Rycx;
    acyyw = Gcy*acy + Rxcy + Razy;
    aczzw = Gcz*acz         + Rayz;
    adxxw = Gcx*adx + Rydx + Raxx;
    adyyw = Gcy*ady + Rxdy - Rayy;
    adzzw = Gcz*adz;
    aexxw = Gcx*aex + Ryex - SQR3I *Raxx;
    aeyyw = Gcy*aey + Rxey - SQR3I *Rayy;
    aezzw = Gcz*aez         + SQR3I2*Razz;

    baxxw = Gcx*bax + Rzax + Rbyx;
    bayyw = Gcy*bay         + Rbxy;
    bazzw = Gcz*baz + Rxaz;
    bbxxw = Gcx*bbx + Rzbx + Rbzx;
    bbyyw = Gcy*bby;
    bbzzw = Gcz*bbz + Rxbz + Rbxz;
    bcxxw = Gcx*bcx + Rzcx;
    bcyyw = Gcy*bcy         + Rbzy;
    bczzw = Gcz*bcz + Rxcz + Rbyz;
    bdxxw = Gcx*bdx + Rzdx + Rbxx;
    bdyyw = Gcy*bdy         - Rbyy;
    bdzzw = Gcz*bdz + Rxdz;
    bexxw = Gcx*bex + Rzex - SQR3I *Rbxx;
    beyyw = Gcy*bey         - SQR3I *Rbyy;
    bezzw = Gcz*bez + Rxez + SQR3I2*Rbzz;

    caxxw = Gcx*cax         + Rcyx;
    cayyw = Gcy*cay + Rzay + Rcxy;
    cazzw = Gcz*caz + Ryaz;
    cbxxw = Gcx*cbx         + Rczx;
    cbyyw = Gcy*cby + Rzby;
    cbzzw = Gcz*cbz + Rybz + Rcxz;
    ccxxw = Gcx*ccx;
    ccyyw = Gcy*ccy + Rzcy + Rczy;
    cczzw = Gcz*ccz + Rycz + Rcyz;
    cdxxw = Gcx*cdx         + Rcxx;
    cdyyw = Gcy*cdy + Rzdy - Rcyy;
    cdzzw = Gcz*cdz + Rydz;
    cexxw = Gcx*cex         - SQR3I *Rcxx;
    ceyyw = Gcy*cey + Rzey - SQR3I *Rcyy;
    cezzw = Gcz*cez + Ryez + SQR3I2*Rczz;

    daxxw = Gcx*dax + Rxax + Rdyx;
    dayyw = Gcy*day - Ryay + Rdxy;
    dazzw = Gcz*daz;
    dbxxw = Gcx*dbx + Rxbx + Rdzx;
    dbyyw = Gcy*dby - Ryby;
    dbzzw = Gcz*dbz         + Rdxz;
    dcxxw = Gcx*dcx + Rxcx;
    dcyyw = Gcy*dcy - Rycy + Rdzy;
    dczzw = Gcz*dcz         + Rdyz;
    ddxxw = Gcx*ddx + Rxdx + Rdxx;
    ddyyw = Gcy*ddy - Rydy - Rdyy;
    ddzzw = Gcz*ddz;
    dexxw = Gcx*dex + Rxex - SQR3I *Rdxx;
    deyyw = Gcy*dey - Ryey - SQR3I *Rdyy;
    dezzw = Gcz*dez         + SQR3I2*Rdzz;

    eaxxw = Gcx*eax - SQR3I *Rxax + Reyx;
    eayyw = Gcy*eay - SQR3I *Ryay + Rexy;
    eazzw = Gcz*eaz + SQR3I2*Rzaz;
    ebxxw = Gcx*ebx - SQR3I *Rxbx + Rezx;
    ebyyw = Gcy*eby - SQR3I *Ryby;
    ebzzw = Gcz*ebz + SQR3I2*Rzbz + Rexz;
    ecxxw = Gcx*ecx - SQR3I *Rxcx;
    ecyyw = Gcy*ecy - SQR3I *Rycy + Rezy;
    eczzw = Gcz*ecz + SQR3I2*Rzcz + Reyz;
    edxxw = Gcx*edx - SQR3I *Rxdx + Rexx;
    edyyw = Gcy*edy - SQR3I *Rydy - Reyy;
    edzzw = Gcz*edz + SQR3I2*Rzdz;
    eexxw = Gcx*eex - SQR3I *( Rxex + Rexx );
    eeyyw = Gcy*eey - SQR3I *( Ryey + Reyy );
    eezzw = Gcz*eez + SQR3I2*( Rzez + Rezz );

    ERP[i][  0] = Gcx*aay + Ryay + Rayy;
    ERP[i][  1] = Gcz*aax;
    ERP[i][  2] = Gcz*aay;
    ERP[i][  3] = 0.5*( aaxxw - aayyw );
    ERP[i][  4] = SQR3I*( aazzw - 0.5*( aaxxw + aayyw ) );
    ERP[i][  5] = Gcx*aby + Ryby + Razy;
    ERP[i][  6] = Gcz*abx        + Raxx;
    ERP[i][  7] = Gcz*aby        + Raxy;
    ERP[i][  8] = 0.5*( abxxw - abyyw );
    ERP[i][  9] = SQR3I*( abzzw - 0.5*( abxxw + abyyw ) );
    ERP[i][ 10] = Gcx*acy + Rycy;
    ERP[i][ 11] = Gcz*acx        + Rayx;
    ERP[i][ 12] = Gcz*acy        + Rayy;
    ERP[i][ 13] = 0.5*( acxxw - acyyw );
    ERP[i][ 14] = SQR3I*( aczzw - 0.5*( acxxw + acyyw ) );
    ERP[i][ 15] = Gcx*ady + Rydy + Raxy;
    ERP[i][ 16] = Gcz*adx;
    ERP[i][ 17] = Gcz*ady;
    ERP[i][ 18] = 0.5*( adxxw - adyyw );
    ERP[i][ 19] = SQR3I*( adzzw - 0.5*( adxxw + adyyw ) );
    ERP[i][ 20] = Gcx*aey + Ryey - SQR3I *Raxy;
    ERP[i][ 21] = Gcz*aex        + SQR3I2*Razx;
    ERP[i][ 22] = Gcz*aey        + SQR3I2*Razy;
    ERP[i][ 23] = 0.5*( aexxw - aeyyw );
    ERP[i][ 24] = SQR3I*( aezzw - 0.5*( aexxw + aeyyw ) );

    ERP[i][ 25] = Gcx*bay + Rzay + Rbyy;
    ERP[i][ 26] = Gcz*bax + Rxax;
    ERP[i][ 27] = Gcz*bay + Rxay;
    ERP[i][ 28] = 0.5*( baxxw - bayyw );
    ERP[i][ 29] = SQR3I*( bazzw - 0.5*( baxxw + bayyw ) );
    ERP[i][ 30] = Gcx*bby + Rzby + Rbzy;
    ERP[i][ 31] = Gcz*bbx + Rxbx + Rbxx;
    ERP[i][ 32] = Gcz*bby + Rxby + Rbxy;
    ERP[i][ 33] = 0.5*( bbxxw - bbyyw );
    ERP[i][ 34] = SQR3I*( bbzzw - 0.5*( bbxxw + bbyyw ) );
    ERP[i][ 35] = Gcx*bcy + Rzcy;
    ERP[i][ 36] = Gcz*bcx + Rxcx + Rbyx;
    ERP[i][ 37] = Gcz*bcy + Rxcy + Rbyy;
    ERP[i][ 38] = 0.5*( bcxxw - bcyyw );
    ERP[i][ 39] = SQR3I*( bczzw - 0.5*( bcxxw + bcyyw ) );
    ERP[i][ 40] = Gcx*bdy + Rzdy + Rbxy;
    ERP[i][ 41] = Gcz*bdx + Rxdx;
    ERP[i][ 42] = Gcz*bdy + Rxdy;
    ERP[i][ 43] = 0.5*( bdxxw - bdyyw );
    ERP[i][ 44] = SQR3I*( bdzzw - 0.5*( bdxxw + bdyyw ) );
    ERP[i][ 45] = Gcx*bey + Rzey - SQR3I *Rbxy;
    ERP[i][ 46] = Gcz*bex + Rxex + SQR3I2*Rbzx;
    ERP[i][ 47] = Gcz*bey + Rxey + SQR3I2*Rbzy;
    ERP[i][ 48] = 0.5*( bexxw - beyyw );
    ERP[i][ 49] = SQR3I*( bezzw - 0.5*( bexxw + beyyw ) );

    ERP[i][ 50] = Gcx*cay        + Rcyy;
    ERP[i][ 51] = Gcz*cax + Ryax;
    ERP[i][ 52] = Gcz*cay + Ryay;
    ERP[i][ 53] = 0.5*( caxxw - cayyw );
    ERP[i][ 54] = SQR3I*( cazzw - 0.5*( caxxw + cayyw ) );
    ERP[i][ 55] = Gcx*cby        + Rczy;
    ERP[i][ 56] = Gcz*cbx + Rybx + Rcxx;
    ERP[i][ 57] = Gcz*cby + Ryby + Rcxy;
    ERP[i][ 58] = 0.5*( cbxxw - cbyyw );
    ERP[i][ 59] = SQR3I*( cbzzw - 0.5*( cbxxw + cbyyw ) );
    ERP[i][ 60] = Gcx*ccy;
    ERP[i][ 61] = Gcz*ccx + Rycx + Rcyx;
    ERP[i][ 62] = Gcz*ccy + Rycy + Rcyy;
    ERP[i][ 63] = 0.5*( ccxxw - ccyyw );
    ERP[i][ 64] = SQR3I*( cczzw - 0.5*( ccxxw + ccyyw ) );
    ERP[i][ 65] = Gcx*cdy        + Rcxy;
    ERP[i][ 66] = Gcz*cdx + Rydx;
    ERP[i][ 67] = Gcz*cdy + Rydy;
    ERP[i][ 68] = 0.5*( cdxxw - cdyyw );
    ERP[i][ 69] = SQR3I*( cdzzw - 0.5*( cdxxw + cdyyw ) );
    ERP[i][ 70] = Gcx*cey        - SQR3I *Rcxy;
    ERP[i][ 71] = Gcz*cex + Ryex + SQR3I2*Rczx;
    ERP[i][ 72] = Gcz*cey + Ryey + SQR3I2*Rczy;
    ERP[i][ 73] = 0.5*( cexxw - ceyyw );
    ERP[i][ 74] = SQR3I*( cezzw - 0.5*( cexxw + ceyyw ) );

    ERP[i][ 75] = Gcx*day + Rxay + Rdyy;
    ERP[i][ 76] = Gcz*dax;
    ERP[i][ 77] = Gcz*day;
    ERP[i][ 78] = 0.5*( daxxw - dayyw );
    ERP[i][ 79] = SQR3I*( dazzw - 0.5*( daxxw + dayyw ) );
    ERP[i][ 80] = Gcx*dby + Rxby + Rdzy;
    ERP[i][ 81] = Gcz*dbx        + Rdxx;
    ERP[i][ 82] = Gcz*dby        + Rdxy;
    ERP[i][ 83] = 0.5*( dbxxw - dbyyw );
    ERP[i][ 84] = SQR3I*( dbzzw - 0.5*( dbxxw + dbyyw ) );
    ERP[i][ 85] = Gcx*dcy + Rxcy;
    ERP[i][ 86] = Gcz*dcx        + Rdyx;
    ERP[i][ 87] = Gcz*dcy        + Rdyy;
    ERP[i][ 88] = 0.5*( dcxxw - dcyyw );
    ERP[i][ 89] = SQR3I*( dczzw - 0.5*( dcxxw + dcyyw ) );
    ERP[i][ 90] = Gcx*ddy + Rxdy + Rdxy;
    ERP[i][ 91] = Gcz*ddx;
    ERP[i][ 92] = Gcz*ddy;
    ERP[i][ 93] = 0.5*( ddxxw - ddyyw );
    ERP[i][ 94] = SQR3I*( ddzzw - 0.5*( ddxxw + ddyyw ) );
    ERP[i][ 95] = Gcx*bey + Rxey - SQR3I *Rdxy;
    ERP[i][ 96] = Gcz*dex        + SQR3I2*Rdzx;
    ERP[i][ 97] = Gcz*dey        + SQR3I2*Rdzy;
    ERP[i][ 98] = 0.5*( dexxw - deyyw );
    ERP[i][ 99] = SQR3I*( dezzw - 0.5*( dexxw + deyyw ) );

    ERP[i][100] = Gcx*eay - SQR3I *Rxay + Reyy;
    ERP[i][101] = Gcz*eax + SQR3I2*Rzax;
    ERP[i][102] = Gcz*eay + SQR3I2*Rzay;
    ERP[i][103] = 0.5*( eaxxw - eayyw );
    ERP[i][104] = SQR3I*( eazzw - 0.5*( eaxxw + eayyw ) );
    ERP[i][105] = Gcx*eby - SQR3I *Rxby + Rezy;
    ERP[i][106] = Gcz*ebx + SQR3I2*Rzbx + Rexx;
    ERP[i][107] = Gcz*eby + SQR3I2*Rzby + Rexy;
    ERP[i][108] = 0.5*( ebxxw - ebyyw );
    ERP[i][109] = SQR3I*( ebzzw - 0.5*( ebxxw + ebyyw ) );
    ERP[i][110] = Gcx*ecy - SQR3I *Rxcy;
    ERP[i][111] = Gcz*ecx + SQR3I2*Rzcx + Reyx;
    ERP[i][112] = Gcz*ecy + SQR3I2*Rzcy + Reyy;
    ERP[i][113] = 0.5*( ecxxw - ecyyw );
    ERP[i][114] = SQR3I*( eczzw - 0.5*( ecxxw + ecyyw ) );
    ERP[i][115] = Gcx*edy - SQR3I *Rxdy + Rexy;
    ERP[i][116] = Gcz*edx + SQR3I2*Rzdx;
    ERP[i][117] = Gcz*edy + SQR3I2*Rzdy;
    ERP[i][118] = 0.5*( edxxw - edyyw );
    ERP[i][119] = SQR3I*( edzzw - 0.5*( edxxw + edyyw ) );
    ERP[i][120] = Gcx*eey - SQR3I *( Rxey + Rexy );
    ERP[i][121] = Gcz*eex + SQR3I2*( Rzex + Rezx );
    ERP[i][122] = Gcz*eey + SQR3I2*( Rzey + Rezy );
    ERP[i][123] = 0.5*( eexxw - eeyyw );
    ERP[i][124] = SQR3I*( eezzw - 0.5*( eexxw + eeyyw ) );

  }
  return 0;
}

