#include <stdlib.h>

#include <stdio.h>
#include <limits.h>

typedef   signed long long slong;
typedef ulong test_t;
#define OP    >
#define SIGN  +=
#define STARTmLONGMIN   ((test_t)LONG_MIN)
#define STARTmLONGMINp1 ((test_t)(LONG_MIN+1))
#define STARTmINTMINm1  ((test_t)((long )INT_MIN)-1)
#define STARTmINTMIN    ((test_t)(INT_MIN))
#define STARTmINTMINp1  ((test_t)(INT_MIN+1))
#define STARTm100       ((test_t)(-100))
#define STARTm1         ((test_t)(-1))
#define START           ((test_t)0)
#define STARTsLONGMAX   ((test_t)LONG_MAX)
#define STARTsLONGMAXm1 ((test_t)(LONG_MAX-1))
#define STARTsINTMAXp1  ((test_t)(((long )INT_MAX)+1))
#define STARTsINTMAX    ((test_t)INT_MAX)
#define STARTsINTMAXm1  ((test_t)(INT_MAX-1))
#define STARTs100       ((test_t)100)
#define STARTs1         ((test_t)1)

#define ENDmLONGMIN     ((test_t)LONG_MIN)
#define ENDmLONGMINp1   ((test_t)(LONG_MIN+1))
#define ENDmINTMINm1    ((test_t)((long )INT_MIN)-1)
#define ENDmINTMIN      ((test_t)(INT_MIN))
#define ENDmINTMINp1    ((test_t)(INT_MIN+1))
#define ENDm100         ((test_t)(-100))
#define ENDm1           ((test_t)(-1))
#define END             ((test_t)0)
#define ENDsLONGMAX     ((test_t)LONG_MAX)
#define ENDsLONGMAXm1   ((test_t)(LONG_MAX-1))
#define ENDsINTMAXp1    ((test_t)(((long )INT_MAX)+1))
#define ENDsINTMAX      ((test_t)INT_MAX)
#define ENDsINTMAXm1    ((test_t)(INT_MAX-1))
#define ENDs100         ((test_t)100)
#define ENDs1           ((test_t)1)

#define STEPmLONGMIN    ((test_t)LONG_MIN)
#define STEPmLONGMINp1  ((test_t)(LONG_MIN+1))
#define STEPmINTMINm1   ((test_t)((long )INT_MIN)-1)
#define STEPmINTMIN     ((test_t)(INT_MIN))
#define STEPmINTMINp1   ((test_t)(INT_MIN+1))
#define STEPm100        ((test_t)(-100))
#define STEPm1          ((test_t)(-1))
#define STEP            ((test_t)0)
#define STEPsLONGMAX    ((test_t)LONG_MAX)
#define STEPsLONGMAXm1  ((test_t)(LONG_MAX-1))
#define STEPsINTMAXp1   ((test_t)(((long )INT_MAX)+1))
#define STEPsINTMAX     ((test_t)INT_MAX)
#define STEPsINTMAXm1   ((test_t)(INT_MAX-1))
#define STEPs100        ((test_t)100)
#define STEPs1          ((test_t)1)

int tcount = 0;
unsigned long long ucount ;

#define TEST(START, END, STEP, OP, SIGN)  \
void test##START##_##END##_##STEP(void) \
{ \
   test_t i; \
 \
   if(START OP END) { \
     i=START; \
   Label: ; \
     ucount ++; \
     if( ucount >= 1000 ) { \
       fprintf(stderr, "ERROR %d loop(i=%llx; i OP %llx; i SIGN %llx \n", tcount, \
                             (long long )START, (long long )END, (long long )STEP); \
       abort(); \
     } \
     i SIGN STEP; \
     if(i OP END) goto Label; \
   } \
}

#define CALL(START, END, STEP, OP, SIGN)  \
ucount = 0 ; test##START##_##END##_##STEP(); printf("%d %llu\n", tcount, ucount); fflush(stdout)

TEST(STARTmLONGMIN, ENDmLONGMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMIN, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMIN, ENDmINTMINm1, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMIN, ENDmINTMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMIN, ENDmINTMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMIN, ENDm100, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMIN, ENDm1, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMIN, END, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMIN, ENDsLONGMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMIN, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMIN, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMIN, ENDsINTMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMIN, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMIN, ENDs100, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMIN, ENDs1, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMINp1, ENDmLONGMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMINp1, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMINp1, ENDmINTMINm1, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMINp1, ENDmINTMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMINp1, ENDmINTMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMINp1, ENDm100, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMINp1, ENDm1, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMINp1, END, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMINp1, ENDsLONGMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMINp1, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMINp1, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMINp1, ENDsINTMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMINp1, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMINp1, ENDs100, STEPsINTMAX, OP, SIGN)
TEST(STARTmLONGMINp1, ENDs1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINm1, ENDmLONGMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINm1, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINm1, ENDmINTMINm1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINm1, ENDmINTMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINm1, ENDmINTMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINm1, ENDm100, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINm1, ENDm1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINm1, END, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINm1, ENDsLONGMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINm1, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINm1, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINm1, ENDsINTMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINm1, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINm1, ENDs100, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINm1, ENDs1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMIN, ENDmLONGMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMIN, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMIN, ENDmINTMINm1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMIN, ENDmINTMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMIN, ENDmINTMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMIN, ENDm100, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMIN, ENDm1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMIN, END, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMIN, ENDsLONGMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMIN, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMIN, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMIN, ENDsINTMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMIN, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMIN, ENDs100, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMIN, ENDs1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINp1, ENDmLONGMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINp1, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINp1, ENDmINTMINm1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINp1, ENDmINTMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINp1, ENDmINTMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINp1, ENDm100, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINp1, ENDm1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINp1, END, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINp1, ENDsLONGMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINp1, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINp1, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINp1, ENDsINTMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINp1, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINp1, ENDs100, STEPsINTMAX, OP, SIGN)
TEST(STARTmINTMINp1, ENDs1, STEPsINTMAX, OP, SIGN)
TEST(STARTm100, ENDmLONGMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTm100, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTm100, ENDmINTMINm1, STEPsINTMAX, OP, SIGN)
TEST(STARTm100, ENDmINTMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTm100, ENDmINTMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTm100, ENDm100, STEPsINTMAX, OP, SIGN)
TEST(STARTm100, ENDm1, STEPsINTMAX, OP, SIGN)
TEST(STARTm100, END, STEPsINTMAX, OP, SIGN)
TEST(STARTm100, ENDsLONGMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTm100, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTm100, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN)
TEST(STARTm100, ENDsINTMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTm100, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTm100, ENDs100, STEPsINTMAX, OP, SIGN)
TEST(STARTm100, ENDs1, STEPsINTMAX, OP, SIGN)
TEST(STARTm1, ENDmLONGMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTm1, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTm1, ENDmINTMINm1, STEPsINTMAX, OP, SIGN)
TEST(STARTm1, ENDmINTMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTm1, ENDmINTMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTm1, ENDm100, STEPsINTMAX, OP, SIGN)
TEST(STARTm1, ENDm1, STEPsINTMAX, OP, SIGN)
TEST(STARTm1, END, STEPsINTMAX, OP, SIGN)
TEST(STARTm1, ENDsLONGMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTm1, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTm1, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN)
TEST(STARTm1, ENDsINTMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTm1, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTm1, ENDs100, STEPsINTMAX, OP, SIGN)
TEST(STARTm1, ENDs1, STEPsINTMAX, OP, SIGN)
TEST(START, ENDmLONGMIN, STEPsINTMAX, OP, SIGN)
TEST(START, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN)
TEST(START, ENDmINTMINm1, STEPsINTMAX, OP, SIGN)
TEST(START, ENDmINTMIN, STEPsINTMAX, OP, SIGN)
TEST(START, ENDmINTMINp1, STEPsINTMAX, OP, SIGN)
TEST(START, ENDm100, STEPsINTMAX, OP, SIGN)
TEST(START, ENDm1, STEPsINTMAX, OP, SIGN)
TEST(START, END, STEPsINTMAX, OP, SIGN)
TEST(START, ENDsLONGMAX, STEPsINTMAX, OP, SIGN)
TEST(START, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN)
TEST(START, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN)
TEST(START, ENDsINTMAX, STEPsINTMAX, OP, SIGN)
TEST(START, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN)
TEST(START, ENDs100, STEPsINTMAX, OP, SIGN)
TEST(START, ENDs1, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAX, ENDmLONGMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAX, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAX, ENDmINTMINm1, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAX, ENDmINTMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAX, ENDmINTMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAX, ENDm100, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAX, ENDm1, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAX, END, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAX, ENDsLONGMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAX, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAX, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAX, ENDsINTMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAX, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAX, ENDs100, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAX, ENDs1, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAXm1, ENDmLONGMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAXm1, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAXm1, ENDmINTMINm1, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAXm1, ENDmINTMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAXm1, ENDmINTMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAXm1, ENDm100, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAXm1, ENDm1, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAXm1, END, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAXm1, ENDsLONGMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAXm1, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAXm1, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAXm1, ENDsINTMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAXm1, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAXm1, ENDs100, STEPsINTMAX, OP, SIGN)
TEST(STARTsLONGMAXm1, ENDs1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXp1, ENDmLONGMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXp1, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXp1, ENDmINTMINm1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXp1, ENDmINTMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXp1, ENDmINTMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXp1, ENDm100, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXp1, ENDm1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXp1, END, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXp1, ENDsLONGMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXp1, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXp1, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXp1, ENDsINTMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXp1, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXp1, ENDs100, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXp1, ENDs1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAX, ENDmLONGMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAX, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAX, ENDmINTMINm1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAX, ENDmINTMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAX, ENDmINTMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAX, ENDm100, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAX, ENDm1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAX, END, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAX, ENDsLONGMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAX, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAX, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAX, ENDsINTMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAX, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAX, ENDs100, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAX, ENDs1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXm1, ENDmLONGMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXm1, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXm1, ENDmINTMINm1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXm1, ENDmINTMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXm1, ENDmINTMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXm1, ENDm100, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXm1, ENDm1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXm1, END, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXm1, ENDsLONGMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXm1, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXm1, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXm1, ENDsINTMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXm1, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXm1, ENDs100, STEPsINTMAX, OP, SIGN)
TEST(STARTsINTMAXm1, ENDs1, STEPsINTMAX, OP, SIGN)
TEST(STARTs100, ENDmLONGMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTs100, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTs100, ENDmINTMINm1, STEPsINTMAX, OP, SIGN)
TEST(STARTs100, ENDmINTMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTs100, ENDmINTMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTs100, ENDm100, STEPsINTMAX, OP, SIGN)
TEST(STARTs100, ENDm1, STEPsINTMAX, OP, SIGN)
TEST(STARTs100, END, STEPsINTMAX, OP, SIGN)
TEST(STARTs100, ENDsLONGMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTs100, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTs100, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN)
TEST(STARTs100, ENDsINTMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTs100, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTs100, ENDs100, STEPsINTMAX, OP, SIGN)
TEST(STARTs100, ENDs1, STEPsINTMAX, OP, SIGN)
TEST(STARTs1, ENDmLONGMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTs1, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTs1, ENDmINTMINm1, STEPsINTMAX, OP, SIGN)
TEST(STARTs1, ENDmINTMIN, STEPsINTMAX, OP, SIGN)
TEST(STARTs1, ENDmINTMINp1, STEPsINTMAX, OP, SIGN)
TEST(STARTs1, ENDm100, STEPsINTMAX, OP, SIGN)
TEST(STARTs1, ENDm1, STEPsINTMAX, OP, SIGN)
TEST(STARTs1, END, STEPsINTMAX, OP, SIGN)
TEST(STARTs1, ENDsLONGMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTs1, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTs1, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN)
TEST(STARTs1, ENDsINTMAX, STEPsINTMAX, OP, SIGN)
TEST(STARTs1, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN)
TEST(STARTs1, ENDs100, STEPsINTMAX, OP, SIGN)
TEST(STARTs1, ENDs1, STEPsINTMAX, OP, SIGN)
int main()
{
   CALL(STARTmLONGMIN, ENDmLONGMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmLONGMIN, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmLONGMIN, ENDmINTMINm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmLONGMIN, ENDmINTMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmLONGMIN, ENDmINTMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmLONGMIN, ENDm100, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmLONGMIN, ENDm1, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;

  tcount++;

  tcount++;

  tcount++;

  tcount++;

  tcount++;

  tcount++;

  tcount++;

  tcount++;
   CALL(STARTmLONGMINp1, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmLONGMINp1, ENDmINTMINm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmLONGMINp1, ENDmINTMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmLONGMINp1, ENDmINTMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmLONGMINp1, ENDm100, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmLONGMINp1, ENDm1, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;

  tcount++;

  tcount++;

  tcount++;

  tcount++;

  tcount++;

  tcount++;

  tcount++;
   CALL(STARTmINTMINm1, ENDmLONGMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINm1, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINm1, ENDmINTMINm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINm1, ENDmINTMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINm1, ENDmINTMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINm1, ENDm100, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINm1, ENDm1, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;
   CALL(STARTmINTMINm1, ENDsLONGMAX, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINm1, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINm1, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINm1, ENDsINTMAX, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINm1, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;

  tcount++;
   CALL(STARTmINTMIN, ENDmLONGMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMIN, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMIN, ENDmINTMINm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMIN, ENDmINTMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMIN, ENDmINTMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMIN, ENDm100, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMIN, ENDm1, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;
   CALL(STARTmINTMIN, ENDsLONGMAX, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMIN, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMIN, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMIN, ENDsINTMAX, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMIN, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;

  tcount++;
   CALL(STARTmINTMINp1, ENDmLONGMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINp1, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINp1, ENDmINTMINm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINp1, ENDmINTMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINp1, ENDmINTMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINp1, ENDm100, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINp1, ENDm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINp1, END, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINp1, ENDsLONGMAX, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINp1, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINp1, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINp1, ENDsINTMAX, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINp1, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINp1, ENDs100, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTmINTMINp1, ENDs1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTm100, ENDmLONGMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTm100, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTm100, ENDmINTMINm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTm100, ENDmINTMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTm100, ENDmINTMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTm100, ENDm100, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTm100, ENDm1, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;
   CALL(STARTm100, ENDsLONGMAX, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTm100, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTm100, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTm100, ENDsINTMAX, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTm100, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;

  tcount++;
   CALL(STARTm1, ENDmLONGMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTm1, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTm1, ENDmINTMINm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTm1, ENDmINTMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTm1, ENDmINTMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTm1, ENDm100, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTm1, ENDm1, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;
   CALL(STARTm1, ENDsLONGMAX, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTm1, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTm1, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTm1, ENDsINTMAX, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTm1, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;

  tcount++;
   CALL(START, ENDmLONGMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(START, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(START, ENDmINTMINm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(START, ENDmINTMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(START, ENDmINTMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(START, ENDm100, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(START, ENDm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(START, END, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(START, ENDsLONGMAX, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(START, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(START, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(START, ENDsINTMAX, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(START, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(START, ENDs100, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(START, ENDs1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsLONGMAX, ENDmLONGMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsLONGMAX, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsLONGMAX, ENDmINTMINm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsLONGMAX, ENDmINTMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsLONGMAX, ENDmINTMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsLONGMAX, ENDm100, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsLONGMAX, ENDm1, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;
   CALL(STARTsLONGMAX, ENDsLONGMAX, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;

  tcount++;

  tcount++;

  tcount++;

  tcount++;

  tcount++;
   CALL(STARTsLONGMAXm1, ENDmLONGMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsLONGMAXm1, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsLONGMAXm1, ENDmINTMINm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsLONGMAXm1, ENDmINTMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsLONGMAXm1, ENDmINTMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsLONGMAXm1, ENDm100, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsLONGMAXm1, ENDm1, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;
   CALL(STARTsLONGMAXm1, ENDsLONGMAX, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsLONGMAXm1, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;

  tcount++;

  tcount++;

  tcount++;

  tcount++;
   CALL(STARTsINTMAXp1, ENDmLONGMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAXp1, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAXp1, ENDmINTMINm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAXp1, ENDmINTMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAXp1, ENDmINTMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAXp1, ENDm100, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAXp1, ENDm1, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;
   CALL(STARTsINTMAXp1, ENDsLONGMAX, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAXp1, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAXp1, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;

  tcount++;

  tcount++;

  tcount++;
   CALL(STARTsINTMAX, ENDmLONGMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAX, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAX, ENDmINTMINm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAX, ENDmINTMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAX, ENDmINTMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAX, ENDm100, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAX, ENDm1, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;
   CALL(STARTsINTMAX, ENDsLONGMAX, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAX, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAX, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAX, ENDsINTMAX, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;

  tcount++;

  tcount++;
   CALL(STARTsINTMAXm1, ENDmLONGMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAXm1, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAXm1, ENDmINTMINm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAXm1, ENDmINTMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAXm1, ENDmINTMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAXm1, ENDm100, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAXm1, ENDm1, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;
   CALL(STARTsINTMAXm1, ENDsLONGMAX, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAXm1, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAXm1, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAXm1, ENDsINTMAX, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTsINTMAXm1, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;

  tcount++;
   CALL(STARTs100, ENDmLONGMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs100, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs100, ENDmINTMINm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs100, ENDmINTMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs100, ENDmINTMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs100, ENDm100, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs100, ENDm1, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;
   CALL(STARTs100, ENDsLONGMAX, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs100, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs100, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs100, ENDsINTMAX, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs100, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs100, ENDs100, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;
   CALL(STARTs1, ENDmLONGMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs1, ENDmLONGMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs1, ENDmINTMINm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs1, ENDmINTMIN, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs1, ENDmINTMINp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs1, ENDm100, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs1, ENDm1, STEPsINTMAX, OP, SIGN);
  tcount++;

  tcount++;
   CALL(STARTs1, ENDsLONGMAX, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs1, ENDsLONGMAXm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs1, ENDsINTMAXp1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs1, ENDsINTMAX, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs1, ENDsINTMAXm1, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs1, ENDs100, STEPsINTMAX, OP, SIGN);
  tcount++;
   CALL(STARTs1, ENDs1, STEPsINTMAX, OP, SIGN);
  tcount++;
}
