extern unsigned char v1 (signed short, signed char);
extern unsigned char (*v2) (signed short, signed char);
extern signed short v3 (signed char, signed int, unsigned char, signed char);
extern signed short (*v4) (signed char, signed int, unsigned char, signed char);
extern void v5 (unsigned char, unsigned int);
extern void (*v6) (unsigned char, unsigned int);
extern unsigned short v7 (signed char, signed int, signed char, signed int);
extern unsigned short (*v8) (signed char, signed int, signed char, signed int);
extern signed char v9 (unsigned short, unsigned char, signed int);
extern signed char (*v10) (unsigned short, unsigned char, signed int);
extern signed int v11 (unsigned short, signed int, unsigned char);
extern signed int (*v12) (unsigned short, signed int, unsigned char);
extern void v13 (signed int, signed int, unsigned int);
extern void (*v14) (signed int, signed int, unsigned int);
extern signed char v15 (void);
extern signed char (*v16) (void);
extern signed short v17 (signed int, signed int, signed char, unsigned short);
extern signed short (*v18) (signed int, signed int, signed char, unsigned short);
extern unsigned short v19 (unsigned int, signed char);
extern unsigned short (*v20) (unsigned int, signed char);
extern void v21 (void);
extern void (*v22) (void);
extern unsigned char v23 (signed int, unsigned short, unsigned short, signed char);
extern unsigned char (*v24) (signed int, unsigned short, unsigned short, signed char);
extern unsigned char v25 (unsigned short);
extern unsigned char (*v26) (unsigned short);
extern signed int v27 (signed int, unsigned char);
extern signed int (*v28) (signed int, unsigned char);
extern signed short v29 (signed char, unsigned char, signed short, signed short);
extern signed short (*v30) (signed char, unsigned char, signed short, signed short);
extern int history[];
extern int history_index;
extern int trace;
unsigned int v67 = 3U;
signed short v66 = -4;
unsigned char v65 = 7;
