set(openmp_tests
  0202_0086
  0202_0132
  0202_0133
  0202_0141
  0202_0142
  0202_0149
  0202_0150
  0202_0151
  0202_0156
  0202_0273
  0202_0274
  0202_0275
  0202_0276
  0202_0277
  0202_0278
  0202_0279
  0202_0280
  0202_0281
  0202_0282
  0202_0360
)
add_subdirectory(0202_0143)
add_subdirectory(0202_0144)
add_subdirectory(0202_0145)
add_subdirectory(0202_0146)
add_subdirectory(0202_0147)
llvm_singlesource_fujitsu(PREFIX "Fujitsu-C-")
if(TEST_SUITE_FUJITSU_ENABLE_${llvm_test_lang}_NON_OPENMP)
  set_property(SOURCE 0202_0075.c APPEND PROPERTY COMPILE_OPTIONS "-fno-inline-functions")
  set_property(SOURCE 0202_0076.c APPEND PROPERTY COMPILE_OPTIONS "-fno-inline-functions")
  set_property(SOURCE 0202_0077.c APPEND PROPERTY COMPILE_OPTIONS "-fno-inline-functions")
  set_property(SOURCE 0202_0078.c APPEND PROPERTY COMPILE_OPTIONS "-fno-inline-functions")
  set_property(SOURCE 0202_0079.c APPEND PROPERTY COMPILE_OPTIONS "-fno-inline-functions")
  set_property(SOURCE 0202_0080.c APPEND PROPERTY COMPILE_OPTIONS "-fno-inline-functions")
  set_property(SOURCE 0202_0148.c APPEND PROPERTY COMPILE_OPTIONS "-fsigned-char")
  set_property(SOURCE 0202_0157.c APPEND PROPERTY COMPILE_OPTIONS "-O1")
  set_property(TARGET Fujitsu-C-0202_0157 APPEND PROPERTY LINK_OPTIONS "-O1")
  set_property(SOURCE 0202_0158.c APPEND PROPERTY COMPILE_OPTIONS "-O1")
  set_property(TARGET Fujitsu-C-0202_0158 APPEND PROPERTY LINK_OPTIONS "-O1")
  set_property(SOURCE 0202_0159.c APPEND PROPERTY COMPILE_OPTIONS "-O1")
  set_property(TARGET Fujitsu-C-0202_0159 APPEND PROPERTY LINK_OPTIONS "-O1")
  set_property(SOURCE 0202_0160.c APPEND PROPERTY COMPILE_OPTIONS "-O1")
  set_property(TARGET Fujitsu-C-0202_0160 APPEND PROPERTY LINK_OPTIONS "-O1")
  set_property(SOURCE 0202_0161.c APPEND PROPERTY COMPILE_OPTIONS "-O1")
  set_property(TARGET Fujitsu-C-0202_0161 APPEND PROPERTY LINK_OPTIONS "-O1")
  set_property(SOURCE 0202_0162.c APPEND PROPERTY COMPILE_OPTIONS "-O1")
  set_property(TARGET Fujitsu-C-0202_0162 APPEND PROPERTY LINK_OPTIONS "-O1")
  set_property(SOURCE 0202_0163.c APPEND PROPERTY COMPILE_OPTIONS "-O1")
  set_property(TARGET Fujitsu-C-0202_0163 APPEND PROPERTY LINK_OPTIONS "-O1")
  set_property(TARGET Fujitsu-C-0202_0272 APPEND PROPERTY LINK_LIBRARIES "m")
  set_property(TARGET Fujitsu-C-0202_0283 APPEND PROPERTY LINK_LIBRARIES "m")
  set_property(TARGET Fujitsu-C-0202_0284 APPEND PROPERTY LINK_LIBRARIES "m")
  set_property(TARGET Fujitsu-C-0202_0285 APPEND PROPERTY LINK_LIBRARIES "m")
  set_property(SOURCE 0202_0288.c APPEND PROPERTY COMPILE_OPTIONS "-fno-builtin")
  set_property(TARGET Fujitsu-C-0202_0288 APPEND PROPERTY LINK_LIBRARIES "m")
  set_property(TARGET Fujitsu-C-0202_0410 APPEND PROPERTY LINK_LIBRARIES "m")
  set_property(TARGET Fujitsu-C-0202_0411 APPEND PROPERTY LINK_LIBRARIES "m")
  set_property(TARGET Fujitsu-C-0202_0412 APPEND PROPERTY LINK_LIBRARIES "m")
endif()
