ELEMENTAL FUNCTION ADJUSTC (S)
   CHARACTER(LEN=*), INTENT(IN) :: S
   CHARACTER(LEN=LEN(S)) :: ADJUSTC

   INTEGER :: ILEFT, IRIGHT, IMBALANCE

   ILEFT = VERIFY (S, ' ', BACK=.FALSE.)
   IF (ILEFT == 0) THEN
      ADJUSTC = S
   ELSE
      IRIGHT = LEN (S) - VERIFY (S(ILEFT:), ' ', BACK=.TRUE.) - (ILEFT-1)
      ILEFT  = ILEFT - 1
      IMBALANCE = (IRIGHT-ILEFT)/2
      IF (IMBALANCE > 0) THEN
         ADJUSTC = S(LEN(S)+1-IMBALANCE:) // S
      ELSE
         ADJUSTC = S(1-IMBALANCE:)
      END IF
   END IF
END FUNCTION ADJUSTC
MODULE CHARACTER_MAPS

   TYPE, PUBLIC :: MAP
      PRIVATE
      CHARACTER(LEN=1) :: TRANSLATION (0:255)
   END TYPE MAP

   TYPE(MAP), PARAMETER, PUBLIC :: UPPER_CASE_MAP_8859_1 = MAP ( &
      (/ (CHAR(I),I=0,96), (CHAR(I-32),I=97,122), &
         (CHAR(I),I=123,223), (CHAR(I-32),I=224,246), CHAR(247), &
         (CHAR(I-32),I=248,255) /) )
   TYPE(MAP), PARAMETER, PUBLIC :: LOWER_CASE_MAP_8859_1 = MAP ( &
      (/ (CHAR(I),I=0,127), (CHAR(0),I=128,255) /) )
   TYPE(MAP), PARAMETER, PUBLIC :: ASCII_MAP = MAP ( &
      (/ (CHAR(I),I=0,127), (CHAR(0),I=128,255) /) )
   TYPE(MAP), PARAMETER, PUBLIC :: IDENTITY_MAP = MAP ( &
      (/ (CHAR(I),I=0,255) /) )
   contains
   ELEMENTAL FUNCTION TRANSLATION (S, M)
      CHARACTER(LEN=*), INTENT(IN) :: S
      TYPE(MAP), INTENT(IN) :: M
      CHARACTER(LEN=LEN(S)) :: TRANSLATION
      FORALL (I=1:LEN(S))
         TRANSLATION(I:I) = M%TRANSLATION(ICHAR(S(I:I)))
      END FORALL
   END FUNCTION TRANSLATION

   ELEMENTAL FUNCTION IS_IN_MAP (S, M)
      CHARACTER(LEN=*), INTENT(IN) :: S
      TYPE(MAP), INTENT(IN) :: M
      LOGICAL :: IS_IN_MAP
      IS_IN_MAP = (TRANSLATION(S,M)==S)
   END FUNCTION IS_IN_MAP

   SUBROUTINE SET (M, FROM, TO)
      TYPE(MAP), INTENT(IN OUT) :: M
      CHARACTER(LEN=*), INTENT(IN) :: FROM, TO
      IF (LEN(TO) < LEN(FROM)) STOP 'ERROR'
      FORALL (I=1:LEN(FROM))
         M%TRANSLATION(ICHAR(FROM(I:I))) = TO(I:I)
      END FORALL
   END SUBROUTINE SET

   ELEMENTAL FUNCTION IS_ASCII (S)
      CHARACTER(LEN=*), INTENT(IN) :: S
      LOGICAL :: IS_ASCII
      IS_ASCII = IS_IN_MAP (S, ASCII_MAP)
   END FUNCTION IS_ASCII

   ELEMENTAL FUNCTION TO_UPPER_8859_1 (S)
      CHARACTER(LEN=*), INTENT(IN) :: S
      CHARACTER(LEN=LEN(S)) :: TO_UPPER
      TO_UPPER = TRANSLATION (S, UPPER_CASE_MAP_8859_1)
   END FUNCTION TO_UPPER_8859_1

END MODULE CHARACTER_MAPS
use CHARACTER_MAPS
print *,'pass'
end
