extern unsigned int v1 (void);
extern unsigned int (*v2) (void);
extern void v3 (signed short);
extern void (*v4) (signed short);
extern signed char v5 (signed char, signed char);
extern signed char (*v6) (signed char, signed char);
extern signed short v7 (signed short);
extern signed short (*v8) (signed short);
extern unsigned int v9 (unsigned int);
extern unsigned int (*v10) (unsigned int);
extern unsigned short v11 (unsigned int, unsigned char);
extern unsigned short (*v12) (unsigned int, unsigned char);
extern signed char v13 (signed short, signed int, signed char, signed char);
extern signed char (*v14) (signed short, signed int, signed char, signed char);
extern unsigned int v15 (unsigned char, unsigned int, unsigned int);
extern unsigned int (*v16) (unsigned char, unsigned int, unsigned int);
extern signed short v17 (unsigned short, signed int, signed int);
extern signed short (*v18) (unsigned short, signed int, signed int);
extern signed char v19 (unsigned char);
extern signed char (*v20) (unsigned char);
extern void v21 (signed char, signed short, signed int, signed char);
extern void (*v22) (signed char, signed short, signed int, signed char);
extern unsigned short v23 (signed char, unsigned char, signed int, unsigned char);
extern unsigned short (*v24) (signed char, unsigned char, signed int, unsigned char);
extern signed char v25 (void);
extern signed char (*v26) (void);
extern unsigned char v27 (signed short);
extern unsigned char (*v28) (signed short);
extern unsigned short v29 (unsigned char);
extern unsigned short (*v30) (unsigned char);
extern int history[];
extern int history_index;
extern int trace;
signed char v56 = -4;
signed char v55 = 1;
unsigned char v54 = 2;
