extern void v1 (unsigned int, signed int);
extern void (*v2) (unsigned int, signed int);
extern signed int v3 (unsigned int, unsigned int, unsigned short);
extern signed int (*v4) (unsigned int, unsigned int, unsigned short);
extern unsigned int v5 (signed int, signed char, unsigned char);
extern unsigned int (*v6) (signed int, signed char, unsigned char);
extern signed int v7 (unsigned short, signed char, unsigned int);
extern signed int (*v8) (unsigned short, signed char, unsigned int);
extern signed short v9 (void);
extern signed short (*v10) (void);
extern unsigned int v11 (void);
extern unsigned int (*v12) (void);
extern signed int v13 (signed char, signed char);
extern signed int (*v14) (signed char, signed char);
extern void v15 (unsigned char, unsigned int, unsigned short);
extern void (*v16) (unsigned char, unsigned int, unsigned short);
extern unsigned int v17 (signed char, unsigned short, unsigned int, signed char);
extern unsigned int (*v18) (signed char, unsigned short, unsigned int, signed char);
extern unsigned short v19 (unsigned short, signed short, signed int, signed short);
extern unsigned short (*v20) (unsigned short, signed short, signed int, signed short);
extern signed char v21 (void);
extern signed char (*v22) (void);
extern void v23 (unsigned short, signed char);
extern void (*v24) (unsigned short, signed char);
extern signed int v25 (unsigned short, unsigned int, signed int, signed short);
extern signed int (*v26) (unsigned short, unsigned int, signed int, signed short);
extern void v27 (void);
extern void (*v28) (void);
extern signed int v29 (unsigned short, signed short, unsigned short);
extern signed int (*v30) (unsigned short, signed short, unsigned short);
extern int history[];
extern int history_index;
extern int trace;
signed char v100 = 2;
signed char v99 = -1;
unsigned short v98 = 2;
