SUBROUTINE FOO(A,N)
  REAL(8),DIMENSION(1:N)::A
  LOGICAL(8),DIMENSION(1:N)::B
  INTEGER I,J,N
  DO I=1,N
     A(I) = A(I) + I
     IF(B(I).EQV..TRUE.) THEN
        GOTO 10
     END IF
  ENDDO
10 J=I
END SUBROUTINE FOO

PROGRAM MAIN
END PROGRAM MAIN
