      call s1
      print *,'pass'
      end
      subroutine s1
      call ss1
      call ss2
      end
      subroutine ss1
      integer ,parameter::a1(1:0)=1
      integer ,parameter::a2(1:0,   2)=1
      integer ,parameter::a3(   2,1:0)=1
      integer ,parameter::v0(0)=1,v2(2)=(/1,2/)
      integer ,parameter,dimension(1)::x01=lbound(a1)
      integer ,parameter,dimension(1)::x02=lbound(a1(1:0))
      integer ,parameter,dimension(1)::x03=lbound(a1( 1:0))
      integer ,parameter,dimension(1)::x04=lbound(a1(  : ))
      integer ,parameter,dimension(1)::x05=lbound(a2(1:0,2))
      integer ,parameter,dimension(1)::x06=lbound(a2( 1:0,2))
      integer ,parameter,dimension(1)::x07=lbound(a2(  : ,2))
      integer ,parameter,dimension(1)::x08=lbound(a2(1:0,1))
      integer ,parameter,dimension(1)::x09=lbound(a2( 1:0,1))
      integer ,parameter,dimension(1)::x10=lbound(a2(  : ,1))
      integer ,parameter,dimension(2)::x11=lbound(a2(  : ,1:2))
      integer ,parameter,dimension(2)::x12=lbound(a2(  : , : ))
      integer ,parameter,dimension(2)::x13=lbound(a2(  : ,2:1))
      integer ,parameter,dimension(2)::x14=lbound(a2(  : ,2:1))
      integer ,parameter,dimension(2)::x15=lbound(a2(  : ,v2 ))
      integer ,parameter,dimension(2)::x16=lbound(a2(  : ,v0 ))
      integer ,parameter,dimension(1)::x17=lbound(a2( v0,1))
      integer ,parameter,dimension(2)::x18=lbound(a2( v0,1:2))
      integer ,parameter,dimension(2)::x19=lbound(a2( v0, : ))
      integer ,parameter,dimension(2)::x20=lbound(a2( v0,2:1))
      integer ,parameter,dimension(2)::x21=lbound(a2( v0,2:1))
      integer ,parameter,dimension(2)::x22=lbound(a2( v0,v2 ))
      integer ,parameter,dimension(2)::x23=lbound(a2( v0,v0 ))
      integer ,parameter,dimension(1)::x24=lbound(a3(2, 1:0))
      integer ,parameter,dimension(1)::x25=lbound(a3(2, 1:0))
      integer ,parameter,dimension(1)::x26=lbound(a3(2,   : ))
      integer ,parameter,dimension(1)::x27=lbound(a3(1,1:0))
      integer ,parameter,dimension(1)::x28=lbound(a3(1, 1:0))
      integer ,parameter,dimension(1)::x29=lbound(a3(1,  : ))
      integer ,parameter,dimension(2)::x30=lbound(a3(  1:2,:))
      integer ,parameter,dimension(2)::x31=lbound(a3(   : ,:))
      integer ,parameter,dimension(2)::x32=lbound(a3(  2:1,:))
      integer ,parameter,dimension(2)::x33=lbound(a3(  2:1,:))
      integer ,parameter,dimension(2)::x34=lbound(a3(  v2 ,:))
      integer ,parameter,dimension(2)::x35=lbound(a3(  v0 ,:))
      integer ,parameter,dimension(1)::x36=lbound(a3( 1,v0))
      integer ,parameter,dimension(2)::x37=lbound(a3( 1:2,v0))
      integer ,parameter,dimension(2)::x38=lbound(a3(  : ,v0))
      integer ,parameter,dimension(2)::x39=lbound(a3( 2:1,v0))
      integer ,parameter,dimension(2)::x40=lbound(a3( 2:1,v0))
      integer ,parameter,dimension(2)::x41=lbound(a3( v2 ,v0))
      integer ,parameter,dimension(2)::x42=lbound(a3( v0 ,v0))
      integer ,parameter,dimension(2)::x43=lbound(a3(100:0 ,v0))
      if (any(x01/=1))print *,'fail'
      if (any(x02/=1))print *,'fail'
      if (any(x03/=1))print *,'fail'
      if (any(x04/=1))print *,'fail'
      if (any(x05/=1))print *,'fail'
      if (any(x06/=1))print *,'fail'
      if (any(x07/=1))print *,'fail'
      if (any(x08/=1))print *,'fail'
      if (any(x09/=1))print *,'fail'
      if (any(x10/=1))print *,'fail'
      if (any(x11/=1))print *,'fail'
      if (any(x12/=1))print *,'fail'
      if (any(x13/=1))print *,'fail'
      if (any(x14/=1))print *,'fail'
      if (any(x15/=1))print *,'fail'
      if (any(x16/=1))print *,'fail'
      if (any(x17/=1))print *,'fail'
      if (any(x18/=1))print *,'fail'
      if (any(x19/=1))print *,'fail'
      if (any(x20/=1))print *,'fail'
      if (any(x21/=1))print *,'fail'
      if (any(x22/=1))print *,'fail'
      if (any(x23/=1))print *,'fail'
      if (any(x24/=1))print *,'fail'
      if (any(x25/=1))print *,'fail'
      if (any(x26/=1))print *,'fail'
      if (any(x27/=1))print *,'fail'
      if (any(x28/=1))print *,'fail'
      if (any(x29/=1))print *,'fail'
      if (any(x30/=1))print *,'fail'
      if (any(x31/=1))print *,'fail'
      if (any(x32/=1))print *,'fail'
      if (any(x33/=1))print *,'fail'
      if (any(x34/=1))print *,'fail'
      if (any(x35/=1))print *,'fail'
      if (any(x36/=1))print *,'fail'
      if (any(x37/=1))print *,'fail'
      if (any(x38/=1))print *,'fail'
      if (any(x39/=1))print *,'fail'
      if (any(x40/=1))print *,'fail'
      if (any(x41/=1))print *,'fail'
      if (any(x42/=1))print *,'fail'
      if (any(x43/=1))print *,'fail'
      end
      subroutine ss2
      integer ,parameter::a1(1:0)=1
      integer ,parameter::a2(1:0,   2)=1
      integer ,parameter::a3(   2,1:0)=1
      integer ,parameter::v0(0)=1,v2(2)=(/1,2/)
      integer ,parameter,dimension(1)::x01=ubound(a1)
      integer ,parameter,dimension(1)::x02=ubound(a1(1:0))
      integer ,parameter,dimension(1)::x03=ubound(a1( 1:0))
      integer ,parameter,dimension(1)::x04=ubound(a1(  : ))
      integer ,parameter,dimension(1)::x05=ubound(a2(1:0,2))
      integer ,parameter,dimension(1)::x06=ubound(a2( 1:0,2))
      integer ,parameter,dimension(1)::x07=ubound(a2(  : ,2))
      integer ,parameter,dimension(1)::x08=ubound(a2(1:0,1))
      integer ,parameter,dimension(1)::x09=ubound(a2( 1:0,1))
      integer ,parameter,dimension(1)::x10=ubound(a2(  : ,1))
      integer ,parameter,dimension(2)::x11=ubound(a2(  : ,1:2))
      integer ,parameter,dimension(2)::x12=ubound(a2(  : , : ))
      integer ,parameter,dimension(2)::x13=ubound(a2(  : ,2:1))
      integer ,parameter,dimension(2)::x14=ubound(a2(  : ,2:1))
      integer ,parameter,dimension(2)::x15=ubound(a2(  : ,v2 ))
      integer ,parameter,dimension(2)::x16=ubound(a2(  : ,v0 ))
      integer ,parameter,dimension(1)::x17=ubound(a2( v0,1))
      integer ,parameter,dimension(2)::x18=ubound(a2( v0,1:2))
      integer ,parameter,dimension(2)::x19=ubound(a2( v0, : ))
      integer ,parameter,dimension(2)::x20=ubound(a2( v0,2:1))
      integer ,parameter,dimension(2)::x21=ubound(a2( v0,2:1))
      integer ,parameter,dimension(2)::x22=ubound(a2( v0,v2 ))
      integer ,parameter,dimension(2)::x23=ubound(a2( v0,v0 ))
      integer ,parameter,dimension(1)::x24=ubound(a3(2, 1:0))
      integer ,parameter,dimension(1)::x25=ubound(a3(2, 1:0))
      integer ,parameter,dimension(1)::x26=ubound(a3(2,   : ))
      integer ,parameter,dimension(1)::x27=ubound(a3(1,1:0))
      integer ,parameter,dimension(1)::x28=ubound(a3(1, 1:0))
      integer ,parameter,dimension(1)::x29=ubound(a3(1,  : ))
      integer ,parameter,dimension(2)::x30=ubound(a3(  1:2,:))
      integer ,parameter,dimension(2)::x31=ubound(a3(   : ,:))
      integer ,parameter,dimension(2)::x32=ubound(a3(  2:1,:))
      integer ,parameter,dimension(2)::x33=ubound(a3(  2:1,:))
      integer ,parameter,dimension(2)::x34=ubound(a3(  v2 ,:))
      integer ,parameter,dimension(2)::x35=ubound(a3(  v0 ,:))
      integer ,parameter,dimension(1)::x36=ubound(a3( 1,v0))
      integer ,parameter,dimension(2)::x37=ubound(a3( 1:2,v0))
      integer ,parameter,dimension(2)::x38=ubound(a3(  : ,v0))
      integer ,parameter,dimension(2)::x39=ubound(a3( 2:1,v0))
      integer ,parameter,dimension(2)::x40=ubound(a3( 2:1,v0))
      integer ,parameter,dimension(2)::x41=ubound(a3( v2 ,v0))
      integer ,parameter,dimension(2)::x42=ubound(a3( v0 ,v0))
      integer ,parameter,dimension(2)::x43=ubound(a3(100:0 ,v0))
      if (any(x01/=0))print *,'fail'
      if (any(x02/=0))print *,'fail'
      if (any(x03/=0))print *,'fail'
      if (any(x04/=0))print *,'fail'
      if (any(x05/=0))print *,'fail'
      if (any(x06/=0))print *,'fail'
      if (any(x07/=0))print *,'fail'
      if (any(x08/=0))print *,'fail'
      if (any(x09/=0))print *,'fail'
      if (any(x10/=0))print *,'fail'
      if (any(x11/=(/0,2/)))print *,'fail'
      if (any(x12/=(/0,2/)))print *,'fail'
      if (any(x13/=0))print *,'fail'
      if (any(x14/=0))print *,'fail'
      if (any(x15/=(/0,2/)))print *,'fail'
      if (any(x16/=0))print *,'fail'
      if (any(x17/=0))print *,'fail'
      if (any(x18/=(/0,2/)))print *,'fail'
      if (any(x19/=(/0,2/)))print *,'fail'
      if (any(x20/=0))print *,'fail'
      if (any(x21/=0))print *,'fail'
      if (any(x22/=(/0,2/)))print *,'fail'
      if (any(x23/=0))print *,'fail'
      if (any(x24/=0))print *,'fail'
      if (any(x25/=0))print *,'fail'
      if (any(x26/=0))print *,'fail'
      if (any(x27/=0))print *,'fail'
      if (any(x28/=0))print *,'fail'
      if (any(x29/=0))print *,'fail'
      if (any(x30/=(/2,0/)))print *,'fail'
      if (any(x31/=(/2,0/)))print *,'fail'
      if (any(x32/=0))print *,'fail'
      if (any(x33/=0))print *,'fail'
      if (any(x34/=(/2,0/)))print *,'fail'
      if (any(x35/=0))print *,'fail'
      if (any(x36/=0))print *,'fail'
      if (any(x37/=(/2,0/)))print *,'fail'
      if (any(x38/=(/2,0/)))print *,'fail'
      if (any(x39/=0))print *,'fail'
      if (any(x40/=0))print *,'fail'
      if (any(x41/=(/2,0/)))print *,'fail'
      if (any(x42/=0))print *,'fail'
      if (any(x43/=0))print *,'fail'
      end
