extern signed char v3 (signed int, signed char, signed short, unsigned char);
extern signed char (*v4) (signed int, signed char, signed short, unsigned char);
extern void v5 (signed int, signed short);
extern void (*v6) (signed int, signed short);
extern unsigned int v7 (void);
extern unsigned int (*v8) (void);
extern signed short v9 (signed char, unsigned short, signed int);
extern signed short (*v10) (signed char, unsigned short, signed int);
extern signed char v11 (unsigned int, signed short);
extern signed char (*v12) (unsigned int, signed short);
extern unsigned short v13 (signed short, unsigned int, unsigned char, unsigned int);
extern unsigned short (*v14) (signed short, unsigned int, unsigned char, unsigned int);
extern signed short v15 (void);
extern signed short (*v16) (void);
extern void v17 (signed short, signed char);
extern void (*v18) (signed short, signed char);
extern unsigned short v19 (unsigned short, unsigned short, unsigned short);
extern unsigned short (*v20) (unsigned short, unsigned short, unsigned short);
extern unsigned short v21 (unsigned char);
extern unsigned short (*v22) (unsigned char);
extern unsigned int v23 (void);
extern unsigned int (*v24) (void);
extern signed char v25 (signed char, unsigned short, signed char);
extern signed char (*v26) (signed char, unsigned short, signed char);
extern unsigned int v27 (unsigned short);
extern unsigned int (*v28) (unsigned short);
extern unsigned char v29 (unsigned int, signed int, unsigned short);
extern unsigned char (*v30) (unsigned int, signed int, unsigned short);
extern int history[];
extern int history_index;
extern int trace;
unsigned int v73 = 2U;
signed short v72 = -4;
unsigned char v71 = 3;
