PROGRAM p1
INTEGER ::K,L,M,X,O,N
X=0
K=10
L=20
M=30
N=40
O=50
DO CONCURRENT(K=1:3,K>=2)
  DO CONCURRENT(L=1:3)
    DO CONCURRENT(M=1:3,M>=1)
    END DO
    DO CONCURRENT(N=1:4,K==L)
        X=X+1
     DO CONCURRENT(O=2:4,N>2)
     END DO
   END DO
  END DO
END DO
IF(X==8 .AND. K==10 .AND. L==20 .AND. M==30 .AND. N==40 .AND. O==50) THEN
 PRINT *,"PASS"
ELSE
 PRINT *,"FAIL",X,K,L,M,N,O
END IF
END PROGRAM
