PROGRAM MAIN
IMPLICIT NONE
INTEGER :: K,start1,END1,X,start2,END2,L
INTEGER :: MULT=0,ADD=0
start1=1
END1=5
start2=2
END2=4
X=0
K=10
L=30
DO CONCURRENT(K=start1:END1)
  DO CONCURRENT(L=start2:END2)
    ASSOCIATE(MULT => K*L, ADD => K+L)
      IF(MULT == ADD) THEN
        X=X+1
      ELSE IF(ADD+1 == MULT) THEN
        X=X+2
      END IF
    END ASSOCIATE
  END DO
END DO
IF (X == 5 .AND. ADD==0 .AND. MULT==0 .AND. K==10 .AND. L==30) THEN
 Print *,"PASS"
ELSE
 Print *,"FAIL",X,ADD,MULT
END IF
END PROGRAM
