extern signed char v1 (unsigned int, signed int, unsigned char, unsigned char);
extern signed char (*v2) (unsigned int, signed int, unsigned char, unsigned char);
extern unsigned char v3 (signed short);
extern unsigned char (*v4) (signed short);
extern unsigned short v5 (void);
extern unsigned short (*v6) (void);
extern unsigned char v7 (unsigned int, signed int);
extern unsigned char (*v8) (unsigned int, signed int);
extern signed int v9 (signed short, signed char, unsigned int, unsigned char);
extern signed int (*v10) (signed short, signed char, unsigned int, unsigned char);
extern unsigned char v13 (void);
extern unsigned char (*v14) (void);
extern unsigned char v15 (void);
extern unsigned char (*v16) (void);
extern signed char v17 (unsigned short);
extern signed char (*v18) (unsigned short);
extern unsigned char v19 (signed int, signed int, signed short);
extern unsigned char (*v20) (signed int, signed int, signed short);
extern unsigned char v21 (unsigned int, signed int);
extern unsigned char (*v22) (unsigned int, signed int);
extern void v23 (unsigned short, signed char);
extern void (*v24) (unsigned short, signed char);
extern unsigned char v27 (unsigned char, unsigned char);
extern unsigned char (*v28) (unsigned char, unsigned char);
extern signed short v29 (signed char);
extern signed short (*v30) (signed char);
extern int history[];
extern int history_index;
extern int trace;
unsigned short v57 = 6;
signed short v56 = 0;
unsigned int v55 = 7U;
