extern signed char v3 (void);
extern signed char (*v4) (void);
extern unsigned char v7 (unsigned int, signed char);
extern unsigned char (*v8) (unsigned int, signed char);
extern signed short v9 (void);
extern signed short (*v10) (void);
extern unsigned char v11 (unsigned int, unsigned char, unsigned char);
extern unsigned char (*v12) (unsigned int, unsigned char, unsigned char);
extern unsigned short v13 (void);
extern unsigned short (*v14) (void);
extern signed short v15 (unsigned int, unsigned short, signed int);
extern signed short (*v16) (unsigned int, unsigned short, signed int);
extern unsigned char v17 (unsigned int);
extern unsigned char (*v18) (unsigned int);
extern signed int v19 (void);
extern signed int (*v20) (void);
extern void v21 (signed short, unsigned int, signed int);
extern void (*v22) (signed short, unsigned int, signed int);
extern unsigned char v23 (void);
extern unsigned char (*v24) (void);
extern signed int v25 (signed int, signed int, signed short, unsigned short);
extern signed int (*v26) (signed int, signed int, signed short, unsigned short);
extern signed char v29 (void);
extern signed char (*v30) (void);
extern int history[];
extern int history_index;
extern int trace;
unsigned int v76 = 3U;
unsigned int v75 = 0U;
unsigned char v74 = 5;
