extern signed char v1 (signed short, signed char, signed char);
extern signed char (*v2) (signed short, signed char, signed char);
extern unsigned int v3 (unsigned short, signed char, unsigned int);
extern unsigned int (*v4) (unsigned short, signed char, unsigned int);
extern unsigned short v5 (signed short, signed short);
extern unsigned short (*v6) (signed short, signed short);
extern unsigned short v7 (unsigned short);
extern unsigned short (*v8) (unsigned short);
extern unsigned char v9 (signed int, signed char, signed short, signed short);
extern unsigned char (*v10) (signed int, signed char, signed short, signed short);
extern signed short v11 (signed short, signed int);
extern signed short (*v12) (signed short, signed int);
extern signed short v13 (signed int, signed int, unsigned short, signed short);
extern signed short (*v14) (signed int, signed int, unsigned short, signed short);
extern signed char v15 (void);
extern signed char (*v16) (void);
extern unsigned char v17 (unsigned char, unsigned short, signed short);
extern unsigned char (*v18) (unsigned char, unsigned short, signed short);
extern signed int v19 (void);
extern signed int (*v20) (void);
extern unsigned short v21 (signed char, unsigned char);
extern unsigned short (*v22) (signed char, unsigned char);
extern unsigned int v23 (signed int, signed int, signed int);
extern unsigned int (*v24) (signed int, signed int, signed int);
extern unsigned char v25 (unsigned short, unsigned int);
extern unsigned char (*v26) (unsigned short, unsigned int);
extern signed short v29 (unsigned short);
extern signed short (*v30) (unsigned short);
extern int history[];
extern int history_index;
extern int trace;
signed char v136 = 3;
unsigned short v135 = 5;
signed int v134 = -3;
