
#include <stdio.h>

  struct t {
           signed   char      b01:1;
           unsigned char      b02:2;
           signed   short int b03:3;
           unsigned short int b04:4;
           signed   int       b05:5;
           unsigned int       b06:6;
  } x;
  struct s {
           signed   char      b01:8;
           unsigned char      b02:8;
           signed   short int b03:16;
           unsigned short int b04:16;
           signed   int       b05:32;
           unsigned int       b06:32;
  } y;
int 
dpmk2015 (void){
  char      i1;
  short int i2;
  int       i4;
            i1=1;i2=0;i4=1;
  x.b01=i1; 
            if (x.b01==-1) printf("**dpmk2015-(01)** OK\n");
            else          printf("**dpmk2015-(01)** NG x.b01=%1x\n",x.b01);
  x.b02=i1;
            if (x.b02==1) printf("**dpmk2015-(02)** OK x.b02=%1x\n",x.b02);
            else          printf("**dpmk2015-(02)** NG x.b02=%1x\n",x.b02);
  x.b03=i1;
            if (x.b03==1) printf("**dpmk2015-(03)** OK x.b03=%.4x\n",x.b03);
            else          printf("**dpmk2015-(03)** NG x.b03=%.4x\n",x.b03);
  x.b04=i1;
            if (x.b04==1) printf("**dpmk2015-(04)** OK x.b04=%.4x\n",x.b04);
            else          printf("**dpmk2015-(04)** NG x.b04=%.4x\n",x.b04);
  x.b05=i1;
            if (x.b05==1) printf("**dpmk2015-(05)** OK x.b05=%.8x\n",x.b05);
            else          printf("**dpmk2015-(05)** NG x.b05=%.8x\n",x.b05);
  x.b06=i1; 
            if (x.b06==1) printf("**dpmk2015-(06)** OK x.b06=%.8x\n",x.b06);
            else          printf("**dpmk2015-(06)** NG x.b06=%.8x\n",x.b06);
  x.b01=i2; 
            if (x.b01==0) printf("**dpmk2015-(07)** OK x.b01=%.1x\n",x.b01);
            else          printf("**dpmk2015-(07)** NG x.b01=%.1x\n",x.b01);
  x.b02=i2; 
            if (x.b02==0) printf("**dpmk2015-(08)** OK x.b02=%.1x\n",x.b02);
            else          printf("**dpmk2015-(08)** NG x.b02=%.1x\n",x.b02);
  x.b03=i2;
            if (x.b03==0) printf("**dpmk2015-(09)** OK x.b03=%.4x\n",x.b03);
            else          printf("**dpmk2015-(09)** NG x.b03=%.4x\n",x.b03);
  x.b04=i2; 
            if (x.b04==0) printf("**dpmk2015-(10)** OK x.b04=%.4x\n",x.b04);
            else          printf("**dpmk2015-(10)** NG x.b04=%.4x\n",x.b04);
  x.b05=i2;
            if (x.b05==0) printf("**dpmk2015-(11)** OK x.b05=%.8x\n",x.b05);
            else          printf("**dpmk2015-(11)** NG x.b05=%.8x\n",x.b05);
  x.b06=i2; 
            if (x.b06==0) printf("**dpmk2015-(12)** OK x.b06=%.8x\n",x.b06);
            else          printf("**dpmk2015-(12)** NG x.b06=%.8x\n",x.b06);
  x.b01=i4;
            if (x.b01==-1) printf("**dpmk2015-(13)** OK\n");
            else          printf("**dpmk2015-(13)** NG x.b01=%.1x\n",x.b01);
  x.b02=i4; 
            if (x.b02==1) printf("**dpmk2015-(14)** OK x.b02=%.1x\n",x.b02);
            else          printf("**dpmk2015-(14)** NG x.b02=%.1x\n",x.b02);
  x.b03=i4; 
            if (x.b03==1) printf("**dpmk2015-(15)** OK x.b03=%.4x\n",x.b03);
            else          printf("**dpmk2015-(15)** NG x.b03=%.4x\n",x.b03);
  x.b04=i4; 
            if (x.b04==1) printf("**dpmk2015-(16)** OK x.b04=%.4x\n",x.b04);
            else          printf("**dpmk2015-(16)** NG x.b04=%.4x\n",x.b04);
  x.b05=i4; 
            if (x.b05==1) printf("**dpmk2015-(17)** OK x.b05=%.8x\n",x.b05);
            else          printf("**dpmk2015-(17)** NG x.b05=%.8x\n",x.b05);
  x.b06=i4;
            if (x.b06==1) printf("**dpmk2015-(18)** OK x.b06=%.8x\n",x.b06);
            else          printf("**dpmk2015-(18)** NG x.b06=%.8x\n",x.b06);
 
  y.b01=i1; 
            if (y.b01==1) printf("**dpmk2015-(19)** OK y.b01=%.8x\n",y.b01);
            else          printf("**dpmk2015-(19)** NG y.b01=%.8x\n",y.b01);
  y.b02=i1; 
            if (y.b02==1) printf("**dpmk2015-(20)** OK y.b02=%.8x\n",y.b02);
            else          printf("**dpmk2015-(20)** NG y.b02=%.8x\n",y.b02);
  y.b03=i2; 
            if (y.b03==0) printf("**dpmk2015-(21)** OK y.b03=%.16x\n",y.b03);
            else          printf("**dpmk2015-(21)** NG y.b03=%.16x\n",y.b03);
  y.b04=i2; 
            if (y.b04==0) printf("**dpmk2015-(22)** OK y.b04=%.16x\n",y.b04);
            else          printf("**dpmk2015-(22)** NG y.b04=%.16x\n",y.b04);
  y.b05=i4; 
            if (y.b05==1) printf("**dpmk2015-(23)** OK y.b05=%.32x\n",y.b05);
            else          printf("**dpmk2015-(23)** NG y.b05=%.32x\n",y.b05);
  y.b06=i4;
            if (y.b06==1) printf("**dpmk2015-(24)** OK y.b06=%.32x\n",y.b06);
            else          printf("**dpmk2015-(24)** NG y.b06=%.32x\n",y.b06);
 
}

#define N 100
#define ANS 7106

int 
estreg15 (void)
{
  int i, j;
  int a[N][N];
  int sum = 0;
  int v, w;

  for (i = 0; i < N; i++) {
    for (j = 0; j < N; j++) {
	a[i][j] = i*j % 4;
    }
  }

  v = a[34][15]*a[48][22] % 3;
  w = a[17][33]*a[27][42] % 3;

  for (i = 15; i < N - 15; i++) {
    a[i][0] = v * w;
    a[i][1] = j + w;
    a[i][3] = v * w;
    a[i-1][4] = v * w;
    a[i][5] = j + w;
    a[i][6] = v * w;
    a[i][7] = v * w;
    a[i][8] = v * w;
    a[i][9] = v * w;
    a[i][10] = v * w;
    a[i][j-9] = j + w;
    a[i][j-8] = v * w;
    a[i][j-7] = j + w;
    a[i][j-6] = v * w;
    a[i-2][j-5] = j + w;
    a[i][j-4] = v * w;
    a[i][j-3] = j + w;
    a[i][j-2] = v * w;
    a[i][j-1] = j + w;
    a[i][11] = v * w;
    a[i][12] = v * w;
    a[i][13] = j + w;
    a[i][14] = v * w;
    a[i][15] = v * w;
    a[i][16] = v * w;
    a[i][17] = v * w;
    a[i-3][18] = j + w;
    a[i][19] = v * w;
    a[i][20] = v + w;
    a[i][21] = v + w;
    i = i + 3;
    a[i][22] = v + w;
    a[i][23] = j + w;
    a[i][24] = v + w;
    a[i][25] = v + w;
    a[i][26] = v + w;
    a[i][27] = v + w;
    a[i][26] = j + w;
    a[i][27] = v + w;
    a[i][28] = v + w;
    a[i][29] = j - w;
    a[i][30] = v + w;
    a[i][31] = v + w;
    a[i][32] = v + w;
    a[i][33] = v + w;
    a[i][j-11] = v + w;
    a[i][j-10] = v + w;
    a[i][j-9] = j - w;
    a[i][j-8] = v + w;
    a[i][j-7] = j - w;
    a[i][j-6] = v + w;
    a[i][j-5] = j - w;
    a[i][j-4] = v + w;
    a[i][j-3] = j - w;
    a[i][j-2] = v + w;
    a[i][j-1] = j - w;
    a[i][j-3] = v + w;
    a[i][j-4] = v + w;
    a[i][j-5] = v + w;
    a[i][j-35] = j - w;
    a[i][j-34] = j - w;
    a[i][j-15] = v + w;
    a[i][j-16] = v + w;
    a[i][j-17] = v + w;
    a[i][j-18] = j - w;
    a[i][j-19] = v + w;
    a[i][j-20] = v + w;
    a[i][j-21] = v - w;
    a[i][j-22] = v - w;
    a[i][j-23] = j - w;
    a[i][j-24] = v - w;
    i = i - 2;
    a[i][j-25] = v - w;
    a[i][j-26] = v - w;
    a[i][j-27] = v - w;
    a[i][j-26] = j - w;
    a[i][j-27] = v - w;
    a[i][j-28] = v - w;
    a[i][j-29] = j - w;
    a[i][j-30] = v - w;
    a[i][j-31] = v - w;
    a[i][j-32] = v - w;
    a[i][j-33] = v - w;
    a[i][j-11] = v - w;
    a[i][j-10] = v - w;
    a[i][j-9] = j - w;
    a[i][j-8] = v - w;
    a[i][j-7] = i - w;
    a[i][j-6] = v - w;
    a[i][j-5] = i - w;
    a[i][j-4] = v - w;
    a[i][j-3] = i - w;
    a[i][j-2] = v - w;
    a[i][j-1] = i - w;
    a[i][36] = v - w;
    a[i][37] = v - w;
    a[i][38] = v - w;
    a[i][35] = i - w;
    a[i][34] = i - w;
    i = i - 1;
    a[i][j-25] = v - w;
    a[i][j-26] = v - w;
    a[i][j-27] = v - w;
    a[i][j-26] = j - w;
    a[i][j-27] = v - w;
    a[i][j-28] = v - w;
    a[i][j-29] = j - w;
    a[i][j-30] = v - w;
    a[i][j-31] = v - w;
    a[i][j-32] = v - w;
    a[i][j-33] = v - w;
    a[i][j-11] = v - w;
    a[i][j-10] = v - w;
    a[i][j-9] = j - w;
    a[i][j-8] = v - w;
    a[i][j-7] = i - w;
    a[i][j-6] = v - w;
    a[i][j-5] = i - w;
    a[i][j-4] = v - w;
    a[i][j-3] = i - w;
    a[i][j-2] = v - w;
    a[i][j-1] = i - w;
    a[i][36] = v - w;
    a[i][37] = v - w;
    a[i][38] = v - w;
    a[i][35] = i - w;
    a[i][34] = i - w;
    i = i - 5;
    a[i][0] = v * w;
    a[i][1] = j + w;
    a[i][3] = v * w;
    a[i-1][4] = v * w;
    a[i][5] = j + w;
    a[i][6] = v * w;
    a[i][7] = v * w;
    a[i][8] = v * w;
    a[i][9] = v * w;
    a[i][10] = v * w;
    a[i][j-9] = j + w;
    a[i][j-8] = v * w;
    a[i][j-7] = j + w;
    a[i][j-6] = v * w;
    a[i-2][j-5] = j + w;
    a[i][j-4] = v * w;
    a[i][j-3] = j + w;
    a[i][j-2] = v * w;
    a[i][j-1] = j + w;
    a[i][11] = v * w;
    a[i][12] = v * w;
    a[i][13] = j + w;
    a[i][14] = v * w;
    a[i][15] = v * w;
    a[i][16] = v * w;
    a[i][17] = v * w;
    a[i-3][18] = j + w;
    a[i][19] = v * w;
    a[i][20] = v + w;
    a[i][21] = v + w;
    i = i + 3;
    a[i][22] = v + w;
    a[i][23] = j + w;
    a[i][24] = v + w;
    a[i][25] = v + w;
    a[i][26] = v + w;
    a[i][27] = v + w;
    a[i][26] = j + w;
    a[i][27] = v + w;
    a[i][28] = v + w;
    a[i][29] = j - w;
    a[i][30] = v + w;
    a[i][31] = v + w;
    a[i][32] = v + w;
    a[i][33] = v + w;
    a[i][j-11] = v + w;
    a[i][j-10] = v + w;
    a[i][j-9] = j - w;
    a[i][j-8] = v + w;
    a[i][j-7] = j - w;
    a[i][j-6] = v + w;
    a[i][j-5] = j - w;
    a[i][j-4] = v + w;
    a[i][j-3] = j - w;
    a[i][j-2] = v + w;
    a[i][j-1] = j - w;
    a[i][j-3] = v + w;
    a[i][j-4] = v + w;
    a[i][j-5] = v + w;
    a[i][j-35] = j - w;
    a[i][j-34] = j - w;
    a[i][j-15] = v + w;
    a[i][j-16] = v + w;
    a[i][j-17] = v + w;
    a[i][j-18] = j - w;
    a[i][j-19] = v + w;
    a[i][j-20] = v + w;
    a[i][j-21] = v - w;
    a[i][j-22] = v - w;
    a[i][j-23] = j - w;
    a[i][j-24] = v - w;
    i = i + 2;
    a[i][j-25] = v - w;
    a[i][j-26] = v - w;
    a[i][j-27] = v - w;
    a[i][j-26] = j - w;
    a[i][j-27] = v - w;
    a[i][j-28] = v - w;
    a[i][j-29] = j - w;
    a[i][j-30] = v - w;
    a[i][j-31] = v - w;
    a[i][j-32] = v - w;
    a[i][j-33] = v - w;
    a[i][j-11] = v - w;
    a[i][j-10] = v - w;
    a[i][j-9] = j - w;
    a[i][j-8] = v - w;
    a[i][j-7] = i - w;
    a[i][j-6] = v - w;
    a[i][j-5] = i - w;
    a[i][j-4] = v - w;
    a[i][j-3] = i - w;
    a[i][j-2] = v - w;
    a[i][j-1] = i - w;
    a[i][36] = v - w;
    a[i][37] = v - w;
    a[i][38] = v - w;
    a[i][35] = i - w;
    a[i][34] = i - w;
    a[i-4][j-25] = v - w;
    a[i][j-26] = v - w;
    a[i][j-27] = v - w;
    a[i-1][j-26] = j - w;
    a[i][j-27] = v - w;
    a[i][j-28] = v - w;
    a[i][j-29] = j - w;
    a[i][j-30] = v - w;
    a[i][j-31] = v - w;
    a[i][j-32] = v - w;
    a[i][j-33] = v - w;
    a[i][j-11] = v - w;
    a[i][j-10] = v - w;
    a[i][j-9] = j - w;
    a[i][j-8] = v - w;
    a[i][j-7] = i - w;
    a[i][j-6] = v - w;
    a[i][j-5] = i - w;
    a[i][j-4] = v - w;
    a[i][j-3] = i - w;
    a[i][j-2] = v - w;
    a[i][j-1] = i - w;
    a[i][36] = v - w;
    a[i][37] = v - w;
    a[i][38] = v - w;
    a[i][35] = i - w;
    a[i][34] = i - w;
    i = i + 3;
    a[i-1][0] = v * w;
    a[i][1] = j + w;
    a[i][3] = v * w;
    a[i-1][4] = v * w;
    a[i][5] = j + w;
    a[i][6] = v * w;
    a[i][7] = v * w;
    a[i][8] = v * w;
    a[i][9] = v * w;
    a[i][10] = v * w;
    a[i][j-9] = j + w;
    a[i][j-8] = v * w;
    a[i][j-7] = j + w;
    a[i][j-6] = v * w;
    a[i-2][j-5] = j + w;
    a[i][j-4] = v * w;
    a[i][j-3] = j + w;
    a[i][j-2] = v * w;
    a[i][j-1] = j + w;
    a[i][11] = v * w;
    a[i][12] = v * w;
    a[i][13] = j + w;
    a[i][14] = v * w;
    a[i][15] = v * w;
    a[i][16] = v * w;
    a[i][17] = v * w;
    a[i-3][18] = j + w;
    a[i][19] = v * w;
    a[i][20] = v + w;
    a[i][21] = v + w;
    i = i - 3;
    a[i][22] = v + w;
    a[i][23] = j + w;
    a[i][24] = v + w;
    a[i][25] = v + w;
    a[i][26] = v + w;
    a[i][27] = v + w;
    a[i][26] = j + w;
    a[i][27] = v + w;
    a[i][28] = v + w;
    a[i][29] = j - w;
    a[i][30] = v + w;
    a[i][31] = v + w;
    a[i][32] = v + w;
    a[i][33] = v + w;
    a[i][j-11] = v + w;
    a[i][j-10] = v + w;
    a[i][j-9] = j - w;
    a[i][j-8] = v + w;
    a[i][j-7] = j - w;
    a[i][j-6] = v + w;
    a[i][j-5] = j - w;
    a[i][j-4] = v + w;
    a[i][j-3] = j - w;
    a[i][j-2] = v + w;
    a[i][j-1] = j - w;
    a[i][j-3] = v + w;
    a[i][j-4] = v + w;
    a[i][j-5] = v + w;
    a[i][j-35] = j - w;
    a[i][j-34] = j - w;
    a[i][j-15] = v + w;
    a[i][j-16] = v + w;
    a[i][j-17] = v + w;
    a[i][j-18] = j - w;
    a[i][j-19] = v + w;
    a[i][j-20] = v + w;
    a[i][j-21] = v - w;
    a[i][j-22] = v - w;
    a[i][j-23] = j - w;
    a[i][j-24] = v - w;
    i = i + 4;
    a[i][j-25] = v - w;
    a[i][j-26] = v - w;
    a[i][j-27] = v - w;
    a[i][j-26] = j - w;
    a[i][j-27] = v - w;
    a[i][j-28] = v - w;
    a[i][j-29] = j - w;
    a[i][j-30] = v - w;
    a[i][j-31] = v - w;
    a[i][j-32] = v - w;
    a[i][j-33] = v - w;
    a[i][j-11] = v - w;
    a[i][j-10] = v - w;
    a[i][j-9] = j - w;
    a[i][j-8] = v - w;
    a[i][j-7] = i - w;
    a[i][j-6] = v - w;
    a[i][j-5] = i - w;
    a[i][j-4] = v - w;
    a[i][j-3] = i - w;
    a[i][j-2] = v - w;
    a[i][j-1] = i - w;
    a[i][36] = v - w;
    a[i][37] = v - w;
    a[i][38] = v - w;
    a[i][35] = i - w;
    a[i][34] = i - w;
    i = i - 1;
    a[i][j-25] = v - w;
    a[i][j-26] = v - w;
    a[i][j-27] = v - w;
    a[i][j-26] = j - w;
    a[i][j-27] = v - w;
    a[i][j-28] = v - w;
    a[i][j-29] = j - w;
    a[i][j-30] = v - w;
    a[i][j-31] = v - w;
    a[i][j-32] = v - w;
    a[i][j-33] = v - w;
    a[i][j-11] = v - w;
    a[i][j-10] = v - w;
    a[i][j-9] = j - w;
    a[i][j-8] = v - w;
    a[i][j-7] = i - w;
    a[i][j-6] = v - w;
    a[i][j-5] = i - w;
    a[i][j-4] = v - w;
    a[i][j-3] = i - w;
    a[i][j-2] = v - w;
    a[i][j-1] = i - w;
    a[i][36] = v - w;
    a[i][37] = v - w;
    a[i][38] = v - w;
    a[i][35] = i - w;
    a[i][34] = i - w;
    i = i - 3;
    a[i][0] = v * w;
    a[i][1] = j + w;
    a[i][3] = v * w;
    a[i-1][4] = v * w;
    a[i][5] = j + w;
    a[i][6] = v * w;
    a[i][7] = v * w;
    a[i][8] = v * w;
    a[i][9] = v * w;
    a[i][10] = v * w;
    a[i][j-9] = j + w;
    a[i][j-8] = v * w;
    a[i][j-7] = j + w;
    a[i][j-6] = v * w;
    a[i-2][j-5] = j + w;
    a[i][j-4] = v * w;
    a[i][j-3] = j + w;
    a[i][j-2] = v * w;
    a[i][j-1] = j + w;
    a[i][11] = v * w;
    a[i][12] = v * w;
    a[i][13] = j + w;
    a[i][14] = v * w;
    a[i][15] = v * w;
    a[i][16] = v * w;
    a[i][17] = v * w;
    a[i-3][18] = j + w;
    a[i][19] = v * w;
    a[i][20] = v + w;
    a[i][21] = v + w;
    i = i + 3;
    a[i][22] = v + w;
    a[i][23] = j + w;
    a[i][24] = v + w;
    a[i][25] = v + w;
    a[i][26] = v + w;
    a[i][27] = v + w;
    a[i][26] = j + w;
    a[i][27] = v + w;
    a[i][28] = v + w;
    a[i][29] = j - w;
    a[i][30] = v + w;
    a[i][31] = v + w;
    a[i][32] = v + w;
    a[i][33] = v + w;
    a[i][j-11] = v + w;
    a[i][j-10] = v + w;
    a[i][j-9] = j - w;
    a[i][j-8] = v + w;
    a[i][j-7] = j - w;
    a[i][j-6] = v + w;
    a[i][j-5] = j - w;
    a[i][j-4] = v + w;
    a[i][j-3] = j - w;
    a[i][j-2] = v + w;
    a[i][j-1] = j - w;
    a[i][j-3] = v + w;
    a[i][j-4] = v + w;
    a[i][j-5] = v + w;
    a[i][j-35] = j - w;
    a[i][j-34] = j - w;
    a[i][j-15] = v + w;
    a[i][j-16] = v + w;
    a[i][j-17] = v + w;
    a[i][j-18] = j - w;
    a[i][j-19] = v + w;
    a[i][j-20] = v + w;
    a[i][j-21] = v - w;
    a[i][j-22] = v - w;
    a[i][j-23] = j - w;
    a[i][j-24] = v - w;
    i = i + 2;
    a[i][j-25] = v - w;
    a[i][j-26] = v - w;
    a[i][j-27] = v - w;
    a[i][j-26] = j - w;
    a[i][j-27] = v - w;
    a[i][j-28] = v - w;
    a[i][j-29] = j - w;
    a[i][j-30] = v - w;
    a[i][j-31] = v - w;
    a[i][j-32] = v - w;
    a[i][j-33] = v - w;
    a[i][j-11] = v - w;
    a[i][j-10] = v - w;
    a[i][j-9] = j - w;
    a[i][j-8] = v - w;
    a[i][j-7] = i - w;
    a[i][j-6] = v - w;
    a[i][j-5] = i - w;
    a[i][j-4] = v - w;
    a[i][j-3] = i - w;
    a[i][j-2] = v - w;
    a[i][j-1] = i - w;
    a[i][36] = v - w;
    a[i][37] = v - w;
    a[i][38] = v - w;
    a[i][35] = i - w;
    a[i][34] = i - w;
    a[i-4][j-25] = v - w;
    a[i][j-26] = v - w;
    a[i][j-27] = v - w;
    a[i-1][j-26] = j - w;
    a[i][j-27] = v - w;
    a[i][j-28] = v - w;
    a[i][j-29] = j - w;
    a[i][j-30] = v - w;
    a[i][j-31] = v - w;
    a[i][j-32] = v - w;
    a[i][j-33] = v - w;
    a[i][j-11] = v - w;
    a[i][j-10] = v - w;
    a[i][j-9] = j - w;
    a[i][j-8] = v - w;
    a[i][j-7] = i - w;
    a[i][j-6] = v - w;
    a[i][j-5] = i - w;
    a[i][j-4] = v - w;
    a[i][j-3] = i - w;
    a[i][j-2] = v - w;
    a[i][j-1] = i - w;
    a[i][36] = v - w;
    a[i][37] = v - w;
    a[i][38] = v - w;
    a[i][35] = i - w;
    a[i][34] = i - w;
    i = i - 5;
    a[i][0] = v * w;
    a[i][1] = j + w;
    a[i][3] = v * w;
    a[i-1][4] = v * w;
    a[i][5] = j + w;
    a[i][6] = v * w;
    a[i][7] = v * w;
    a[i][8] = v * w;
    a[i][9] = v * w;
    a[i][10] = v * w;
    a[i][j-9] = j + w;
    a[i][j-8] = v * w;
    a[i][j-7] = j + w;
    a[i][j-6] = v * w;
    a[i-2][j-5] = j + w;
    a[i][j-4] = v * w;
    a[i][j-3] = j + w;
    a[i][j-2] = v * w;
    a[i][j-1] = j + w;
    a[i][11] = v * w;
    a[i][12] = v * w;
    a[i][13] = j + w;
    a[i][14] = v * w;
    a[i][15] = v * w;
    a[i][16] = v * w;
    a[i][17] = v * w;
    a[i-3][18] = j + w;
    a[i][19] = v * w;
    a[i][20] = v + w;
    a[i][21] = v + w;
    a[i][22] = v + w;
    a[i][23] = j + w;
    a[i][24] = v + w;
    a[i][25] = v + w;
    a[i][26] = v + w;
    a[i][27] = v + w;
    a[i][26] = j + w;
    i = i - 7;
    a[i][27] = v + w;
    a[i][28] = v + w;
    a[i][29] = j - w;
    a[i][30] = v + w;
    a[i][31] = v + w;
    a[i][32] = v + w;
    a[i][33] = v + w;
    a[i][j-11] = v + w;
    a[i][j-10] = v + w;
    a[i][j-9] = j - w;
    a[i][j-8] = v + w;
    a[i][j-7] = j - w;
    a[i][j-6] = v + w;
    a[i][j-5] = j - w;
    a[i][j-4] = v + w;
    a[i][j-3] = j - w;
    a[i][j-2] = v + w;
    a[i][j-1] = j - w;
    a[i][j-3] = v + w;
    a[i][j-4] = v + w;
    a[i][j-5] = v + w;
    a[i][j-35] = j - w;
    a[i][j-34] = j - w;
    a[i][j-15] = v + w;
    a[i][j-16] = v + w;
    a[i][j-17] = v + w;
    a[i][j-18] = j - w;
    a[i][j-19] = v + w;
    a[i][j-20] = v + w;
    a[i][j-21] = v - w;
    a[i][j-22] = v - w;
    a[i][j-23] = j - w;
    a[i][j-24] = v - w;
    a[i][j-25] = v - w;
    a[i][j-26] = v - w;
    a[i][j-27] = v - w;
    a[i][j-26] = j - w;
    a[i][j-27] = v - w;
    a[i][j-28] = v - w;
    a[i][j-29] = j - w;
    i = i + 3;
    a[i][j-30] = v - w;
    a[i][j-31] = v - w;
    a[i][j-32] = v - w;
    a[i][j-33] = v - w;
    a[i][j-11] = v - w;
    a[i][j-10] = v - w;
    i = i + 4;
    a[i][j-9] = j - w;
    a[i][j-8] = v - w;
    a[i][j-7] = i - w;
    a[i][j-6] = v - w;
    a[i][j-5] = i - w;
    a[i][j-4] = v - w;
    a[i][j-3] = i - w;
    a[i][j-2] = v - w;
    a[i][j-1] = i - w;
    a[i][36] = v - w;
    a[i][37] = v - w;
    a[i][38] = v - w;
    a[i][35] = i - w;
    a[i][34] = i - w;
    a[i][j-25] = v - w;
    a[i][j-26] = v - w;
    a[i][j-27] = v - w;
    a[i][j-26] = j - w;
    a[i][j-27] = v - w;
    a[i][j-28] = v - w;
    a[i][j-29] = j - w;
    a[i][j-30] = v - w;
    a[i][j-31] = v - w;
    a[i][j-32] = v - w;
    a[i][j-33] = v - w;
    a[i][j-11] = v - w;
    a[i][j-10] = v - w;
    a[i][j-9] = j - w;
    a[i][j-8] = v - w;
    a[i][j-7] = i - w;
    a[i][j-6] = v - w;
    a[i][j-5] = i - w;
    a[i][j-4] = v - w;
    a[i][j-3] = i - w;
    a[i][j-2] = v - w;
    a[i][j-1] = i - w;
    a[i][36] = v - w;
    a[i][37] = v - w;
    a[i][38] = v - w;
    a[i][35] = i - w;
    a[i][34] = i - w;
    a[i][0] = v * w;
    a[i][1] = j + w;
    a[i][3] = v * w;
    a[i-1][4] = v * w;
    a[i][5] = j + w;
    a[i][6] = v * w;
    a[i][7] = v * w;
    a[i][8] = v * w;
    i = i + 2;
    a[i][9] = v * w;
    a[i][10] = v * w;
    a[i][j-9] = j + w;
    a[i][j-8] = v * w;
    a[i][j-7] = j + w;
    a[i][j-6] = v * w;
    a[i-2][j-5] = j + w;
    a[i][j-4] = v * w;
    a[i][j-3] = j + w;
    a[i][j-2] = v * w;
    a[i][j-1] = j + w;
    a[i][11] = v * w;
    a[i][12] = v * w;
    a[i][13] = j + w;
    a[i][14] = v * w;
    a[i][15] = v * w;
    a[i][16] = v * w;
    a[i][17] = v * w;
    a[i-3][18] = j + w;
    a[i][19] = v * w;
    a[i][20] = v + w;
    a[i][21] = v + w;
    a[i][22] = v + w;
    a[i][23] = j + w;
    a[i][24] = v + w;
    a[i][25] = v + w;
    a[i][26] = v + w;
    a[i][27] = v + w;
    a[i][26] = j + w;
    a[i][27] = v + w;
    a[i][28] = v + w;
    a[i][29] = j - w;
    a[i][30] = v + w;
    a[i][31] = v + w;
    a[i][32] = v + w;
    a[i][33] = v + w;
    a[i][j-11] = v + w;
    a[i][j-10] = v + w;
    a[i][j-9] = j - w;
    a[i][j-8] = v + w;
    a[i][j-7] = j - w;
    i = i + 1;
    a[i][j-6] = v + w;
    a[i][j-5] = j - w;
    a[i][j-4] = v + w;
    a[i][j-3] = j - w;
    a[i][j-2] = v + w;
    a[i][j-1] = j - w;
    a[i][j-3] = v + w;
    a[i][j-4] = v + w;
    a[i][j-5] = v + w;
    a[i][j-35] = j - w;
    a[i][j-34] = j - w;
    a[i][j-15] = v + w;
    a[i][j-16] = v + w;
    a[i][j-17] = v + w;
    a[i][j-18] = j - w;
    a[i][j-19] = v + w;
    a[i][j-20] = v + w;
    a[i][j-21] = v - w;
    a[i][j-22] = v - w;
    a[i][j-23] = j - w;
    a[i][j-24] = v - w;
    a[i][j-25] = v - w;
    a[i][j-26] = v - w;
    a[i][j-27] = v - w;
    a[i][j-26] = j - w;
    a[i][j-27] = v - w;
    a[i][j-28] = v - w;
    i = i - 3;
    a[i][j-29] = j - w;
    a[i][j-30] = v - w;
    a[i][j-31] = v - w;
    a[i][j-32] = v - w;
    a[i][j-33] = v - w;
    a[i][j-11] = v - w;
    a[i][j-10] = v - w;
    a[i][j-9] = j - w;
    a[i][j-8] = v - w;
    a[i][j-7] = i - w;
    a[i][j-6] = v - w;
    a[i][j-5] = i - w;
    a[i][j-4] = v - w;
    a[i][j-3] = i - w;
    a[i][j-2] = v - w;
    a[i][j-1] = i - w;
    a[i][36] = v - w;
    a[i][37] = v - w;
    a[i][38] = v - w;
    a[i][35] = i - w;
    a[i][34] = i - w;
    a[i-4][j-25] = v - w;
    a[i][j-26] = v - w;
    a[i][j-27] = v - w;
    a[i-1][j-26] = j - w;
    a[i][j-27] = v - w;
    a[i][j-28] = v - w;
    a[i][j-29] = j - w;
    a[i][j-30] = v - w;
    a[i][j-31] = v - w;
    a[i][j-32] = v - w;
    a[i][j-33] = v - w;
    a[i][j-11] = v - w;
    a[i][j-10] = v - w;
    a[i][j-9] = j - w;
    a[i][j-8] = v - w;
    a[i][j-7] = i - w;
    a[i][j-6] = v - w;
    a[i][j-5] = i - w;
    i = i - 4;
    a[i][j-4] = v - w;
    a[i][j-3] = i - w;
    a[i][j-2] = v - w;
    a[i][j-1] = i - w;
    a[i][36] = v - w;
    a[i][37] = v - w;
    a[i][38] = v - w;
    a[i][35] = i - w;
    a[i][34] = i - w;
    a[i][0] = v * w;
    a[i][1] = j + w;
    a[i][3] = v * w;
    a[i-1][4] = v * w;
    a[i][5] = j + w;
    a[i][6] = v * w;
    a[i][7] = v * w;
    a[i][8] = v * w;
    a[i][9] = v * w;
    a[i][10] = v * w;
    a[i][j-9] = j + w;
    a[i][j-8] = v * w;
    a[i][j-7] = j + w;
    a[i][j-6] = v * w;
    a[i-2][j-5] = j + w;
    a[i][j-4] = v * w;
    a[i][j-3] = j + w;
    a[i][j-2] = v * w;
    a[i][j-1] = j + w;
    a[i][11] = v * w;
    a[i][12] = v * w;
    a[i][13] = j + w;
    a[i][14] = v * w;
    a[i][15] = v * w;
    a[i][16] = v * w;
    a[i][17] = v * w;
    i = i + 2;
    a[i-3][18] = j + w;
    a[i][19] = v * w;
    a[i][20] = v + w;
    a[i][21] = v + w;
    a[i][22] = v + w;
    a[i][23] = j + w;
    a[i][24] = v + w;
    a[i][25] = v + w;
    a[i][26] = v + w;
    a[i][27] = v + w;
    a[i][26] = j + w;
    a[i][27] = v + w;
    a[i][28] = v + w;
    a[i][29] = j - w;
    a[i][30] = v + w;
    a[i][31] = v + w;
    a[i][32] = v + w;
    a[i][33] = v + w;
    a[i][j-11] = v + w;
    a[i][j-10] = v + w;
    a[i][j-9] = j - w;
    a[i][j-8] = v + w;
    a[i][j-7] = j - w;
    a[i][j-6] = v + w;
    a[i][j-5] = j - w;
    a[i][j-4] = v + w;
    i = i + 3;
    a[i][j-3] = j - w;
    a[i][j-2] = v + w;
    a[i][j-1] = j - w;
    a[i][j-3] = v + w;
    a[i][j-4] = v + w;
    a[i][j-5] = v + w;
    a[i][j-35] = j - w;
    a[i][j-34] = j - w;
    a[i][j-15] = v + w;
    a[i][j-16] = v + w;
    a[i][j-17] = v + w;
    a[i][j-18] = j - w;
    a[i][j-19] = v + w;
    a[i][j-20] = v + w;
    a[i][j-21] = v - w;
    a[i][j-22] = v - w;
    a[i][j-23] = j - w;
    a[i][j-24] = v - w;
    a[i][j-25] = v - w;
    a[i][j-26] = v - w;
    a[i][j-27] = v - w;
    a[i][j-26] = j - w;
    a[i][j-27] = v - w;
    a[i][j-28] = v - w;
    a[i][j-29] = j - w;
    a[i][j-30] = v - w;
    a[i][j-31] = v - w;
    a[i][j-32] = v - w;
    a[i][j-33] = v - w;
    a[i][j-11] = v - w;
    a[i][j-10] = v - w;
    a[i][j-9] = j - w;
    a[i][j-8] = v - w;
    a[i][j-7] = i - w;
    a[i][j-6] = v - w;
    a[i][j-5] = i - w;
    a[i][j-4] = v - w;
    a[i][j-3] = i - w;
    a[i][j-2] = v - w;
    a[i][j-1] = i - w;
    a[i][36] = v - w;
    a[i][37] = v - w;
    a[i][38] = v - w;
    a[i][35] = i - w;
    a[i][34] = i - w;
    i = i - 1;
    a[i][j-25] = v - w;
    a[i][j-26] = v - w;
    a[i][j-27] = v - w;
    a[i][j-26] = j - w;
    a[i][j-27] = v - w;
    a[i][j-28] = v - w;
    a[i][j-29] = j - w;
    a[i][j-30] = v - w;
    a[i][j-31] = v - w;
    a[i][j-32] = v - w;
    a[i][j-33] = v - w;
    a[i][j-11] = v - w;
    a[i][j-10] = v - w;
    a[i][j-9] = j - w;
    a[i][j-8] = v - w;
    a[i][j-7] = i - w;
    a[i][j-6] = v - w;
    a[i][j-5] = i - w;
    a[i][j-4] = v - w;
    a[i][j-3] = i - w;
    a[i][j-2] = v - w;
    a[i][j-1] = i - w;
    a[i][36] = v - w;
    a[i][37] = v - w;
    a[i][38] = v - w;
    a[i][35] = i - w;
    a[i][34] = i - w;
    a[i][0] = v * w;
    a[i][1] = j + w;
    a[i][3] = v * w;
    a[i-1][4] = v * w;
    a[i][5] = j + w;
    a[i][6] = v * w;
    a[i][7] = v * w;
    a[i][8] = v * w;
    a[i][9] = v * w;
    a[i][10] = v * w;
    a[i][j-9] = j + w;
    a[i][j-8] = v * w;
    a[i][j-7] = j + w;
    a[i][j-6] = v * w;
    a[i-2][j-5] = j + w;
    a[i][j-4] = v * w;
    a[i][j-3] = j + w;
    a[i][j-2] = v * w;
    a[i][j-1] = j + w;
    a[i][11] = v * w;
    a[i][12] = v * w;
    a[i][13] = j + w;
    a[i][14] = v * w;
    a[i][15] = v * w;
    a[i][16] = v * w;
    a[i][17] = v * w;
    a[i-3][18] = j + w;
    a[i][19] = v * w;
    a[i][20] = v + w;
    a[i][21] = v + w;
    i = i + 3;
    a[i][22] = v + w;
    a[i][23] = j + w;
    a[i][24] = v + w;
    a[i][25] = v + w;
    a[i][26] = v + w;
    a[i][27] = v + w;
    a[i][26] = j + w;
    a[i][27] = v + w;
    a[i][28] = v + w;
    a[i][29] = j - w;
    a[i][30] = v + w;
    a[i][31] = v + w;
    a[i][32] = v + w;
    a[i][33] = v + w;
    a[i][j-11] = v + w;
    a[i][j-10] = v + w;
    a[i][j-9] = j - w;
    a[i][j-8] = v + w;
    a[i][j-7] = j - w;
    a[i][j-6] = v + w;
    a[i][j-5] = j - w;
    a[i][j-4] = v + w;
    a[i][j-3] = j - w;
    a[i][j-2] = v + w;
    a[i][j-1] = j - w;
    a[i][j-3] = v + w;
    a[i][j-4] = v + w;
    a[i][j-5] = v + w;
    a[i][j-35] = j - w;
    a[i][j-34] = j - w;
    a[i][j-15] = v + w;
    a[i][j-16] = v + w;
    a[i][j-17] = v + w;
    a[i][j-18] = j - w;
    i = i + 2;
    a[i][j-19] = v + w;
    a[i][j-20] = v + w;
    a[i][j-21] = v - w;
    a[i][j-22] = v - w;
    a[i][j-23] = j - w;
    a[i][j-24] = v - w;
    a[i][j-25] = v - w;
    a[i][j-26] = v - w;
    a[i][j-27] = v - w;
    a[i][j-26] = j - w;
    a[i][j-27] = v - w;
    a[i][j-28] = v - w;
    a[i][j-29] = j - w;
    a[i][j-30] = v - w;
    a[i][j-31] = v - w;
    a[i][j-32] = v - w;
    a[i][j-33] = v - w;
    a[i][j-11] = v - w;
    a[i][j-10] = v - w;
    a[i][j-9] = j - w;
    a[i][j-8] = v - w;
    a[i][j-7] = i - w;
    a[i][j-6] = v - w;
    a[i][j-5] = i - w;
    a[i][j-4] = v - w;
    a[i][j-3] = i - w;
    a[i][j-2] = v - w;
    a[i][j-1] = i - w;
    a[i][36] = v - w;
    a[i][37] = v - w;
    a[i][38] = v - w;
    a[i][35] = i - w;
    a[i][34] = i - w;
    a[i-4][j-25] = v - w;
    a[i][j-26] = v - w;
    a[i][j-27] = v - w;
    a[i-1][j-26] = j - w;
    a[i][j-27] = v - w;
    a[i][j-28] = v - w;
    a[i][j-29] = j - w;
    a[i][j-30] = v - w;
    a[i][j-31] = v - w;
    a[i][j-32] = v - w;
    a[i][j-33] = v - w;
    a[i][j-11] = v - w;
    a[i][j-10] = v - w;
    i = i - 5;
    a[i][j-9] = j - w;
    a[i][j-8] = v - w;
    a[i][j-7] = i - w;
    a[i][j-6] = v - w;
    a[i][j-5] = i - w;
    a[i][j-4] = v - w;
    a[i][j-3] = i - w;
    a[i][j-2] = v - w;
    a[i][j-1] = i - w;
    a[i][36] = v - w;
    a[i][37] = v - w;
    a[i][38] = v - w;
    a[i][35] = i - w;
    a[i][34] = i - w;
    i = i - 1;
    a[i][j-6] = v - w;
    a[i][j-5] = i - w;
    a[i][j-4] = v - w;
    a[i][j-3] = i - w;
    a[i][j-2] = v - w;
    a[i][j-1] = i - w;
    a[i][36] = v - w;
    a[i][37] = v - w;
    a[i][38] = v - w;
    a[i][35] = i - w;
    a[i][34] = i - w;
    a[i-4][j-25] = v - w;
    a[i][j-26] = v - w;
    a[i][j-27] = v - w;
    a[i-1][j-26] = j - w;
    a[i][j-27] = v - w;
    a[i][j-28] = v - w;
    a[i][j-29] = j - w;
    a[i][j-30] = v - w;
    a[i][j-31] = v - w;
    a[i][j-32] = v - w;
    a[i][j-33] = v - w;
    a[i][j-11] = v - w;
    a[i][j-10] = v - w;
    a[i][j-9] = j - w;
    a[i][j-8] = v - w;
    a[i][j-7] = i - w;
    a[i][j-6] = v - w;
    a[i][j-5] = i - w;
    a[i][j-4] = v - w;
    a[i][j-3] = i - w;
    a[i][j-2] = v - w;
    a[i][j-1] = i - w;
    a[i][36] = v - w;
    a[i][37] = v - w;
    a[i][38] = v - w;
    i = i + 1;
    a[i][35] = i - w;
    a[i][34] = i - w;
    a[i-1][j-21] = v - w;
    a[i-2][j-22] = v - w;
    a[i-3][j-23] = j - w;
    a[i][j-24] = v - w;
    a[i][j-25] = v - w;
    a[i][j-26] = v - w;
    a[i][j-27] = v - w;
    a[i][j-26] = j - w;
    a[i][j-27] = v - w;
    a[i][j-28] = v - w;
    a[i][j-29] = j - w;
    a[i][j-30] = v - w;
    a[i][j-31] = v - w;
    a[i][j-32] = v - w;
    a[i-4][j-33] = v - w;
    a[i][j-11] = v - w;
    a[i][j-10] = v - w;
    a[i][j-9] = j - w;
    a[i][j-8] = v - w;
    a[i][j-7] = i - w;
    a[i][j-6] = v - w;
    a[i-5][j-5] = i - w;
    a[i+3][j-4] = v - w;
    a[i][j-3] = i - w;
    a[i][j-2] = v - w;
    a[i][j-1] = i - w;
    a[i][36] = v - w;
    a[i+2][37] = v - w;
    a[i][38] = v - w;
    a[i][35] = i - w;
    a[i][34] = i - w;
    a[i-4][j-25] = v - w;
    a[i][j-26] = v - w;
    a[i][j-27] = v - w;
    a[i-1][j-26] = j - w;
    a[i][j-27] = v - w;
    a[i][j-28] = v - w;
    a[i-3][j-29] = j - w;
  }

  for (i = 0; i < N; i++) {
    for (j = 0; j < N; j++) {
      if (a[i][j] < 10) {
	sum += 1;
      }
      else {
        sum += -1;
      }
    }
  }

  printf("sum  = %d --- ", sum); 

  if (sum == ANS) {
    printf("OK\n");
  }
  else {
    printf("NG, Answer => %d\n", ANS);
  }
}

#include  <stdio.h>
  
#ifdef __STDC__
   void func1(int);
#else
   void func1();
#endif
   int *a[5],b,c;
   int 
mptest15 (void)
     {
        printf("\n*** MPTEST15 -- START ***\n") ;
        b=400 ;
        a[0]=&b ;
        func1(b);
        c=*a[0] ;
        if(c==400)
         printf("*** MPTEST15 CHECK01 OK ***\n");
        else
         printf("*** MPTEST15 CHECK01 NG ***\n");
        printf("\n*** MPTEST15 -- END   ***\n") ;
     }
#ifdef __STDC__
   void func1(int d)
#else
   void func1(d)
   int d;
#endif
     {
        int e;
        d=d+200;
        a[1]=&d;
        e=*a[1];
        if(e==600)
         printf("*** MPTEST15 CHECK02 OK ***\n");
        else
         printf("*** MPTEST15 CHECK02 NG ***\n");
     }

int 
reduction15 (void)
{
  volatile int a;
  int s[50], i;

  for (i=0; i<50; i++) {
    s[i] = 1;
  }

  a = 0;
  for (i=0; i<50; i++) {
    a = a + s[i];
  }

  if (a == 50)
    printf("*** ok ***\n");
  else
    printf("*** ng ***\n");
}

#include  <stdio.h>

int 
scn1215 (void) {
  unsigned char          u1();
  unsigned short int     u2();
  unsigned int           u4();
  unsigned char          u1a,u1b;
  unsigned short int     u2a,u2b;
  unsigned int           u4a,u4b;
  printf("scn1215 start\n");
  u1a=0xff;u1b=0xff;
  if (u1(u1a,u1b)==1) printf("u1:ok\n");else printf("u1:ng\n");
  u2a=0xffff;u2b=0xffff;
  if (u2(u2a,u2b)==1) printf("u2:ok\n");else printf("u2:ng\n");
  u4a=0xffffffff;u4b=0xffffffff;
  if (u4(u4a,u4b)==1) printf("u4-1:ok\n");else printf("u4-1:ng\n");
  u4a=0x80000000;u4b=0x80000000;
  if (u4(u4a,u4b)==1) printf("u4-2:ok\n");else printf("u4-2:ng\n");
  u4a=0x10000000;u4b=0x10000000;
  if (u4(u4a,u4b)==1) printf("u4-3:ok\n");else printf("u4-3:ng\n");
  printf("scn1215 ended\n");
}
unsigned char 
u1 (int ua, int ub){return(ua/ub);}
unsigned short int 
u2 (int ua, int ub){return(ua/ub);}
unsigned int 
u4 (unsigned int ua, unsigned int ub){return(ua/ub);}

#include  <stdio.h>

union {
      char a ;
      int  b ;
      int  c[5] ;
      } xm = { 'a' } ;
int 
scpii15 (void)
{
  printf("********** SCPII15 TEST START **********\n");

  if (xm.a=='a' && xm.c[1] == 0)
    printf("********** O  K   **********************\n");
  else
    printf("********** N  G   **********************\n");

  printf("********** SCPII15 TEST  END  **********\n");
}

int 
comk3115 (void) {
volatile register int i;
long int a=0x70000000;
long long int c=0x70000000LL;
long long int b,d,z[5],x[5];

for (i=0; i<5; i++) {
  a=a+i;
  c=c+(long long)i;
  b=~ ((long long)a << 32);
  d=~((*(volatile    long long *) &c) << 32);

  if ((~b) ==(~d) && b == d) {
    z[i]=b;
    x[i]=d;
  }
  else {
    z[i]=0;
    x[i]=0;
    printf("%.8x %.8x\n",*(long*)&b,*(((long*)&b)+1));
    printf("%.8x %.8x\n",*(long*)&d,*(((long*)&d)+1));
    printf("%.8x %.8x\n",~(*(long*)&b),~(*(((long*)&b)+1)));
    printf("%.8x %.8x\n",~(*(long*)&d),~(*(((long*)&d)+1)));
    goto L2;
  }
L1:;
   a=0x70000000;
   c=0x70000000LL;
L2:;
}
  if (z[i-1]==x[i-1]
   && z[i-2]==z[i-2]
   && z[i-3]==z[i-3]
   && z[i-4]==z[i-4]
   && z[i-5]==z[i-5])
    printf("comk3115 ok\n");
}
int 
main (void) {
  scpii15( );
  reduction15( );
  dpmk2015( );
  mptest15( );
  estreg15( );
  scn1215( );
  comk3115( );
}
