extern signed char v3 (unsigned int);
extern signed char (*v4) (unsigned int);
extern void v5 (signed short);
extern void (*v6) (signed short);
extern unsigned char v7 (signed char, unsigned char);
extern unsigned char (*v8) (signed char, unsigned char);
extern unsigned short v9 (signed int, signed char, unsigned int);
extern unsigned short (*v10) (signed int, signed char, unsigned int);
extern unsigned char v11 (void);
extern unsigned char (*v12) (void);
extern signed short v13 (signed int, unsigned int);
extern signed short (*v14) (signed int, unsigned int);
extern signed char v15 (signed short);
extern signed char (*v16) (signed short);
extern unsigned int v17 (void);
extern unsigned int (*v18) (void);
extern unsigned int v21 (signed short, signed short);
extern unsigned int (*v22) (signed short, signed short);
extern unsigned short v23 (signed short);
extern unsigned short (*v24) (signed short);
extern unsigned char v25 (void);
extern unsigned char (*v26) (void);
extern unsigned char v27 (signed short, signed int, unsigned short, unsigned char);
extern unsigned char (*v28) (signed short, signed int, unsigned short, unsigned char);
extern unsigned char v29 (void);
extern unsigned char (*v30) (void);
extern int history[];
extern int history_index;
extern int trace;
unsigned char v93 = 6;
unsigned int v92 = 5U;
unsigned char v91 = 6;
