extern unsigned int v1 (unsigned short, unsigned short, signed int);
extern unsigned int (*v2) (unsigned short, unsigned short, signed int);
extern signed char v3 (signed int, unsigned int);
extern signed char (*v4) (signed int, unsigned int);
extern unsigned char v5 (signed int);
extern unsigned char (*v6) (signed int);
extern unsigned short v7 (signed char, signed short, signed char, unsigned int);
extern unsigned short (*v8) (signed char, signed short, signed char, unsigned int);
extern unsigned char v9 (signed short, unsigned short, signed char, unsigned short);
extern unsigned char (*v10) (signed short, unsigned short, signed char, unsigned short);
extern signed int v11 (unsigned short, signed short);
extern signed int (*v12) (unsigned short, signed short);
extern signed char v13 (void);
extern signed char (*v14) (void);
extern void v15 (signed int, unsigned int, signed short, unsigned short);
extern void (*v16) (signed int, unsigned int, signed short, unsigned short);
extern unsigned int v19 (unsigned char, signed short, signed short, signed char);
extern unsigned int (*v20) (unsigned char, signed short, signed short, signed char);
extern unsigned int v21 (signed char, unsigned short);
extern unsigned int (*v22) (signed char, unsigned short);
extern signed char v23 (unsigned char, signed char, signed int, unsigned char);
extern signed char (*v24) (unsigned char, signed char, signed int, unsigned char);
extern unsigned char v25 (signed char);
extern unsigned char (*v26) (signed char);
extern unsigned int v27 (signed int, signed short, signed short);
extern unsigned int (*v28) (signed int, signed short, signed short);
extern signed short v29 (unsigned char);
extern signed short (*v30) (unsigned char);
extern int history[];
extern int history_index;
extern int trace;
signed int v170 = 0;
signed int v169 = 0;
unsigned char v168 = 6;
