extern unsigned short v1 (signed char, unsigned char);
extern unsigned short (*v2) (signed char, unsigned char);
extern signed short v5 (signed short, signed char, signed int);
extern signed short (*v6) (signed short, signed char, signed int);
extern signed char v7 (signed short, signed int);
extern signed char (*v8) (signed short, signed int);
extern unsigned char v9 (void);
extern unsigned char (*v10) (void);
extern unsigned short v11 (void);
extern unsigned short (*v12) (void);
extern unsigned short v13 (signed int);
extern unsigned short (*v14) (signed int);
extern unsigned short v15 (unsigned short, signed int, signed short);
extern unsigned short (*v16) (unsigned short, signed int, signed short);
extern unsigned int v17 (void);
extern unsigned int (*v18) (void);
extern void v19 (unsigned short, signed short, signed int);
extern void (*v20) (unsigned short, signed short, signed int);
extern signed int v23 (signed short, signed int);
extern signed int (*v24) (signed short, signed int);
extern signed short v25 (signed short, signed char, unsigned char, signed char);
extern signed short (*v26) (signed short, signed char, unsigned char, signed char);
extern signed char v27 (signed int, signed int);
extern signed char (*v28) (signed int, signed int);
extern unsigned int v29 (unsigned short, signed short);
extern unsigned int (*v30) (unsigned short, signed short);
extern int history[];
extern int history_index;
extern int trace;
signed char v138 = 3;
signed int v137 = 1;
unsigned int v136 = 6U;
