extern unsigned int v1 (signed int, signed char, signed short, unsigned int);
extern unsigned int (*v2) (signed int, signed char, signed short, unsigned int);
extern unsigned short v3 (signed short, signed char);
extern unsigned short (*v4) (signed short, signed char);
extern unsigned int v5 (signed short, signed int);
extern unsigned int (*v6) (signed short, signed int);
extern void v7 (unsigned char, signed short, signed char, unsigned short);
extern void (*v8) (unsigned char, signed short, signed char, unsigned short);
extern unsigned int v9 (unsigned short, unsigned int);
extern unsigned int (*v10) (unsigned short, unsigned int);
extern void v11 (void);
extern void (*v12) (void);
extern unsigned char v13 (signed int);
extern unsigned char (*v14) (signed int);
extern signed char v15 (signed char, unsigned int, signed char, signed char);
extern signed char (*v16) (signed char, unsigned int, signed char, signed char);
extern void v17 (unsigned int, signed int);
extern void (*v18) (unsigned int, signed int);
extern unsigned int v19 (unsigned short, signed int, unsigned short, unsigned short);
extern unsigned int (*v20) (unsigned short, signed int, unsigned short, unsigned short);
extern signed short v21 (void);
extern signed short (*v22) (void);
extern void v23 (void);
extern void (*v24) (void);
extern unsigned int v25 (void);
extern unsigned int (*v26) (void);
extern unsigned short v27 (signed short, unsigned int, unsigned char);
extern unsigned short (*v28) (signed short, unsigned int, unsigned char);
extern signed int v29 (signed short, signed short);
extern signed int (*v30) (signed short, signed short);
extern int history[];
extern int history_index;
extern int trace;
signed short v148 = 2;
unsigned int v147 = 3U;
unsigned int v146 = 6U;
