IMPLICIT NONE
  REAL SEC
  INTRINSIC SYSTEM_CLOCK ! FORTRAN90 INTRINSIC ROUTINE
  INTEGER(8) CNT, CNT_RATE ! (INT64)
  !--------------
  CALL SYSTEM_CLOCK (COUNT=CNT, COUNT_RATE=CNT_RATE) 
!SEC = DBLE / CNT_RATE

 write(3,*) 'CNT=', CNT, ', CNT_RATE=', CNT_RATE
! write(3,*) 'SEC=', SEC 
print *,'sngg741j : pass'
END
