MODULE M
TYPE T
 integer:: x1
END TYPE
CONTAINS
SUBROUTINE PROCESS(X,Y,RESULT,MONITOR)
TYPE(T),INTENT(IN) :: X(:,:),Y(:,:)
TYPE(T),INTENT(OUT) :: RESULT(:,:)
 INTERFACE
  SUBROUTINE MONITOR(ITERATION_NUMBER,CURRENT_ESTIMATE)
   IMPORT T
     INTEGER,INTENT(IN) :: ITERATION_NUMBER
     TYPE(T),INTENT(IN) :: CURRENT_ESTIMATE(:,:)
  END SUBROUTINE
 END INTERFACE
 call MONITOR( 3 , y )
 result%x1 = X%x1 + Y%x1
END SUBROUTINE
END MODULE

  SUBROUTINE MONITOR(ITERATION_NUMBER,CURRENT_ESTIMATE)
   use M
     INTEGER,INTENT(IN) :: ITERATION_NUMBER
     TYPE(T),INTENT(IN) :: CURRENT_ESTIMATE(:,:)
     if (any(CURRENT_ESTIMATE%x1 /= ITERATION_NUMBER)) print *,101
     if (any( ubound(CURRENT_ESTIMATE) /= [3,4]) ) print *,102
  END SUBROUTINE

use m
TYPE(T) :: X(3,4),Y(3,4)
TYPE(T):: RESULT(3,4)
interface
  SUBROUTINE MONITOR(ITERATION_NUMBER,CURRENT_ESTIMATE)
   IMPORT T
     INTEGER,INTENT(IN) :: ITERATION_NUMBER
     TYPE(T),INTENT(IN) :: CURRENT_ESTIMATE(:,:)
  END SUBROUTINE
end interface
x%x1=2
y%x1=3
call PROCESS(X,Y,RESULT,MONITOR)
if (any(result%x1/= 5) ) print *,201
print *,'pass'
end

