extern signed int v1 (void);
extern signed int (*v2) (void);
extern unsigned short v3 (signed short, signed char, unsigned short, unsigned short);
extern unsigned short (*v4) (signed short, signed char, unsigned short, unsigned short);
extern signed char v5 (signed int, unsigned int, signed char);
extern signed char (*v6) (signed int, unsigned int, signed char);
extern unsigned short v7 (signed char, signed short, signed short);
extern unsigned short (*v8) (signed char, signed short, signed short);
extern signed int v9 (signed char, signed short, unsigned int, signed short);
extern signed int (*v10) (signed char, signed short, unsigned int, signed short);
extern unsigned char v13 (unsigned short, unsigned char, unsigned int);
extern unsigned char (*v14) (unsigned short, unsigned char, unsigned int);
extern unsigned char v15 (unsigned int, signed short);
extern unsigned char (*v16) (unsigned int, signed short);
extern signed char v17 (void);
extern signed char (*v18) (void);
extern unsigned char v19 (void);
extern unsigned char (*v20) (void);
extern unsigned short v21 (signed char);
extern unsigned short (*v22) (signed char);
extern unsigned char v23 (unsigned char, unsigned short, unsigned char, signed int);
extern unsigned char (*v24) (unsigned char, unsigned short, unsigned char, signed int);
extern unsigned char v25 (unsigned short);
extern unsigned char (*v26) (unsigned short);
extern unsigned int v27 (unsigned int, unsigned short);
extern unsigned int (*v28) (unsigned int, unsigned short);
extern signed short v29 (signed int, signed short, signed int, signed char);
extern signed short (*v30) (signed int, signed short, signed int, signed char);
extern int history[];
extern int history_index;
extern int trace;
unsigned short v97 = 5;
signed short v96 = -1;
signed int v95 = 1;
