IMPLICIT REAL(2) (R-T)
TYPE TY
REAL(2),ALLOCATABLE :: R2CMP(:)
END TYPE

REAL(KIND=2) :: RR2 = 2
REAL(KIND=2):: CC2(2)
REAL(KIND=2),TARGET :: AC2(2)
REAL(KIND=2),POINTER:: PAC2(:)
TYPE(TY),TARGET :: OBJ = TY(NULL())
REAL(2),PARAMETER :: ARR(*) = [2,3]
PROCEDURE(REAL(2)),POINTER :: PPTR
REAL(2),ALLOCATABLE :: R2ALC(:)

PPTR=>R2FUN
IF(PPTR() .NE. 2) PRINT*,"110"
ALLOCATE(REAL(2)::R2ALC(3))

IF(KIND(TIMP) .NE. 2) PRINT*,"120"
IF(ANY(ARR  .NE. [2,3])) PRINT*,"120_1"
ASSOCIATE(AA=>RR2+RR2)
IF(KIND(AA) .NE. 2) PRINT*,121
IF(AA .NE. 4) PRINT*,122
IF(AA+3 .NE. 7) PRINT*,122
END ASSOCIATE
CC2 = [REAL(2)::2,3]
AC2 = CC2
IF(ANY(CC2 .NE. [REAL(2)::2,3])) PRINT*,123
OBJ = TY(CC2)
CALL SUB(OBJ,AC2,AC2+AC2,(AC2),R2ALC(1:3:2),R2ALC)
CALL SUBC(AC2(2))
IF(AC2(2) .NE. 5) PRINT*,"223"
IF(ANY(OBJ%R2CMP .NE. [REAL(2)::4,5])) PRINT*,124
PAC2=>OBJ%R2CMP
IF(ANY(PAC2.NE. [4,5])) PRINT*,"222"
PRINT*,"PASS"
CONTAINS
SUBROUTINE SUB(DPTR,ADPTR,ADEXP,ADPAR,DANULL,ASIZE)
TYPE(TY),POINTER,INTENT(IN) :: DPTR
REAL(2),POINTER,INTENT(IN) :: ADPTR(:)
REAL(2) :: ADEXP(:)
REAL(2) :: ADPAR(:)
TYPE(*),target :: DANULL(:)

REAL(2) :: ASIZE(..)
IF(SIZE(ASIZE) .NE. 3) PRINT*,"220"
IF(ANY(DPTR%R2CMP .NE. [2,3])) PRINT*,"221"
IF(ANY(ADPTR .NE. [2,3])) PRINT*,"222"
IF(ANY(ADPAR .NE. [2,3])) PRINT*,"223"
IF(ANY(ADEXP .NE. [4,6])) PRINT*,"224"
IF(SIZE(DANULL) .NE. 2) PRINT*,"225"
IF(IS_CONTIGUOUS(DANULL) .NEQV. .FALSE.) PRINT*,"225_1"
DPTR%R2CMP = DPTR%R2CMP + 2
END
SUBROUTINE SUBC(CDPTR)
CLASS(*) :: CDPTR
CLASS(*),POINTER :: CPTR
REAL(2),TARGET:: TRG = 6
CPTR => TRG
SELECT TYPE(CDPTR)
TYPE IS(REAL(KIND=2))
     IF(CDPTR .NE. 3) PRINT*,"302"
     CDPTR = 5
CLASS DEFAULT
  PRINT*,"301"
END SELECT
IF(SAME_TYPE_AS(CPTR,CDPTR) .NEQV. .TRUE.) PRINT*,"302"
END
REAL(2) FUNCTION R2FUN()
  R2FUN = 2
END
END
