MODULE M1
TYPE TY
 REAL*2,POINTER::R2(:)
 COMPLEX(KIND=2),ALLOCATABLE::C2(:,:)
END TYPE
END MODULE

USE M1
TYPE(TY) :: OBJ
REAL*2,TARGET :: TAR(-3:4)
TAR=7.0
OBJ%R2=>TAR
ALLOCATE(OBJ%C2(2,3))
OBJ%C2=(8.0,9.0)
IF(ALLOCATED(OBJ%C2) .EQV. .FALSE.)PRINT*,"101"
IF(ANY(OBJ%R2 .NE. 7.0))PRINT*,"102"
PRINT*,"PASS"
END
