TYPE TY
REAL (KIND=2),ALLOCATABLE :: R2(:)
COMPLEX(KIND=2),POINTER :: C2(:)
END TYPE
TYPE(TY) :: OBJ
B1: BLOCK
ALLOCATE(OBJ%R2(2))
ALLOCATE(OBJ%C2(2))
OBJ%R2=4
OBJ%C2=(8,9)
B2: BLOCK
COMPLEX(2),ALLOCATABLE :: CMP
REAL(2),ALLOCATABLE :: RMP
ALLOCATE(CMP)
ALLOCATE(RMP)
CMP=(7,8)+OBJ%C2(1)
RMP=5+OBJ%R2(1)
IF(RMP .NE. 9)PRINT*,"101"
IF(CMP .NE. (15,17))PRINT*,"102"
END BLOCK B2
IF(ANY(OBJ%R2 .NE. 4))PRINT*,"103"
IF(ANY(OBJ%C2 .NE. (8,9)))PRINT*,"104"
END BLOCK B1
PRINT *,"PASS"
END 
