TYPE TY
COMPLEX(2),POINTER :: C2(:)
REAL(2),POINTER:: R2(:)
COMPLEX(2) :: C2_TAR(2)
REAL(2):: R2_TAR(2)
END TYPE
TYPE(TY),TARGET :: OBJ
OBJ%R2_TAR=5
OBJ%C2_TAR=(6,7)
DATA OBJ%R2/OBJ%R2_TAR/ 
DATA OBJ%C2/OBJ%C2_TAR/ 
IF(ANY(OBJ%R2 .NE. 5))PRINT*,"101"
IF(ANY(OBJ%C2 .NE. (6,7)))PRINT*,"102"
PRINT*,"PASS"
END
