COMPLEX(KIND=2),ALLOCATABLE :: C1
COMPLEX(KIND=2),ALLOCATABLE :: C2(:)
COMPLEX(KIND=2),ALLOCATABLE :: C3(:,:)
COMPLEX(KIND=2),ALLOCATABLE :: C4(:,:,:)
ALLOCATE(COMPLEX(2) :: C1)
ALLOCATE(COMPLEX(2) :: C2(4))
ALLOCATE(COMPLEX(2) :: C3(5,6),C4(1,2,3))
IF(ALLOCATED(C1) .EQV. .FALSE.)PRINT*,"101"
IF(ALLOCATED(C2) .EQV. .FALSE.)PRINT*,"102"
IF(ALLOCATED(C3) .EQV. .FALSE.)PRINT*,"103"
IF(ALLOCATED(C4) .EQV. .FALSE.)PRINT*,"104"
DEALLOCATE(C1,C2,C3,C4)
IF(ALLOCATED(C1) .EQV. .TRUE.)PRINT*,"105"
IF(ALLOCATED(C2) .EQV. .TRUE.)PRINT*,"106"
IF(ALLOCATED(C3) .EQV. .TRUE.)PRINT*,"107"
IF(ALLOCATED(C4) .EQV. .TRUE.)PRINT*,"108"
PRINT*,"PASS"
END
