extern signed char v1 (signed char, signed char, unsigned int, unsigned char);
extern signed char (*v2) (signed char, signed char, unsigned int, unsigned char);
extern signed char v3 (unsigned char, signed short);
extern signed char (*v4) (unsigned char, signed short);
extern signed short v5 (signed char);
extern signed short (*v6) (signed char);
extern unsigned int v7 (void);
extern unsigned int (*v8) (void);
extern void v11 (unsigned short, unsigned short, signed short);
extern void (*v12) (unsigned short, unsigned short, signed short);
extern void v15 (unsigned char);
extern void (*v16) (unsigned char);
extern unsigned int v17 (unsigned char, signed char);
extern unsigned int (*v18) (unsigned char, signed char);
extern signed char v19 (unsigned int);
extern signed char (*v20) (unsigned int);
extern unsigned short v21 (unsigned short);
extern unsigned short (*v22) (unsigned short);
extern unsigned short v23 (unsigned char);
extern unsigned short (*v24) (unsigned char);
extern signed char v25 (unsigned int);
extern signed char (*v26) (unsigned int);
extern signed char v27 (signed int, unsigned int);
extern signed char (*v28) (signed int, unsigned int);
extern signed short v29 (unsigned char, signed char, signed int);
extern signed short (*v30) (unsigned char, signed char, signed int);
extern int history[];
extern int history_index;
extern int trace;
unsigned char v86 = 4;
signed short v85 = -1;
unsigned int v84 = 5U;
