extern unsigned short v1 (void);
extern unsigned short (*v2) (void);
extern signed short v3 (unsigned int, signed int);
extern signed short (*v4) (unsigned int, signed int);
extern unsigned short v5 (unsigned short, signed char);
extern unsigned short (*v6) (unsigned short, signed char);
extern signed int v7 (unsigned int, unsigned int);
extern signed int (*v8) (unsigned int, unsigned int);
extern unsigned short v9 (signed short);
extern unsigned short (*v10) (signed short);
extern unsigned short v11 (void);
extern unsigned short (*v12) (void);
extern unsigned short v13 (unsigned short);
extern unsigned short (*v14) (unsigned short);
extern void v15 (signed char, unsigned int);
extern void (*v16) (signed char, unsigned int);
extern signed short v17 (void);
extern signed short (*v18) (void);
extern signed char v19 (unsigned short, signed int, signed short);
extern signed char (*v20) (unsigned short, signed int, signed short);
extern unsigned char v21 (void);
extern unsigned char (*v22) (void);
extern void v23 (signed char, signed int, signed short, signed int);
extern void (*v24) (signed char, signed int, signed short, signed int);
extern unsigned char v25 (void);
extern unsigned char (*v26) (void);
extern unsigned int v27 (signed short);
extern unsigned int (*v28) (signed short);
extern unsigned int v29 (void);
extern unsigned int (*v30) (void);
extern int history[];
extern int history_index;
extern int trace;
signed short v47 = -4;
unsigned short v46 = 5;
unsigned int v45 = 2U;
