extern unsigned int v1 (unsigned int, signed int);
extern unsigned int (*v2) (unsigned int, signed int);
extern unsigned short v3 (signed short, signed int, unsigned short, signed short);
extern unsigned short (*v4) (signed short, signed int, unsigned short, signed short);
extern unsigned short v5 (unsigned short, unsigned char, unsigned int, signed char);
extern unsigned short (*v6) (unsigned short, unsigned char, unsigned int, signed char);
extern signed char v7 (unsigned char);
extern signed char (*v8) (unsigned char);
extern signed int v9 (signed char);
extern signed int (*v10) (signed char);
extern signed int v11 (unsigned short);
extern signed int (*v12) (unsigned short);
extern signed int v15 (signed char, signed int, unsigned char);
extern signed int (*v16) (signed char, signed int, unsigned char);
extern signed short v17 (signed short);
extern signed short (*v18) (signed short);
extern signed char v19 (unsigned int, signed int);
extern signed char (*v20) (unsigned int, signed int);
extern signed int v21 (signed int, signed short, unsigned short, signed int);
extern signed int (*v22) (signed int, signed short, unsigned short, signed int);
extern unsigned char v23 (unsigned int, signed int, unsigned int);
extern unsigned char (*v24) (unsigned int, signed int, unsigned int);
extern void v25 (unsigned char);
extern void (*v26) (unsigned char);
extern signed short v27 (signed short);
extern signed short (*v28) (signed short);
extern unsigned short v29 (unsigned short, signed char);
extern unsigned short (*v30) (unsigned short, signed char);
extern int history[];
extern int history_index;
extern int trace;
signed char v110 = -2;
signed int v109 = 3;
unsigned int v108 = 1U;
