  INTERFACE GENERIC_NAME
    SUBROUTINE SUB1()
    END SUBROUTINE SUB1
  END INTERFACE GENERIC_NAME
  INTERFACE ASSIGNMENT(=)
    SUBROUTINE ASS_1(ARG1,ARG2)
      LOGICAL,INTENT(OUT) :: ARG1
      INTEGER,INTENT(IN)  :: ARG2
    END SUBROUTINE
  END INTERFACE ASSIGNMENT(=)
  print *,'pass'
  end
