 ELEMENTAL FUNCTION FUN(ARG1,ARG2) RESULT(RES)
  INTEGER,INTENT(IN) :: ARG1,ARG2
  INTEGER :: RES
  RES = ARG1 + ARG2
  END FUNCTION FUN

  PROGRAM MAIN
  INTEGER,DIMENSION(3) :: A=(/2,4,6/)
  INTEGER,DIMENSION(3) :: B=(/1,2,3/)
  INTERFACE
    ELEMENTAL FUNCTION FUN(ARG1,ARG2) RESULT(RES)
    INTEGER,INTENT(IN) :: ARG1,ARG2
    INTEGER :: RES
    END FUNCTION FUN
  END INTERFACE
  if(any(FUN(A,B)/=(/3,6,9/)))write(6,*) "NG"
  print *,'pass'
  END PROGRAM MAIN
