INTEGER,PARAMETER::M=5
INTEGER I
INTEGER::ARR(5),BRR(5),CRR(5)=(/2,3,4,5,6/)
I=45
DO CONCURRENT (INTEGER::I=1:M)
  ARR(I)=10+I
 BLOCK
 INTEGER::I
  I=44
  DO CONCURRENT (INTEGER::I=1:M)
   BRR(I)= I+1
  END DO
 IF(I /= 44)PRINT*,201
 END BLOCK
 IF(ANY(BRR/= CRR))PRINT*,101
END DO
 IF(ANY(ARR/= CRR+9))PRINT*,102
 IF(I /= 45)PRINT*,202

PRINT*,"PASS"
END
