INTEGER::ARR(2)

ASSOCIATE(II=>5)

DATA (ARR(II),INTEGER::II=1,2) /2*44/ 
IF (ANY(ARR /= [(44,INTEGER::II=1,2)]))PRINT*,103,ARR

DO CONCURRENT(INTEGER::II=1:2)
ARR(II)=II
END DO
IF(ANY(ARR /= (/(II,INTEGER::II=1,2)/)))PRINT*,101

FORALL (INTEGER::II=1:2)
ARR(II)=II+2
END FORALL
IF(ANY(ARR /= (/(II+2,INTEGER::II=1,2)/)))PRINT*,102

END ASSOCIATE
PRINT*,"PASS"
END


