extern signed short v1 (unsigned int, unsigned char, signed short);
extern signed short (*v2) (unsigned int, unsigned char, signed short);
extern signed short v3 (void);
extern signed short (*v4) (void);
extern unsigned int v5 (unsigned char, unsigned short, signed int, signed int);
extern unsigned int (*v6) (unsigned char, unsigned short, signed int, signed int);
extern unsigned short v7 (void);
extern unsigned short (*v8) (void);
extern unsigned char v9 (signed short, unsigned int, signed int);
extern unsigned char (*v10) (signed short, unsigned int, signed int);
extern unsigned short v11 (unsigned int, signed short, unsigned int, signed short);
extern unsigned short (*v12) (unsigned int, signed short, unsigned int, signed short);
extern unsigned char v13 (void);
extern unsigned char (*v14) (void);
extern unsigned short v15 (void);
extern unsigned short (*v16) (void);
extern signed short v17 (unsigned int, unsigned char);
extern signed short (*v18) (unsigned int, unsigned char);
extern unsigned short v19 (signed char, unsigned short, signed int, unsigned int);
extern unsigned short (*v20) (signed char, unsigned short, signed int, unsigned int);
extern signed short v21 (signed short, signed short, unsigned char);
extern signed short (*v22) (signed short, signed short, unsigned char);
extern signed int v23 (unsigned char, unsigned short, signed char);
extern signed int (*v24) (unsigned char, unsigned short, signed char);
extern void v25 (void);
extern void (*v26) (void);
extern signed short v27 (unsigned short, signed short);
extern signed short (*v28) (unsigned short, signed short);
extern signed int v29 (void);
extern signed int (*v30) (void);
extern int history[];
extern int history_index;
extern int trace;
unsigned int v54 = 7U;
signed short v53 = 0;
signed short v52 = 1;
