TYPE POINT
REAL :: X,Y
END TYPE POINT
TYPE, EXTENDS(POINT) :: POINT_3D
REAL :: Z
END TYPE POINT_3D
TYPE, EXTENDS(POINT) :: COLOR_POINT
INTEGER :: COLOR
END TYPE COLOR_POINT
TYPE(POINT), TARGET :: P
TYPE(POINT_3D), TARGET :: P3
TYPE(COLOR_POINT), TARGET :: C
CLASS(POINT), POINTER :: P_OR_C
P3%X=1
P3%y=2
P3%z=3
P_OR_C => P3
SELECT TYPE ( P_OR_C )
CLASS IS ( POINT )
write(1,*) P_OR_C%X, P_OR_C%Y
TYPE IS ( POINT_3D )
write(1,*) P_OR_C%X, P_OR_C%Y, P_OR_C%Z
END SELECT
rewind 1
read(1,*) r1,r2,r3
if (r1/=1)print *,1001
if (r2/=2)print *,1001
if (r3/=3)print *,1001
print *,'pass'
end
