extern unsigned short v1 (unsigned short, signed char, unsigned char);
extern unsigned short (*v2) (unsigned short, signed char, unsigned char);
extern signed short v3 (unsigned char);
extern signed short (*v4) (unsigned char);
extern unsigned int v5 (signed char, unsigned short);
extern unsigned int (*v6) (signed char, unsigned short);
extern unsigned char v7 (unsigned short, unsigned char, unsigned short);
extern unsigned char (*v8) (unsigned short, unsigned char, unsigned short);
extern unsigned int v9 (signed short);
extern unsigned int (*v10) (signed short);
extern unsigned char v11 (unsigned char);
extern unsigned char (*v12) (unsigned char);
extern unsigned char v15 (void);
extern unsigned char (*v16) (void);
extern unsigned int v19 (unsigned short, unsigned char, signed int);
extern unsigned int (*v20) (unsigned short, unsigned char, signed int);
extern signed int v21 (unsigned char);
extern signed int (*v22) (unsigned char);
extern signed char v23 (void);
extern signed char (*v24) (void);
extern unsigned char v25 (signed char, unsigned int);
extern unsigned char (*v26) (signed char, unsigned int);
extern unsigned char v27 (signed int, signed int, unsigned int, signed char);
extern unsigned char (*v28) (signed int, signed int, unsigned int, signed char);
extern unsigned int v29 (unsigned int, signed int, unsigned int);
extern unsigned int (*v30) (unsigned int, signed int, unsigned int);
extern int history[];
extern int history_index;
extern int trace;
unsigned char v148 = 3;
signed int v147 = 2;
unsigned int v146 = 5U;
