INTERFACE SWITCH

   SUBROUTINE INT_SWITCH(X, Y)
      INTEGER, INTENT (INOUT) :: X, Y
   END SUBROUTINE INT_SWITCH

   SUBROUTINE REAL_SWITCH (X, Y)
      REAL, INTENT (INOUT) :: X, Y
   END SUBROUTINE REAL_SWITCH

   SUBROUTINE COMPLEX_SWITCH (X, Y)
      COMPLEX, INTENT (INOUT) :: X, Y
   END SUBROUTINE COMPLEX_SWITCH

END INTERFACE

INTEGER MAX_VAL, LOC_VAL
REAL    REAL_X, REAL_Y
COMPLEX COMPLEX_X, COMPLEX_Y
MAX_VAL = 100; LOC_VAL = 1
REAL_X = 123456789e+30; REAL_Y = 1.0
COMPLEX_X = (123456789e+30, 1.0); COMPLEX_Y = (1.0, 1.0)
CALL SWITCH (MAX_VAL, LOC_VAL)
CALL SWITCH (REAL_X, REAL_Y)
CALL SWITCH (COMPLEX_X, COMPLEX_Y)
PRINT *,'PASS'
END

SUBROUTINE INT_SWITCH(X, Y)
   INTEGER, INTENT (INOUT) :: X, Y
   NAMELIST /INTLIST/ X,Y
   PRINT *,'*** int_switch ***'
   WRITE (*, INTLIST)
END SUBROUTINE INT_SWITCH

SUBROUTINE REAL_SWITCH (X, Y)
   REAL, INTENT (INOUT) :: X, Y
   NAMELIST /REALLIST/ X,Y
   PRINT *,'*** real_switch ***'
   WRITE (*, REALLIST)
END SUBROUTINE REAL_SWITCH

SUBROUTINE COMPLEX_SWITCH (X, Y)
   COMPLEX, INTENT (INOUT) :: X, Y
   NAMELIST /COMPLEXLIST/ X,Y
   PRINT *,'*** complex_switch ***'
   WRITE (*, COMPLEXLIST)
END SUBROUTINE COMPLEX_SWITCH
