INTERFACE SWITCH
   SUBROUTINE COMPLEX_SWITCH (X)
      COMPLEX, INTENT (INOUT) :: X
   END SUBROUTINE COMPLEX_SWITCH
END INTERFACE

COMPLEX COMPLEX_X
COMPLEX_X = (123456789e+30, 1.0)
CALL SWITCH (COMPLEX_X)
PRINT *,'PASS'
END

SUBROUTINE COMPLEX_SWITCH (X)
   COMPLEX, INTENT (INOUT) :: X
   NAMELIST /COMPLEXLIST/ X
   WRITE (*, COMPLEXLIST)
END SUBROUTINE COMPLEX_SWITCH

