extern signed int v3 (signed char, signed int, signed short);
extern signed int (*v4) (signed char, signed int, signed short);
extern void v5 (void);
extern void (*v6) (void);
extern unsigned char v7 (signed char, signed short, signed char);
extern unsigned char (*v8) (signed char, signed short, signed char);
extern unsigned short v9 (unsigned int, signed int, unsigned short);
extern unsigned short (*v10) (unsigned int, signed int, unsigned short);
extern signed char v11 (unsigned char, unsigned short, signed char, signed short);
extern signed char (*v12) (unsigned char, unsigned short, signed char, signed short);
extern unsigned int v13 (signed short);
extern unsigned int (*v14) (signed short);
extern unsigned int v15 (void);
extern unsigned int (*v16) (void);
extern void v17 (unsigned char, unsigned int);
extern void (*v18) (unsigned char, unsigned int);
extern signed int v19 (signed int);
extern signed int (*v20) (signed int);
extern signed int v21 (void);
extern signed int (*v22) (void);
extern void v25 (signed short, signed short, unsigned char, unsigned char);
extern void (*v26) (signed short, signed short, unsigned char, unsigned char);
extern void v27 (unsigned short, unsigned int, unsigned int, unsigned char);
extern void (*v28) (unsigned short, unsigned int, unsigned int, unsigned char);
extern unsigned int v29 (signed int, signed char);
extern unsigned int (*v30) (signed int, signed char);
extern int history[];
extern int history_index;
extern int trace;
signed char v61 = -4;
signed int v60 = 0;
unsigned int v59 = 0U;
