extern signed short v1 (unsigned short, unsigned short);
extern signed short (*v2) (unsigned short, unsigned short);
extern signed int v3 (signed char, signed char, unsigned int);
extern signed int (*v4) (signed char, signed char, unsigned int);
extern unsigned short v5 (unsigned int, signed short, signed int, unsigned int);
extern unsigned short (*v6) (unsigned int, signed short, signed int, unsigned int);
extern unsigned char v7 (signed int, signed int, signed int, signed char);
extern unsigned char (*v8) (signed int, signed int, signed int, signed char);
extern unsigned short v9 (unsigned short, signed short);
extern unsigned short (*v10) (unsigned short, signed short);
extern unsigned char v13 (signed short, unsigned char, unsigned char);
extern unsigned char (*v14) (signed short, unsigned char, unsigned char);
extern signed char v15 (void);
extern signed char (*v16) (void);
extern unsigned int v17 (signed int, signed char, signed int, unsigned char);
extern unsigned int (*v18) (signed int, signed char, signed int, unsigned char);
extern unsigned int v19 (signed short);
extern unsigned int (*v20) (signed short);
extern signed char v21 (unsigned int);
extern signed char (*v22) (unsigned int);
extern unsigned char v23 (unsigned int, unsigned int, signed char, unsigned short);
extern unsigned char (*v24) (unsigned int, unsigned int, signed char, unsigned short);
extern void v25 (unsigned short, unsigned short);
extern void (*v26) (unsigned short, unsigned short);
extern signed int v27 (void);
extern signed int (*v28) (void);
extern signed int v29 (unsigned short, unsigned char, unsigned char);
extern signed int (*v30) (unsigned short, unsigned char, unsigned char);
extern int history[];
extern int history_index;
extern int trace;
signed int v78 = 1;
unsigned int v77 = 3U;
signed short v76 = 3;
