extern signed char v3 (signed char);
extern signed char (*v4) (signed char);
extern unsigned int v5 (void);
extern unsigned int (*v6) (void);
extern unsigned int v7 (signed char);
extern unsigned int (*v8) (signed char);
extern unsigned char v9 (unsigned int, unsigned int);
extern unsigned char (*v10) (unsigned int, unsigned int);
extern void v11 (unsigned int, unsigned char, signed char, unsigned char);
extern void (*v12) (unsigned int, unsigned char, signed char, unsigned char);
extern signed int v13 (unsigned short, signed char);
extern signed int (*v14) (unsigned short, signed char);
extern signed short v15 (signed char, unsigned short);
extern signed short (*v16) (signed char, unsigned short);
extern unsigned char v17 (signed short, signed char, signed short);
extern unsigned char (*v18) (signed short, signed char, signed short);
extern unsigned char v19 (unsigned int, unsigned int, unsigned short, unsigned char);
extern unsigned char (*v20) (unsigned int, unsigned int, unsigned short, unsigned char);
extern signed char v21 (unsigned short, signed int, signed char);
extern signed char (*v22) (unsigned short, signed int, signed char);
extern signed int v23 (unsigned int, signed int, unsigned short, unsigned char);
extern signed int (*v24) (unsigned int, signed int, unsigned short, unsigned char);
extern unsigned short v25 (signed short);
extern unsigned short (*v26) (signed short);
extern unsigned char v27 (unsigned short, signed int, unsigned char);
extern unsigned char (*v28) (unsigned short, signed int, unsigned char);
extern unsigned int v29 (unsigned char, signed char);
extern unsigned int (*v30) (unsigned char, signed char);
extern int history[];
extern int history_index;
extern int trace;
unsigned short v122 = 0;
unsigned char v121 = 1;
signed short v120 = 3;
