extern unsigned char v1 (signed char, unsigned int, unsigned int, unsigned int);
extern unsigned char (*v2) (signed char, unsigned int, unsigned int, unsigned int);
extern signed char v3 (signed int, unsigned char, unsigned int, unsigned char);
extern signed char (*v4) (signed int, unsigned char, unsigned int, unsigned char);
extern unsigned short v5 (void);
extern unsigned short (*v6) (void);
extern signed char v7 (signed short, unsigned short);
extern signed char (*v8) (signed short, unsigned short);
extern signed char v9 (signed char, unsigned short, unsigned int);
extern signed char (*v10) (signed char, unsigned short, unsigned int);
extern unsigned short v13 (unsigned char, signed short, unsigned char);
extern unsigned short (*v14) (unsigned char, signed short, unsigned char);
extern signed short v15 (signed char, signed short);
extern signed short (*v16) (signed char, signed short);
extern signed char v17 (signed short, unsigned char);
extern signed char (*v18) (signed short, unsigned char);
extern unsigned short v19 (signed int, signed char, signed short, unsigned short);
extern unsigned short (*v20) (signed int, signed char, signed short, unsigned short);
extern signed char v21 (void);
extern signed char (*v22) (void);
extern unsigned int v23 (signed int, unsigned short);
extern unsigned int (*v24) (signed int, unsigned short);
extern void v25 (void);
extern void (*v26) (void);
extern unsigned short v27 (signed char);
extern unsigned short (*v28) (signed char);
extern int history[];
extern int history_index;
extern int trace;
signed char v145 = -1;
unsigned int v144 = 0U;
unsigned short v143 = 5;
