MODULE mod1
IMPLICIT NONE
TYPE ty
  INTEGER :: ii=1
  CONTAINS
    FINAL::destructor_ty
END TYPE
CONTAINS
SUBROUTINE destructor_ty(dmy)
  TYPE(ty)::dmy
  PRINT*,dmy%ii
END SUBROUTINE
END MODULE 


MODULE mod2
USE mod1
IMPLICIT NONE
TYPE,EXTENDS(ty)::ty1
  INTEGER :: jj=2
  CLASS(*),ALLOCATABLE::ty_ptr
END TYPE
END MODULE 


PROGRAM MAIN
USE mod2
IMPLICIT NONE
TYPE(ty1)  :: ty1_obj1
TYPE(ty1)  :: ty1_obj2
ty1_obj2%ii=50
ALLOCATE(ty1_obj1%ty_ptr,SOURCE=ty1_obj2)
DEALLOCATE(ty1_obj1%ty_ptr)
END
