extern signed int v1 (unsigned short);
extern signed int (*v2) (unsigned short);
extern signed char v3 (unsigned char);
extern signed char (*v4) (unsigned char);
extern unsigned char v5 (unsigned int, unsigned char);
extern unsigned char (*v6) (unsigned int, unsigned char);
extern unsigned int v7 (unsigned int, unsigned char);
extern unsigned int (*v8) (unsigned int, unsigned char);
extern signed short v9 (unsigned short, unsigned int);
extern signed short (*v10) (unsigned short, unsigned int);
extern unsigned int v11 (void);
extern unsigned int (*v12) (void);
extern signed char v13 (unsigned char, signed char, unsigned int);
extern signed char (*v14) (unsigned char, signed char, unsigned int);
extern signed char v15 (unsigned short, unsigned int, unsigned int, signed short);
extern signed char (*v16) (unsigned short, unsigned int, unsigned int, signed short);
extern void v17 (signed int);
extern void (*v18) (signed int);
extern unsigned int v19 (signed char);
extern unsigned int (*v20) (signed char);
extern unsigned char v21 (unsigned int, unsigned int, signed char, unsigned int);
extern unsigned char (*v22) (unsigned int, unsigned int, signed char, unsigned int);
extern unsigned short v25 (signed int, unsigned int);
extern unsigned short (*v26) (signed int, unsigned int);
extern signed int v27 (unsigned short, signed char, unsigned int, unsigned char);
extern signed int (*v28) (unsigned short, signed char, unsigned int, unsigned char);
extern unsigned char v29 (void);
extern unsigned char (*v30) (void);
extern int history[];
extern int history_index;
extern int trace;
signed short v126 = -1;
signed char v125 = -4;
unsigned short v124 = 7;
