extern unsigned int v1 (signed int);
extern unsigned int (*v2) (signed int);
extern void v3 (unsigned char, signed int, signed char);
extern void (*v4) (unsigned char, signed int, signed char);
extern signed char v5 (signed int, signed short, unsigned int, signed int);
extern signed char (*v6) (signed int, signed short, unsigned int, signed int);
extern unsigned int v7 (unsigned char);
extern unsigned int (*v8) (unsigned char);
extern unsigned char v9 (signed short, unsigned char, signed char, unsigned short);
extern unsigned char (*v10) (signed short, unsigned char, signed char, unsigned short);
extern signed short v11 (signed char, signed int, signed int);
extern signed short (*v12) (signed char, signed int, signed int);
extern signed short v13 (void);
extern signed short (*v14) (void);
extern unsigned char v15 (unsigned short);
extern unsigned char (*v16) (unsigned short);
extern unsigned int v17 (unsigned char, unsigned short, unsigned short, unsigned int);
extern unsigned int (*v18) (unsigned char, unsigned short, unsigned short, unsigned int);
extern unsigned int v19 (signed char, signed char, signed short, signed short);
extern unsigned int (*v20) (signed char, signed char, signed short, signed short);
extern signed char v21 (void);
extern signed char (*v22) (void);
extern signed short v23 (unsigned int);
extern signed short (*v24) (unsigned int);
extern void v25 (unsigned int, signed char);
extern void (*v26) (unsigned int, signed char);
extern signed short v27 (signed int, unsigned short, unsigned int, signed char);
extern signed short (*v28) (signed int, unsigned short, unsigned int, signed char);
extern signed short v29 (signed int, signed short, signed char);
extern signed short (*v30) (signed int, signed short, signed char);
extern int history[];
extern int history_index;
extern int trace;
signed char v83 = -4;
unsigned char v82 = 3;
unsigned char v81 = 2;
