extern void v1 (unsigned int, signed char);
extern void (*v2) (unsigned int, signed char);
extern unsigned int v3 (signed int);
extern unsigned int (*v4) (signed int);
extern signed char v5 (signed short);
extern signed char (*v6) (signed short);
extern unsigned char v7 (unsigned int, unsigned char, signed short);
extern unsigned char (*v8) (unsigned int, unsigned char, signed short);
extern signed short v9 (signed int, unsigned int, unsigned int, signed int);
extern signed short (*v10) (signed int, unsigned int, unsigned int, signed int);
extern signed short v11 (unsigned char, signed short, unsigned short, signed int);
extern signed short (*v12) (unsigned char, signed short, unsigned short, signed int);
extern unsigned short v13 (unsigned char, unsigned char, signed char);
extern unsigned short (*v14) (unsigned char, unsigned char, signed char);
extern unsigned char v15 (unsigned int, signed char);
extern unsigned char (*v16) (unsigned int, signed char);
extern unsigned int v17 (signed short, unsigned int);
extern unsigned int (*v18) (signed short, unsigned int);
extern void v19 (signed char, signed char, signed int);
extern void (*v20) (signed char, signed char, signed int);
extern signed int v21 (unsigned int);
extern signed int (*v22) (unsigned int);
extern signed char v25 (unsigned int, unsigned char, signed short);
extern signed char (*v26) (unsigned int, unsigned char, signed short);
extern signed char v27 (signed short, signed short, signed int);
extern signed char (*v28) (signed short, signed short, signed int);
extern signed int v29 (signed int, signed int, unsigned int, signed char);
extern signed int (*v30) (signed int, signed int, unsigned int, signed char);
extern int history[];
extern int history_index;
extern int trace;
unsigned char v146 = 5;
signed short v145 = 0;
signed int v144 = 0;
