extern unsigned int v1 (void);
extern unsigned int (*v2) (void);
extern unsigned char v3 (void);
extern unsigned char (*v4) (void);
extern unsigned short v5 (signed char);
extern unsigned short (*v6) (signed char);
extern unsigned short v7 (signed short, unsigned short, unsigned int);
extern unsigned short (*v8) (signed short, unsigned short, unsigned int);
extern signed char v9 (unsigned short, signed char);
extern signed char (*v10) (unsigned short, signed char);
extern signed int v11 (signed char, unsigned char);
extern signed int (*v12) (signed char, unsigned char);
extern unsigned char v13 (signed int, signed int, unsigned short, signed short);
extern unsigned char (*v14) (signed int, signed int, unsigned short, signed short);
extern signed char v15 (unsigned int, signed int, unsigned short);
extern signed char (*v16) (unsigned int, signed int, unsigned short);
extern signed char v17 (void);
extern signed char (*v18) (void);
extern unsigned short v19 (void);
extern unsigned short (*v20) (void);
extern signed char v21 (void);
extern signed char (*v22) (void);
extern void v23 (signed int, unsigned int, signed int);
extern void (*v24) (signed int, unsigned int, signed int);
extern signed char v25 (signed int, signed int, unsigned int, unsigned short);
extern signed char (*v26) (signed int, signed int, unsigned int, unsigned short);
extern unsigned char v27 (signed int, signed short, unsigned char, signed int);
extern unsigned char (*v28) (signed int, signed short, unsigned char, signed int);
extern unsigned char v29 (unsigned short, unsigned short, signed short, unsigned short);
extern unsigned char (*v30) (unsigned short, unsigned short, signed short, unsigned short);
extern int history[];
extern int history_index;
extern int trace;
unsigned char v126 = 1;
signed char v125 = -1;
signed short v124 = -3;
