extern unsigned char v1 (void);
extern unsigned char (*v2) (void);
extern void v3 (signed short, signed int, unsigned char, signed int);
extern void (*v4) (signed short, signed int, unsigned char, signed int);
extern signed short v5 (unsigned char);
extern signed short (*v6) (unsigned char);
extern unsigned short v7 (unsigned int, unsigned short, signed char);
extern unsigned short (*v8) (unsigned int, unsigned short, signed char);
extern unsigned char v9 (signed int);
extern unsigned char (*v10) (signed int);
extern signed char v11 (void);
extern signed char (*v12) (void);
extern void v13 (signed short, signed short, signed int, signed int);
extern void (*v14) (signed short, signed short, signed int, signed int);
extern void v15 (signed int, unsigned int, signed char, unsigned int);
extern void (*v16) (signed int, unsigned int, signed char, unsigned int);
extern void v19 (signed char, unsigned char, unsigned int, unsigned char);
extern void (*v20) (signed char, unsigned char, unsigned int, unsigned char);
extern unsigned int v21 (signed short, signed short, unsigned short, unsigned char);
extern unsigned int (*v22) (signed short, signed short, unsigned short, unsigned char);
extern signed int v23 (unsigned char);
extern signed int (*v24) (unsigned char);
extern signed short v25 (unsigned int, unsigned char, unsigned int);
extern signed short (*v26) (unsigned int, unsigned char, unsigned int);
extern unsigned int v27 (signed char, signed int, signed int);
extern unsigned int (*v28) (signed char, signed int, signed int);
extern signed char v29 (void);
extern signed char (*v30) (void);
extern int history[];
extern int history_index;
extern int trace;
unsigned short v143 = 5;
signed int v142 = 1;
unsigned short v141 = 4;
