extern unsigned short v3 (void);
extern unsigned short (*v4) (void);
extern unsigned char v5 (unsigned char);
extern unsigned char (*v6) (unsigned char);
extern signed int v7 (unsigned short, signed short, unsigned short);
extern signed int (*v8) (unsigned short, signed short, unsigned short);
extern signed int v9 (signed int, signed short, signed int);
extern signed int (*v10) (signed int, signed short, signed int);
extern unsigned short v11 (unsigned char, unsigned short);
extern unsigned short (*v12) (unsigned char, unsigned short);
extern signed char v13 (unsigned int, signed int, unsigned char, signed int);
extern signed char (*v14) (unsigned int, signed int, unsigned char, signed int);
extern signed short v15 (unsigned int);
extern signed short (*v16) (unsigned int);
extern signed char v17 (unsigned int, signed short, unsigned char, unsigned short);
extern signed char (*v18) (unsigned int, signed short, unsigned char, unsigned short);
extern unsigned char v19 (void);
extern unsigned char (*v20) (void);
extern signed short v21 (unsigned short, signed int, signed char);
extern signed short (*v22) (unsigned short, signed int, signed char);
extern unsigned short v23 (unsigned int, unsigned int, unsigned short, unsigned short);
extern unsigned short (*v24) (unsigned int, unsigned int, unsigned short, unsigned short);
extern void v25 (signed int, unsigned char, signed short, unsigned short);
extern void (*v26) (signed int, unsigned char, signed short, unsigned short);
extern unsigned char v29 (signed int, unsigned short, signed char, signed short);
extern unsigned char (*v30) (signed int, unsigned short, signed char, signed short);
extern int history[];
extern int history_index;
extern int trace;
unsigned int v115 = 2U;
signed char v114 = -3;
signed int v113 = 1;
