extern unsigned char v1 (unsigned int, unsigned char, signed int);
extern unsigned char (*v2) (unsigned int, unsigned char, signed int);
extern void v3 (void);
extern void (*v4) (void);
extern signed char v5 (signed char);
extern signed char (*v6) (signed char);
extern signed short v7 (void);
extern signed short (*v8) (void);
extern signed int v9 (unsigned char, signed char, unsigned int);
extern signed int (*v10) (unsigned char, signed char, unsigned int);
extern unsigned short v11 (signed char, unsigned short, signed int, unsigned int);
extern unsigned short (*v12) (signed char, unsigned short, signed int, unsigned int);
extern signed char v13 (unsigned short, signed char, signed char);
extern signed char (*v14) (unsigned short, signed char, signed char);
extern unsigned char v15 (unsigned char);
extern unsigned char (*v16) (unsigned char);
extern signed char v17 (signed int, unsigned int, signed char);
extern signed char (*v18) (signed int, unsigned int, signed char);
extern signed char v19 (signed char, unsigned short, unsigned short);
extern signed char (*v20) (signed char, unsigned short, unsigned short);
extern void v21 (signed char, signed char);
extern void (*v22) (signed char, signed char);
extern unsigned char v23 (signed char, signed char, unsigned short);
extern unsigned char (*v24) (signed char, signed char, unsigned short);
extern void v25 (unsigned int, unsigned char, signed short, unsigned int);
extern void (*v26) (unsigned int, unsigned char, signed short, unsigned int);
extern unsigned short v27 (unsigned int, unsigned short);
extern unsigned short (*v28) (unsigned int, unsigned short);
extern signed int v29 (unsigned int, signed char, signed short, unsigned short);
extern signed int (*v30) (unsigned int, signed char, signed short, unsigned short);
extern int history[];
extern int history_index;
extern int trace;
signed char v89 = 3;
unsigned int v88 = 5U;
unsigned int v87 = 5U;
