program vct011
  implicit none
  integer::i,j
  integer,parameter::n=100
  real,dimension(n)::r
  real,dimension(n,n)::a
  logical,dimension(n,n)::l=reshape((/(.true.,i=1,n*n)/),(/n,n/))
  logical,dimension(n,n)::xl=reshape((/(.true.,i=1,n*n)/),(/n,n/))
  logical,dimension(n,n)::yl=reshape((/(.false.,i=1,n*n)/),(/n,n/))
  logical,dimension(n,n)::zl=reshape((/(.true.,i=1,n*n)/),(/n,n/))
  call random_number(a)
  call random_number(r)
  do j=1,100
     call sub1
  end do
  write(6,*) r(1),r(50)
  stop
contains
  subroutine sub1
    r(1)=maxval(a,mask=l)
    r(3)=maxval(a,mask=yl)
    r(4)=maxval(a,mask=l)
    r(5)=maxval(a,mask=zl)
    r(6)=maxval(a,mask=xl)
    r(2)=maxval(a,xl)
    r(7)=maxval(a,yl)
    r(8)=maxval(a,l)
    r(9)=maxval(a,zl)
    r(10)=maxval(a,l)
    r(21)=maxval(a,mask=l)
    r(23)=maxval(a,mask=yl)
    r(24)=maxval(a,mask=l)
    r(25)=maxval(a,mask=zl)
    r(26)=maxval(a,mask=xl)
    r(22)=maxval(a,xl)
    r(27)=maxval(a,yl)
    r(28)=maxval(a,l)
    r(29)=maxval(a,zl)
    r(30)=maxval(a,l)
    r(31)=maxval(a,mask=l)
    r(33)=maxval(a,mask=yl)
    r(34)=maxval(a,mask=l)
    r(35)=maxval(a,mask=zl)
    r(36)=maxval(a,mask=xl)
    r(32)=maxval(a,xl)
    r(37)=maxval(a,yl)
    r(38)=maxval(a,l)
    r(39)=maxval(a,zl)
    r(40)=maxval(a,l)
    r(41)=maxval(a,mask=l)
    r(43)=maxval(a,mask=yl)
    r(44)=maxval(a,mask=l)
    r(45)=maxval(a,mask=zl)
    r(46)=maxval(a,mask=xl)
    r(42)=maxval(a,xl)
    r(47)=maxval(a,yl)
    r(48)=maxval(a,l)
    r(49)=maxval(a,zl)
    r(50)=maxval(a,l)
    r(51)=maxval(a,mask=l)
    r(53)=maxval(a,mask=yl)
    r(54)=maxval(a,mask=l)
    r(55)=maxval(a,mask=zl)
    r(56)=maxval(a,mask=xl)
    r(52)=maxval(a,xl)
    r(57)=maxval(a,yl)
    r(58)=maxval(a,l)
    r(59)=maxval(a,zl)
    r(60)=maxval(a,l)
    r(61)=maxval(a,mask=l)
    r(63)=maxval(a,mask=yl)
    r(64)=maxval(a,mask=l)
    r(65)=maxval(a,mask=zl)
    r(66)=maxval(a,mask=xl)
    r(62)=maxval(a,xl)
    r(67)=maxval(a,yl)
    r(68)=maxval(a,l)
    r(69)=maxval(a,zl)
    r(70)=maxval(a,l)
    r(71)=maxval(a,mask=l)
    r(73)=maxval(a,mask=yl)
    r(74)=maxval(a,mask=l)
    r(75)=maxval(a,mask=zl)
    r(76)=maxval(a,mask=xl)
    r(72)=maxval(a,xl)
    r(77)=maxval(a,yl)
    r(78)=maxval(a,l)
    r(79)=maxval(a,zl)
    r(80)=maxval(a,l)
    r(81)=maxval(a,mask=l)
    r(83)=maxval(a,mask=yl)
    r(84)=maxval(a,mask=l)
    r(85)=maxval(a,mask=zl)
    r(86)=maxval(a,mask=xl)
    r(82)=maxval(a,xl)
    r(87)=maxval(a,yl)
    r(88)=maxval(a,l)
    r(89)=maxval(a,zl)
    r(90)=maxval(a,l)

    return
  end subroutine sub1
end program vct011
