extern void v1 (signed char, unsigned short);
extern void (*v2) (signed char, unsigned short);
extern void v3 (unsigned int, unsigned short, signed short, unsigned short);
extern void (*v4) (unsigned int, unsigned short, signed short, unsigned short);
extern void v5 (unsigned char);
extern void (*v6) (unsigned char);
extern unsigned short v7 (unsigned int, signed short, signed short);
extern unsigned short (*v8) (unsigned int, signed short, signed short);
extern unsigned int v9 (signed int, signed int, unsigned short);
extern unsigned int (*v10) (signed int, signed int, unsigned short);
extern signed short v11 (unsigned int, unsigned short, unsigned int, unsigned short);
extern signed short (*v12) (unsigned int, unsigned short, unsigned int, unsigned short);
extern void v13 (signed char, unsigned short, signed int, unsigned short);
extern void (*v14) (signed char, unsigned short, signed int, unsigned short);
extern signed int v15 (unsigned int, unsigned int);
extern signed int (*v16) (unsigned int, unsigned int);
extern signed short v17 (signed short, unsigned int, signed char);
extern signed short (*v18) (signed short, unsigned int, signed char);
extern unsigned short v19 (void);
extern unsigned short (*v20) (void);
extern signed short v21 (unsigned short, unsigned int, signed short, unsigned char);
extern signed short (*v22) (unsigned short, unsigned int, signed short, unsigned char);
extern signed short v23 (unsigned char, signed char, unsigned char);
extern signed short (*v24) (unsigned char, signed char, unsigned char);
extern signed char v25 (signed short, signed int, unsigned int, signed short);
extern signed char (*v26) (signed short, signed int, unsigned int, signed short);
extern unsigned short v27 (void);
extern unsigned short (*v28) (void);
extern unsigned short v29 (unsigned short, signed short);
extern unsigned short (*v30) (unsigned short, signed short);
extern int history[];
extern int history_index;
extern int trace;
unsigned int v99 = 1U;
signed char v98 = 0;
unsigned int v97 = 0U;
