extern unsigned short v1 (unsigned int, unsigned char, signed short, unsigned char);
extern unsigned short (*v2) (unsigned int, unsigned char, signed short, unsigned char);
extern unsigned int v3 (unsigned char);
extern unsigned int (*v4) (unsigned char);
extern unsigned char v5 (signed int, signed short);
extern unsigned char (*v6) (signed int, signed short);
extern signed char v7 (signed int, signed char);
extern signed char (*v8) (signed int, signed char);
extern unsigned short v9 (void);
extern unsigned short (*v10) (void);
extern signed int v11 (unsigned int, unsigned int, signed short);
extern signed int (*v12) (unsigned int, unsigned int, signed short);
extern unsigned short v13 (unsigned short, signed short, signed int, unsigned short);
extern unsigned short (*v14) (unsigned short, signed short, signed int, unsigned short);
extern signed char v15 (signed int, unsigned int, unsigned short, unsigned int);
extern signed char (*v16) (signed int, unsigned int, unsigned short, unsigned int);
extern unsigned int v17 (signed char, signed int, signed short, signed char);
extern unsigned int (*v18) (signed char, signed int, signed short, signed char);
extern signed int v19 (unsigned short);
extern signed int (*v20) (unsigned short);
extern signed short v21 (signed int, unsigned int);
extern signed short (*v22) (signed int, unsigned int);
extern signed int v23 (void);
extern signed int (*v24) (void);
extern signed char v25 (unsigned char, unsigned int, unsigned char, unsigned char);
extern signed char (*v26) (unsigned char, unsigned int, unsigned char, unsigned char);
extern unsigned char v27 (unsigned char, signed char);
extern unsigned char (*v28) (unsigned char, signed char);
extern unsigned short v29 (unsigned char, unsigned int, unsigned short, unsigned short);
extern unsigned short (*v30) (unsigned char, unsigned int, unsigned short, unsigned short);
extern int history[];
extern int history_index;
extern int trace;
unsigned char v114 = 7;
signed int v113 = -2;
unsigned short v112 = 6;
