TYPE TEMPERATURES
   INTEGER :: HIGH , LOW
END TYPE TEMPERATURES

TYPE WEATHER
   CHARACTER (LEN = 32) CITY
   TYPE (TEMPERATURES) RANGE (1:50)
END TYPE WEATHER

TYPE (WEATHER) ::WORLDWIDE (200)=&
   WEATHER( ' ' , TEMPERATURES( 300 , -300 ) )

TYPE (TEMPERATURES) :: WATER = TEMPERATURES(100,0)

i=100
WORLDWIDE (I) % CITY = "Nome"
WORLDWIDE (I) % RANGE (1) % LOW = -83
write(91,*)WORLDWIDE (I) % CITY
write(91,*)WORLDWIDE (I) % RANGE (1) % LOW
write(91,*)WORLDWIDE (I) % RANGE (1) % LOW
write(91,*)water%high
print *,'pass'
end
