SUBROUTINE SUB()
TYPE NODE
INTEGER,ALLOCATABLE :: VALUE
TYPE (NODE), ALLOCATABLE :: NEXT_NODE
END TYPE

TYPE(NODE),ALLOCATABLE :: OBJ


OBJ%VALUE = 10
OBJ%NEXT_NODE%VALUE = 11
OBJ%NEXT_NODE%NEXT_NODE%VALUE = 12
OBJ%NEXT_NODE%NEXT_NODE%NEXT_NODE%VALUE = 13

DEALLOCATE(OBJ)

IF(ALLOCATED(OBJ))print*,101

PRINT*,"PASS"
END SUBROUTINE

CALL SUB()
END
