extern signed short v1 (void);
extern signed short (*v2) (void);
extern void v3 (signed short);
extern void (*v4) (signed short);
extern unsigned int v5 (signed char, unsigned int);
extern unsigned int (*v6) (signed char, unsigned int);
extern unsigned short v7 (signed int, unsigned int, signed int, unsigned short);
extern unsigned short (*v8) (signed int, unsigned int, signed int, unsigned short);
extern signed int v9 (unsigned short);
extern signed int (*v10) (unsigned short);
extern signed char v11 (signed int, unsigned short, signed char);
extern signed char (*v12) (signed int, unsigned short, signed char);
extern signed short v13 (unsigned short, unsigned int, signed short);
extern signed short (*v14) (unsigned short, unsigned int, signed short);
extern unsigned short v15 (void);
extern unsigned short (*v16) (void);
extern void v17 (signed short, signed short);
extern void (*v18) (signed short, signed short);
extern unsigned int v19 (unsigned short);
extern unsigned int (*v20) (unsigned short);
extern unsigned char v23 (signed char, unsigned int, signed int);
extern unsigned char (*v24) (signed char, unsigned int, signed int);
extern unsigned short v25 (unsigned short, unsigned int);
extern unsigned short (*v26) (unsigned short, unsigned int);
extern unsigned int v27 (unsigned int, unsigned short, unsigned char, unsigned int);
extern unsigned int (*v28) (unsigned int, unsigned short, unsigned char, unsigned int);
extern unsigned char v29 (void);
extern unsigned char (*v30) (void);
extern int history[];
extern int history_index;
extern int trace;
unsigned char v145 = 1;
unsigned int v144 = 6U;
unsigned int v143 = 0U;
