extern signed char v3 (signed short, signed short, unsigned int);
extern signed char (*v4) (signed short, signed short, unsigned int);
extern signed short v5 (signed int, signed int);
extern signed short (*v6) (signed int, signed int);
extern void v7 (signed int);
extern void (*v8) (signed int);
extern unsigned short v9 (signed int);
extern unsigned short (*v10) (signed int);
extern signed int v11 (signed short, signed int);
extern signed int (*v12) (signed short, signed int);
extern signed short v13 (unsigned short, unsigned int, unsigned int);
extern signed short (*v14) (unsigned short, unsigned int, unsigned int);
extern unsigned int v15 (signed short, signed short, unsigned char);
extern unsigned int (*v16) (signed short, signed short, unsigned char);
extern signed short v17 (signed short, unsigned char, unsigned char, signed char);
extern signed short (*v18) (signed short, unsigned char, unsigned char, signed char);
extern unsigned int v19 (unsigned short);
extern unsigned int (*v20) (unsigned short);
extern signed int v21 (unsigned int, unsigned short, signed int);
extern signed int (*v22) (unsigned int, unsigned short, signed int);
extern unsigned char v23 (unsigned int, signed short, signed char, unsigned char);
extern unsigned char (*v24) (unsigned int, signed short, signed char, unsigned char);
extern unsigned char v25 (unsigned char, unsigned short, unsigned short);
extern unsigned char (*v26) (unsigned char, unsigned short, unsigned short);
extern unsigned char v27 (unsigned char, signed short, unsigned short, signed short);
extern unsigned char (*v28) (unsigned char, signed short, unsigned short, signed short);
extern int history[];
extern int history_index;
extern int trace;
unsigned char v118 = 0;
unsigned char v117 = 5;
unsigned char v116 = 3;
