extern void v1 (void);
extern void (*v2) (void);
extern signed int v3 (unsigned char, unsigned char);
extern signed int (*v4) (unsigned char, unsigned char);
extern void v5 (unsigned char);
extern void (*v6) (unsigned char);
extern unsigned char v7 (signed int, signed int);
extern unsigned char (*v8) (signed int, signed int);
extern signed int v9 (signed int, unsigned int, signed int);
extern signed int (*v10) (signed int, unsigned int, signed int);
extern signed char v11 (signed int, signed int, signed char, unsigned short);
extern signed char (*v12) (signed int, signed int, signed char, unsigned short);
extern unsigned int v13 (signed short);
extern unsigned int (*v14) (signed short);
extern unsigned char v15 (unsigned short, unsigned char, signed int, signed char);
extern unsigned char (*v16) (unsigned short, unsigned char, signed int, signed char);
extern signed char v19 (signed short);
extern signed char (*v20) (signed short);
extern signed char v21 (signed short, signed int, unsigned short);
extern signed char (*v22) (signed short, signed int, unsigned short);
extern signed int v23 (void);
extern signed int (*v24) (void);
extern signed int v25 (signed int, unsigned int);
extern signed int (*v26) (signed int, unsigned int);
extern signed char v27 (unsigned int, signed int, signed char, unsigned short);
extern signed char (*v28) (unsigned int, signed int, signed char, unsigned short);
extern unsigned int v29 (void);
extern unsigned int (*v30) (void);
extern int history[];
extern int history_index;
extern int trace;
signed char v44 = -3;
unsigned int v43 = 4U;
signed int v42 = -1;
