	a=1
 	b=1
  	c=1
   	d=1
    	e=1
     	f=1
      	g=1
       	h=1
        	i=1
9	j=19
99	k=19
999	l=19
9999	m=19
99999	n=19
        if (abs(a-1)>0.001)print *,'e'
        if (abs(b-1)>0.001)print *,'e'
        if (abs(c-1)>0.001)print *,'e'
        if (abs(d-1)>0.001)print *,'e'
        if (abs(e-1)>0.001)print *,'e'
        if (abs(f-1)>0.001)print *,'e'
        if (abs(g-1)>0.001)print *,'e'
        if (abs(h-1)>0.001)print *,'e'
        if (i/=1)print *,'e'
        if (j/=19)print *,'e'
        if (k/=19)print *,'e'
        if (l/=19)print *,'e'
        if (m/=19)print *,'e'
        if (n/=19)print *,'e'
        print *,'pass'
        end
