	i1=1
	=1
 	i2=1
 	=1
  	i3=1
  	=1
   	i4=1
   	=1
    	i5=1
    	=1
     	i6=1
     	=1
      	i7=1
     x 	1
       	i8=1
     x 	1
        	i9=1
		i9=1
1	ia=1
2	=1

        if (i1/=11)print *,'er'
        if (i2/=11)print *,'er'
        if (i3/=11)print *,'er'
        if (i4/=11)print *,'er'
        if (i5/=11)print *,'er'
        if (i6/=11)print *,'er'
        if (i7/=11)print *,'er'
        if (i8/=11)print *,'er'
        if (i9/=1)print *,'er'
        if (ia/=11)print *,'er'
        print *,'pass'
        end
