	i1=1
	=1
 	i2=1
 	=1
  	i3=1
  	=1
   	i4=1
   	=1
    	i5=1
    	=1
     	i6=1
     	=1
      	i7=1
1	ia=1
2	=1
	ib=1
	=1
	=1
	id=1
	23
	45
        if (i1/=11)print *,'er'
        if (i2/=11)print *,'er'
        if (i3/=11)print *,'er'
        if (i4/=11)print *,'er'
        if (i5/=11)print *,'er'
        if (i6/=11)print *,'er'
        if (i7/=1)print *,'er'
        if (ia/=11)print *,'er'
        if (ib/=111)print *,'er'
        if (id/=135)print *,'er'
        print *,'pass'
        end
