extern signed int v1 (signed short, unsigned char, signed short, unsigned int);
extern signed int (*v2) (signed short, unsigned char, signed short, unsigned int);
extern signed char v3 (signed char, unsigned int, signed short);
extern signed char (*v4) (signed char, unsigned int, signed short);
extern void v5 (void);
extern void (*v6) (void);
extern signed int v9 (void);
extern signed int (*v10) (void);
extern void v11 (unsigned int, signed short, unsigned short, signed short);
extern void (*v12) (unsigned int, signed short, unsigned short, signed short);
extern signed char v13 (unsigned short, signed char, signed int, unsigned char);
extern signed char (*v14) (unsigned short, signed char, signed int, unsigned char);
extern unsigned int v15 (void);
extern unsigned int (*v16) (void);
extern unsigned short v17 (unsigned int, signed short, signed int, signed short);
extern unsigned short (*v18) (unsigned int, signed short, signed int, signed short);
extern void v19 (unsigned short, signed short);
extern void (*v20) (unsigned short, signed short);
extern unsigned short v21 (unsigned char, unsigned int);
extern unsigned short (*v22) (unsigned char, unsigned int);
extern signed char v23 (signed char, signed short);
extern signed char (*v24) (signed char, signed short);
extern unsigned int v25 (unsigned char);
extern unsigned int (*v26) (unsigned char);
extern unsigned int v27 (signed char, unsigned int, signed char, signed char);
extern unsigned int (*v28) (signed char, unsigned int, signed char, signed char);
extern void v29 (unsigned int);
extern void (*v30) (unsigned int);
extern int history[];
extern int history_index;
extern int trace;
signed int v56 = 3;
signed short v55 = 1;
unsigned char v54 = 2;
