extern signed short v1 (signed int, signed char);
extern signed short (*v2) (signed int, signed char);
extern unsigned char v3 (signed short);
extern unsigned char (*v4) (signed short);
extern unsigned char v5 (unsigned char, unsigned short, unsigned char, unsigned char);
extern unsigned char (*v6) (unsigned char, unsigned short, unsigned char, unsigned char);
extern signed short v7 (unsigned short, signed short, unsigned char, unsigned short);
extern signed short (*v8) (unsigned short, signed short, unsigned char, unsigned short);
extern unsigned char v9 (unsigned int, unsigned int, unsigned short);
extern unsigned char (*v10) (unsigned int, unsigned int, unsigned short);
extern unsigned char v11 (unsigned char, unsigned short, unsigned short, unsigned short);
extern unsigned char (*v12) (unsigned char, unsigned short, unsigned short, unsigned short);
extern signed char v13 (void);
extern signed char (*v14) (void);
extern void v15 (signed short, unsigned char);
extern void (*v16) (signed short, unsigned char);
extern unsigned char v17 (void);
extern unsigned char (*v18) (void);
extern unsigned int v19 (signed short, signed char, signed char, unsigned char);
extern unsigned int (*v20) (signed short, signed char, signed char, unsigned char);
extern void v21 (signed char, signed int, signed char);
extern void (*v22) (signed char, signed int, signed char);
extern unsigned short v23 (signed short, signed int, unsigned int, signed short);
extern unsigned short (*v24) (signed short, signed int, unsigned int, signed short);
extern signed char v25 (signed int, unsigned short, unsigned char);
extern signed char (*v26) (signed int, unsigned short, unsigned char);
extern signed char v27 (signed int, signed char, signed int);
extern signed char (*v28) (signed int, signed char, signed int);
extern void v29 (signed char, signed char, unsigned char, signed int);
extern void (*v30) (signed char, signed char, unsigned char, signed int);
extern int history[];
extern int history_index;
extern int trace;
signed char v100 = -3;
unsigned char v99 = 0;
signed int v98 = -1;
