extern unsigned int v1 (void);
extern unsigned int (*v2) (void);
extern signed short v3 (signed char, unsigned int, unsigned int, signed short);
extern signed short (*v4) (signed char, unsigned int, unsigned int, signed short);
extern signed int v5 (unsigned short);
extern signed int (*v6) (unsigned short);
extern signed char v11 (unsigned short, signed short);
extern signed char (*v12) (unsigned short, signed short);
extern unsigned char v13 (signed short, signed short);
extern unsigned char (*v14) (signed short, signed short);
extern void v17 (unsigned short, signed short);
extern void (*v18) (unsigned short, signed short);
extern unsigned short v19 (unsigned char, signed int, signed char, unsigned char);
extern unsigned short (*v20) (unsigned char, signed int, signed char, unsigned char);
extern signed int v21 (void);
extern signed int (*v22) (void);
extern unsigned char v23 (unsigned short, unsigned int, signed int, unsigned int);
extern unsigned char (*v24) (unsigned short, unsigned int, signed int, unsigned int);
extern signed short v25 (signed short, unsigned int, signed int, unsigned char);
extern signed short (*v26) (signed short, unsigned int, signed int, unsigned char);
extern unsigned char v27 (signed char);
extern unsigned char (*v28) (signed char);
extern signed char v29 (unsigned int, unsigned int);
extern signed char (*v30) (unsigned int, unsigned int);
extern int history[];
extern int history_index;
extern int trace;
signed int v53 = -2;
unsigned char v52 = 4;
signed int v51 = -1;
