      common /com/ i1,i2,i3,i4,i5,i6,i7,i8,i9,i0,j1,j2,j3,j4,j5,j6,j7,j8,j9,j0
      i1=1
      i2=2
      i3=3
      i4=4
      i5=5
      i6=6
      i7=7
      i8=8
      i9=9
      i0=0
      j1=1
      j2=2
      j3=3
      j4=4
      j5=5
      j6=6
      j7=7
      j8=8
      j9=9
      j0=0
!$omp parallel private(/com/)
      i1=1
      i2=1
      i3=1
      i4=1
      i5=1
      i6=1
      i7=1
      i8=1
      i9=1
      i0=1
      j1=2
      j2=2
      j3=2
      j4=2
      j5=2
      j6=2
      j7=2
      j8=2
      j9=2
      j0=2
      if(i1/=1) print *,"fail"
      if(i2/=1) print *,"fail"
      if(i3/=1) print *,"fail"
      if(i4/=1) print *,"fail"
      if(i5/=1) print *,"fail"
      if(i6/=1) print *,"fail"
      if(i7/=1) print *,"fail"
      if(i8/=1) print *,"fail"
      if(i9/=1) print *,"fail"
      if(i0/=1) print *,"fail"
      if(j1/=2) print *,"fail"
      if(j2/=2) print *,"fail"
      if(j3/=2) print *,"fail"
      if(j4/=2) print *,"fail"
      if(j5/=2) print *,"fail"
      if(j6/=2) print *,"fail"
      if(j7/=2) print *,"fail"
      if(j8/=2) print *,"fail"
      if(j9/=2) print *,"fail"
      if(j0/=2) print *,"fail"
!$omp end parallel
!$    if (.true.) then
!$      if(i1/=1) print *,"fail"
!$      if(i2/=2) print *,"fail"
!$      if(i3/=3) print *,"fail"
!$      if(i4/=4) print *,"fail"
!$      if(i5/=5) print *,"fail"
!$      if(i6/=6) print *,"fail"
!$      if(i7/=7) print *,"fail"
!$      if(i8/=8) print *,"fail"
!$      if(i9/=9) print *,"fail"
!$      if(i0/=0) print *,"fail"
!$      if(j1/=1) print *,"fail"
!$      if(j2/=2) print *,"fail"
!$      if(j3/=3) print *,"fail"
!$      if(j4/=4) print *,"fail"
!$      if(j5/=5) print *,"fail"
!$      if(j6/=6) print *,"fail"
!$      if(j7/=7) print *,"fail"
!$      if(j8/=8) print *,"fail"
!$      if(j9/=9) print *,"fail"
!$      if(j0/=0) print *,"fail"
!$    else
        if(i1/=1) print *,"fail"
        if(i2/=1) print *,"fail"
        if(i3/=1) print *,"fail"
        if(i4/=1) print *,"fail"
        if(i5/=1) print *,"fail"
        if(i6/=1) print *,"fail"
        if(i7/=1) print *,"fail"
        if(i8/=1) print *,"fail"
        if(i9/=1) print *,"fail"
        if(i0/=1) print *,"fail"
        if(j1/=2) print *,"fail"
        if(j2/=2) print *,"fail"
        if(j3/=2) print *,"fail"
        if(j4/=2) print *,"fail"
        if(j5/=2) print *,"fail"
        if(j6/=2) print *,"fail"
        if(j7/=2) print *,"fail"
        if(j8/=2) print *,"fail"
        if(j9/=2) print *,"fail"
        if(j0/=2) print *,"fail"
!$    endif
      print *,'pass'
  end
