extern void v1 (unsigned short, unsigned int, unsigned int, signed short);
extern void (*v2) (unsigned short, unsigned int, unsigned int, signed short);
extern void v3 (signed short, signed short, unsigned char);
extern void (*v4) (signed short, signed short, unsigned char);
extern unsigned char v5 (unsigned int, signed short);
extern unsigned char (*v6) (unsigned int, signed short);
extern signed int v7 (signed char, signed char, unsigned short, signed char);
extern signed int (*v8) (signed char, signed char, unsigned short, signed char);
extern void v9 (signed short, unsigned int, unsigned int, unsigned int);
extern void (*v10) (signed short, unsigned int, unsigned int, unsigned int);
extern signed short v11 (unsigned int, signed short);
extern signed short (*v12) (unsigned int, signed short);
extern unsigned int v13 (signed int, unsigned short, unsigned int);
extern unsigned int (*v14) (signed int, unsigned short, unsigned int);
extern unsigned char v15 (signed int, unsigned char, unsigned int, unsigned short);
extern unsigned char (*v16) (signed int, unsigned char, unsigned int, unsigned short);
extern unsigned short v17 (void);
extern unsigned short (*v18) (void);
extern unsigned char v19 (signed char, signed char, unsigned int);
extern unsigned char (*v20) (signed char, signed char, unsigned int);
extern signed short v21 (signed short, unsigned int, unsigned short);
extern signed short (*v22) (signed short, unsigned int, unsigned short);
extern void v23 (void);
extern void (*v24) (void);
extern unsigned short v25 (signed char, unsigned char);
extern unsigned short (*v26) (signed char, unsigned char);
extern unsigned int v27 (unsigned short, signed short);
extern unsigned int (*v28) (unsigned short, signed short);
extern unsigned char v29 (unsigned char, unsigned char, unsigned int, signed short);
extern unsigned char (*v30) (unsigned char, unsigned char, unsigned int, signed short);
extern int history[];
extern int history_index;
extern int trace;
signed char v154 = 3;
unsigned int v153 = 2U;
signed int v152 = 3;
