extern void v1 (signed short, signed short, unsigned short, unsigned int);
extern void (*v2) (signed short, signed short, unsigned short, unsigned int);
extern unsigned char v3 (signed short, signed int);
extern unsigned char (*v4) (signed short, signed int);
extern signed short v5 (void);
extern signed short (*v6) (void);
extern signed int v7 (unsigned int, signed short, signed short, signed short);
extern signed int (*v8) (unsigned int, signed short, signed short, signed short);
extern signed char v9 (signed short, signed char, unsigned char);
extern signed char (*v10) (signed short, signed char, unsigned char);
extern void v11 (signed short);
extern void (*v12) (signed short);
extern unsigned char v13 (unsigned int, unsigned int, unsigned char);
extern unsigned char (*v14) (unsigned int, unsigned int, unsigned char);
extern unsigned char v15 (unsigned char, unsigned int);
extern unsigned char (*v16) (unsigned char, unsigned int);
extern signed char v17 (signed int, signed char);
extern signed char (*v18) (signed int, signed char);
extern unsigned int v19 (unsigned int, signed short);
extern unsigned int (*v20) (unsigned int, signed short);
extern unsigned char v21 (unsigned int, unsigned int, signed short);
extern unsigned char (*v22) (unsigned int, unsigned int, signed short);
extern void v23 (unsigned char, signed int);
extern void (*v24) (unsigned char, signed int);
extern signed int v25 (unsigned short);
extern signed int (*v26) (unsigned short);
extern signed int v27 (unsigned char);
extern signed int (*v28) (unsigned char);
extern void v29 (unsigned int, signed int, signed short, signed char);
extern void (*v30) (unsigned int, signed int, signed short, signed char);
extern int history[];
extern int history_index;
extern int trace;
signed int v73 = 1;
signed char v72 = 2;
unsigned int v71 = 7U;
